### PR TITLE
Fixes #30701 - stop showing :5000 for default docker url

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jjeffers** [comment]
While creating a docker repository, I ran across this error:
```
14:07:57 rails.1   | 2020-09-30T14:07:57 [E|bac|] undefined method `auto_enabled?' for #<Katello::RootRepository:0x0000000012affdb8> (NoMethodError)
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/activemodel-6.0.3.2/lib/active_model/attribute_methods.rb:432:in `method_missing'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/audited-4.9.0/lib/audited/auditor.rb:99:in `method_missing'
14:07:57 rails.1   |  | /home/vagrant/projects/katello/app/lib/actions/katello/product/content_create.rb:21:in `block in plan'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.7/lib/dynflow/execution_plan.rb:384:in `switch_flow'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.7/lib/dynflow/action.rb:422:in `sequence'
14:07:57 rails.1   |  | /home/vagrant/projects/katello/app/lib/actions/katello/product/content_create.rb:8:in `plan'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.7/lib/dynflow/action.rb:514:in `block (3 levels) in execute_plan'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.7/lib/dynflow/middleware/stack.rb:27:in `pass'
14:07:57 rails.1   |  | /home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.7/lib/dynflow/middleware.rb:19:in `pass'
14:07:57 rails.1   |  | /home/vagrant/projects/katello/app/lib/actions/middleware/remote_action.rb:9:in `plan'
```

**Comment by jjeffers** [comment]
> While creating a docker repository, I ran across this error:

This doesn't appear to be related to the PR, at least as far I can tell. Still investigating.

**Comment by jlsherrill** [comment]
@jjeffers i think you need to db:migrate.  I believe that was a change in master

**Comment by jlsherrill** [comment]
actually just rebase against master, it looks like that feature was reverted

**Review by jjeffers — APPROVED** [review]
Checks out, looks as described.

**Pull request merged**
