### PR TITLE
Fixes #23966 - empty state buttons should work with react router

### PR DESCRIPTION
**Pull request by amirfefer**
192 168 121 17_3000_xui_subscriptions 1

### CODE REVIEW

**Comment by amirfefer** [comment]
@beav, I use screencastify (chrome's plugin)

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
@amirfefer can you look at the failing test please?

**Comment by amirfefer** [comment]
@waldenraines  - done :)

**Pull request merged**
