### PR TITLE
Fixes #26767 - Custom products on bulk content host manage page

### PR DESCRIPTION
**Pull request by sjha4**
**Steps to Reproduce:**
1. Create a custom product
2. Create a repository in a custom product
3. Register content host(s) to your box
4. Goto Hosts -> Content Hosts
5. Select one or more hosts with checkbox
6. Select Action (Dropdown) -> Manage Repository Sets

Actual results:
Repository list is empty (in case you don't have any redhat products) with the message 'No enabled Repository Sets provided through subscriptions.'
This list only shows redhat products.

Expected results:
Ability to change Repository Sets for hosts selected, like in Host -> Content Hosts ->host -> Repository Sets

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jturel** [comment]
@sjha4 this works well, but I noticed an existing problem that is arguably made more prevalent with this change.

Manage Repository Sets presents a list that is not a superset of all the selected hosts available repo sets, but rather all repo sets for the org. This is inconsistent with the other options in the dropdown because their lists sum up the applicable items for the selected hosts. And with this change we've made that list even longer.

In contrast if I select 3 hosts then the errata shown under Manage Errata are applicable to at least 1 of the selected hosts. This might be a good opportunity to make Repository Sets consistent with the other dropdown options since we are making changes in this area via the bulk_hosts_controller.

Example API:

```
    api :POST, "/hosts/bulk/repository_sets", N_("Fetch available repository sets for hosts.")                                                                               
    param_group :bulk_params                                                                                                                                                 
    def repository_sets                                                                                                                                                      
      content_finder = ProductContentFinder.new(                                                                                                                             
          :consumables => @hosts,                                                                                                                                            
          :match_subscription => true,                                                                                                                                       
          :match_environment => false                                                                                                                                        
      )                                                                                                                                                                      
                                                                                                                                                                             
      respond_for_index(...)                                                                                                                                                 
    end
```

I could be missing something. Maybe @parthaa can comment to weigh in on the suggestion just in case it's not a good one

**Comment by sjha4** [comment]
@jturel: Thanks for the review. I have pushed a second commit trying to implement what you suggested. The only problem which still exists is that if we have a superset of repository sets provided by subscriptions, we would still end up disabling/enabling repo sets for hosts which are not subscribed to the product.
I had this discussion with @jlsherrill around showing all repos on the bulk manage page. AFAIR, he said we can enable a repo for a host without the associated subscription and then add the subscription later to be able to use the repo. In which case restricting the list to a superset of repos would be more confusing than showing all?

**Comment by jturel** [comment]
@sjha4 i actually didn't realize we could do the overrides while a host isn't subscribed; i guess that's a useful feature! looks like we shouldn't go with my suggestion after all. sorry that you wrote most of the code for it already :disappointed:

**Comment by ianballou** [comment]
I'm not sure what the status of this PR is, but I gave it a try.  I found that the Red Hat repositories I have also disappear from the Repository Sets Management window.

**Comment by sjha4** [comment]
Can you see only custom products in the Content Host> Select a few content hosts> Actions> Manage Repository Sets page? Do you have subscriptions for the redhat product attached to the content host?

**Comment by ianballou** [comment]
Before applying your PR I saw only Red Hat related content on the Manage
Repo Sets page. After applying your PR, the Manage Repo Sets page was
blank.  I don't have anything attached to the content host.

**Pull request merged**
