### PR TITLE
fixes #14709 - update facts on separate host object

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
Do you think it would be possible to write a test for this case?  I don't *think* it'd be too bad

**Comment by thomasmckay** [comment]
@jlsherrill - Suggestion for what/how to test? Is there an example of similar test?

**Comment by jlsherrill** [comment]
You could try adding another test here https://github.com/thomasmckay/katello/blob/14709-sub-facet/test/actions/katello/host/update_test.rb and pass in facts to be updated?

**Comment by thomasmckay** [comment]
@jlsherrill - Added facts to both the factory and a call to update. Confirmed that w/o the Host.find() it errored and w/ it passed.

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
