### PR TITLE
Fixes #34795 - Add Deb Repository releases detailed info in GUI

### PR DESCRIPTION
**Pull request by Manisha15**
Added more information regarding Debian Repository Releases/Distributions field

### CODE REVIEW

**Comment by Manisha15** [comment]
[test katello]

**Review by sjha4 — APPROVED** [review]
Screenshot from 2022-04-25 15-13-47
The description seems fairly detailed. Should we add dome documentation in the katello documentation along with the help text?

https://docs.theforeman.org/nightly/Content_Management_Guide/index-katello.html#Adding_Custom_DEB_Repositories_content-management

**Comment by Manisha15** [comment]
> Screenshot from 2022-04-25 15-13-47 The description seems fairly detailed. Should we add dome documentation in the katello documentation along with the help text?
> 
> https://docs.theforeman.org/nightly/Content_Management_Guide/index-katello.html#Adding_Custom_DEB_Repositories_content-management

Yes, sounds good.

**Comment by maximiliankolb** [comment]
I have created a PR to document this: https://github.com/theforeman/foreman-documentation/pull/1243 Please review and let me know when to merge or if it needs to be cherry-picked.

**Comment by quba42** [comment]
@sjha4 It is fairly detailed. We feel this is necessary, since we have seen users overcorrect for our original hint about "flat repos" needing a trailing slash, by trying to sync everything with a trailing slash (which does not work...)

In the long run, it might be possible to teach pulp_deb to recognize flat vs. structured repos without user specification, but until then I would rather have a detailed explanation in the UI were users are most likely to see it.

**Comment by sjha4** [comment]
This is good to go. Merging. 👍🏼

**Pull request merged**
