### PR TITLE
Merge ostree branch to master

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by ehelms** [comment]
Would you mind listing out all the requirements for this to be merged if there are any as well as a list of changes this introduces (to make review and testing easier)? (e.g. Runcible, packaging, etc.)

**Comment by parthaa** [comment]
@ehelms http://projects.theforeman.org/issues/10034

**Comment by ehelms** [comment]
Missing half the question -- requirements and dependent PRs?

**Comment by parthaa** [comment]
Requirements : Pulp 2.8,  
Other Dependent PRs -> https://github.com/Katello/katello/pull/5570

**Comment by ehelms** [comment]
I assume this will need a PR to add ostree as a type with the new Repository type manager?

**Comment by ehelms** [comment]
@parthaa @daviddavis  the commit history for this  long-lived branch has gotten a bit ugly and out of hand including some what appear to be direct commits without Redmine issues. What do you think about reducing it via either a squash or cherry-picks of the substantive commits?

**Comment by daviddavis** [comment]
@parthaa why are there direct merges without commits? I thought we only allowed merge commits to go without issue #s.

**Comment by daviddavis** [comment]
@ehelms to answer your question, I am fine with a squash or cherry pick. Another option might be to rebase the ostree branch against master. That'd drop the merge commits from the branch, and we could update the commits without issues attached too.

**Comment by ehelms** [comment]
I am OK with any of those options.

**Comment by parthaa** [comment]
> I am OK with any of those options.

@ehelms @daviddavis rebase is not an option at this stage for me. There is just one commit that has no redmine. That was just one commit with a test fix that needed to be added when a master merge failed (https://github.com/Katello/katello/commit/f10c5188c060afc12507f1dd39667a391b5e6e6e.)  And that 1 line test was validated by a reviewer

**Comment by jlsherrill** [comment]
@parthaa i wouldn't use the words 'validated by a reviewer' as those commits were somewhat difficult to spot and kinda snuck in.  If @daviddavis is okay with a sqash, lets just do that.

**Comment by parthaa** [comment]
@ehelms @daviddavis more importantly I do not want to spend time on the  humongous amount of merge conflicts with a possibility of inducing mistakes. 
@jlsherrill squashing will rewrite history and take away authorship. And reference to what a particular commit was added and what functionality was added by a commit.
 A lot of the complaints by that foreman bot is about the message format, "Fixes #### - ,," instead of "Fixes ####: ..." . That used to be the norm when this branch was started. It has gone through almost an year of evaluation.
If we have issues with 'git merge master' and want a "redmine issue" for every master merge, lets create a generic story "Master Merge" and apply that number to all commit histories when this operation is done.

**Comment by parthaa** [comment]
> A lot of the complaints by that foreman bot is about the message format, "Fixes #### - ,," instead of "Fixes ####: ..." . That used to be the norm when this branch was started. It has gone through almost an year of evaluation.

 I evaluated that wrong. hmm why is it pointing out this is bad -> https://github.com/Katello/katello/commit/b9402386e8afa23df2d2832dd63e6c72b8c119dc

**Comment by parthaa** [comment]
Merged! -> https://github.com/Katello/katello/pull/5755

**Comment by daviddavis** [comment]
giphy

**Pull request closed without merging**
