### PR TITLE
fixes #11094 - assign default location to new puppet environments

### PR DESCRIPTION
**Pull request by jlsherrill**
this way non-admin users can create them, as they need to be assigned
to at least one location if a non-admin user creates them

Also fixes a class loading issue seen in development during publish

### CODE REVIEW

**Comment by stbenjam** [comment]
What about scoping to all locations?

New foreman hosts have to have a location, thus hiding operating systems, installation media, and puppet environments that Katello creates without any location. It really causes a lot of trouble.  

I'm not completely sure what the right thing to do is though.

**Comment by jlsherrill** [comment]
The goal as I understand it is that you assign locations to capsules/smart proxies as well as lifecycle environments , and then any content in that lifecycle environment is automatically assigned to those  locations.  This allows you to select a location for a host, select a puppet environment (ideally in a content view/lifecyce environment) and rest assured that the puppet environment content has been deployed out to the capsule you are provisioning against.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
and i should add, we already do the location assignment to the puppet environment, we just do it after creation later down in the code.

**Comment by jlsherrill** [comment]
@stbenjam any thoughts?

**Comment by stbenjam** [comment]
@jlsherrill Looks fine and seems to work, I was more referring to the general problem of us not assigning locations to everything (i.e. installation media), but that's a separate issue.

ACK

**Pull request merged**
