### PR TITLE
Fixes #23033 - Remove force_post_sync_actions

### PR DESCRIPTION
**Pull request by sjha4**
Removing force_post_sync Settings option.

This can be achieved using Hammer flag skip-metadata-check and on the UI using complete sync.

### CODE REVIEW

**Comment by jlsherrill** [comment]
Mind adding a migration to delete the Setting from the db?  Similar to this line: https://github.com/Katello/katello/blob/master/db/migrate/20171114150937_cleanup_installed_packages.rb#L46

**Comment by sjha4** [comment]
@jlsherrill :+1: Added migration to delete the setting: force_post_sync_actions .

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Pull request merged**
