### PR TITLE
Fixes #37683 - Add product counting on a per host basis

### PR DESCRIPTION
**Pull request by nadjaheitmann**
#### What are the changes introduced in this pull request?
With SCA and subscriptions (count) gone, users still want to keep track of how many hosts are consumed on a per product basis. The use case is there for SUSE, Debian-based system, etc. In this PR, we re-add a column to the 'Subscriptions' page to have an overview over the hosts that are subscribed to a particular product. 'Subscribed' means that the repository must be enabled for that host and it must be accessible on the host itself running 'subscription-manager repos'.

#### Considerations taken when implementing this change?
We try to use the means of counting host that are provided by Katello itself without being dependent on subscriptions which are basically host_content_facets. 

#### What are the testing steps for this pull request?
Create a host and subscribe one or multiple repositories. The number of hosts that consume the product should increase. If a host consumes multiple repositories from one product, this does not count twice. 

image

#### Open points:

- [x] Not sure if this column should be added permanently or as an option/setting. The implementation is mixed up right now (providing a parameter but then hard-coding it to true in the UI). This should be clarified.
- [x] Besides fixing existing tests, we need new ones for the new feature.

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@jeremylenz Do you mind taking a look at this? I would like to know whether this is worth moving forward and if yes, how to resolve the open questions above.

**Review by jeremylenz — COMMENTED** [review]
Hi @nadjaheitmann 

Thanks for the PR!

My initial feeling is that product host count may be useful to people. However, it doesn't feel like the Subscriptions page is the right place for it. People generally go here to perform subscription-related actions, not necessarily to view reporting information. 

Instead, what if we added it to a report instead? There's an existing report, "Subscription - General Report," which already iterates through all your pools and gives information about each one. It lives [in Foreman](https://github.com/theforeman/foreman/blob/develop/app/views/unattended/report_templates/subscription_-_general_report.erb). We could extend that report to use `pool.product_host_count`. And here in Katello, we would need to add `product_host_count` to the Jail.

This way it won't require changing any API requests or params, and it also puts the information in a place that I think makes more sense. Let me know your thoughts.

One more thing to keep in mind, which is still a few months down the road - The Subscriptions page as we know it is about to change soon, and the whole concept of Pools in your manifest may or may not stick around. That's because manifests will become "SCA-aware" and not necessarily care about entitlement quantities anymore. I think that's an additional argument for this change living in a report.

**Comment by nadjaheitmann** [comment]
Hi @jeremylenz , 
thanks a lot for your input! 

> People generally go here to perform subscription-related actions, not necessarily to view reporting information

The reason why I put the product host count here is because there is already the 'Consumed' column which gives (gave) a similar information. Please let me know if I am mistaken about the 'Consumed' field.

> Instead, what if we added it to a report instead? There's an existing report, "Subscription - General Report," which already iterates through all your pools and gives information about each one. 

I feel that the report gives very much the same information as the page (although it does not contain the 'Consumed' field). I agree that it is a good idea to add the product host count here. 

From my personal feeling, I think it would not hurt to add the column in the UI and also add it to the template. I think, the API could just stay as is and I could remove the optional parameter. I see your point that the UI change would probably not last long if there was a significant change to how pools are treated. Is there any information on which changes are planned and when? 

Another idea about where in the UI it could live: What about the 'Products' page? However, then it is totally unrelated to subscriptions which does not seem right, either.

**Comment by jeremylenz** [comment]
> The reason why I put the product host count here is because there is already the 'Consumed' column which gives (gave) a similar information.

ah, that makes sense! Thanks for explaining.

> I think it would not hurt to add the column in the UI and also add it to the template. I think, the API could just stay as is and I could remove the optional parameter.

I can accept that. :+1:  Let's remove the API changes and just keep the change on the Subscriptions page for now.

**Comment by nadjaheitmann** [comment]
@jeremylenz I have stripped the API (what makes the code much more readable), added some basic tests and added the `product_host_count` to Jail, such that I can open a follow-up PR in Foreman and add the parameter to the 'Subscription - General Report' template. Do you mind having another look?

**Review by jeremylenz — COMMENTED** [review]
Tested by adding `pool.product_host_count` to a cloned Subscription - General report; works as advertised. :+1: 

Try rebasing to current master branch and see if that fixes tests.

**Comment by nadjaheitmann** [comment]
I think I have messed up the tests. Will have another look.

**Comment by jeremylenz** [comment]
I don't think the `could not obtain a connection from the pool within 5.000 seconds (waited 5.005 seconds); all pooled connections were in use
    test/test_helper.rb:88:in 'before_setup'` is related

**Comment by nadjaheitmann** [comment]
> I don't think the `could not obtain a connection from the pool within 5.000 seconds (waited 5.005 seconds); all pooled connections were in use test/test_helper.rb:88:in 'before_setup'` is related

That one is not, but there were other errors related to hard-coded numbers of products/repositories that are expected in the test. Currently working on it. 

I opened another PR https://github.com/Katello/katello/pull/11114 yesterday where the tests were working, so I got suspicious.

**Comment by nadjaheitmann** [comment]
@jeremylenz Got the tests green, finally. I am not a fan of hard-coding the numbers in there.

**Pull request merged**
