### PR TITLE
Fixes #15035 - Adding rails script to katello

### PR DESCRIPTION
**Pull request by daviddavis**
More info: http://guides.rubyonrails.org/engines.html#bin-directory

This will let us do things like generate models, migrations, etc from within katello:

```
$ bin/rails g model foobar foo:integer bar:string baz:references
$ bin/rails g migration add_user_id_to_content_views user_id:references
```

### CODE REVIEW

**Comment by daviddavis** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK

**Comment by jlsherrill** [comment]
No more generating and copying migration from the foreman directory???  asdf

**Comment by ehelms** [comment]
Is there a way (or script/tool) we could use so that all plugins can run these operations from the base or individual plugin directory without each having to have a copy of this file?

**Comment by daviddavis** [comment]
My initial guess would be no since rails generates this file every time you generate a mountable rails engine. Let me check on Monday though. If nothing else, we could maybe build one ourselves too.

**Pull request merged**
