### PR TITLE
fixes #11939 - Debugging transient fixture test failure

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
:(((((((((((

**Comment by daviddavis** [comment]
[test]

**Comment by jlsherrill** [comment]
this occured again:  http://ci.theforeman.org/job/test_katello/2580/

@ehelms any thoughts on actually merging this (with an issue filed of coursed), to debug this long term?

**Comment by ehelms** [comment]
Could we spit out this as well -- https://github.com/theforeman/foreman/blob/9a9ec5b1f88ada7b86c39bb982a6902f6171d4d1/app/models/role.rb#L130

Just so we are executing and spitting out the result of, the code that is being called ?

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
