### PR TITLE
Fixes #9132 - use networking snippet during provisioning

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
Note that this the config template snippet should be added in next Foreman release (1.8). It has been merged into comunity-templates repo recently https://github.com/theforeman/community-templates/pull/107

**Comment by stbenjam** [comment]
Looks fine to me, I'll try to find some time to test it.  

Could we get community-templates synced to foreman @domcleal? I know you only want to do that just before releases, but for this case, we'll break provisioning in katello nightly if this is merged now.

**Comment by stbenjam** [comment]
Actually, looking at this... I guess the template is backwards compatible with previous Foreman versions?

It would be nice to have the templates still synced more often though.

**Comment by domcleal** [comment]
> Could we get community-templates synced to foreman @domcleal?

https://github.com/theforeman/foreman/commit/c0fe869d28f3a79ba65bc7d433c15c9d548b0baa

**Comment by stbenjam** [comment]
@domcleal Do you have a time machine? :watch:  Thanks :+1:

**Comment by ares** [comment]
@stbenjam for the record, yes, it should be backward compatible. It would skip network configuration on older version.

**Comment by stbenjam** [comment]
@ares 

```
There was an error rendering the Katello Kickstart Default template: The snippet 'kickstart_networking_setup' threw an error: undefined method 'has_primary_interface?' for Host::Managed::Jail (Host::Managed)
```

**Comment by stbenjam** [comment]
http://projects.theforeman.org/issues/9394

**Comment by stbenjam** [comment]
Wrong button :-) I meant: http://projects.theforeman.org/issues/9394

**Comment by jlsherrill** [comment]
@stbenjam http://projects.theforeman.org/issues/9394 seems resolved, is this good to merge?

**Comment by stbenjam** [comment]
@jlsherrill I'm sure it's fine, but I want to actually provision a machine with it first to make sure it works with Katello.

**Comment by stbenjam** [comment]
Will do that this week sometime.

**Comment by stbenjam** [comment]
@ares It works fine-ish, except setting the default gateway doesn't work correctly on EL7.

http://projects.theforeman.org/issues/9505

**Comment by stbenjam** [comment]
The mentioned bug was resolved, so ACK for me

**Pull request merged**
