### PR TITLE
[CP] Katello 3.12 Cherrypicks from Toolbelt

### PR DESCRIPTION
**Pull request by chris1984**
@jturel how does this look?

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@chris1984 looks good. let's leave this open until next week. I think we'll have a few more items ready to pick over

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@chris1984 I think this is why tests are not working: https://github.com/theforeman/foreman-infra/pull/1039

**Comment by chris1984** [comment]
[test katello]

**Comment by jturel** [comment]
probably have to wait a little longer for puppet to update the node

**Pull request merged**
