### PR TITLE
Fixes #26389 - process org creation errors

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
@ares test failures seem related

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by ares** [comment]
this should help with tests, I added `::` before Foreman namespace

**Comment by ares** [comment]
Green now, easy merge

**Comment by jlsherrill** [comment]
Thanks @ares !

**Pull request merged**
