### PR TITLE
Fixes #35763 - Switch to standard PF4 search input in Katello

### PR DESCRIPTION
**Pull request by lfu**
#### What are the changes introduced in this pull request?
Katello is switching to Foreman's standard PF4 search input.

#### Considerations taken when implementing this change?
Depends on https://github.com/theforeman/foreman/pull/9571

#### What are the testing steps for this pull request?
Check all the search field work well in new host details pages and content view components.
Verify this PR fixes https://projects.theforeman.org/issues/35988.

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
Thanks @lfu 

First impression is that this looks great! More comments coming soon, but for now I'll just say I love that we were able to remove the searchDelay and autoSearch scopes from all the tests.

Now that we don't use those settings anymore, I think we should also remove the `autosearch_while_typing` and `autosearch_delay` settings themselves.  (it's in `plugin.rb`.)

**Comment by lfu** [comment]
> Now that we don't use those settings anymore, I think we should also remove the `autosearch_while_typing` and `autosearch_delay` settings themselves. (it's in `plugin.rb`.)

I have not deleted anything since the Katello search field is being used by some other components.

**Comment by jeremylenz** [comment]
> I have not deleted anything since the Katello search field is being used by some other components.

Where is it still used? Shouldn't we use Foreman's everywhere?

**Comment by lfu** [comment]
> Where is it still used? Shouldn't we use Foreman's everywhere?

SubscriptionsToolbar and redhatRepositoriesPage.
Should they be changed as well? Thought this change is only for new host details pages.

**Comment by jeremylenz** [comment]
> SubscriptionsToolbar and redhatRepositoriesPage.
> Should they be changed as well?

Ideally yes, we should standardize everywhere!

**Review by jeremylenz — APPROVED** [review]
Great work @lfu !

Let's continue on in the next PR.  ACK :+1:

**Pull request merged**
