### PR TITLE
Add GitHub Actions based testing to 4.11

### PR DESCRIPTION
**Pull request by ekohl**
#### What are the changes introduced in this pull request?

This picks the changes from KATELLO-4.12 and modifies it as needed.

#### Considerations taken when implementing this change?

This allows us to fully drop the Jenkins tests and finish up the GHA conversion project.

#### What are the testing steps for this pull request?

CI should be green.

### CODE REVIEW

**Comment by ekohl** [comment]
What do the maintainers prefer to do with RuboCop here? Update the TODO file or further pick fixes? I'd lean to updating the TODO file now.

**Comment by chris1984** [comment]
> What do the maintainers prefer to do with RuboCop here? Update the TODO file or further pick fixes? I'd lean to updating the TODO file now.

I am fine with just updating the todo in rubocop, safer than picking more stuff into a stable branch,

**Comment by jeremylenz** [comment]
> I am fine with just updating the todo in rubocop, safer than picking more stuff into a stable branch

Yeah this makes sense to me too. :+1:

**Review by jeremylenz — APPROVED** [review]

**Comment by ekohl** [comment]
Can this be merged so I can wrap up the GHA migration?

**Review by chris1984 — APPROVED** [review]

**Comment by chris1984** [comment]
> Can this be merged so I can wrap up the GHA migration?

Taken care of, Happy Weekend!

**Pull request merged**
