### PR TITLE
fixes #10396 - display better errors on repo metadata sync fail

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Is this simply not finding `repodata/` or `repomd.xml` ? Or is there more to this potential error?

**Comment by jlsherrill** [comment]
either could cause the error.  All we really get from pulp is that the 'metadata' phase has an error of "Not Found'.  this is just indicating to the user which phase the Not Found occured in.

**Comment by ehelms** [comment]
Bummer. Do you know of a bug to Pulp to make that error message more useful to a user by indicating what 404ed? 

ACK regardless

**Comment by jlsherrill** [comment]
@ehelms opened https://pulp.plan.io/issues/958

**Pull request merged**
