### PR TITLE
Fixes #12027 - Subscription link text aligns properly

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@zjhuntin  everything looks fine on activation keys, but you will have to update the tables on content host subscriptions as they are misaligned as well http://www.clipular.com/c/4540063292063744.png?k=vF0KPFcgeccuXjo-qbxl0TuUFjA

**Comment by zjhuntin** [comment]
Ahh, didn't see that one, thanks for the heads up!

**Comment by johnpmitsch** [comment]
Everything LGTM and works fine. I would ack but I'm not too familiar with our css. @waldenraines can you take a glance at the code and confirm it looks ok?

**Comment by zjhuntin** [comment]
[test]

**Comment by waldenraines** [comment]
ACK, thanks @zjhuntin

**Pull request merged**
