### PR TITLE
Fixes #16640 - Change media_ids to medium_ids

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by daviddavis** [comment]
I think you'll need to deprecate `media_ids`.

**Comment by jlsherrill** [comment]
I guess if the previous api didn't work, no need to deprecate it.  Did it ever work?  

Also, shouldn't we update it in foreman too?  

https://github.com/theforeman/foreman/blob/develop/app/controllers/concerns/api/v2/taxonomies_controller.rb#L22

**Comment by xprazak2** [comment]
It never worked, there was a silent fail when hash with `"media_ids" => ["1", "2"]` was passed to `update_attributes` method. There is a pending [PR](https://github.com/theforeman/foreman/pull/3873) for Foreman as well.

**Comment by jlsherrill** [comment]
perfect, ACK thanks @xprazak2 !

**Pull request merged**
