### PR TITLE
Refs #9200: Discovery does not work with Foreman 1.8 currently.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
I might be okay with not installing it by default upstream.  That may make things simpler long term?   

I disagree that we should only use puppet to ensure that it is installed.  'katello' is a sort of meta package that should require what 'katello' requires.

**Comment by stbenjam** [comment]
I guess, but do we really rely on discovery? It's more of a downstream mandate than something in Katello code right? Anyway, I suppose it doesn't matter, foreman-docker, tasks are hard requirements and they could also break us.... so plugins are just cats we have to herd :cat2: :cat2: :cat2:.

I withdraw my complaint :)

**Comment by jlsherrill** [comment]
@stbenjam yeah, thats kinda why i suggested i'd be okay with changing our attitude and not including them upstream by default.

**Comment by bbuckingham** [comment]
Keep in mind that if it is no longer being installed by default in Katello, then there are other projects that will be impacted.  For example, Fusor (RHCI downstream) requires discovery and currently does nothing to include it since Katello already does.

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK from me, we can further discuss removing our inclusion of plugins via the mailing list

**Comment by stbenjam** [comment]
Yes fine ACK, someone needs to tell Fusor so we don't break them if they have something against our nightlies (cc: @isratrade )

**Comment by bbuckingham** [comment]
@stbenjam, I am currently working on Fusor and saw the PR.  I was mainly raising it to create awareness for folks that some decisions (like this one) can affect other projects. :)

**Comment by stbenjam** [comment]
@bbuckingham Ah sorry, I didn't realize :-) Joseph was the only one I knew

**Comment by bbuckingham** [comment]
@stbenjam, No need to apologize.  I am currently working a couple of projects, but main focus has been on fusor for a bit.  That's why I have been not as noisy on katello. :)

**Pull request merged**
