### PR TITLE
Fixes #16647 - restrict host freeform search to a few items

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
This looks good. I would like to hold off on merging for a few days though so we can see the explain plan and ensure it's just these fields.

**Comment by jlsherrill** [comment]
Sounds good to me!

**Comment by tbrisker** [comment]
Just my 2&cent;: I would suggest disabling non-explicit search for any fields that wouldn't make sense to search on non-explicitly. From a quick look, you can also make all the ID fields explicit only. There may be others but I don't know enough about the different use cases to tell which other fields might not make sense to search on non-explicitly.

**Comment by beav** [comment]
I didn't see anything egregious in the explain plan, adding `:only_explicit` should do the trick as mentioned above.

**Comment by jlsherrill** [comment]
@tbrisker yeah i agree, updated to include more fields.

**Pull request merged**
