### PR TITLE
Fixes #28998: update angular dependencies

### PR DESCRIPTION
**Pull request by waldenraines**
I'm going to keep the commits separate for now so it's easier to review.  I will combine them before merging but I'll probably keep the `update ____ to _____` commits separate for clarity. 

TODO:
 - [x] Fix tests

### CODE REVIEW

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
Oops, fixed the bastion tests but not the bastion_katello tests, working on the latter now.

**Comment by waldenraines** [comment]
> Oops, fixed the bastion tests but not the bastion_katello tests, working on the latter now.

This is now ready to review.

**Comment by waldenraines** [comment]
Going to merge :crossed_fingers:

**Comment by ekohl** [comment]
FYI: packaging doesn't have angular 1.7.9 and still builds with 1.5.5. Please open a [PR](https://github.com/theforeman/foreman-packaging/pulls)

**Comment by jlsherrill** [comment]
i didn't realize this was packaged since bation vendors it, opened a pr here:  https://github.com/theforeman/foreman-packaging/pull/4940

**Pull request merged**
