### PR TITLE
Refs #10838 - Move backend Status widget to dashboard

### PR DESCRIPTION
**Pull request by thomasmckay**
* moves about templates so they can be found in rail's template search path
* register the status template as a default template on init
* addressed reviewer comments

replaces https://github.com/Katello/katello/pull/5310

### CODE REVIEW

**Comment by ehelms** [comment]
With the current sizing, the message column is sorta worthless:

screenshot from 2015-07-20 16 36 54

**Comment by thomasmckay** [comment]
@ehelms - there is a tooltip on hover w/ full info. i don't have a strong opinion on whether to resize this widget or not. the majority of the time there will be no messages.

**Comment by ehelms** [comment]
Sure, but when there is there is almost no point in showing any part of the message outside of the tooltip. You'd be better off replacing it with an icon that you hover over.

**Comment by stbenjam** [comment]
Why width 4? I think plugins should try to standardize on 6 so I can arrange things how the user sees fit.  At least until the widgets themselves are resizable. Otherwise we don't give users many options in terms of how to arrange them.

**Comment by stbenjam** [comment]
For example, discovery at 7 really gums up the works, and this one would do similarly by being too small:

capture

**Comment by thomasmckay** [comment]
@ehelms - Thoughts on removing the message column entirely? The messages are fairly cryptic and would require users to get to server console to debug regardless. Alternatively could tooltip on the OK/FAIL.

**Comment by ehelms** [comment]
Tooltip via an icon would work OK for me (icon so that it's more discoverable). Maybe file an RFE to build out a page that has more detailed information on services and user friendly error messages so that it can be investigated?

**Comment by thomasmckay** [comment]
Updated width and added icon in case of FAIL services

**Comment by ehelms** [comment]
I think the changes look good. One usability question for you, what are your thoughts on colored badge or icon style indicators next to the services? I am not sure the 'FAIL' would catch my eye compared to visually scanning the page and seeing something red staring at me.

**Comment by ehelms** [comment]
Looks like this needs rebasing and updating.

**Comment by ehelms** [comment]
@thomasmckay do you plan to revisit this in the near future?

**Pull request closed without merging**
