### PR TITLE
Fixes #20278 - Remove Katello specific support information.

### PR DESCRIPTION
**Pull request by bkearney**
This is remnant of katello being not well integrated. I would suggest that
this be removed since katello behaves like the other plugins now.

### CODE REVIEW

**Comment by bkearney** [comment]
[test]

**Comment by bkearney** [comment]
@ehelms I am not seeing logs and failures, what have I screwed up?

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
@bkearney was some npm issue in the CI, should be fixed now

**Comment by bkearney** [comment]
@jlsherrill seems to still be busted.

**Comment by bbuckingham** [comment]
[test]

**Comment by jlsherrill** [comment]
@bkearney current failure is different, its rubocop related.  Hound fails again! 


00:04:33.848 /var/lib/workspace/workspace/test_katello_pull_request/slave/fast/plugin/app/overrides/add_about_page.rb:14:1: C: 1 trailing blank lines detected.

**Pull request merged**
