### PR TITLE
Fixes #31293 - get rid of use_pulp option

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
This requires https://github.com/Katello/katello/pull/9030 to be merged first.

**Comment by jlsherrill** [comment]
looks good, wanna rebase now?

**Comment by sbernhard** [comment]
Rebase done. :)

**Comment by jlsherrill** [comment]
[test katello]

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
thanks @sbernhard !!

**Pull request merged**
