### PR TITLE
Fixes #9472: Remove changelog script in favor of tool_belt

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
What do you think about transferring `tool_belt` to the Katello org to make it easier to find?

**Comment by ehelms** [comment]
I don't have a problem with that as long as I can be guaranteed some as changes are needed. Moving it under the org means that it now falls under the Katello committer rules.

**Comment by stbenjam** [comment]
It doesn't much matter to me, it just seemed to make sense if we're replacing things like this script in favor of tool_belt.  I'll leave it up to you.

Anyway, ACK for this PR

**Comment by ehelms** [comment]
@stbenjam I will look into/think on it some more. I know it is being used by Foreman releases as well so might make sense to center it.

**Pull request merged**
