### PR TITLE
Fixes #14430 - fixing js tests breakage in ApplyErrataController

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Jenkies:  http://ci.theforeman.org/job/test_katello_pr_core/2001/

**Comment by bbuckingham** [comment]
APJ

**Comment by jlsherrill** [comment]
foo

**Comment by jlsherrill** [comment]
Real Jenkies link with JS test goodness:  http://ci.theforeman.org/job/test_katello_pull_request/8876/

**Comment by jlsherrill** [comment]
Merging as I have an ACK and tests agre green.

**Pull request merged**
