### PR TITLE
Fixes #23051 - Display epoch on packages

### PR DESCRIPTION
**Pull request by sjha4**
#### Requirement: 
Show Epoch version in the package name on UI.
#### Possible Approach?
We already have nvrea on the model and returned via API, replacing nvra on UI with the same.

### CODE REVIEW

**Comment by jlsherrill** [comment]
@sjha4 we probably want it to be consistent across several pages, including:

Content > Products > click a product > click a repo > click on the packages count
Content > Content Views > Click a content view > click a version > click on packages tab

**Comment by sjha4** [comment]
@jlsherrill :+1: Added the change in the content view flow. I think we are covering all pages now.

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Pull request merged**
