### PR TITLE
 fixes #10229 - centralizing and isolating capsule communication

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
This will still fail when the UpdateEnvironment call is made since that triggers a node sync operation.

**Comment by iNecas** [comment]
Also, we should not call the async_task from plan method like this, as the repository record might not be just created in the pulp (as that happens in the run phase).

Wouldn't be using timeouts be a better solution for this issue?

**Comment by jlsherrill** [comment]
@iNecas this is occurring in the  the run phase, not the plan phase.  I think for this, the background makes more sense, as even waiting 5-10 seconds would be too long.  I think we should use a timeout as well though.

**Comment by iNecas** [comment]
Ah, right, my bad. No issues then from my side

**Comment by jlsherrill** [comment]
@iNecas keep in mind i completely rewrote this to change how we maintain these relationships now.

**Comment by ehelms** [comment]
ACK for me from testing it and code perspective

**Pull request merged**
