### PR TITLE
Fixes #9867: Update katello-remove for latest packages.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
What about the certificate RPM's that don't get removed?

**Comment by ehelms** [comment]
When I tested this I did not find any on my system based on the command we
discussed.

**Comment by stbenjam** [comment]
@ehelms They won't come from the katello repo - did you look based on `rpm -qa | grep $HOSTNAME'?

I just did a katello-remove on a Satellite box and lots were left over.

**Comment by ehelms** [comment]
I did exactly that command and got nothing. I will re-spin a box and re-test it just to be sure.

**Comment by stbenjam** [comment]
It looks like the top of the RPMS thing there's some of the certs that would be removed there, but I end up with http://projects.theforeman.org/issues/9867#note-1 left over.

**Comment by ehelms** [comment]
@stbenjam updated

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
