### PR TITLE
fixes #9462,#9557,#9556 - various inherited hostgroup issues

### PR DESCRIPTION
**Pull request by jlsherrill**
this commit fixes:
* Error "unable to load activation keys" on initial host group load
* Error "host group not found" when trying to update/save a host group with a parent
* Install Media Url not using inherited cv and lifecycle env

### CODE REVIEW

**Comment by stbenjam** [comment]
What do you think about tests? I think we should test the foreman integration parts more -- so we should create a host group with content-related features, and also test inheritance to nested host groups.

I have some in foreman salt -  https://github.com/theforeman/foreman_salt/blob/master/test/unit/hostgroup_extensions_test.rb

**Comment by jlsherrill** [comment]
@stbenjam i can't really test the javascript portions, but I'd be happy to write some tests that test the ancestry from a model perspective!  :+1:

**Comment by stbenjam** [comment]
Cool, yea that works, I could just see Foreman changing something and this going unnoticed until a user tries nested hostgroups.

**Comment by jlsherrill** [comment]
There are actually a few test here:

https://github.com/Katello/katello/blob/master/app/models/katello/concerns/hostgroup_extensions.rb#L51

I'll add a couple more

**Comment by jlsherrill** [comment]
@stbenjam added a few tests, not a lot i can cover since most of it is javascript changes :/

**Comment by stbenjam** [comment]
Ok, this fixes the issues mentioned - ACK

Note activation keys don't seem to get inherited - http://projects.theforeman.org/issues/9151

**Pull request merged**
