### PR TITLE
refs #10970 - wrapping active_record scopes with lambdas

### PR DESCRIPTION
**Pull request by komidore64**
http://guides.rubyonrails.org/active_record_querying.html#scopes

### CODE REVIEW

**Comment by komidore64** [comment]
prefer `lambda` or lambda rocket (`->`)?

**Comment by ehelms** [comment]
I suppose `->` is fashionable, but if I had to pick one I like that lambda is explicit. I can live with either as long as we are consistent.

**Comment by jlsherrill** [comment]
yeah, i'd just follow foreman's lead unless there are strong opinions

**Comment by komidore64** [comment]
alright, i'm cool with that. I will switch them all to `->`.

**Comment by komidore64** [comment]
closing this PR in favor or commiting to the [rails4](https://github.com/Katello/katello/tree/rails4) branch.

**Comment by ehelms** [comment]
If this is compatible with Rails 3, I think merging it to master does make sense. The less changes sitting in a branch, the easier it will be overall over time with having to merge and account for changes in master. Is there a rubocop to enforce `->` syntax perchance?

**Comment by komidore64** [comment]
There is a cop to enforce lambda rocket syntax i believe.

**Comment by ehelms** [comment]
That'd be cool if it can, I am good with this PR once they are swapped over to `->`

**Comment by komidore64** [comment]
it appears that Foreman isn't particularly consistent with `lambda` or `->`. if anything it looks like `lambda` appears much more than `->`.

Foreman's rubocop [isn't enforcing](https://github.com/theforeman/foreman/blob/develop/.rubocop_todo.yml#L208-L210) any kind of lambda style.

**Comment by komidore64** [comment]
@ehelms plz2rereview

**Comment by ehelms** [comment]
APJ

**Pull request merged**
