### PR TITLE
fixes #14404 - hammer-cli-import cannot create a content view

### PR DESCRIPTION
**Pull request by komidore64**
[bugzilla #1316110](https://bugzilla.redhat.com/show_bug.cgi?id=1316110)

### CODE REVIEW

**Comment by beav** [comment]
ACK from me

is there a way to discover if the explicit `inverse_of` is needed elsewhere?

**Comment by komidore64** [comment]
Not that I know of? Mostly because this only fails on (at the time of writing) upstream and downstream production installations. My guess is it has to do with the specific versions of one or more gems. If I can't reproduce it in a development environment, then the tests wouldn't be able to pick it up either because those are run in a development environment.

**Comment by johnpmitsch** [comment]
LGTM

My only thought is that ```:inverse_of``` should be added [here](https://git.io/vVZzE) as well, since similar problems may happen with that part of the relation, but that is just me speculating.

**Comment by johnpmitsch** [comment]
[test]

**Pull request merged**
