### PR TITLE
Fixes #8039 - upgrade patternfly to version 1.1.1.

### PR DESCRIPTION
**Pull request by waldenraines**
Upgrades patternfly to 1.1.1 and fix places where the upgrade broke
the UI.

http://projects.theforeman.org/issues/8039

Requires https://github.com/Katello/bastion/pull/10

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by jlsherrill** [comment]
Played around with this a bit and i could not find any issues.  ACK from me

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
A few things I noticed:

Environments list page:

lifecycle environment paths

Alerts, looking at https://www.patternfly.org/widgets/#alerts, appear to be missing the icons.

Seeing a gap on either side of the title and search bars for index pages:

products

Icon is missing on Remove buttons.

Content host index missing proper colors. Subscription status is black and should be green. I suspect the errata icons are similar.

**Comment by waldenraines** [comment]
@ehelms updated.  Many of the fixes were in the corresponding [Bastion PR](https://github.com/Katello/bastion/pull/10).

**Pull request merged**
