### PR TITLE
Fixes #36205 - re-record test VCRs for pulp-rpm 3.19.2

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
Pulpcore 3.19.2 introduced changes to the json structure of data from their API: https://github.com/pulp/pulp_rpm/commit/4df9e506a791c303143b33e872d31c905a42bae5

#### Considerations taken when implementing this change?
I decided to rerecord all of the VCRs because it only helps us keep our tests up-to-date.

#### What are the testing steps for this pull request?
See that the tests run successfully.

### CODE REVIEW

**Review by sjha4 — APPROVED** [review]
Since there are only VCRs on the PR, I am assuming there were no changes needed for 3.19.2? Ack to re-recording VCRs to keep them recent. 👍🏼

**Comment by sjha4** [comment]
Did we want to revert the changes here since this has been changed in pulp?
https://github.com/Katello/katello/pull/10453/files#diff-fa78c7dabf1fcbd56c495b489097d3a829afdade1d3ea5887766e65a7cea547bR28

**Comment by ianballou** [comment]
> Did we want to revert the changes here since this has been changed in pulp? https://github.com/Katello/katello/pull/10453/files#diff-fa78c7dabf1fcbd56c495b489097d3a829afdade1d3ea5887766e65a7cea547bR28

I'll take a look at the data structure now and see if we can remove the compatibility bits.

**Review by sjha4 — APPROVED** [review]
Able to index module stream profiles and artifacts correctly. Ack 👍🏼 
Screenshot from 2023-04-28 12-08-34
Screenshot from 2023-04-28 12-08-22

**Pull request merged**
