### PR TITLE
Fixes #9511: update manifest upload styling to bootstrap 3, BZ1194531

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/9511
https://bugzilla.redhat.com/show_bug.cgi?id=1194531

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
Do our other uploads need this treatment?

**Comment by waldenraines** [comment]
@ehelms good point, will update those too.

**Comment by waldenraines** [comment]
@ehelms updated.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
