### PR TITLE
[CP] 3.13 RC2 cherry-picks

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
Gotta add [CP] when opening this kind of PR otherwise this PR gets added to all the redmine issues :(

**Comment by jturel** [comment]
Looks good. Its probably time to look at the 3.13 release and bump things off to 3.14.

Just checking - did you make sure to pull the latest master of tool belt to ensure that you have the latest config? Important to do that so nothing is missed

**Comment by chris1984** [comment]
> Looks good. Its probably time to look at the 3.13 release and bump things off to 3.14.
> 
> Just checking - did you make sure to pull the latest master of tool belt to ensure that you have the latest config? Important to do that so nothing is missed

+1 to what @jturel said

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test prprocessor]

**Comment by chris1984** [comment]
[test pr processor]

**Comment by jjeffers** [comment]
I pulled latest toolbelt from master just before I generated the cherry-picks.

**Comment by jjeffers** [comment]
[test katello]

**Comment by chris1984** [comment]
[test prprocessor]

**Comment by chris1984** [comment]
[test]

**Comment by jturel** [comment]
The failure looks related to one of the changes in this PR but not sure why  - it works fine on master and locally.

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
It looks like there is some missing code in app/models/setting/content.rb - were there any merge conflicts when you did the cherry picks?

**Pull request closed without merging**
