### PR TITLE
fixes #11222 - corrected calls to display_manifest_message()

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by ehelms** [comment]
APJ

**Comment by thomasmckay** [comment]
@ehelms - rubocop sniffed out an unused arg (see 2nd commit). i will squash once re-APJ'ed.

**Comment by ehelms** [comment]
Squash and then ACK

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
