### PR TITLE
Fixes #14915: make use of Pulp's incremental repomd feature

### PR DESCRIPTION
**Pull request by beav**
Newer versions of Pulp have a `incremental_repomd` flag. This allows
incremental exports to be in the same format as "regular" exports.

This patch allows Katello to use this new flag. It also removes Katello's
special handling of incremental imports which was very slow and is no longer
needed.

### CODE REVIEW

**Comment by beav** [comment]
do not merge until Pulp 2.9.0 is available!

**Comment by beav** [comment]
yay 2.9.1 is in nightly! removing "DO NOT MERGE" warning.

**Comment by beav** [comment]
@Katello/katello-core anyone up for reviewing this? It got moved off the first page of PRs since its from May and required Pulp 2.9 which is now tagged in.

**Comment by johnpmitsch** [comment]
@beav how do you recommend testing it?

**Comment by beav** [comment]
@johnpmitsch something like this should work:

 * create a product with a yum repo, sync repo
 * wait five minutes
 * via the web UI or hammer, upload an RPM to the yum repo you created
 * run this: `hammer repository export --id <ID> --since <ISO8601 date>`, where the date is within that 5 minute range

This should create an export with just the one RPM you uploaded, but *without* a json file. It should create a repodata dir, indicating the yum repo is syncable.

**Comment by beav** [comment]
@johnpmitsch there is also https://github.com/Katello/katello.org/pull/287/files which is a docs update in this area if you are interested in reviewing them both at once :koala:

**Comment by johnpmitsch** [comment]
@beav 

```
2016-08-30T17:17:57 fc96f6f9 [app] [I] Completed 500 Internal Server Error in 273ms (Views: 0.3ms | ActiveRecord: 75.5ms)
2016-08-30T17:17:57 fc96f6f9 [app] [D] With body: {"displayMessage":"ERF42-3196 [Foreman::Exception]: Unable to export, 'pulp_export_destination' setting is not set to a valid directory.","errors":["ERF42-3196 [Foreman::Exception]: Unable to export, 'pulp_export_destination' setting is not set to a valid directory."]}
 |
```

Do I have to add this setting to my katello.yaml file?

**Comment by beav** [comment]
@johnpmitsch oh that dir is not created in a dev setup. It defaults to `/var/lib/pulp/katello-export`, if you create it and change ownership to `vagrant:vagrant` (or whoever you run rails server as) it should work.

re: the `--since` time, the timestamp should be somewhere within the 5 min range. So if you exported at 12:00 and uploaded at 12:05, 12:03 would be a good value. The trick is you need to pick something that's later than the original sync, but further back that the upload, so you get just the one file you uploaded when exporting.

**Comment by johnpmitsch** [comment]
@beav 
After running
```
hammer repository export --id 10 --since "2016-08-30T16:57:59-04:00"
```
I see a folder created :+1: 
```
[vagrant@chicken hammer-cli-katello{master}]$ ls /var/lib/pulp/katello-export/
Default_Organization-prod2-zoo-incremental
```
With no json file in that directory

ACK (unless I tested wrong) :smile:

**Comment by beav** [comment]
@johnpmitsch thanks!

**Pull request merged**
