### PR TITLE
Fixes #22726: add RH subscriptions skeleton page.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/22726

### CODE REVIEW

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by tstrachota** [comment]
:+1: works fine, no comments about the code.

**Comment by waldenraines** [comment]
> 👍 works fine, no comments about the code.

I'm taking that as permission to merge :)

**Pull request merged**
