### PR TITLE
[WIP] Fixes #10970:  upgrade Katello to rails 4

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/10970

Todo
 - [x] Get https://github.com/Katello/katello/pull/5338 merged.
 - [ ] Fix tests
 - [ ] Figure out why bastion pages are 404s
 - [ ] Fix dashboard
 - [ ] Fix sync status

### CODE REVIEW

**Comment by ehelms** [comment]
Are there changes that are backwards compatible to 3.X within the scope of these changes?

**Comment by waldenraines** [comment]
> Are there changes that are backwards compatible to 3.X within the scope of these changes?

Those changes have been merged with #5338.

**Comment by ehelms** [comment]
For those of us not working directly on Rails 4, I think it might help to enumerate the categories of changes with short explanations to help with review. For example, removing attr_accessible, and changing restrict to restrict_with_error.

**Comment by waldenraines** [comment]
Closing as @komidore64 and @cpeters have picked this up.

**Pull request closed without merging**
