### PR TITLE
Fixes #27250 - docker manifest downloaded not used

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
rubocop failure:

```
[2019-07-09T17:38:59.817Z] /home/jenkins/workspace/katello-pr-test/app/services/katello/pulp/docker_manifest.rb:8:59: C: Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

[2019-07-09T17:38:59.817Z]                           :digest => backend_data[:digest],
```

**Comment by ianballou** [comment]
Should be fixed, thanks for listing that @jlsherrill

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jlsherrill** [comment]
mind removing this field from the fixtures? https://github.com/Katello/katello/blob/master/test/fixtures/pulp/docker_manifests.yml#L14   and https://github.com/Katello/katello/blob/master/test/fixtures/pulp/docker_manifest_lists.yml#L6

**Pull request merged**
