### PR TITLE
Fixes #17400: Use ca_cert to talk to Pulp

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires https://github.com/Katello/runcible/pull/183 to work properly. This can be tested via the same basic idea from:

https://github.com/Katello/katello/pull/6459#issuecomment-261256578

Deployment changes via: https://github.com/Katello/puppet-katello/pull/155

**Comment by jlsherrill** [comment]
Need updates for ping

**Comment by ehelms** [comment]
Updated to fix the Ping for Pulp without auth, which led me to DRY up some of the code I had introduced. Please check Candlepin status as well when reviewing.

**Comment by jlsherrill** [comment]
APJ

**Pull request merged**
