### PR TITLE
Fixes #18403 - Add rake task to regenerate ueber certs

### PR DESCRIPTION
**Pull request by johnpmitsch**
This is a necessary step after the CA has changed for
any reason (like using katello-change-hostname)

### CODE REVIEW

**Comment by johnpmitsch** [comment]
on 3.3:

1) installed a content smart proxy and synced
2) performed a hostname change on the katello server
3) ran 
```
::Organization.all.each do |org|
  ::Katello::Resources::Candlepin::Owner.generate_ueber_cert(org.label)
end
```
4) installed a new smart proxy (same org) and was able to sync it fine

**Comment by jlsherrill** [comment]
Mind adding a test for this?  Rake tasks tend to break and no one notices till a user tries to use it

**Comment by jlsherrill** [comment]
ACK pending a test

**Comment by johnpmitsch** [comment]
@jlsherrill updated

**Pull request merged**
