### PR TITLE
Fixes #25954 - fix capsule refresh for cvpe

### PR DESCRIPTION
**Pull request by jlsherrill**
This did not take Content view puppet environments
into account

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test
1) setup an external smart proxy, assign it to some environment 'Dev'
2) upload a puppet module to a puppet repo
3) create a cv, add the puppet module to the puppet repo
4) publish and  promote to Dev
5) check monitor > tasks to verify that capsule synced worked fine
6) go to the infrastructure > Smart proxies page, click on your external smart proxy
7) perform an optimized sync on the smart proxy

**Comment by sjha4** [comment]
[test katello]
So with these changes on the reproducer, no longer able to see the error.
Was not able to reproduce this on local setup with puppet modules which is strange. This change however is necessary. APJ :+1:

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by evgeni** [comment]
tests are blocked on https://github.com/theforeman/foreman/pull/6447 :(

**Comment by iNecas** [comment]
https://github.com/theforeman/foreman/pull/6447 has been merged

**Comment by evgeni** [comment]
[test katello]

**Pull request merged**
