### PR TITLE
Fixes #24671 - remove dead sync plan code

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by sjha4** [comment]
Do we need to remove these as well?
https://github.com/Katello/katello/blob/961148c07b550096bd8ec9b57dd5b3cc5a8bbed3/app/lib/actions/katello/repository/sync.rb#L39

https://github.com/Katello/katello/blob/2d170866abd0ebae1cb530f14e0fb5ace772f3dc/app/lib/actions/katello/product/create.rb#L28

https://github.com/Katello/katello/blob/75c442286e7d9b9479dabb21483cea6e93bf6696/app/lib/actions/pulp/repository/ensure_sync_notification.rb#L6

I am hitting the following error when syncing repository:
`NoMethodError undefined method 'ensure_sync_notification' for #<Class:0x0000000cc8c948>`

**Comment by jlsherrill** [comment]
@sjha4 good catch! updated

**Comment by jlsherrill** [comment]
@sjha4 its because your system is still configured to use a sync notifier.  I guess your rake task hadn't been run yet to remove those on your box? :)

**Pull request merged**
