### PR TITLE
Refs #10970 - Rails4 Substitute find_or_create_by with first_or_create

### PR DESCRIPTION
**Pull request by johnpmitsch**
find_or_create_by with old hash style is deprected in rails 4, updating to use where(args).first_or_create

### CODE REVIEW

**Comment by cpeters** [comment]
ACK pending successful test results

**Comment by johnpmitsch** [comment]
[test]

**Comment by johnpmitsch** [comment]
@ehelms Not sure why there are syntax errors on one of foreman's gem files, but I can investigate further tomorrow. Please let me know if you have any insight.

**Comment by johnpmitsch** [comment]
[test]

**Comment by johnpmitsch** [comment]
[test]

**Pull request merged**
