### PR TITLE
fixes #10537 - Fixes toggle issue when switching between subscription panes on content host, BZ1207488

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
This needs a fix to the commit message and PR title.

**Comment by ehelms** [comment]
Functionally this works, just need to fix any test errors and the commit message.

**Comment by cfouant** [comment]
@ehelms - commit message fixed and tests as well.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
