### PR TITLE
Fixes #32087 - fix test failure around template kinds

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
ACK

**Review by jeremylenz — APPROVED** [review]
LGTM :+1: 
APJ

**Comment by jlsherrill** [comment]
[test katello]

**Comment by ares** [comment]
was this the right fix to merge? I thought https://github.com/Katello/katello/pull/9137 was fixing the cause without removing the valid tests (I may be cmpletely wrong)

**Pull request merged**
