### PR TITLE
Katello 2.4.0 backports

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by parthaa** [comment]
apj

**Comment by jlsherrill** [comment]
Had to lock foreman-docker to lower version, jenkins kicked off here:  http://ci.theforeman.org/job/test_katello_pull_request/7962/

**Comment by jlsherrill** [comment]
1.9.3  is green:  http://ci.theforeman.org/job/test_katello_pr_core/1085/database=postgresql,ruby=1.9.3/

**Comment by ehelms** [comment]
ACK

**Comment by jlsherrill** [comment]
pushed a few more commits:  http://ci.theforeman.org/job/test_katello_pull_request/

**Comment by ehelms** [comment]
APJ

**Comment by jlsherrill** [comment]
Green ruby 193:  http://ci.theforeman.org/job/test_katello_pr_core/1087/database=postgresql,ruby=1.9.3/

**Pull request merged**
