### PR TITLE
Rails 4 ActiveRecord query changes

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by komidore64** [comment]
i'm just guessing that these tests are going to fail, but we'll see what happens.

**Comment by cpeters** [comment]
They should fail. Small incremental progress.

**Comment by ehelms** [comment]
I assume you are still going to mark each PR with an issue + single commit unless you are squashing the entire Rails 4 branch to a single commit before it gets merged to master?

**Comment by cpeters** [comment]
What makes the most sense?

**Comment by ehelms** [comment]
Typically in a branch we stick to the 1 PR = 1 issue and mark it the same as master so its logical chunks and easier to track historically.

**Comment by komidore64** [comment]
best to reference redmine issue [10970](http://projects.theforeman.org/issues/10970)

**Comment by komidore64** [comment]
ACK

**Pull request merged**
