### PR TITLE
Fixes #31322 - repo update fails immediately after repo create

### PR DESCRIPTION
**Pull request by ianballou**
Updating a repo can fail if it runs immediately after repo creation due to a race condition with MetadataGenerate.  If the time gap between the two actions is small enough, the DistributionReference won't exist and the second MetadataGenerate will try to create the distribution again instead of updating it.

To test:
Run this playbook after creating "Test Product" on a production machine to reproduce the error (dev machines seem to be too slow):
```yaml
---
- hosts: localhost
  collections:
    - theforeman.foreman
  gather_facts: false
  vars:
    foreman_username: admin
    foreman_password: "changeme" 
    foreman_server_url: "https://your_fqdn" 
    foreman_validate_certs: false
    organization_name: "Default Organization" 
    product_name: "Test Product" 
    repository_name: "Test Repository" 
    repository_content_type: "yum" 
    repository_label: "just_a_test_repo" 
    repository_mirror_on_sync: false
    repository_url: "https://repos.fedorapeople.org/pulp/pulp/demo_repos/zoo/" 
    repository_state: present
  tasks:
    - name: create repo
      repository:
        username: "{{ foreman_username }}" 
        password: "{{ foreman_password }}" 
        server_url: "{{ foreman_server_url }}" 
        validate_certs: "{{ foreman_validate_certs }}" 
        organization: "{{ organization_name }}" 
        name: "{{ repository_name }}" 
        label: "{{ repository_label | default(omit) }}" 
        mirror_on_sync: False
        state: "{{ repository_state }}" 
        product: "{{ product_name }}" 
        content_type: "{{ repository_content_type }}" 
        url: "{{ repository_url | default(omit) }}" 

    - name: update repo
      repository:
        username: "{{ foreman_username }}" 
        password: "{{ foreman_password }}" 
        server_url: "{{ foreman_server_url }}" 
        validate_certs: "{{ foreman_validate_certs }}" 
        organization: "{{ organization_name }}" 
        name: "{{ repository_name }}" 
        label: "{{ repository_label | default(omit) }}" 
        mirror_on_sync: True
        state: "{{ repository_state }}" 
        product: "{{ product_name }}" 
        content_type: "{{ repository_content_type }}" 
        url: "{{ repository_url | default(omit) }}" 
```

### CODE REVIEW

**Comment by ianballou** [comment]
I'm trying a different strategy here, so wait on reviewing for now.

**Comment by ianballou** [comment]
Looks like I have a lot of VCRs to re-record.

**Comment by ianballou** [comment]
This is all set to test now.

**Review by jjeffers — APPROVED** [review]
Tested this on a multi core VM with katello 3.18, which reliably recreated the issue. Applied the PR (as a patch) to the system, and the problem appears to be resolved.

APJ

**Pull request merged**
