### PR TITLE
Fixes #25605 - drop hypervisor_guest_uuids from SubscriptionFacet

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by beav** [comment]
It looks like `guestIds` is cut out here as well:

```ruby
      def finalize_registration(host)
        host = ::Host.find(host.id)
        host.subscription_facet.update_from_consumer_attributes(host.subscription_facet.candlepin_consumer.
            consumer_attributes.except(:guestIds, :facts))
        host.subscription_facet.save!
        host.subscription_facet.update_subscription_status
        host.content_facet.update_errata_status
        host.refresh_global_status!
      end
```

The change seems OK to me, but let's give it a couple days for further comment.

**Comment by evgeni** [comment]
But the line is never executed, because `consumer_params` never has both `hypervisor_guest_uuids` AND `guestIds`. And if I change the check, I get an error as posted in the redmine issue.

**Comment by jlsherrill** [comment]
Oh you're right, it gets transformed to 'guestIds' here: https://github.com/Katello/katello/blob/master/app/controllers/katello/api/v2/host_subscriptions_controller.rb#L100

**Comment by jlsherrill** [comment]
Thanks @evgeni

**Pull request merged**
