### PR TITLE
refs #8477 - remove defaulting of foreman templates

### PR DESCRIPTION
**Pull request by stbenjam**
In 1.8 (https://github.com/theforeman/foreman/pull/1973), Foreman does this itself.

### CODE REVIEW

**Comment by domcleal** [comment]
@stbenjam ticket "8477", not "8447"

**Comment by stbenjam** [comment]
Oh ffs, I should get tested, this is like the 4th bug I've done this to recently.

**Comment by stbenjam** [comment]
Thanks @domcleal !

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
Thanks @ehelms

**Pull request merged**
