### PR TITLE
fixes #9360 - set feature flag host collection actions

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by cfouant** [comment]
This needs to hide the route for "Change assigned lifecycle environment or content view". You can do so by adding `content-hosts.bulk-actions.environment` to the remote actions list in (../blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/katello-features.run.js)

**Comment by thomasmckay** [comment]
@cfouant - updated, thanks for noticing that!

**Comment by cfouant** [comment]
ACK

**Pull request merged**
