### PR TITLE
fixes #12297 - removes max of 5 limit on selector value, BZ1266310

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
APJ -- you don't need to include the BZ number in the commit anymore

**Comment by thomasmckay** [comment]
NACK ... This is not going to work for larger subscription quantities. The correct fix is to make it an editable choice box with a small number of choices (such as I had before). Please revert this PR. Thanks!

**Comment by cfouant** [comment]
@thomasmckay - I'm not seeing this functionality you mention in the history. Previously, it would show 1-5 or the max quantity, there was no editable choice box (so say, 9 wouldn't be an option for a subscription with 20 available, only 1-5 and 20). The subscription box does include a scroll, so how does it not work for larger quantities?

**Comment by thomasmckay** [comment]
Sorry, I meant that the existing methodology (smallest, largest, plus a few in between) should be choices as before. Do you think having a choice box of 1 to 1000 would be usable? Even 1 to 20 would be painful to look at. Also note that creating dropdowns with 100s of values is slow (or at least was). You can try this by modifying the cp psql directly and increasing the quantities. Make sure you have multiple subscriptions listed, each with at least a 1000 quantity.

Adding an text field would be a good solution: Use a built in choice or specify a number explicitly.

**Pull request merged**
