### PR TITLE
Fixes #26547 - truncate package list in audit

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by bbuckingham** [comment]
@ares, The change looks good; however, should we also apply the same to the following host actions:

```
./erratum/install.rb:            host.update(audit_comment: _("Installation of errata requested: %{errata}") % {errata: input[:errata].join(", ")})
./package/install.rb:            host.update(audit_comment: _("Installation of package(s) requested: %{packages}") % {packages: input[:packages].join(", ")})
./package/remove.rb:            host.update(audit_comment: _("Removal of package(s) requested: %{packages}") % {packages: input[:packages].join(", ")})
./package_group/install.rb:            host.update(audit_comment: _("Installation of package group(s) requested: %{groups}") % {groups: input[:groups].join(", ")})
./package_group/remove.rb:            host.update(audit_comment: _("Removal of package group(s) requested: %{groups}") % {groups: input[:groups].join(", ")})

```

**Comment by ares** [comment]
Thanks @bbuckingham, good catch! Updated everywhere.

**Comment by jturel** [comment]
[test katello]

**Comment by bbuckingham** [comment]
Tests are :green_heart: , merging...

**Comment by ares** [comment]
Thank you!

**Comment by rplevka** [comment]
It would be also nice to implement an unit test  for this

**Pull request merged**
