### PR TITLE
fixes #24239 - fix tests environment taxonomies validation

### PR DESCRIPTION
**Pull request by iNecas**
Required for https://github.com/theforeman/foreman/pull/5793

### CODE REVIEW

**Comment by stbenjam** [comment]
I *think* this should probably have a Katello issue linked to the foreman one, to ensure we triage it and it gets aligned to a release

**Comment by stbenjam** [comment]
Although it's just a test, so I'm not sure it really matters

**Comment by iNecas** [comment]
Updated

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
