### PR TITLE
Fixes #25344 - subclass error with db:migrate

### PR DESCRIPTION
**Pull request by sean797**
Without this, I get the error in the Redmine issue. Fix came from @tbrisker :+1:

### CODE REVIEW

**Comment by beav** [comment]
:robot: https://projects.theforeman.org/issues/25344 :robot:

**Comment by beav** [comment]
@sean797 the code change looks ok. How do you repro the issue?

**Comment by jlsherrill** [comment]
When using classes within a migration (rather than pure db schema modifications), the order that migrations are run in can play a HUGE part in errors that occur, meaning you may not see upgrade errors until we start testing with user data.

**Comment by beav** [comment]
@jlsherrill with pleasure!

@jlsherrill @sean797 @tbrisker thanks for the PR + reviews!

:goat:

**Pull request merged**
