### PR TITLE
Fixes #25911 - remove components from Katello's 'move_to_foreman'

### PR DESCRIPTION
**Pull request by MariaAga**
Remove the ~~'ConfirmDialog', 'Dialog',~~ 'ModalProgressBar' and 'Settings' Components from Katello
Remove some of the helper functions from Katello
PR for adding these files to foreman: https://github.com/theforeman/foreman/pull/6441
PR for changing 'ConfirmDialog', 'Dialog' to 'MessageDialog': https://github.com/Katello/katello/pull/7970

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
@MariaAga looks like there is now a merge conflict

**Comment by sharvit** [comment]
Can you update the PR based on the latest changes in https://github.com/theforeman/foreman/pull/6441?

**Comment by MariaAga** [comment]
@sharvit It is already updated

**Comment by sharvit** [comment]
@MariaAga notice relevant test errors

**Comment by MariaAga** [comment]
@sharvit tests are failing with this error: `Can't resolve 'foremanReact/common/urlHelpers'`
Which makes sense as the Foreman PR is not merged yet, therefore the file doesn't exists yet

**Comment by sharvit** [comment]
@MariaAga I have tested the build in production and everything works as expected.

LGTM but let's wait for https://github.com/theforeman/foreman/pull/6441 to get merged and then retrigger CI builds to make sure CI doesn't break.

**Comment by mmoll** [comment]
Foreman core PR got merged.

**Comment by sharvit** [comment]
[test katello]

**Comment by sharvit** [comment]
@MariaAga is this PR still WIP?

**Comment by waldenraines** [comment]
> @MariaAga is this PR still WIP?

It seems like now that https://github.com/theforeman/foreman/pull/6441 is merged we should be able to retest this and merge it.  @MariaAga please remove the [WIP] if it's ready to be reviewed.

**Comment by sharvit** [comment]
The [Blocked by another PR](https://github.com/Katello/katello/labels/Blocked%20by%20another%20PR) label can be removed

**Comment by mmoll** [comment]
Maybe this also needs a rebase

**Comment by MariaAga** [comment]
This has been re based

**Comment by mmoll** [comment]
all :green_heart: now

**Comment by MariaAga** [comment]
@waldenraines Can you remove the `Blocked by another PR` label?

**Comment by waldenraines** [comment]
> @waldenraines Can you remove the `Blocked by another PR` label?

Done, sorry I neglected to do this prior.

**Comment by MariaAga** [comment]
@waldenraines about the remaining components:
move_to_foreman/common/helpers.js - 
Is a helper for the Subscriptions component only.
move_to_foreman/components/common/table - 
I understood that we are going to change soon the table component in Foreman/Katello to a new table component and this one is going to be deleted

**Comment by waldenraines** [comment]
@MariaAga any thoughts on the above JS error?

**Comment by MariaAga** [comment]
@waldenraines just got my Katello env running today, I didn't get these errors while going back to the subscriptions page when a task is running, or while refreshing a manifest.

**Comment by waldenraines** [comment]
> @waldenraines just got my Katello env running today, I didn't get these errors while going back to the subscriptions page when a task is running, or while refreshing a manifest.

I no longer get this error either.

**Pull request merged**
