### PR TITLE
Fixes #21357 - stop using TaxonomyScope concern

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
Running together with modified Foreman at http://ci.theforeman.org/job/test_katello_pull_request/12735/

**Comment by iNecas** [comment]
Rubocop is failing so far so the tests are red.

**Comment by iNecas** [comment]
Pending the main PR merge + rubocop (haven't seen the tests results yet)

**Comment by ares** [comment]
new run with Foreman at http://ci.theforeman.org/job/test_katello_pull_request/12750/

**Comment by akofink** [comment]
Hmm... I believe there is an issue in [katello's `find_organization` method](https://github.com/Katello/katello/blob/master/app/controllers/katello/api/v2/api_controller.rb#L133). This was found by trying to create a lifecycle environment in a non-default organization.

The 'Test' environment exists in organization with ID 1 (aka Organization.current for admin user).

```
# POST /katello/api/v2/organizations/11/environments
params:
{
	"name": "Test",
	"label": "Test",
	"prior_id": 16,
	"api_version": "v2",
	"organization_id": 11,
	"environment": {
		"name": "Test",
		"label": "Test",
		"prior_id": 16
	}
}
```
I think we need to modify `find_organization` to prefer params over `Organization.current`.

**Comment by ares** [comment]
@akofink could you or someone else merge please? I don't have perms here

**Comment by ekohl** [comment]
@ares you can see from his gray approval that he has no permissions. If he had it would be green.

**Comment by akofink** [comment]
Yeah, maybe @jlsherrill has perms.

**Comment by ares** [comment]
Oh, I haven't realized, sorry

**Comment by bbuckingham** [comment]
@ares, @akofink, thanks! merging

**Pull request merged**
