### PR TITLE
Fixes #16575 - Increase UI poll time

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@jlsherrill its possible I don't have something set up correctly, but I am seeing a task refresh the  UI every couple seconds or so, it doesn't seem like this has changed anything.

**Comment by jlsherrill** [comment]
@johnpmitsch which page did you try it on?  Also did you refresh your browser after checking out the change?

**Comment by johnpmitsch** [comment]
@jlsherrill I synced a large repo and went to the individual task page (clicking 'more details'). I restarted the server and did a hard refresh after checking this out, though its possible I goofed something up

**Comment by jlsherrill** [comment]
Ahhh, that code resides in ForemanTasks.  The polling here is on any katello page using bastion, that initial progress bar before clicking 'more details', content view publish, etc...

**Comment by johnpmitsch** [comment]
@jlsherrill oh ok, I'll just check that then and report back :smile:

**Comment by johnpmitsch** [comment]
ACK 

Up to you if you want @waldenraines or @ehelms to review before merging

**Comment by waldenraines** [comment]
I'm fine with it, but I'm also not too familiar with this code.

**Pull request merged**
