### PR TITLE
Refs #25180 - Fix product list on RH repos

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I set this boolean wrong in https://github.com/Katello/katello/pull/7928

**Comment by sjha4** [comment]
[test katello] 
Failure does not look related to the PR.

**Comment by evgeni** [comment]
I think the tests are broken due to https://github.com/theforeman/foreman/commit/202c65d0efc0345b883ba6d1e70aedc90b3d5294, @jlsherrill is looking into it :green_heart:

**Comment by jlsherrill** [comment]
[test katello]

**Comment by johnpmitsch** [comment]
[test katello]

**Pull request merged**
