### PR TITLE
Fixes #4796: Use Patternfly from Foreman core

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires https://github.com/Katello/bastion/pull/88

**Comment by stbenjam** [comment]
From a functionality perspective, this and bastion PR work for me.

@Katello/ui folks should review these from a code perspective

**Comment by ehelms** [comment]
[test]

**Comment by johnpmitsch** [comment]
I am seeing http://www.clipular.com/c/5101877532819456.png?k=kFyOaec_5zSZqzmr2Ep_L2R_r3M when using this PR with https://github.com/Katello/bastion/pull/88

**Comment by stbenjam** [comment]
@johnpmitsch Are you running latest foreman develop?

**Comment by johnpmitsch** [comment]
@stbenjam just double checked, yes, its the latest foreman develop

**Comment by ehelms** [comment]
See - https://github.com/theforeman/foreman/pull/3031

**Comment by waldenraines** [comment]
It looks like the placement of the actions and total selected count is incorrect on the product repositories page:

screen shot 2016-01-08 at 9 35 54 am

**Comment by waldenraines** [comment]
The create new GPG keys page looks odd to me:

screen shot 2016-01-08 at 9 49 18 am

**Comment by waldenraines** [comment]
The new sync plans button is missing the '+' (this could have been from before but if you don't mind fixing that would be great):

screen shot 2016-01-08 at 9 54 31 am

**Comment by waldenraines** [comment]
Looks good other than the comments above.  Tested pretty much everything I could think of.

**Comment by ehelms** [comment]
This depends on the width of your browser -- on my laptop it appears fine
until I shrink it. The minimum width needed to see this effect could have
changed so I can adjust the columns in use if you like.

On Fri, Jan 8, 2016 at 9:47 AM, Walden Raines <notifications@github.com>
wrote:

> It looks like the placement of the actions and total selected count is
> incorrect on the product repositories page:
>
> [image: screen shot 2016-01-08 at 9 35 54 am]
> <https://cloud.githubusercontent.com/assets/4116405/12200436/d913526e-b5ec-11e5-9e98-26bf88b3aaae.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Katello/katello/pull/5687#issuecomment-170021771>.
>



-- 
Eric D. Helms
Red Hat Engineering
Ph.D. Student - North Carolina State University

**Comment by waldenraines** [comment]
> This depends on the width of your browser -- on my laptop it appears fine
> until I shrink it. The minimum width needed to see this effect could have
> changed so I can adjust the columns in use if you like.

But it appears fine for me on other details-nutupane pages.

**Comment by ehelms** [comment]
I don't see any other pages that have the number of action buttons repositories has - so we'd either need to change the rows in the details nutupane as a whole or leave it be. Looks like right now that is broken into a 4, 3, 4 which would leave 1 left over that I could expand the final 4 to a 5. Or change to 4,2,6 which worked down to a viewport width of 1300 for me.

**Comment by dLobatog** [comment]
:+1: , I didn't notice any discrepancies. Kind of related, this fix https://github.com/Katello/katello/pull/5696 will add all bastion changes to precompile so it works in develop with https://github.com/theforeman/foreman/pull/3031

**Comment by ehelms** [comment]
Manual green run in the CI system -- http://ci.theforeman.org/job/test_katello_pull_request/8014/ so this PR will fix test_katello and get PRs back to running.

**Comment by waldenraines** [comment]
> I don't see any other pages that have the number of action buttons repositories has - so we'd either need to change the rows in the details nutupane as a whole or leave it be. Looks like right now that is broken into a 4, 3, 4 which would leave 1 left over that I could expand the final 4 to a 5. Or change to 4,2,6 which worked down to a viewport width of 1300 for me.

Using the change you suggested:

```diff
diff --git a/app/assets/javascripts/bastion/layouts/details-nutupane.html b/app/assets/javascripts/bastion/layouts/details-nutupane.html
index 796e057..51534dc 100644
--- a/app/assets/javascripts/bastion/layouts/details-nutupane.html
+++ b/app/assets/javascripts/bastion/layouts/details-nutupane.html
@@ -33,11 +33,11 @@
       </div>
     </div>

-    <div class="col-sm-3">
+    <div class="col-sm-2">
       <span class="nutupane-info" data-block="result-count" translate>Showing {{ detailsTable.rows.length }} of {{ detailsTable.resource.subtotal }} ({{ detailsTable.resource.total }} Total)</span>
     </div>

-    <div class="col-sm-4 fr">
+    <div class="col-sm-6 fr">
       <div class="fr">
         <span class="nutupane-info fl" data-block="selection-summary">
           <span translate>{{ detailsTable.numSelected }} Selected</span>
```

Fixes the page and doesn't seem to cause any collateral damage that I can see.

ACK pending opening an issue for changing the column widths in bastion.

**Comment by ehelms** [comment]
@waldenraines Created here to tackle in next minor release of bastion -- http://projects.theforeman.org/issues/13159

**Comment by ehelms** [comment]
Thanks for reviews!

**Pull request merged**
