### PR TITLE
Fixes #18049: remove nutupane from environment pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/18049

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/158 and https://github.com/Katello/bastion/pull/160

**Comment by jlsherrill** [comment]
[test]

**Comment by waldenraines** [comment]
> The filter dropdowns are appearing in a strange location beneath the search:

Do you have any other idea where they should go?  This isn't really addressed by patternfly's full page table design.

**Comment by ehelms** [comment]
Looking at (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html?#) I'd think to the left of the search box itself or to the right of the search/bookmarks.

**Comment by waldenraines** [comment]
@Rohoover any thoughts on what to do with our secondary filters?

**Comment by Rohoover** [comment]
If the dropdown affects the filter search, then I would put it to the left of the input box. 

Patternfly currently has a team together that is looking at filter/search across applications to create more unified components.

**Comment by waldenraines** [comment]
@ehelms issue for fixing the filters in bastion:  http://projects.theforeman.org/issues/18184

**Comment by waldenraines** [comment]
> @ehelms issue for fixing the filters in bastion: http://projects.theforeman.org/issues/18184

I would like to handle this outside this PR because multiple pages have this same issue.

**Comment by ehelms** [comment]
OK - can we fix the environment highlight problem then that I pointed out in the puppet module PR?

**Comment by waldenraines** [comment]
> OK - can we fix the environment highlight problem then that I pointed out in the puppet module PR?

I believe this happens in master as well.  I'd rather fix this outside the PR if possible so as to not delay this PR as I have some change I'd like to make that are dependent on nutupane being gone across the applciation.

**Comment by ehelms** [comment]
@waldenraines works for me, got an issue for it already?

**Comment by waldenraines** [comment]
> @waldenraines works for me, got an issue for it already?

http://projects.theforeman.org/issues/18203

**Pull request merged**
