### PR TITLE
Fixes #32379 -  Autopublish switch reloads entire page

### PR DESCRIPTION
**Pull request by Andrewgdewar**
#### What are the changes introduced in this pull request?
Prevents full page reload when updating information on the content view info page, as well as on the repository review after adding or removing a repo.

#### What are the testing steps for this pull request?
- Go to the contentView details page and change name, description and autopublish. 
- Only the change detail item should show a spinner.

- Go to repositories and add/remove repos. (bulk or not)
- Only the repo sub-page should update.

### CODE REVIEW

**Review by sjha4 — APPROVED** [review]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Review by jeremylenz — CHANGES_REQUESTED** [review]
Thanks for taking a look at this @Andrewgdewar!

I notice the page now doesn't need to reload when you make changes on either Details or Repositories tab. :heavy_check_mark:   But I'm still hoping it can be one step better. As I wrote in the original bug,

"When I toggle autopublish for a content view, it shouldn't have to display a spinner for the entire page. The spinner should be localized to the switch element only."

I'm still seeing the spinner visually replace the entire form. I was hoping the visual disruption could be either eliminated, or localized to only the form field you're editing-- whether that's a spinner, skeleton, or etc.

**Comment by sjha4** [comment]
[test katello]

**Comment by Andrewgdewar** [comment]
@jeremylenz  Done!

**Review by jeremylenz — CHANGES_REQUESTED** [review]
When I submit an edit, there's one render where the spinner is ridiculously large:

spinner_huge

To see it, put a debugger on line 58 of `EditableTextInput.js` before the `await`.  Or set the CPU to 6x slowdown in the Performance tab of chrome dev tools.

I think it's something to do with the `<EmptyState>` inside `<Loading>`, but not sure..

**Comment by Andrewgdewar** [comment]
> When I submit an edit, there's one render where the spinner is ridiculously large:
> 
> spinner_huge
> 
> To see it, put a debugger on line 58 of `EditableTextInput.js` before the `await`. Or set the CPU to 6x slowdown in the Performance tab of chrome dev tools.
> 
> I think it's something to do with the `<EmptyState>` inside `<Loading>`, but not sure..

I was hoping to get away without touching details. I'll take a look.

**Comment by Andrewgdewar** [comment]
@jeremylenz  Updated so that the same spinner is used in all inline editable fields.
You can see this working in filterDetails (for name/description) as well as in ContentViewVersionDetails for description.

**Review by jeremylenz — APPROVED** [review]
Works well now, LGTM :+1:

**Pull request merged**
