### PR TITLE
Fixes #14207 - skip failed publish and promote steps involving capsules

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
What makes the skips specific to Capsules?

**Comment by jlsherrill** [comment]
It means to skip any failures in the run or finalize phases of those actions if there is a failure. The only other thing happening during those phases is the content view history updating which really shouldn't fail and if it does really isn't important enough to cause the task to be paused

**Comment by jlsherrill** [comment]
Testing note:

With a capsule configured for Library and Dev, shut down httpd on the capsule. 

Create a repo, sync it.
Publish it in a content view
Promote it to Dev

all 3 of these actions should NOT result in a paused task.

**Comment by johnpmitsch** [comment]
publishing a content view was a paused task: http://www.clipular.com/c/6745925920227328.png?k=YVYuwlYiELdOsaU_eAEb-XysUa8

**Comment by johnpmitsch** [comment]
here is the task with the error http://www.clipular.com/c/5247247279718400.png?k=-vxy9xMpwCzJ0RvtwnHXcZDf2bI

**Comment by johnpmitsch** [comment]
@jlsherrill Not sure what I was seeing before, but I was unable to reproduce it as well

**Comment by johnpmitsch** [comment]
ACK unless you think we should look into what I saw, I suspect it is just something strange in my environment or from switching branches.

**Pull request merged**
