### PR TITLE
Fixes #36172 - Add ellipsis to columns in hosts index

### PR DESCRIPTION
**Pull request by adamruzicka**
A companion to https://github.com/theforeman/foreman/pull/9629

### CODE REVIEW

**Comment by jeremylenz** [comment]
@adamruzicka Works well, can you please fix the Redmine project?

**Comment by jeremylenz** [comment]
[test redmine]

**Comment by adamruzicka** [comment]
There, fixed

**Review by jeremylenz — APPROVED** [review]
APJ :+1:

**Pull request merged**
