### PR TITLE
Fix some cops

### PR DESCRIPTION
**Pull request by archanaserver**
#### What are the changes introduced in this pull request?
Based on https://github.com/Katello/katello/pull/11009

This pull request addresses the Style/TrailingCommaInArrayLiteral RuboCop offense by ensuring that all multiline array literals in the codebase have a trailing comma after the last item.

#### Considerations taken when implementing this change?
Ensured that all multiline array literals are updated uniformly with trailing commas.
Verified that the changes do not impact existing functionality or cause syntax errors.

#### What are the testing steps for this pull request?
`bundle exec rubocop`

### CODE REVIEW

**Comment by ianballou** [comment]
This PR has no changes in it.

**Comment by ianballou** [comment]
I think a rebase is needed.

**Comment by archanaserver** [comment]
@ianballou so i tested with this changes https://github.com/Katello/katello/pull/11064/commits/7efa86e9adff456d8849140be43797043e160342, and it is working fine, at least rubocop is green

**Comment by archanaserver** [comment]
> @ianballou so i tested with this changes [7efa86e](https://github.com/Katello/katello/commit/7efa86e9adff456d8849140be43797043e160342), and it is working fine, at least rubocop is green

again it is passing rubocop, with https://github.com/Katello/katello/commit/7efa86e9adff456d8849140be43797043e160342 changes. we can merge this one @ianballou.

**Comment by ianballou** [comment]
Seeing one more rubocop issue:
```
Error: unrecognized cop Lint/ConstantDefinitionInBlock found in .rubocop_todo.yml, unrecognized cop Lint/RedundantSafeNavigation found in .rubocop_todo.yml, unrecognized cop Lint/UselessMethodDefinition found in .rubocop_todo.yml, unrecognized cop Style/CombinableLoops found in .rubocop_todo.yml
```

**Comment by archanaserver** [comment]
> Seeing one more rubocop issue:
> 
> ```
> Error: unrecognized cop Lint/ConstantDefinitionInBlock found in .rubocop_todo.yml, unrecognized cop Lint/RedundantSafeNavigation found in .rubocop_todo.yml, unrecognized cop Lint/UselessMethodDefinition found in .rubocop_todo.yml, unrecognized cop Style/CombinableLoops found in .rubocop_todo.yml
> ```

@ianballou it is due to these cops are not compatible with the rubocop version we have in this branch, but i tested with this changes f6a162b4404e9f761db2e3d971086cf68f7db5b0 and it's all green, may be we can merge this one and see it in https://github.com/Katello/katello/pull/11009. i'm not sure if we can do this, like merging this with rubocop failure? WDYT?

**Comment by archanaserver** [comment]
@ianballou this is what i was talking about, if we combine #11064 and #11009, passing all rubocop tests https://github.com/Katello/katello/pull/11093

**Comment by archanaserver** [comment]
> @ianballou this is what i was talking about, if we combine #11064 and #11009, passing all rubocop tests #11093

@ianballou in case you missed it, any thoughts on the recent changes?

**Comment by ianballou** [comment]
@archanaserver rubocop is still failing, was that intentional?

**Comment by archanaserver** [comment]
> @archanaserver rubocop is still failing, was that intentional?

so the changes i have made here, few cops need `gem 'theforeman-rubocop', '~> 0.1.0'`, so that's why the failure was occuring, but i'm trying to do this on our main PR now https://github.com/Katello/katello/pull/11009, where we already upgrade the gem.

**Comment by archanaserver** [comment]
Closing this one, as the commits present here are already merged in https://github.com/Katello/katello/pull/11009

**Pull request closed without merging**
