### PR TITLE
Refs #10970 Merging upstream fix for test fixtures

### PR DESCRIPTION
**Pull request by cpeters**
Fixes #11189 - copy and load fixtures from tmpdir

(cherry picked from commit d1700574401a7da01ceeea31ab792c6763e0e96c)

### CODE REVIEW

**Comment by ehelms** [comment]
This seems like it might cause weirdness when you try to merge it back into master? I've only ever done cherry picks as a backport, not as a backport that is then merged back in.

**Comment by cpeters** [comment]
Is there a work-around; short of copying and pasting the changes?

**Comment by komidore64** [comment]
try it. pretty sure i've seen git notice the the same commit on two branches being merged before and account for it.

**Comment by ehelms** [comment]
They aren't the same commit anymore though with the conflicts IIRC? The hashes are certainly different. But yea, I would suggest trying this locally just to see.

**Comment by cpeters** [comment]
Pull request from cpeters/rails4-test-fixtures into cpeters/master goes cleanly.

**Comment by ehelms** [comment]
To clarify, for the rails4 branch, the tactic is to strategically merge certain commits into it as opposed to periodically merging master in?

**Comment by komidore64** [comment]
i think this PR was created prior to Chris and I discussing a plan for recurring katello/master to katello/rails4 merges to keep rails4 up to date.

**Comment by komidore64** [comment]
this should no longer be necessary as Katello/master (as of sept 10, 2015) [has been merged](https://github.com/Katello/katello/pull/5479) into rails4.

**Pull request closed without merging**
