### PR TITLE
Fixes #17912 - require bastion 4.0.0

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@ehelms notice here i deleted the bastion_katello gemspec.  It doesn't seem to be used by katello nor required (although there could be some edge case i missed testing) and it seemed to confuse people as walden updated its dependencies without updating katello's.  If the gemspec had been used we would have noticed the conflict, but since it wasn't we didn't.

**Comment by ehelms** [comment]
Couple of thoughts:

 1) This would need to be updated -- https://github.com/Katello/katello/blob/9834e25f3d75843dcd5d9e8cfb778212bd96469d/katello.gemspec#L18
 2) Did you test gem and RPM build?
 3) Test in production with it's removal?

**Comment by jlsherrill** [comment]
I will test 2) and 3)  i haven't done that yet.

**Comment by jlsherrill** [comment]
@ehelms tested a gem build and production install and all worked fine

**Comment by ehelms** [comment]
@jlsherrill sounds good -- can you update #1?

**Comment by jlsherrill** [comment]
whoops, thought i did, updated

**Comment by jlsherrill** [comment]
errr wth Github?

**Pull request merged**
