### PR TITLE
Fixes #22384 - turn div back into a form for rex integration

### PR DESCRIPTION
**Pull request by iNecas**
Otherwise, the remote-execution actions don't work as expected.

Steps to reproduce:

1. got to host collections
2. select host collection and enter 'Package Installation, Removal, and Update'
3. try to peform any action via remote execution

### CODE REVIEW

**Comment by waldenraines** [comment]
I think this is fine as long as it doesn't cause a regression of http://projects.theforeman.org/issues/18711 (https://github.com/Katello/katello/pull/6713).

**Comment by iNecas** [comment]
From what I understood, the additional turn of form to div for the hidded fields that we use for rex, was not needed for ##18711

**Comment by waldenraines** [comment]
> From what I understood, the additional turn of form to div for the hidded fields that we use for rex, was not needed for ##18711

Could be.  The problem I was fixing in http://projects.theforeman.org/issues/18711 was related to there being a `<form>` within a `<form>` which is invalid html.

**Comment by waldenraines** [comment]
Thanks @iNecas!

**Pull request merged**
