### PR TITLE
Fixes #6954 - Add additions that allow Foreman tests to pass.

### PR DESCRIPTION
**Pull request by ehelms**
Foreman allows a plugin to provide a file to be loaded during their
test runs. Here we address:
- Dynflow transaction issues due to using hooks on extended Foreman
  models

### CODE REVIEW

**Comment by stbenjam** [comment]
Just curious to see the failures, the previous test results were purged

[test]

**Comment by ehelms** [comment]
If you want to see this run, with Foreman core tests, you'll want to run http://ci.theforeman.org/job/test_katello_core_gsutcliffe/ because our current job doesn't run in this context currently.

**Comment by ehelms** [comment]
As part of this as well, I have been working on making re-usable tasks in the core that plugins can take advantage of as well as run combinations of tests: https://github.com/theforeman/foreman/pull/2571

**Comment by unorthodoxgeek** [comment]
https://github.com/theforeman/foreman/pull/3056 should make this work :smile:

although I really hate this hack. I'd prefer if you found a way for doing this without changing behaviour, as plugins should add behaviour, not change it.

**Comment by beav** [comment]
@ehelms https://github.com/theforeman/foreman/pull/3056 is merged, mind giving this a rebase?

**Comment by beav** [comment]
@ehelms is this still needed? I am not sure of the context of this PR

**Comment by ehelms** [comment]
@beav this is something that would be nice for me to finish, all other plugins run their own tests and all Foreman unit tests combined to verify whether they are breaking core functionality or at least intentionally skipping over it.

**Pull request closed without merging**
