### PR TITLE
Refs #10962 - update to the Dynflow 0.8.1

### PR DESCRIPTION
**Pull request by iNecas**
Since the new Dynflow removes the limitation of on executor running, we need
to handle better the case to make sure only one action is running at a time.

It uses the Dynflow coordination mechanism to make sure we run the action only 
once.

Also, new Dynflow provides before_termination_hooks, that are safer than the 
at_exit.

Requires https://github.com/theforeman/foreman-tasks/pull/116

The RPMs for deps are in progress as well https://github.com/theforeman/foreman-packaging/pull/695

In the meantime, I've prepared scratch for testing https://inecas.fedorapeople.org/dynflow-scratch/ : You will need to update the
gemspec file on your setup
`/opt/rh/ruby193/root/usr/share/gems/specifications/katello-2.3.0.gemspec` to
`s.add_dependency(%q<foreman-tasks>, ["~> 0.7.0"])` instead the version that's in the current gemspec.

### CODE REVIEW

**Comment by iNecas** [comment]
@ehelms @jlsherrill would you mind looking at this? I would like to get this rolling as part of the foreman 1.9 release

**Comment by iNecas** [comment]
I've released foreman-tasks 0.7.0, rebased and updated the gemspec and rpm spec to use the new version

**Comment by iNecas** [comment]
The rpm builds should be green after this https://github.com/theforeman/foreman-packaging/pull/697 is in

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
Apparently, there was a combination of bugs in VCR and old Dynflow: the VCR is causing the tests to crash before finishing the rest of the tests, when there is some http call missed, and old Dynflow have prevented from the tests to exit with non-zero exit code. As a result, the tests on the PR always ended up on some VCR crash (such as http://ci.theforeman.org/job/test_katello_core/14050/database=postgresql,ruby=1.9.3/console), but nobody noticed, because the tests were marked as green due to zero exit status (fortunately, at least when some tests failed before the crash, they were reported as failures)

Most of the crashes were caused by the status checking, but there were also other failures caused by not running all the tests in the CI (since the test suite ended preliminary). I've fixed all of the failures, so we should be ok now.

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
The rhel6 rpm build was failing on

```
DEBUG util.py:264:  Error: Package: ruby193-rubygem-fog-core-1.32.0-1.el6.noarch (build)
DEBUG util.py:264:             Requires: ruby193-rubygem-excon >= 0.45.0
DEBUG util.py:264:             Installing: ruby193-rubygem-excon-0.38.0-1.el6.noarch (build)
DEBUG util.py:264:                 ruby193-rubygem-excon = 0.38.0-1.el6
```

This was due to 0.38 being tagged in the `katello-thirdparty-rhel6`, I've untagged that, since it was not done so in rhel7 neither.

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
And all tests are green now!!! yay

**Comment by waldenraines** [comment]
ACK.  Merging this so as to fix katello pull request RPM builds.

**Pull request merged**
