### PR TITLE
Fixes #16295 - add manual applicability generation

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@waldenraines hey, curious if you could give me a little CSS help here.  

I hate markdown image syntax

**Comment by beav** [comment]
@jlsherrill the change itself looks good, but I am wondering if this needs to be a button vs a rake task that can be run from command-line. Is it a common case to manually regenerate applicability?

**Comment by jlsherrill** [comment]
@beav its common enough i think.  There are a bunch of other tasks I'd like to add such as regenerating repo metadata to the UI as well

**Comment by beav** [comment]
@jlsherrill After some thought, I'm OK with the button since it won't harm anything by pressing it

**Comment by waldenraines** [comment]
> @waldenraines hey, curious if you could give me a little CSS help here.
> I think its a preexisting issue, but made worse by adding a button

This is a preexisting issue.  The problem here is the use of `input-group`.  The `input-group` class was meant to be used within a `<form>` and on an `<input>` not a `<button>`, etc.

The correct component to use here is a [dropdown](https://angular-ui.github.io/bootstrap/#/dropdown).  I would be happy to fix this issue after your PR if you want to file an issue and assign it to me.

**Comment by jlsherrill** [comment]
@waldenraines opened issue: http://projects.theforeman.org/issues/16367

**Comment by jlsherrill** [comment]
To test:

1) Get a host into a state where it has applicable errata
2) in the rails console:  Katello::ContentFacetErratum.destroy_all
3) go to Hosts > Content Hosts > click your host > Errata  (should show no errata, as we deleted them)
4) click the 'recalculate' button 
5) wait for the task to complete
6) navigate back to  Hosts > Content Hosts > click your host > Errata 

you should see errata

**Comment by bbuckingham** [comment]
Testing this one out...

**Comment by bbuckingham** [comment]
Interesting behavior observed testing out the proposed scenario.  Everything looks good up through the defined steps (1-6).  After doing that, selecting an errata and clicking 'Apply Selected' prompts the user regarding how they would like to handle the 'Unregister Host'.

**Comment by jlsherrill** [comment]
@bbuckingham should be fixed, good find!

**Comment by johnpmitsch** [comment]
@jlsherrill seeing this when generating applicability

```There was an issue with the backend service pulp_auth: Permission denied @ rb_sysopen - /etc/pki/katello/private/pulp-client.key```

Its a fresh installed box from today, so I imagine this is an issue with the installer? I've seen similar with capsule installs.

I'l chmod to change and proceed with testing

**Comment by johnpmitsch** [comment]
Its also worth mentioning that the error did not show up in the UI nor was I redirected to the task when clicking "Recalculate". But after changing the permissions, I was redirected to the task on clicking "Recalculate"

**Comment by johnpmitsch** [comment]
@jlsherrill All worked from me (aside from one related error). Can we confirm that errors in the generating applicability task are reported after clicking the "Recalculate" button? If they are, I give ACK

**Comment by bbuckingham** [comment]
@jlsherrill, Confirmed that the updated PR addresses the behavior that I saw with applying errata.  I did encounter an error in pulp; however, that is totally unrelated to this PR (and may actually be my dev install).

**Pull request merged**
