### PR TITLE
fixes #12397 - properly detect pulp task failures again

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@iNecas curious about your thoughts on this, i believe it was caused by this change:  https://github.com/Dynflow/dynflow/commit/6f56df9#diff-15e875d53193085cf195d9fe4e81e5b2R84

wanted to make sure this i the right place to add this check, as it worked fine before but now treats these exceptions as 'failed polls'

**Comment by iNecas** [comment]
I'm not sure this change really helps, as the `done?` method is still called from within the block catched for errors,  I think overriding `rescue_poll_external_task(error)` from https://github.com/Dynflow/dynflow/commit/6f56df9#diff-15e875d53193085cf195d9fe4e81e5b2R98 and raising the error immediately  on `::Katello::Errors::PulpError` is what you want

**Comment by jlsherrill** [comment]
@iNecas at that commit `done?` is still caught, but in master it isn't:  

https://github.com/Dynflow/dynflow/blob/master/lib/dynflow/action/polling.rb#L28

Overriding rescue_poll_external_task is an option, id' rather not have to reproduce all of that logic, but it seems like a better place than sticking the exception in done?.  Will give that a try.

**Comment by iNecas** [comment]
@jlsherrill right, this works then… :) :+1:

**Comment by bbuckingham** [comment]
ACK

**Pull request merged**
