### PR TITLE
fixes #11270 Do not insert this many spaces

### PR DESCRIPTION
**Pull request by jhutar**
Fixing multiple spaces in the option description:

    # hammer content-host -h | grep available-incremental-updates
     available-incremental-updates Given a set of systems and errata, lists the content view versions                                                                   and environments that need updating.

### CODE REVIEW

**Comment by ehelms** [comment]
Please open a Redmine issue and update the commit message -- http://theforeman.org/contribute.html#SubmitPatches

**Comment by jhutar** [comment]
@ehelms Hello. Issue created and commit updated

**Comment by ehelms** [comment]
@jhutar thanks!

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
ACK, thanks @jhutar !

**Pull request merged**
