### PR TITLE
refs #10970 - adding in protected_attributes for `attr_accessible`

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by cpeters** [comment]
ACK

**Comment by ehelms** [comment]
Is the plan to remove this before going to master?

**Comment by komidore64** [comment]
it can be?

**Comment by ehelms** [comment]
The implications vary depending on your plan, that is why I ask. One requires a packaging effort and broader question of should this be in the core and not a katello only thing and the other requires nothing additive.

**Comment by komidore64** [comment]
it would probably be better for us to remove this before merging to katello/master

**Comment by komidore64** [comment]
@ehelms, updated todo comment specifying fixing this before merge to master.

**Comment by ehelms** [comment]
Would it be more likely to be remembered if we generated an issue and blocked the Rails 4 tracker with it?

**Comment by komidore64** [comment]
i am indifferent. whatever you think is best

**Comment by ehelms** [comment]
I would prefer the issue, easier to manage than a todo for something like this. ACK for pending/post the issue :)

**Comment by komidore64** [comment]
@ehelms [redmine issue #11756](http://projects.theforeman.org/issues/11756)

**Comment by ehelms** [comment]
Awesome, thanks @komidore64

**Pull request merged**
