### PR TITLE
fixes #24149 - use new template renderer

### PR DESCRIPTION
**Pull request by timogoebel**
This needs theforeman/foreman#5683 and https://github.com/theforeman/foreman_remote_execution/pull/363.

I don't have a katello development environment at hand and don't know the codebase well enough. This is a shot in the dark. Please help me with testing this.

### CODE REVIEW

**Comment by jlsherrill** [comment]
I still need to test this, but the update seems sane :+1:

**Comment by johnpmitsch** [comment]
@timogoebel  running into the issue [I mentioned on the mailing list](https://community.theforeman.org/t/errors-in-katello-ui-potentially-due-to-renderer-change/10601?u=john_mitsch) (this was before I saw this PR), the subscriptions page isn't loading.

**Comment by timogoebel** [comment]
I can't tell how this could be related. The commit you mention just changed stuff in the template rendering. `notification_recipients_path` should be defined by rails based on the [defined routes](https://github.com/theforeman/foreman/blob/b58439fabbeac20b68902021fed366725c26dc92/config/routes.rb#L548-L553).

Can you look into this a bit more?

My gut feeling is that `Foreman::ForemanUrlRenderer ` was mixed into some controller (as templates were rendered in the controller context) and included [this](https://github.com/theforeman/foreman/blob/b58439fabbeac20b68902021fed366725c26dc92/lib/foreman/foreman_url_renderer.rb#L5) that made the url available. But I don't have a katello dev env to verify.

**Comment by akofink** [comment]
This only seems to be an issue on all our react pages in Katello (RH Repos and Subscriptions). `rake routes` shows the route there, so it must just be the missing helper method. The actual trace shows the error coming from [mount_react_component](https://github.com/theforeman/foreman/blob/develop/app/views/home/_user_dropdown.html.erb#L16) in foreman.

**Comment by johnpmitsch** [comment]
I'm really not sure where to start looking, maybe someone more familiar with the templating change can weigh in. Git bisect narrows it down to [the template rendering change](https://github.com/theforeman/foreman/commit/f715a7c98457c6f43a1f803a75ba4540372d8544) so something must have changed that we are missing.

@ares @kamils-iRonin @tbrisker @tstrachota @lzap Do you have any ideas on the error we are seeing on the Katello React pages?

subs page

**Comment by akofink** [comment]
IDK if this is helpful, but I checked in the console with Katello loaded, and the following works fine:

```rb
> include Rails.application.routes.url_helpers
> notification_recipients_path
=> "/notification_recipients"
```

**Comment by timogoebel** [comment]
Can you try changing [this](https://github.com/Katello/katello/blob/4cb1be28aa04c7fdabac0b82ae956c091dee8e2c/app/controllers/katello/react_controller.rb#L6) to something like:

```
render layout: 'katello/layouts/react'
```

and defining an empty view for the index action?

**Comment by timogoebel** [comment]
@tbrisker: I had similar thoughts. I guess the methods need to be available in the helpers and not in the controller, correct?
But I believe a katello maintainer needs to look at this. I expect them to know katello and the codebase better then I do.

**Comment by akofink** [comment]
Yes, it appears adding `include Rails.application.routes.url_helpers` to the ReactController fixes the issue. I also noticed that we do this already in the [BastionController](https://github.com/Katello/bastion/blob/master/app/controllers/bastion/bastion_controller.rb#L7), so it's not without precedent.

**Comment by timogoebel** [comment]
A fix for the url issue is in #7589.

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
@timogoebel works well for me!  I've opened an issue to add tests to all the untested extensions here: https://projects.theforeman.org/issues/24549

and will be opening a PR to add those, but thanks for your updates here.

**Pull request merged**
