### PR TITLE
Fixes #22797 - support SLES os fact

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jturel** [comment]
I think this is working as intended:

```
irb(main):010:0> Operatingsystem.all
+----+-------+------+-------+---------------+-----------------+------------------+--------------+------+-------------+---------------+-----------+
| id | major | name | minor | nameindicator | created_at      | updated_at       | release_name | type | description | password_hash | title     |
+----+-------+------+-------+---------------+-----------------+------------------+--------------+------+-------------+---------------+-----------+
| 1  | 12    | SLES | 3     |               | 2018-03-08 2... | 2018-03-08 21... |              | Suse |             | SHA256        | SLES 12.3 |
+----+-------+------+-------+---------------+-----------------+------------------+--------------+------+-------------+---------------+-----------+
```

Operatingsystem is created when registering my suse box. Suse is shown properly under Operatingsystem column in the host list as well. Anything else I should be looking for?

**Comment by jlsherrill** [comment]
Make sure the is is created with a sure family.  We should probably also
check sles 11, I'm happy to do that as I probably should have already,
either way

**Comment by jturel** [comment]
This works with my SLES12 VM. I didn't test 11. ACK

**Comment by jlsherrill** [comment]
sub-man for sles 11 seems broken atm :(

**Comment by jlsherrill** [comment]
It appears sles 11 is inconsistent with sles 12:

```
# subscription-manager facts --list | grep dist
distribution.id: x86_64
distribution.name: SUSE Linux Enterprise Server 
distribution.version: 11
distribution.version.modifier: Unknown
```

will update to fix this.

**Comment by jturel** [comment]
@jlsherrill looks good - your test case convinces me this'll work but I haven't tested SLES11 due to the subman issue you mentioned.

**Pull request merged**
