### PR TITLE
Fixes #24597 - Exit properly for eslint

### PR DESCRIPTION
**Pull request by johnpmitsch**
Eslint hasn't been failing on errors in jenkins since we were using
"|| exit 0" with it. This removes that and fixes linting
errors.

### CODE REVIEW

**Comment by waldenraines** [comment]
[test katello]

**Comment by akofink** [comment]
Maybe we should change it to `|| exit 1` or `&& exit 0`, at least to see what Jenkins does.

**Comment by johnpmitsch** [comment]
Needs jenkins change: https://github.com/theforeman/foreman-infra/pull/769

**Comment by johnpmitsch** [comment]
[test katello]

**Comment by johnpmitsch** [comment]
[test katello]

**Pull request merged**
