### PR TITLE
Bumps gem to resolve packaging dependency.

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
@jjeffers can you catch me up? how can I verify that this is the right change?

**Comment by jturel** [comment]
The foreman 2.0 repos have foreman-tasks 1.1.1 which this change is disallowing. Is there gonna be a foreman-tasks 1.1.3 ?

**Comment by jturel** [comment]
Ok, I get it now. This seems like it will be OK, but we need a version bump for the gem too

**Comment by evgeni** [comment]
@jturel fwiw, 1.1.3 is packaged (today) so you'll see it in the repos tomorrow

**Pull request merged**
