### PR TITLE
Fixes #17663 - add virt-who report rake task

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by thomasmckay** [comment]
@akofink : while you're testing subs... ;)

**Comment by thomasmckay** [comment]
I am not going to push terribly hard for this, but if there is a "happy medium" we can come to, that would be beneficial for users in the future...

The report here is similar to that generated by 'hammer csv'. A csv export can also be imported, which is very often helpful in reproducing user issues. Here is an example of the "itemized subscriptions" export:

```
$ hammer --server https://10.33.144.209 --username admin --password redhat csv content-hosts --export --search dhcp182 --itemized-subscriptions
Name,Organization,Environment,Content View,Host Collections,Virtual,Guest of Host,OS,Arch,Sockets,RAM,Cores,SLA,Products,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
dhcp182-7.gsslab.rdu2.redhat.com,Default Organization,Library,Default Organization View,"",Yes,virt-who-bulgaria.hq.gsslab.rdu.redhat.com-1,Red Hat Enterprise Linux Server 7.3,x86_64,1,1884124,1,"",69|Red Hat Enterprise Linux Server,,,,,,,,,
```

Note that a --search option is available, as shown above, to limit the export. Custom columns are also supported for content-hosts subcommand. I would guess that neither of these would allow full parity of what is implemented in this PR at this time. RFEs for such would be very welcome.

Stepping back, I would like to see the column names that overlap match the style of hammer csv (capitalization and same-named where appropriate). I would also suggest that more information be included in the export that specifically applies to how subscriptions are attached. You'll note that columns such as _Sockets_ and _Guest of Host_ are present in hammer csv. The purpose of these columns is to allow later import and debugging for how/why a certain subscription was attached.

Again, while I would prefer that hammer csv be the tooling used for this task I understand the need for performance and immediate value.

**Comment by jlsherrill** [comment]
@thomasmckay i think longer term being able to perform a search for hosts such as:

'consumer_type = hypervisor && subscription_count = 0' 
or
'consumer_type = guest && physical_subscription_count > 0'
would be highly beneficial.  It could then be used within hammer csv.  We are not there yet, but may be soon at least for some parts?

**Comment by akofink** [comment]
My hypervisor  is being identified as a guest, for some reason:

```
akofink-desktop.usersys.redhat.com (1): Has physical entitlements: Employee SKU. Could not identify hypervisor.
```

Here's its info, from the show.json api endpoint: https://paste.fedoraproject.org/505929/81661768/

**Comment by akofink** [comment]
LGTM! ACK from me, though I'd encourage others to try it out.

**Comment by thomasmckay** [comment]
ack

**Comment by jlsherrill** [comment]
[test]

**Pull request merged**
