### PR TITLE
Fixes #26868 - change pulp-selector invocation

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jturel** [comment]
I think this change has given rise to this showing up in the logs with a hefty stack trace

```
2019-05-27T07:38:40 [E|dyn|1e488780] Value (Module) 'Actions::Katello::PulpSelector' is not child any of: Dynflow::Action. (TypeError)  
```

**Comment by jjeffers** [comment]
Seeing similar errors even after a `spring stop`:
https://pastebin.com/CtrmUKRy

**Comment by jlsherrill** [comment]
@jturel have you tried shutting down your rails server and stopping spring?

**Comment by jturel** [comment]
That did work. Thanks ... always forget about spring!

**Pull request merged**
