### PR TITLE
Refs #10970 Fix mass assignment security error on environment extensions

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
If foreman permits these attributes http://git.io/v4U7V can we try passing the location_ids and organization_ids instead and see if that shows up in the error message still? We may need to have them add katello_ids or figure out a way to do so ourselves. Though not sure how that works with us using strong_params and foreman using protected attributes

**Comment by daviddavis** [comment]
@johnpmitsch is right. If you use location_ids and organization_ids and this you should be good:

https://gist.github.com/daviddavis/9326fb56c7aaebb8797e

**Comment by daviddavis** [comment]
Theoretically we'll have to make this change anyway though when Foreman drops protected_attributes in 1.12 though but for now we need to whitelist katello_id since we're using their api which doesn't support strong_params.

**Comment by cpeters** [comment]
@daviddavis @johnpmitsch 

Ok, I understand that... but why add another attr accessor in katello? I thought we are moving away from protected_attributes?

**Comment by cpeters** [comment]
@daviddavis @johnpmitsch 

When foreman drops protected_attributes... this is the code we will end up with. Right?

**Comment by daviddavis** [comment]
Yes. And actually, this is what you want since we don't want to make katello_id accessible from the api (I was wrong in my previous comment/gist):

```ruby
env = Environment.new(:name => env_name, :organization_ids => [org.id], :location_ids => [::Location.default_location.id])
env.katello_id = katello_id
```

**Comment by johnpmitsch** [comment]
@daviddavis +1 to that

**Comment by cpeters** [comment]
@daviddavis 
Ok. I agree with the second version.

**Comment by cpeters** [comment]
@johnpmitsch @komidore64 

Updated

**Comment by johnpmitsch** [comment]
ACK thanks @cpeters!

**Pull request merged**
