### PR TITLE
Fixes #35031 - Delete ModuleProfile and ModuleProfileRpms before ModuleStreams

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
Move deletion of child records before parent in migration.
#### Considerations taken when implementing this change?
I have a feeling destroy_all instead of delete_all for child records will resolve this too but it will be a costlier operation.

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by chris1984** [comment]
Code looks good. starting to test

**Review by parthaa — APPROVED** [review]
ACK

**Review by chris1984 — APPROVED** [review]

**Comment by chris1984** [comment]
Works good, merge away

**Pull request merged**
