### PR TITLE
Fixes #32007 - remove old pulp2-based upgrade tasks

### PR DESCRIPTION
**Pull request by chris1984**
Updated clean_backend_objects as well since it fails to connect with
runcible and sends back an SSL error

### CODE REVIEW

**Comment by jlsherrill** [comment]
This all looks great!   i would go ahead and get rid of these upgrade tasks too:

lib/katello/tasks/upgrades/3.15/set_sub_facet_dmi_uuid.rake
lib/katello/tasks/upgrades/3.16/update_applicable_el8_hosts.rake
lib/katello/tasks/upgrades/3.18/add_cvv_export_history_metadata.rb

**Comment by jjeffers** [comment]
Tested this with a patched katello install (via `yum install katello`). Cleared the upgrade_task db, migrated, etc, re-ran the installer:
```
Executing: foreman-rake upgrade:run
=============================================
Upgrade Step 1/4: katello:correct_repositories. This may take a long while.
=============================================
Upgrade Step 2/4: katello:correct_puppet_environments. This may take a long while.
=============================================
Upgrade Step 3/4: katello:clean_backend_objects. This may take a long while.
0 orphaned consumer id(s) found in candlepin.
Candlepin orphaned consumers: []
=============================================
Upgrade Step 4/4: katello:upgrades:4.0:remove_ostree_puppet_content.   Success!
```

**Review by jjeffers — APPROVED** [review]
After testing these changes... LGTM.

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
