### PR TITLE
Fixes #18699 - fix styling on host subscriptions add/remove

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note this is a 3.3 only fix

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
Woot - passing now!

**Comment by jlsherrill** [comment]
WOOT ehelms++  👍

**Pull request merged**
