### PR TITLE
Fixes #30256 - Add DSL docs for pools

### PR DESCRIPTION
**Pull request by ofedoren**
Needs https://github.com/Katello/katello/pull/8801, https://github.com/Katello/katello/pull/8823.

### CODE REVIEW

**Comment by ares** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
requires https://github.com/Katello/katello/pull/8823

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
