### PR TITLE
Fixes #14939 - prefer https for capsule syncs

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note this was tested by the user that reported the issue and they gave it a :+1:

**Comment by ehelms** [comment]
APJ

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Pull request merged**
