### PR TITLE
Fixes #31151 - updates 404 conditions in before action filters

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by jturel** [comment]
mind adding a test @chris1984 ?

**Comment by chris1984** [comment]
@jturel updated with a test to assert a `404`

**Review by jturel — APPROVED** [review]
APJ

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
