### PR TITLE
Fixes #22360 - fix non-admin cv publish

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test rails-5]

**Comment by jlsherrill** [comment]
[test default]

**Comment by sbernhard** [comment]
Can you please explain, why you remove the "include Authorizable" for these 3 files?

**Comment by jlsherrill** [comment]
@sbernhard those models aren't actually controlled by permissions (there is no 'Repository' permission, its governed by the Product model).  So these modules just provide some helper methods.  I don't see any reason that the Authroizable module be included, and i think recent changes in that module are what broke this.

**Pull request merged**
