### PR TITLE
refs #11513 - hypervisors only have subscription aspect

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by jlsherrill** [comment]
@thomasmckay can you merge master to host_unification (and then re-push this commit) ?   This isn't really reviewable with the extra commits.

**Comment by jlsherrill** [comment]
@thomasmckay i'd really prefer this all get moved to dynflow like all the other registration and aspect creation code and out of the old orchestration stuff.  Seems silly to update alll this code that will have to be deleted anyways.

**Comment by thomasmckay** [comment]
@jlsherrill oops! I merged master to host_unification (because candlepin event listener was bombing on the branch) and then rebased my PR against it.

Agree re: dynflow and will work on that today.

**Comment by thomasmckay** [comment]
obsolete PR

**Pull request closed without merging**
