### PR TITLE
[CP] Katello 3.12 Cherrypicks from Toolbelt

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@jturel here is the updated list of cherry-picks from toolbelt for 3.12

**Comment by jturel** [comment]
Looks good! If this is the last of picks for GA I think it'd be appropriate to version bump and add an updated changelog

**Comment by chris1984** [comment]
@jturel updated with the version bump and updated changelog from toolbelt.

**Comment by jturel** [comment]
my only request here would be to completely regenerate the changelog so everything inside is under the 3.12.0 heading (there are two now). otherwise looks good!

**Comment by chris1984** [comment]
@jturel updated with fresh changelog!

**Pull request merged**
