### PR TITLE
Fixes #30280 - replaces 'master' with 'primary'

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Review by jeremylenz — COMMENTED** [review]
I think we should also address  https://github.com/Katello/katello/blob/9dc14ebc5e8d5351b15e1d9c8bb82855b7964bbd/app/models/katello/rhsm_fact_parser.rb#L116

**Comment by jjeffers** [comment]
[test katello]

**Comment by jturel** [comment]
```
test/controllers/api/v2/content_view_versions_controller_test.rb:      SmartProxy.stubs(:pulp_master).returns(FactoryBot.create(:smart_proxy, :default_smart_proxy, :with_pulp3))
```

Found this last occurrence of pulp_master - but other than that looks good

**Review by jeremylenz — APPROVED** [review]
Agree with @jturel on the version.

clicked around a bit and seems not to break anything!  ACK

**Pull request merged**
