### PR TITLE
[CP] Cherrypicks for Katello 3.17 RC2

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by ianballou** [comment]
Looks like there's an actual test failure in `test/actions/katello/content_view_version_test.rb`.  Did all the cherry pick merges go through okay?

**Comment by chris1984** [comment]
> Looks like there's an actual test failure in `test/actions/katello/content_view_version_test.rb`. Did all the cherry pick merges go through okay?

There was 2 merge conflicts I will see what is going on with it.

**Comment by chris1984** [comment]
[test katello]

**Review by ianballou — COMMENTED** [review]
I see there's a gem error, maybe we need to pin one of our gems back in `katello.gemspec`?

**Comment by chris1984** [comment]
@ianballou tests pass minus the chromium issue, if you want to review again. I will make a seperate pr for the updated version. I am afraid to add anything more to this lol

**Review by ianballou — APPROVED** [review]
ACK pending the Angular tests passing!

**Comment by chris1984** [comment]
[test katello]

**Review by ianballou — APPROVED** [review]

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
