### PR TITLE
Update 3.8.1 Changelog

### PR DESCRIPTION
**Pull request by sjha4**

### CODE REVIEW

**Comment by jturel** [comment]
This looks a bit different than the changelog I generated for 3.7.1 for example: https://github.com/Katello/katello/blob/KATELLO-3.7/CHANGELOG.md

I think there should be separate 3.8.0 and 3.8.1 sections to show what changed. What was the command you used to generate the changelog?

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@sjha4 angular passed! go ahead and merge once the build finishes assuming on ruby tests fail ;)

**Pull request merged**
