### PR TITLE
Fixes #16745 - environment_id is required to promote CV-version

### PR DESCRIPTION
**Pull request by swapnilabnave**
API : `POST /katello/api/v2/content_view_versions/:id/promote`
Enforce parameter `environment_id` while promoting a content_view_version

### CODE REVIEW

**Comment by swapnilabnave** [comment]
@daviddavis Thank You for reviewing.
I had thought about it.
1. `ContentViewVersionsController#find_environment` could have been legitimate place unless it was shared by `:promote and :index`
2. `ContentViewVersionsController#authorize_promotable` don't want to change it's purpose.
3. `promote` action itself. (I too prefer this option. Just avoiding growing actions)
4. Isolated validation checks for environment_id.
here I'll go with option#3

**Comment by swapnilabnave** [comment]
I have renamed ContentViewVersionsController#authorize_promotable to ContentViewVersionsController#validate_promotable and extended to check environment existence.

**Comment by swapnilabnave** [comment]
[`ContentViewVersionsController#authorize_promotable`](https://github.com/swapnilabnave/katello/blob/71e65c0c5fe69bc26c3287a369005ad115c4e8cd/app/controllers/katello/api/v2/content_view_versions_controller.rb#L258) wont allow promote action to execute further. Hence the above change.
let me know if you think that the right thing to do.

**Comment by swapnilabnave** [comment]
Oh I just realized existence check is not required. Removed the `NotFound` check.

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
Thanks @swapnilabnave.

**Pull request merged**
