### PR TITLE
Fixes #14336,#13254 - bug fixes and improvements for incremental update

### PR DESCRIPTION
**Pull request by jlsherrill**
This commit does a few things:

* Converts the incremental update api to reference only hosts
* Adds the ability to specify uuid or id for packages
* Adds the ability to specify uuid, id, or errata id for errata
* Removes the 'update_all_systems' parameters, as you can just pass in an
   empty search string to accomplish the same function
* Does not create dynflow subtask for non-applicable hosts
* Converts the errata apply UI to be host based
* Adds installable_errata to the things you can search hosts for
   (needed for above)

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note that this will currently fail with a pulp error:  https://pulp.plan.io/issues/1792

Not sure if we want to try to validate/review this PR now or wait

**Comment by jlsherrill** [comment]
Note this can be tested using this patch: https://github.com/pulp/pulp_rpm/pull/830

**Comment by bbuckingham** [comment]
Adding some comments based on testing of incremental update.  If a comment is unrelated to the changes in this PR, a separate redmine can be created.

- go to Content -> Errata
- select an applicable errata
- select Content Hosts tab
- select a Content Host
- ERROR: page redirects to:  https://katello/content_hosts//info  <- missing the ID

**Comment by bbuckingham** [comment]
Scenario 2:
- go to Content -> Errata
- select an applicable errata
- select Content Hosts tab
- select a lifecycle environment from the dropdown (e.g. Library)
- ERROR: observed in console:
AbstractController::DoubleRenderError in Api::V2::HostsController#index
Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

**Comment by bbuckingham** [comment]
Scenario 3:
- go to Content -> Errata
- select an applicable errata
- select Content Hosts tab
- ERROR: the following columns are empty for the content host:  OS, Environment, Content View

**Comment by bbuckingham** [comment]
Scenario 4:
- go to Content -> Errata
- select an applicable errata
- select Content Hosts tab
- select a host
- select Apply to Hosts
- select the content view
- ERROR: user enters a redirect loop to resource similar to https://katello/content_views/2/versions/2

**Comment by bbuckingham** [comment]
Scenario 5:
- go to Content -> Errata
- select an applicable errata
- select Content Hosts tab
- select a host
- select Apply to Hosts
- select 'Apply to Content Host Immediately after publishing'
- click Confirm
- Task Details:  Stopped/Warning
  - Version 1.1 created in Dev, added 1 errata and 3 packages, as expected
  - ERROR: Warning result appears to be error installing the erratum on the client.  The error message on the client is : https://gist.github.com/bbuckingham/59750c587e5ed0b96b17c601bc93ecf1 .  This may be a config error on my environment; however, mentioning in case others see the same.

**Comment by bbuckingham** [comment]
Scenario 6: (after incremental update)
- go to Content -> Content Views
- select the content view that was just incrementally updated
- click History
- observation:  there are 2 rows for the new version (e.g. 1.1).  Neither of them as an 'Action' specified.

**Comment by bbuckingham** [comment]
Scenario 7:
- Hosts -> Content Hosts
- observation: we show 'Installable Errata' on the summary

- select a host
- observation: on Details, we show 'Installable Errata'

- Would it be useful to also show 'Applicable Errata' from one or both of these, so that the user does not need to go Content -> Errata to find out?

**Comment by bbuckingham** [comment]
@daviddavis, @parthaa, @ehelms, @waldenraines, Given the size of this PR, if someone has cycles, it might be nice get have an additional reviewer look over the code.

**Comment by bbuckingham** [comment]
Scenario 5.1:  A variation on the scenario where the incremental update is performed and the content view that needs to be updated is a composite.   In this scenario, the following error is shown to the user:
- undefined method `map' for nil:NilClass
- log info: https://gist.github.com/bbuckingham/f903a267f01e6cd2ceeb5d0484a2da5d

Content view config was:
- zoo view - with zoo repo
- composite view - with with zoo view

**Comment by jlsherrill** [comment]
@bbuckingham all scenarios should be fixed except:

Scenario 5:  I was not able to reproduce this
Scenario 5.1:  I will cover this while looking into http://projects.theforeman.org/issues/14399
Scenario 6:  Pretty sure this is an existing issue, opened http://projects.theforeman.org/issues/14398
Scenario 7:  Filed http://projects.theforeman.org/issues/14400

**Comment by bbuckingham** [comment]
@jlsherrill, ACK from me on the updates.  Also, I did review the code; however, I did not see any issues during the review.  Unless there are objections from others, I would be Ok with merging this in to master as it certainly improves the behavior of the incremental update feature.

**Comment by jlsherrill** [comment]
Nobody took the bait, merging, thanks @bbuckingham for the review

**Pull request merged**
