### PR TITLE
Fixes #25559 - update seeds to assume taxonomies are seeded in core

### PR DESCRIPTION
**Pull request by rahulbajaj0509**
This patch makes sure that the seeds for katello are updated with the changes made in core: https://github.com/theforeman/foreman/pull/6283.

### CODE REVIEW

**Comment by johnsonm325** [comment]
@jlsherrill Do we want to add the "blocked by another pr" tag on this one? Or is it different because they need to be merged together?

**Comment by tbrisker** [comment]
@johnsonm325 @jlsherrill is this ok to merge once we merge the core PR? they are interdependent so we need to merge them together

**Comment by tbrisker** [comment]
[test katello] - core has been merged

**Comment by jlsherrill** [comment]
[test katello]

**Comment by tbrisker** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Looks like seeds is failing with this: 
```
ActiveRecord::AssociationTypeMismatch: Katello::KTEnvironment(#110786060) expected, got #<ActiveRecord::Relation []> which is an instance of Katello::KTEnvironment::ActiveRecord_Relation(#110784900)
```

**Comment by jlsherrill** [comment]
Opened a PR to fix this: https://github.com/theforeman/foreman/pull/6350

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by tbrisker** [comment]
not sure if this is related [test katello]
```
Failure:

Katello::UpdateSubscriptionFacetBackendDataTest#test_run [/var/lib/workspace/workspace/katello-pr-test/test/lib/tasks/update_subscription_facet_backend_data_test.rb:22]:

not all expectations were satisfied

unsatisfied expectations:

- expected exactly once, not yet invoked: Katello::Host::SubscriptionFacet(id: integer, host_id: integer, uuid: string, last_checkin: datetime, service_level: string, release_version: string, autoheal: boolean, registered_at: datetime, registered_through: string, user_id: integer, hypervisor: boolean, hypervisor_host_id: integer, purpose_usage: text, purpose_role: text, purpose_addons: text).update_facts(#<Host::Managed:0xec4a5a0>, {:foo => :bar})

satisfied expectations:

- allowed any number of times, not yet invoked: Katello::Ping.ping(any_parameters)

- allowed any number of times, not yet invoked: Cert::Certs.ssl_client_key(any_parameters)

- allowed any number of times, not yet invoked: Cert::Certs.ssl_client_cert(any_parameters)

- allowed any number of times, not yet invoked: Cert::Certs.ca_cert(any_parameters)

- allowed any number of times, invoked once: #<Organization:0xef3d438>.label_not_changed(any_parameters)

- allowed any number of times, invoked 9 times: #<AnyInstance:Katello::Host::SubscriptionFacet(id: integer, host_id: integer, uuid: string, last_checkin: datetime, service_level: string, release_version: string, autoheal: boolean, registered_at: datetime, registered_through: string, user_id: integer, hypervisor: boolean, hypervisor_host_id: integer, purpose_usage: text, purpose_role: text, purpose_addons: text)>.host(any_parameters)

- allowed any number of times, invoked once: #<AnyInstance:Katello::Candlepin::Consumer>.consumer_attributes(any_parameters)

- allowed any number of times, invoked once: Katello::Resources::Candlepin::Consumer.virtual_host(any_parameters)

- allowed any number of times, invoked once: Katello::Resources::Candlepin::Consumer.virtual_guests(any_parameters)

**Comment by jlsherrill** [comment]
@tbrisker currently looking at this, going to open a 2nd pr to replace this one with an additional (unrelated) change

**Comment by rahulbajaj0509** [comment]
@jlsherrill @tbrisker closing this pr :)

**Pull request closed without merging**
