### PR TITLE
Fixes #14579 - Enables image based prov of atomic

### PR DESCRIPTION
**Pull request by parthaa**
Ties subscription manager linking and other content managing options
when one provisions atomic by using an image

### CODE REVIEW

**Comment by jlsherrill** [comment]
ACK from a code perspective

**Comment by sghai** [comment]
Tested this change with satellite beta.

But I've to update the `Satellite Kickstart Default User Data` template with changes defined in `userdata-katello.erb` manually otherwise I don't see changes rendered properly in the userdata template. 

I can login to atomic-host using `admin` user provisioned via image-based prov. Also, host is getting registered with server via userdata template.

**Comment by stbenjam** [comment]
What changes @sghai? It looks like the templates are the same to me.

**Comment by sghai** [comment]
@stbenjam : To test this PR I made the changes in `userdata-katello.erb` and restarted foreman-tasks and httpd services.. but didn't see the changes reflected under `Satellite Kickstart Default User Data`. I had a word with @parthaa and realized `foreman-rake db:seed` needs to be run.

Now I can login to provisioned atomic host with `admin` user and can see the host registered with server.

**Comment by jlsherrill** [comment]
Tested this, and it worked great. 

ACK

**Pull request merged**
