### PR TITLE
Fixes #34548 - Host collections Add & Remove modals

### PR DESCRIPTION
**Pull request by jeremylenz**
#### What are the changes introduced in this pull request?

add_hc
remove_hc

* Add Host collections Add & Remove modals to Host collections overview card.
* Refactors `errorToast` in HostDetails (see relevant commit)

#### Considerations taken when implementing this change?

I was pleased to discover that there is already a single API for adding or removing host collections from a host.  The API is kinda weird (instead of saying which host collections to add or remove, you instead have to send _what you want the new list of host collections to be_) but works quite well and didn't require any changes!

Knowing that the two modals would be very similar, I combined them into one component. The use of ternaries etc. is a _bit_ higher than I'd like, but I think the tradeoffs are worth it.

Because it would cause significant complexity and is not a common use case, the tables don't have Select All available-- only Select Page. (this is ok per Maria)

#### What are the testing steps for this pull request?

* Create some host collections
* On the host collections overview, click the kebab > __Add host to collections__
* Select one or more available host collections and click Add
* Note that they appear on the card after the success toast appears
* Click the kebab >  __Remove host from collections__  - verify that the collections you just added are now showing as available to remove
* Select one or more available host collections and click Remove
* Click the kebab > __Add host to collections__ - verify that the host collection you just removed is available to add
* Make sure that any host collection at its host limit is not selectable in the table
* Change hosts using the breadcrumb switcher and verify everything still works correctly for the new host

### CODE REVIEW

**Comment by jeremylenz** [comment]
rebased after Packages reorg PR merged.

**Comment by jeremylenz** [comment]
rebased & incorporated card hiding feature from https://github.com/Katello/katello/pull/9942 :)

**Comment by jeremylenz** [comment]
[test katello]

**Review by jturel — APPROVED** [review]
Wow, that was a surprisingly small amount of code (excluding tests) to wire this up. Nice!

Code looks good, everything works as far as I can tell, and I agree with the design considerations.

One observation: I noticed that certain actions led to the modal resizing itself. For example, I had one collection in the Add modal. Then I searched for a bogus collection which made the modal smaller. Any way to make that more stable?

**Comment by jeremylenz** [comment]
> Any way to make that more stable?

Tried a few things with `minHeight` but didn't get very far. But then I discovered that `position: top` makes it a lot less jarring because the search box stays in the same place!  Also I think the other issue with the wonky shifting left/right should be fixed by https://github.com/theforeman/foreman/pull/9124.

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Pull request merged**
