### PR TITLE
fixes #16484 - hostgroup - fix create params

### PR DESCRIPTION
**Pull request by bbuckingham**
Update to sync up the extensions params with foreman as well
as fix 'ActiveModel::ForbiddenAttributesError' error.

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
we really need to add a way to add things rather than continuing this madness :)

**Comment by jlsherrill** [comment]
ACK

**Comment by stbenjam** [comment]
@bbuckingham Isn't this missing activation keys?

**Comment by bbuckingham** [comment]
@stbenjam, there is some hidden magical logic that creates a group parameter to store the activation key associated with the hostgroup.  I believe it is controlled by https://github.com/Katello/katello/blob/master/app/assets/javascripts/katello/hosts/activation_key_edit.js

**Comment by bbuckingham** [comment]
@jlsherrill, agreed, it would be good to have a different solution for this down the road.  This was primarily to quickly address a regression.

**Comment by stbenjam** [comment]
Oh I see, for some reason I thought they were moved to attributes of the host group.  Nevermind then, ACK

**Comment by bbuckingham** [comment]
@stbenjam, @jlsherrill, Thanks!

**Pull request merged**
