### PR TITLE
Fixes #23301: hook up upstream subscriptions to API.

### PR DESCRIPTION
**Pull request by waldenraines**
TODO:
- [x] Fix failing test
- [x] Add new tests for upstream subscriptions reducer

http://projects.theforeman.org/issues/23301

### CODE REVIEW

**Comment by sean797** [comment]
Do you mean http://projects.theforeman.org/issues/23301 ? ;)

**Comment by waldenraines** [comment]
> Do you mean http://projects.theforeman.org/issues/23301 ? ;)

Yes, I did, thanks.  Updated.

**Comment by jlsherrill** [comment]
* If i get an error from the support portal the UI shows "There are no Subscription Allocations to display" instead of reporting any error (could be misleading)
* also if there are no subscription allocations (either through error or because there is none), the submit button still appears and allows you to click it (resulting in an error).  Also the submit button is clickable while the subs are loading
* Paging seems broken (it only shows 1-20 of 20 subs, but when i increase the page size to 25, i get 1-25 of 25)
* The consumed quantity is shown in the box where i put the quantity i want to add.  This seems really confusing as It makes me think that my current allocation has consumed this amount and that i'm changing that quantity.  I think it should be in another column if we are going to list it.
* When i click submit after putting a 1 in one of the sub boxes, nothing happens, no error, no request
* If i enter a number in one of the boxes and hit enter, the page refreshes.  Should it submit?
* The subscription names link to /subscriptions  which doesn't seem right.  If anything it should link tot the support portal?

**Comment by jturel** [comment]
You'll want to add another parameter `attachable=true` to

https://github.com/waldenraines/katello/blob/869a51a0f77206d3c839e8e0b792dfd38044b34c/webpack/scenes/Subscriptions/UpstreamSubscriptions/UpstreamSubscriptionsActions.js#L16

The reason is that without it, the list returns everything available to the customers account. `attachable=true` forces upstream candlepin to return attachable subs only - ones that have available quantity, among other business logic.

**Comment by waldenraines** [comment]
> If i get an error from the support portal the UI shows "There are no Subscription Allocations to display" instead of reporting any error (could be misleading)

Do you mind if I fix this in a different PR?

> also if there are no subscription allocations (either through error or because there is none), the submit button still appears and allows you to click it (resulting in an error). Also the submit button is clickable while the subs are loading

Fixed.

> Paging seems broken (it only shows 1-20 of 20 subs, but when i increase the page size to 25, i get 1-25 of 25)

Fixed.

> The consumed quantity is shown in the box where i put the quantity i want to add. This seems really confusing as It makes me think that my current allocation has consumed this amount and that i'm changing that quantity. I think it should be in another column if we are going to list it.

Fixed.

> When i click submit after putting a 1 in one of the sub boxes, nothing happens, no error, no request

Should be fixed.

> If i enter a number in one of the boxes and hit enter, the page refreshes. Should it submit?

Fixed.

> The subscription names link to /subscriptions which doesn't seem right. If anything it should link tot the support portal?

Is there a programmatic way to do that?  I don't know enough about the portal to know how to generate the links.

> You'll want to add another parameter attachable=true to

Done, thanks for catching that.

I've included a commit from @johnpmitsch that this PR now requires.  I will rebase this once http://projects.theforeman.org/issues/22731 is resolved.

**Comment by jlsherrill** [comment]
>      Do you mind if I fix this in a different PR?

:+1:

**Comment by jlsherrill** [comment]
- Submit button seems gone,  aren't we normally opposed to 'hiding' buttons rather than disabling them?
- a window open from yesterday was pinging the task bulk search  api every 5-10 seconds and triggered the brute-force protection in foreman.  Should this be triggered every 5-10 seconds? If so, should it be smarter and stop after some auth failures or when the user is not interacting with the page or a combination of both?

**Comment by waldenraines** [comment]
> Submit button seems gone, aren't we normally opposed to 'hiding' buttons rather than disabling them?

Sorry, I broke that accidentally with my last commit, fixed now.

> a window open from yesterday was pinging the task bulk search api every 5-10 seconds and triggered the brute-force protection in foreman. Should this be triggered every 5-10 seconds? If so, should it be smarter and stop after some auth failures or when the user is not interacting with the page or a combination of both? (a separate issue is fine)

Yeah, that's a good catch, thanks.  See http://projects.theforeman.org/issues/23475.

> when hitting enter to submit the page, it took me back to the subs list with a notification of the task. I think it might be better to take me to a task page showing the status. I can't see any result of my action or use the page any more until that task is complete.

In the future (hopefully this iteration) we will show a tasks progress bar within the subscriptions table.  The toast message is just a stop gap until then.  See http://projects.theforeman.org/issues/23285.

> 'add subscriptions' seems to be missing breadrumbs, intentional? I know there is some work going on.

Both pages will have breadcrumbs added once http://projects.theforeman.org/issues/22900 is completed. 

> should something prevent me from trying to add entitlements while an existing task doing add entitlements is running?

That is part of http://projects.theforeman.org/issues/23325.

Sorry there are so many different tasks referenced here, I tried to break up the work here into small tasks.

**Comment by jlsherrill** [comment]
@waldenraines looks like some react failures

**Comment by waldenraines** [comment]
> @waldenraines looks like some react failures

Yeah, my todo in the description is still accurate unfortunately.  I hope to get this green today.

**Comment by waldenraines** [comment]
This is blocked by John's upcoming PR which should include 9e603cb40a2841b180f7563b7e46fd340d227188 or something similar.

**Comment by jlsherrill** [comment]
*  if i put a number in one of the add subs quantity boxes, click out of it, the checkbox gets checked.  if i delete the # and click out of it, it stays checked.

**Comment by waldenraines** [comment]
> This is blocked by @johnpmitsch's upcoming PR which should include 9e603cb or something similar. Will rebase after that is merged.

This no longer depends on anything.

**Comment by waldenraines** [comment]
> if i put a number in one of the add subs quantity boxes, click out of it, the checkbox gets checked. if i delete the # and click out of it, it stays checked.

Fixed.

> If the submit throws an error on the server, the UI doesn't really handle it at all, it just points the user to the task.

The task itself failed?  If so, that will be handled by the progress bar within the table task - http://projects.theforeman.org/issues/23285.  If the call to upstream subscriptions (to start the initial task) failed then we should be showing an error on this page I think.  Which were you seeing fail?

**Pull request merged**
