### PR TITLE
Fixes #21797 - handle various edge cases related to registration

### PR DESCRIPTION
**Pull request by beav**
This commit fixes various edge cases and errors related to
registration and hosts unregistering before actions complete.

This is tied closely to #21703.

### CODE REVIEW

**Comment by jlsherrill** [comment]
@beav apologies for the delay, will get to this tomorrow

**Comment by jlsherrill** [comment]
Getting an error when registering:

```
2018-02-28T18:18:18 178886ce [background] [E] Couldn't find ForemanTasks::Task::DynflowTask with [WHERE "foreman_tasks_tasks"."type" IN ('ForemanTasks::Task::DynflowTask') AND "foreman_tasks_tasks"."external_id" = $1] (ActiveRecord::RecordNotFound)
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/relation/finder_methods.rb:340:in `raise_record_not_found_exception!'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.4/lib/active_record/relation/finder_methods.rb:129:in `first!'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/foreman-tasks-0.12.0/app/lib/actions/base.rb:6:in `task'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/foreman-tasks-0.12.0/app/lib/actions/helpers/lock.rb:19:in `link!'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/foreman-tasks-0.12.0/app/lib/actions/entry_action.rb:40:in `action_subject'
 | /home/vagrant/git/katello/app/lib/actions/katello/host/upload_package_profile.rb:8:in `plan'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/dynflow-0.8.35/lib/dynflow/action.rb:473:in `block (3 levels) in execute_plan'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/dynflow-0.8.35/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/dynflow-0.8.35/lib/dynflow/middleware.rb:18:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/dynflow-0.8.35/lib/dynflow/middleware.rb:35:in `plan'
 | /home/vagrant/.rvm/gems/ruby-2.4.1/gems/dynflow-0.8.35/lib/dynflow/middleware/stack.rb:22:in `call'

```

**Comment by jlsherrill** [comment]
actually this seems unrelated to your pr :(

**Comment by jlsherrill** [comment]
got it working (needed a db:Migrate).  thanks @beav !

**Comment by beav** [comment]
@jlsherrill thanks for the review!

**Pull request merged**
