### PR TITLE
Fixes #17016 - Convert pulp filter dates to UTC

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by daviddavis** [comment]
[test]

**Comment by iNecas** [comment]
@tstrachota I remember you were talking about this today, is it the same issue you've seen?

**Comment by daviddavis** [comment]
@iNecas yea I worked with @tstrachota on this.

**Comment by iNecas** [comment]
Ah, ok, I though ti was just a lucky coincidence :)

**Comment by cfouant** [comment]
ACK thanks @daviddavis

**Pull request merged**
