### PR TITLE
Fixes #12925 - Reduced Repository Model size

### PR DESCRIPTION
**Pull request by parthaa**
Moved content related functionality to individual modules

Repository model is close to breaking the max class length rubo cop limit.
According to our rubocop metrics, max length per class is 500 lines. Repository.rb is very close to crossing that.
https://github.com/Katello/katello/blob/master/app/models/katello/repository.rb

One approach is to split functionality to different modules and include it in the main model.

This commit attempts to address that.

### CODE REVIEW

**Comment by jlsherrill** [comment]
I'm some what torn with this change.  It does split it up into more logical concerns but i'm not positive if this is the best way to do it.  @ehelms and I had discussed using STI I believe which would be better IMHO.

The result of this would be that the repository object is split between 5 different ruby files, which seems like it'd be confusing. 

Any thoughts @ehelms @daviddavis ?

**Comment by daviddavis** [comment]
:+1: to STI.

**Comment by ehelms** [comment]
@parthaa do you plan to revist this anytime soon?

**Comment by ehelms** [comment]
@parthaa Given the previous lack of response and staleness, I am going to give this a few days and close if no response.

**Pull request closed without merging**
