### PR TITLE
Fixes #24283 - remove pf bindMethods function

### PR DESCRIPTION
**Pull request by amirfefer**
According to [this](https://github.com/patternfly/patternfly-react/issues/294), patternfly bindMethods is depracted and uses Class properties instead.

### CODE REVIEW

**Comment by johnpmitsch** [comment]
Nice, now we won't have to see those annoying deprecation warnings :)
Can you explain the eslint changes?

**Comment by amirfefer** [comment]
@johnpmitsch , `class properties` is a babel experimental feature, katello has no babel parser at all, foreman does it.

**Comment by johnpmitsch** [comment]
@amirfefer gotcha, thanks for the explanation :)

looks good, but needs a rebase

**Comment by waldenraines** [comment]
> Rebased.

Sorry, @amirfefer looks like another rebase is needed.

**Comment by jlsherrill** [comment]
@amirfefer mind rebasing?  @waldenraines, amir doesn't have merge permissions so we have to merge for him.

**Comment by waldenraines** [comment]
> @amirfefer mind rebasing? @waldenraines, amir doesn't have merge permissions so we have to merge for him.
> 
>   1

Oops, I completely forgot about this PR, sorry @amirfefer!

**Comment by amirfefer** [comment]
@waldenraines  could you have another look (this time don't forget the merging staff :) )

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
@amirfefer looks like there are a couple of linting issues to fix here.

**Pull request merged**
