### PR TITLE
Fixes #33292 - ostree repo upload

### PR DESCRIPTION
**Pull request by jlsherrill**
This PR introduces change to allow for CLI uploads of OSTree content (primarily `commit_ref` content units) via the CLI/API.

To test, you will need to create a file based OSTree archive:

1. wget --no-parent -r https://fixtures.pulpproject.org/ostree/small/
2. tar --exclude="index.html" -cvf "fixtures_small_repo.tar" -C fixtures.pulpproject.org/ostree "small"

Using hammer:
```
hammer repository upload-content --id <repostory_id> --content-type ostree_ref --path <path to fixtures_small_repo.tar file> --ostree-repository-name small
```
After the import process completes, hammer will report the file was uploaded. Check for 2 things in Katello - 1. that the upload task completed (which includes both the upload and import actions), and 2. that the new content is present in the repository. The "small" repo will have 2 commit refs present with labels "stable" and "rawhide". 

There are additional options that can be passed to the content import process for ostree content (commit refs): `ref`, `repository_name`, and `parent_commit`. Repository name is *required*, although the default is typically "repo", so that can be used in most other examples.

Some more things to check:
If you omit the repository name (that is, the name _inside_ the uploaded ostree archive), the upload should fail:
```
[vagrant@centos7-hammer-devel ~]$ hammer repository upload-content --path ~/projects/2efad613-fb5e-4485-b67c-10f8ebed27e8-commit.tar  --id 1
Could not upload the content:
  OSTree commit ref uploads require a repository name.
```

Another note for testing: hammer ostree uploads may take enough time to "fail" with sync timeout errors, however the actual upload task may complete successfully. Check the upload task in the Katello task monitoring to be sure.

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Review by rverdile — COMMENTED** [review]
Fixes the sync then upload bug!

If you sync the "small" repository, upload that same content to it, then sync it again, it looks like this is what happens:
1. uploading replaces the content with the uploaded pulp objects
2. syncing again replaces the 2 units with new pulp objects, rather than using the ones from the original sync

I'm basing that mainly on the pulp hrefs being different. This is confusing so I'm not 100% I'm understanding it correctly :)

Is this expected?

**Comment by jlsherrill** [comment]
I believe this is expected.  Its not really a normal use case to do both syncing and importing on the same repository refs they would get overwritten

**Review by jjeffers — APPROVED** [review]
ACK

**Pull request merged**
