### PR TITLE
Fixes #21953 Adding enable/disable and search bar

### PR DESCRIPTION
**Pull request by danseethaler**
This adds the ability to search through repositories
and repository sets.

Waiting on #7185

http://projects.theforeman.org/issues/21953

TODO:
- [x] Update text on each list when search yields no results

### CODE REVIEW

**Comment by waldenraines** [comment]
We may want to show a different message when the enabled search is fired and the results is 0.  Right now it says "No repositories enabled." even though there is one.

**Comment by waldenraines** [comment]
Will you be able to add tests as part of this?

**Comment by danseethaler** [comment]
@waldenraines if you're using the latest code you should see a different message if the search is active - https://github.com/Katello/katello/pull/7180/files#diff-4d6c38f9ffec8f6b6d102d1e9530d0a3R17. Let me know if that doesn't seem to work for you.

I'll try to get some tests in as well.

**Comment by waldenraines** [comment]
> @waldenraines if you're using the latest code you should see a different message if the search is active - https://github.com/Katello/katello/pull/7180/files#diff-4d6c38f9ffec8f6b6d102d1e9530d0a3R17. Let me know if that doesn't seem to work for you.

You're right, I had an old version

**Comment by danseethaler** [comment]
@waldenraines cool - just pushed up a new version that will open the dropdown when the input is focused.

**Comment by waldenraines** [comment]
Closing in favor of https://github.com/Katello/katello/pull/7196.

**Pull request closed without merging**
