### PR TITLE
Fixes #22873 - handle race condition on host unregister

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
[test katello]

**Comment by beav** [comment]
`app/models/katello/content_facet_applicable_rpm.rb` may need a comment that `delete_all` is being called, similar to https://github.com/Katello/katello/blob/master/app/models/katello/content_facet_erratum.rb#3

**Comment by jlsherrill** [comment]
[test katello]

**Comment by beav** [comment]
ACK, thanks @jlsherrill

**Pull request merged**
