### PR TITLE
Fixes #28461 - simplify initial version_href saving

### PR DESCRIPTION
**Pull request by jlsherrill**
previously we had to create a new version for a newly created
pulp3 repository manually.  But starting with rc8, one is created
for us automatically.  This changes repo creation to save
the version_href at creation time, instead of waiting until
metadata generate is called.

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note the 2nd commit simply removes some unneeded metadata generates, that i think were being done to make sure a version was created.

**Comment by ianballou** [comment]
I tried to publish a file content view in Pulp 3 and hit this error: `NoMethodError: undefined method 'latest_version_href' for nil:NilClass`

Traceback:
```
/home/vagrant/katello/app/lib/actions/pulp3/repository/create.rb:12:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:563:in `block (3 levels) in execute_run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:32:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:16:in `block in run'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:40:in `block in as_remote_user'
/home/vagrant/katello/app/models/katello/concerns/user_extensions.rb:21:in `cp_config'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:27:in `as_cp_user'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:39:in `as_remote_user'
/home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:16:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/rails_executor_wrap.rb:14:in `block in run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/rails_executor_wrap.rb:13:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action/progress.rb:31:in `with_progress_calculation'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action/progress.rb:17:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:11:in `block in run'
/home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:22:in `with_locale'
/home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:11:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_request_id.rb:49:in `restore_current_request_id'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_user.rb:44:in `restore_curent_user'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/foreman-tasks-0.17.4/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:27:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:19:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware.rb:32:in `run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/stack.rb:23:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/middleware/world.rb:31:in `execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:562:in `block (2 levels) in execute_run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:561:in `catch'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:561:in `block in execute_run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:475:in `block in with_error_handling'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:475:in `catch'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:475:in `with_error_handling'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:556:in `execute_run'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/action.rb:285:in `execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/execution_plan/steps/abstract.rb:167:in `with_meta_calculation'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/director.rb:68:in `execute'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/executors/parallel/worker.rb:15:in `block in on_message'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/executors.rb:12:in `run_user_code'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/executors/parallel/worker.rb:14:in `on_message'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/context.rb:46:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/actor.rb:106:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/actor.rb:47:in `block in on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/actor.rb:59:in `with_backtrace'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/dynflow-1.4.1/lib/dynflow/actor.rb:47:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/buffer.rb:38:in `process_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/buffer.rb:31:in `process_envelopes?'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/buffer.rb:20:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/abstract.rb:25:in `pass'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:162:in `process_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:96:in `block in on_envelope'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:119:in `block (2 levels) in schedule_execution'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-edge-0.4.1/lib-edge/concurrent/actor/core.rb:116:in `block in schedule_execution'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/serialized_execution.rb:18:in `call'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/serialized_execution.rb:96:in `work'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/home/vagrant/foreman/.vendor/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by jlsherrill** [comment]
Hrmm, i only hit that when i hit an error and went to resume, which brought up a good point, that the action run phases need to be able to be re-run in their entirety. I refactored SaveVersion a bit, and it seems to behave better now.

**Comment by ianballou** [comment]
Alright, the latest commit fixed the issue I was seeing.

**Pull request merged**
