### PR TITLE
Fixes #23516 - handle registration if sub status already exists

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@beav the patch we discussed

**Comment by jlsherrill** [comment]
No reproducer steps, as we don't know how to reproduce, but this solved it for a user.

**Comment by beav** [comment]
The `active_record_retry` will catch `ActiveRecord::RecordNotUnique` and `ActiveRecord::RecordInvalid` and then try again 3x, then abort.

I guess what will happen is if the record gets inserted mysteriously by another process between the `if` conditional and insert, the whole conditional will be retried and will then succeed since `empty?` will be false.

Would it make more sense if the `active_record_retry` was replaced rescue block for catching `RecordNotUnique` and passing (asking for forgiveness rather than permission). Maybe something like

```ruby
begin
    ::Katello::SubscriptionStatus.create!(:host => host, :status => ::Katello::SubscriptionStatus::UNKNOWN)
rescue ActiveRecord::RecordNotUnique
    Rails.logger.info("attempted to create SubscriptionStatus object for %s, but object already exists" % host.id)
end
```

The code in the PR works correctly but I could imagine someone refactoring it in the future and re-introducing the race condition by moving the if statement out of the `active_record_retry` block.

**Comment by jlsherrill** [comment]
@beav updated based on our conversation

**Comment by beav** [comment]
it looks like if you pass in `status_override`, it will always do the `save!` which is what we want.

APJ

**Pull request merged**
