### PR TITLE
Fixes #17362 - EQUAL operator equation was modified from <SQL>version_s…

### PR DESCRIPTION
**Pull request by GAZDOWN**
…ortable = version OR (version_sortable = version AND release_sortable)</SQL> to <SQL>version_sortable = version AND release_sortable</SQL> because accordint to boolean algebra A + (AB) = A, so the condition was always true for the version and was completele ignoring release version

### CODE REVIEW

**Comment by jlsherrill** [comment]
Also keep in mind that our commit subject guidelines require a certain format;  `Fixes #redmine_number - brief description`
You're missing the dash '-' in the commit message

**Comment by beav** [comment]
@GAZDOWN is this PR still needed? It looks like the last update was November 2016

**Comment by beav** [comment]
@GAZDOWN If you need assistance or more time for the rebase just let us know, otherwise I am going to close the PR on or after July 1.

**Comment by beav** [comment]
closing PR. Feel free to either re-open or put in a new PR if needed.

**Pull request closed without merging**
