### PR TITLE
Fixes #26011 - use MessageDialog from patternfly

### PR DESCRIPTION
**Pull request by MariaAga**
Change the 'ConfirmDialog' and 'Dialog' Katello's components to 'MessageDialog' from patternfly,
Small design changes can be seen here: https://projects.theforeman.org/issues/26011
Related to the "remove components from Katello's 'move_to_foreman'" PR : https://github.com/Katello/katello/pull/7965

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Thanks @MariaAga

**Pull request merged**
