### PR TITLE
Fixes #10809: Remove unused doc/ directory.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK

**Comment by stbenjam** [comment]
Uh, @ehelms @jlsherrill  you broke my dev install.

```
lrwxrwxrwx. 1 vagrant vagrant 42 May 21 06:27 /home/vagrant/foreman/bundler.d/katello.local.rb -> /home/vagrant/katello/doc/katello.local.rb
```

**Comment by ehelms** [comment]
I noticed this today, I'll work on updating the development module today
and send and email how to fix environments.

**Comment by komidore64** [comment]
@stbenjam :+1:

**Pull request merged**
