### PR TITLE
Fixes #31150 - content view component auth fixes

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by parthaa** [comment]
I tested it and most of it seems to work ok except for a couple of things
I have  user with the `edit_content_views` perm and a filter criteria of `composite=true`
I'd expect the following to fail
```
$ hammer -u raja -p changeme content-view component add   --component-content-view-id=8 --composite-content-view-id=9  --latest
Component added to content view.
```

looks like it doesn't do a look up on the perms for the objects being added.

**Comment by jlsherrill** [comment]
updated partha to throw a 404 on the add

**Review by parthaa — APPROVED** [review]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
