### PR TITLE
Fixes #23652 - Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by johnsonm325**
Updated links

### CODE REVIEW

**Comment by beav** [comment]
@johnsonm325 thanks for the patch!

It looks like you changed the PR title, but the prprocessor bot is complaining about the commit message. Can you make the same text update to the first line of the commit message and repush? :robot:

**Comment by johnsonm325** [comment]
@beav Sure thing, I'll just need to do this later. Didn't see this message last night. I'll take care of it when I get home.

This bot and I are quickly becoming enemies! :)

**Comment by jlsherrill** [comment]
@johnsonm325 hi!  you updated the PR title, but your commit is still incorrect.  You'll need to amend your commit message and push the new commit overtop the old

**Comment by johnsonm325** [comment]
yeah, thanks @jlsherrill. I meant to take care of this yesterday since @beav asked me to do the same. I'll handle tonight.

**Pull request merged**
