### PR TITLE
Fixes #17865 - FileUnitPresenter has the wrong filename

### PR DESCRIPTION
**Pull request by dLobatog**
Since FileUnitPresenter has the wrong file name, Rails is not able to
load it. Therefore, every time Actions::Pulp::Repository::Sync is
called, an error "uninitialized constant
Actions::Pulp::Repository::Presenters::FileUnitPresenter". This blocks
critical operations such as simply installing katello-agent from a newly
provisioned host.

### CODE REVIEW

**Comment by ehelms** [comment]
Interesting - did something recently change in core that caused this issue to suddenly start appearing?

**Comment by jlsherrill** [comment]
I'm guessing its only an issue on the dev env?  

I haven't seen any issues myself, but these types of things tend to be luck (or unluck) related.

**Comment by jlsherrill** [comment]
[test]

**Comment by dLobatog** [comment]
Nothing changed, Rails does not load `FileUnitPresenter` if the file isn't called exactly that (with underscores, `file_unit_presenter`) - it happens with any class/module whose name doesn't match the filename exactly. I'm not sure if it affects production or not to be honest, I saw it on my dev setup 😄 

I'll try to sync something on production without the patch see what happens

**Comment by jlsherrill** [comment]
ACK Thanks @dLobatog !

**Pull request merged**
