### PR TITLE
Fixes #18286: fix usages of filters and search-filter blocks.

### PR DESCRIPTION
**Pull request by waldenraines**
We now have a distinct purpose for the blocks filters and search-filter
and we should use these blocks appropriately.

http://projects.theforeman.org/issues/18286

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/170

**Comment by waldenraines** [comment]
Still need to fix the filters and search-filters in https://github.com/Katello/katello/pull/6494.  Will do that after that is merged or in that PR if the bastion changes in https://github.com/Katello/bastion/pull/170 are merged first.

**Comment by waldenraines** [comment]
> Still need to fix the filters and search-filters in #6494. Will do that after #6494 is merged or will fix in #6494 if the bastion changes in Katello/bastion#170 are merged first.

Updated to include necessary OSTree changes from #6494

**Comment by ehelms** [comment]
This just fixes the usage? And is not intended to put the filters to the left of the search box? Just want to clarify what to review.

**Comment by waldenraines** [comment]
> This just fixes the usage? And is not intended to put the filters to the left of the search box? Just want to clarify what to review.

Right, the changes in the required Katello/bastion#170 move the search-filters to the left.  The filters should be displayed on the right (if I remember correctly).  This PR fixes the issue of us using 'filter' and 'search-filter' interchangeably and inconsistently.

**Pull request merged**
