### PR TITLE
Fixes #14433 - Migrations no longer fail on mysql

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ehelms** [comment]
I'm happy to merge this, but since Katello does not officially support MySQL there is no guarantee future changes won't break it again. What is your use case out of curiosity?

**Comment by xprazak2** [comment]
Jenkins runs test_plugin_matrix when testing plugin PRs and foreman_pipeline plugin needs Katello, that is where I came across this. If it breaks in the future I can fix again, I now know where to look :-)

**Comment by ehelms** [comment]
@xprazak2 that works :)

@daviddavis would you mind checking this? you know AR/database better than I

**Comment by daviddavis** [comment]
This looks good to me.

**Pull request merged**
