### PR TITLE
Fixes #22850 - resolve registration race condition around sub_status

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
@jlsherrill wow nice, thanks. will test today.

**Comment by beav** [comment]
@jlsherrill I get an error but it is kind of odd:

```
[katello/cp_proxy] [E] <Class> ActiveRecord::RecordInvalid
[katello/cp_proxy] [E] host: ["can't be blank"]
```

I'm not sure why this is happening since we are calling `host.save!` before invoking the method.

**Comment by beav** [comment]
@jlsherrill I added this to populate_subscription_facet before the facet `save!` instead of using the existing patch:

```
subscription_facet.update_subscription_status(::Katello::SubscriptionStatus::UNKNOWN)
```

I get a 200 now, but still need to load test.

**Comment by beav** [comment]
@jlsherrill 

I am load testing this, but it looks good so far with the change from `host_id` to `host` that we discussed.

I am :+1: to that after the test is complete.

**Comment by beav** [comment]
@jlsherrill load test success 

before patch, registering 2 machines at a time, 100x: 51 errors

after patch: 0 errors

APJ

**Comment by beav** [comment]
failure seems unrelated to PR

```
FAIL webpack/scenes/RedHatRepositories/components/__tests__/RepositoryTypeIcon.test.js

  ● RepositoryTypeIcon component › rendering › it should get rendered correctly
```

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
