### PR TITLE
fixes #18441 - datetime format should be db independent

### PR DESCRIPTION
**Pull request by pronix**
simple change datetime format correct for pgsql and for mysql
http://projects.theforeman.org/issues/18441
there is problem if switch db to mysql - datetime format not fit.
but by default rails has option to adapt datetime format based on current database.

### CODE REVIEW

**Comment by jlsherrill** [comment]
@pronix thanks for the commit!  There's a small problem with your commit message:

fixes #18441 datetime format should be db independent
should be:
fixes #18441 - datetime format should be db independent

also can you update the commit message (not just the PR title).  Thanks!

**Comment by pronix** [comment]
@jlsherrill thanks for feedback.
commit message, description and pr topic are update.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
Thanks @pronix !

**Comment by pronix** [comment]
thank you.

**Pull request merged**
