### PR TITLE
[CP] Release Katello 4.11.1

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Review by jeremylenz — APPROVED** [review]
APJ :+1:

**Comment by ianballou** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
Seems now the postgresql-evr extension isn't getting installed correctly.

**Comment by ianballou** [comment]
Fix appears to be https://github.com/theforeman/foreman-infra/pull/2026

**Comment by evgeni** [comment]
[test katello]

**Comment by evgeni** [comment]
At least now it's an actual failure? ;)

**Comment by ianballou** [comment]
Stuck on the issue with chrome 121. Waiting for 122 to come out.

**Comment by ianballou** [comment]
[test katello]

**Pull request merged**
