### PR TITLE
Refs #30630 - remove broken monkey for pulp 3.6

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Should this require a new minimum version of the Pulp bindings?

**Review by evgeni — APPROVED** [review]
:see_no_evil:

**Comment by jlsherrill** [comment]
@ekohl  yes, good idea!

**Review by ekohl — APPROVED** [review]

**Review by jturel — APPROVED** [review]
APJ

**Comment by jlsherrill** [comment]
I'm merging this as it looks like it passed all tests but jenkins just timed out: https://ci.theforeman.org/blue/organizations/jenkins/katello-pr-test/detail/katello-pr-test/4906/pipeline

**Pull request merged**
