### PR TITLE
Fixes #18370: fix styling of katello dropdown buttons.

### PR DESCRIPTION
**Pull request by waldenraines**
Instead of using the first item in the list of the actions as the button
use the phrase "Select Action" and don't disable the button when rows
are not selected.

http://projects.theforeman.org/issues/18370

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/184

**Comment by johnpmitsch** [comment]
@waldenraines Its possible something is misconfigured on my end, but the CSS looks broken.
here
I'm using a local bastion checkout with the PR you mentioned

**Comment by waldenraines** [comment]
> @waldenraines Its possible something is misconfigured on my end, but the CSS looks broken.

Looks like you are missing https://github.com/theforeman/foreman/pull/4402.  Update your foreman and bundle install and try again.

**Comment by johnpmitsch** [comment]
@waldenraines Thanks, that fixed it
Not sure if this is related to this PR, but the tasks page under products looks greyed-out
here
I'm seeing these errors in the console
```
bundle-9aa8502….js:75 Uncaught TypeError: Cannot read property 'markup' of undefined
    at Object.i [as mount] (bundle-9aa8502….js:75)
    at tasks:86

bastion.js:11757 GET http://192.168.121.157:3000/katello/api/v2/tasks?organization_id=1&page=1&paged=true&per_page=20&search= 404 (Not Found)
```
The normal top-level task page seems to work fine

**Comment by johnpmitsch** [comment]
When I select "Change Errata" in the content host dropdown, I get a [traceback](https://paste.fedoraproject.org/paste/0Swis-G6thJ1Yif128yEw15M1UNdIGYhyRLivL9gydE=)

**Comment by johnpmitsch** [comment]
@waldenraines everything else looks good :+1:

**Comment by waldenraines** [comment]
> Not sure if this is related to this PR, but the tasks page under products looks greyed-out

https://github.com/Katello/katello/pull/6712

> bundle-9aa8502….js:75 Uncaught TypeError: Cannot read property 'markup' of undefined

That is coming from foreman.

**Comment by waldenraines** [comment]
> When I select a host and click "Manage Errata" in the content host dropdown, I get a traceback

Ah, oops, will fix.

**Comment by johnpmitsch** [comment]
> Not sure if this is related to this PR, but the tasks page under products looks greyed-out
> #6712

@waldenraines thanks, I was able to view it fine after a rebase

**Comment by waldenraines** [comment]
> When I select a host and click "Manage Errata" in the content host dropdown, I get a traceback

This also happens in master.  I have filed http://projects.theforeman.org/issues/19136 for this issue and would like to fix this outside of the context of this PR.

**Comment by waldenraines** [comment]
> and would like to fix this outside of the context of this PR.

https://github.com/Katello/katello/pull/6720

**Pull request merged**
