### PR TITLE
fixes #10440 - gpg key validation by default

### PR DESCRIPTION
**Pull request by dustints**

### CODE REVIEW

**Comment by ehelms** [comment]
Reading through the Redmine issue, the reporter is talking about the UI not showing errors to the user. I don't see how this change addresses that issue.

**Comment by dustints** [comment]
@ehelms let me ask reporter to find what he means.
validation seems to be appearing on the UI correctly with validations turned on.

**Comment by ehelms** [comment]
@dustints Hrmm, I would think create validations would appear whether this setting was on or off.

**Comment by dustints** [comment]
@ehelms nix my comment, was meaning key validator. I feel like that's what the reporter was getting at.

**Comment by ehelms** [comment]
Reading the bugzilla, the reporter seems to be talking strictly of UI notifications appearing and not this particular setting being on by default.

**Pull request closed without merging**
