### PR TITLE
Fixes #15056 - Use 'show_feature_version' to display Pulp and Pulp no…

### PR DESCRIPTION
**Pull request by shlomizadok**
…de versions

### CODE REVIEW

**Comment by shlomizadok** [comment]
@ehelms, @stbenjam, @mccun934  mind giving this a spin please?
Thanks :)

**Comment by johnpmitsch** [comment]
@shlomizadok what page can these changes be found on?

**Comment by shlomizadok** [comment]
@johnpmitsch smart_proxies#show, in the services tab. Thanks :)

**Comment by johnpmitsch** [comment]
@shlomizadok nevermind, I checked the issue :) This fixes the spinner issue for me, so ACK from me.

**Comment by shlomizadok** [comment]
@johnpmitsch :+1: thanks!

**Comment by johnpmitsch** [comment]
Thanks @shlomizadok!

**Pull request merged**
