### PR TITLE
Fixes #14309 - Copy content view no longer raises NoMethodError

### PR DESCRIPTION
**Pull request by xprazak2**
This was a weird one. Current code in master works in development, but not in production. Additional save seems to take care of the issue.

### CODE REVIEW

**Comment by bbuckingham** [comment]
Thanks @xprazak2 !  I tested with the fix and the error is gone on my production install.  APJ !  (Note: there is one rubocop error to address).

@daviddavis, Would you mind taking a quick peak at this one as well?  I am curious if there is a better way to do this without the additional 'save' or if that is simply required now.

**Comment by daviddavis** [comment]
I wonder if you can remove the `save!` on line 89?

**Comment by xprazak2** [comment]
Seems like we can. I had to extract a method, `copy` got too long and rubocop was complaining.

**Comment by daviddavis** [comment]
LGTM

**Comment by daviddavis** [comment]
Oh, you hit the class length cop. Technically if you remove line 88 and just add the save, you won't have to break out another method.

**Comment by xprazak2** [comment]
Right, I actually removed the other `save!`. Should turn green now.

**Comment by bbuckingham** [comment]
@xprazak2 , ACK.  Thanks for the fix!

**Pull request merged**
