### PR TITLE
Fixes #32312 - Typo on the test

### PR DESCRIPTION
**Pull request by waldirio**
State field was testing `stoppped` instead of `stopped`

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by ares** [comment]
LGTM, the redmine issues check fails because the commit message should also say "Fixes #32312 - ...". @waldirio could you please update and `git push --force`? Thanks for the patch!!

**Comment by waldirio** [comment]
> LGTM, the redmine issues check fails because the commit message should also say "Fixes #32312 - ...". @waldirio could you please update and `git push --force`? Thanks for the patch!!

done my friend. Thank you!

**Comment by waldirio** [comment]
[test katello]

**Review by jturel — APPROVED** [review]
Thanks @waldirio !

**Pull request merged**
