### PR TITLE
Fixes #16282: Explicitly require i18n, components and ui.router modules

### PR DESCRIPTION
**Pull request by ehelms**
Changes in Bastion required explicit requires on some modules
that were detected by breaking tests.

### CODE REVIEW

**Comment by ehelms** [comment]
Will require https://github.com/Katello/bastion/pull/125 to fully pass

**Comment by waldenraines** [comment]
Hah,  I was making the exact same changes so ACK pending other PR merge and Jenkins.

**Comment by ehelms** [comment]
Kickedoff here -- http://ci.theforeman.org/job/test_katello_pull_request/9895/

**Comment by waldenraines** [comment]
ACK.

**Comment by waldenraines** [comment]
I'm going to go ahead and merge this so we can have a green build in the morning.

**Pull request merged**
