### PR TITLE
Fixes #35516 - Reconfigure yggdrasil on content source change

### PR DESCRIPTION
**Pull request by adamruzicka**
if present

### CODE REVIEW

**Comment by ianballou** [comment]
[test katello]

**Review by ianballou — APPROVED** [review]
After running the job invocation, my yggdrasil config switched over to my smart proxy:
```
# yggdrasil global configuration settings written by katello-pull-transport-migrate
broker = ["mqtts://centos8-stream-foreman-proxy-4-6.cannolo.example.com:1883"]
cert-file = "/etc/pki/consumer/cert.pem"
key-file = "/etc/pki/consumer/key.pem"
ca-root = ["/etc/rhsm/ca/katello-server-ca.pem"]
log-level = "error"
```

**Review by ianballou — COMMENTED** [review]
I ran it again without changing the content source for a test and realized that the new job invocation is hanging without completion.  It ends up with "Actions::ProxyAction (suspended)".  I'm testing this on Katello 4.6.

```
 Input:

---
proxy_operation_name: ssh
ssh_user: root
effective_user: root
effective_user_method: sudo
cleanup_working_dirs: true
ssh_port: 22
hostname: centos8.cannolo.example.com
script: "#!/bin/sh\n\n# Prepare SSL certificate\n\nKATELLO_SERVER_CA_CERT=/etc/rhsm/ca/katello-server-ca.pem\nSSL_CA_CERT=$(mktemp)\ncat
  << EOF > $SSL_CA_CERT\n-----BEGIN CERTIFICATE-----\nMIIHRzCCBS+gAwIBAgIUTe/BPqwySkDXn+ly167u3Jl9+WgwDQYJKoZIhvcNAQEL\nBQAwgZkxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G\nA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UECwwLU29tZU9y\nZ1VuaXQxNzA1BgNVBAMMLmNlbnRvczgtc3RyZWFtLWthdGVsbG8tNC02LmNhbm5v\nbG8uZXhhbXBsZS5jb20wHhcNMjIwOTIyMTUxMDA1WhcNMzgwMTE4MTUxMDA1WjCB\nmTELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQLDAtTb21lT3JnVW5p\ndDE3MDUGA1UEAwwuY2VudG9zOC1zdHJlYW0ta2F0ZWxsby00LTYuY2Fubm9sby5l\neGFtcGxlLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALBhNdWa\nSuVKuedX3SwTyAUtXu06/zC6QcGsR7MAYCtLbrC8zY0r65UQh4XQsWeGQQcrauyR\nzA/U1T5VcFFNufjhQdsAqX3D1UfCWRbUynExKEF+gAQHAXu60oN2dkqh2oiA/zAX\ni8Rc5YtZfIqNS9sonildVlboYUo2D/tvz8QQfJib8wFlhWK2/X3wx+pF1wrezsAr\nj+ETJtBirbp0kJYtBSxxO7yxciv6V9vEnZ8cUIP7zXyIM65vpB2EQd192uEAljDv\nCvv3R214prhOeH5UZcNXJyFToqoWOKD4+KKVekthGqfTtbygBLkLyah/kE3qlNRm\nsTvFN68SWOWiakchR1eGEpYj7oMmu4ar7u/78EpokYAw9cWH0bplKnKXKGmJVsBh\nn7OoCPpw/xMdUCjnd2xqr7asxINQk6fAnrKl96m7ZD8J+TyvUkXnpQkmafLg3wkt\ncP+rcu/D8sh+mCFuABb9zt7hko82hJp7APfj4An06QqafSEEOmzkJxZQosKzSlIy\nZJhHO6aSCH5y1k09jZ1N4bbuwW+EJwxo2V1Bp8WfT5GteAFKrCMaud02hzLxX16H\nf9gNOrXqSl9J+i0+ADqRFxc0ElO4nNMJVcRAIyLaUTuxox9fEfNHib/mwEtLQERl\nAFgn3UwT0u9rk6Sq3Obek5T0qzu3qjR4GMz1AgMBAAGjggGDMIIBfzAMBgNVHRME\nBTADAQH/MAsGA1UdDwQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH\nAwIwEQYJYIZIAYb4QgEBBAQDAgJEMDUGCWCGSAGG+EIBDQQoFiZLYXRlbGxvIFNT\nTCBUb29sIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU9kg1WN0B7jBc\nk+NPt8jMHghiXjowgdkGA1UdIwSB0TCBzoAU9kg1WN0B7jBck+NPt8jMHghiXjqh\ngZ+kgZwwgZkxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQ\nMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHS2F0ZWxsbzEUMBIGA1UECwwLU29t\nZU9yZ1VuaXQxNzA1BgNVBAMMLmNlbnRvczgtc3RyZWFtLWthdGVsbG8tNC02LmNh\nbm5vbG8uZXhhbXBsZS5jb22CFE3vwT6sMkpA15/pcteu7tyZffloMA0GCSqGSIb3\nDQEBCwUAA4ICAQA3dQmdpmEO5r4NKlFkwvB71vU530iMXB4bzfd7SnplGBI1QWrK\nCrR6ERHvtCkempv+tqy6w5VGciGGuqzBv5jLoB21R7MZ42DV7nSRcwd6Mcn3Ofgd\neHVlXThs6zNVafrXbWlb3XdNaecGgz8FmIUAin4kC95zJrHqqE7XBQ+IBAH8eaJt\nljaSitzAVg9gOPGRM74Xoa33Diaom9FJqvQqxk+aP+nfvrFmsCoZYtWz47GrPhNu\n/w595QfPWO0jlXxDIKyOE61erUugR1eF/1M0tkGbFmY8I8ZF6idj6Zkw423vLJo4\ne9BikJBeU4UrKNhJQMR9q7P2yo+iRqHYc9t6N1Ra4NMUwZebWZcmI7KLmhqpCcAw\nDiBHcA84RfHJbYzQbeCp9DxaqjFiCoHQNRdlaQB4C+wf41zToe6TGAOdVqpZ8naT\nrI6hGHu4iWuZQROhMipZ3QmVv2BHD91rtCnbbyd6XvMgRhyi+1ObspdrPZ4OHFmt\nP5V99Xp+gMtpOiNUGPSEmMlJ76coy4JlLfKhipb4d6CldG4XpOG6XlzBfA51+naV\nhLTAuzrkGgkpnWjlI21uFM8wLVaI5KhKUld0W0UjjU+PrrHe5VyUDSYMLFFeZ3p5\nntyMyc1AJWPyvRu4pK/3vPyo96/AunZYET76mj8aZZZ+3k579xfEfUKi0A==\n-----END
  CERTIFICATE-----\n\nEOF\n\nmkdir -p /etc/rhsm/ca\ncp -f $SSL_CA_CERT $KATELLO_SERVER_CA_CERT\nchmod
  644 $KATELLO_SERVER_CA_CERT\n\n# Configure subscription-manager\nRHSM_CFG=/etc/rhsm/rhsm.conf\n\ntest
  -f $RHSM_CFG.bak || cp $RHSM_CFG $RHSM_CFG.bak\n\nsubscription-manager config   --server.hostname=\"centos8-stream-katello-4-6.cannolo.example.com\"
  \  --server.port=\"443\"   --server.prefix=\"/rhsm\"   --rhsm.repo_ca_cert=\"$KATELLO_SERVER_CA_CERT\"
  \  --rhsm.baseurl=\"https://centos8-stream-katello-4-6.cannolo.example.com/pulp/content\"\n\n\nif
  [ -f /etc/yggdrasil/config.toml ]; then\n  cp /etc/yggdrasil/config.toml /etc/yggdrasil/config.toml.bak\n
  \ \necho \"Starting deployment of REX pull provider\"\n# check if system is registered\nsubscription-manager
  identity > /dev/null\nif [ $? -ne 0 ]; then\n    echo \"Please register with subscription-manager
  first, then re-run '$0'.\"\n    exit 1\nfi\n\nset -e\n\necho '#'\necho '# Installing
  packages'\necho '#'\n\ndnf -y install foreman_ygg_worker\n\n\necho \"Getting configuration
  from subscription-manager...\"\nKPPTEMPFILE=$(mktemp kpp_tempfile_XXXXXXXX)\ntrap
  \"rm -f $KPPTEMPFILE\" ERR EXIT\nsubscription-manager config --list > $KPPTEMPFILE\nCONSUMER_CERT_DIR=$(grep
  'consumercertdir' $KPPTEMPFILE | cut -d= -f2 | xargs | sed 's/[][]//g')\nCERT_FILE=$CONSUMER_CERT_DIR/cert.pem\nKEY_FILE=$CONSUMER_CERT_DIR/key.pem\nCA_FILE=$(grep
  'repo_ca_cert = ' $KPPTEMPFILE | cut -d= -f2 | xargs | cut -d ' ' -f1)\nSERVER_NAME=$(grep
  'hostname = ' $KPPTEMPFILE | cut -d= -f2 | xargs | cut -d ' ' -f1)\n\n# fail if
  no server name, cert dir, or ca file\nif [ -z \"$SERVER_NAME\" ] || [ -z \"$CONSUMER_CERT_DIR\"
  ] || [ -z \"$CA_FILE\" ]; then\n    echo \"Unable to determine config from 'subscription-manager
  config --list'; exiting\"\n    exit 1\nfi\n\n# fail if client is not registered
  to a Katello\nif ! grep -q 'prefix = \\/rhsm' $KPPTEMPFILE; then\n    echo \"Client
  is registered to RHSM; exiting\"\n    exit 1\nfi\n\n# set SYSCONFDIR to /etc if
  it is not set\nif [ -z \"$SYSCONFDIR\" ]; then\n    SYSCONFDIR=/etc\nfi\n\n# see
  if /etc/yggdrasil/config.toml exists\nCONFIGTOML=$SYSCONFDIR/yggdrasil/config.toml\nif
  [ -f $CONFIGTOML ]; then\n    # make a backup of CONFIGTOML\n    cp $CONFIGTOML
  $CONFIGTOML.bak\n    cat <<EOF > $CONFIGTOML\n# yggdrasil global configuration settings
  written by katello-pull-transport-migrate\nbroker = [\"mqtts://$SERVER_NAME:1883\"]\ncert-file
  = \"$CERT_FILE\"\nkey-file = \"$KEY_FILE\"\nca-root = [\"$CA_FILE\"]\nlog-level
  = \"error\"\nEOF\n\nelse\n    echo \"$SYSCONFDIR/yggdrasil/config.toml not found!
  Did 'yum install yggdrasil' succeed?\"\n    exit 1\nfi\n\n# start the yggdrasild
  service\necho \"Starting yggdrasild...\"\nsystemctl try-restart yggdrasild\nsystemctl
  enable --now yggdrasild\n\n# check status of yggdrasild and fail if it is not running\n#
  possible failure reason: incorrect protocol (should be tcp:// or mqtt://) or port
  (should be 1883)\n# also, cert-file and key-file must be valid\n# and broker must
  be running on the server\nyggdrasil status\n\nif ! systemctl is-active --quiet yggdrasild;
  then\n    echo \"\"\n    echo \"yggdrasild failed to start! Check configuration
  in $CONFIGTOML and make sure the broker is running on the server.\"\n    exit $?\nfi\n\necho
  \"Remote execution pull provider successfully configured!\"\n\nfi"
execution_timeout_interval: 
secrets: Secrets hidden
use_batch_triggering: true
use_concurrency_control: false
first_execution: false
alternative_names:
  fqdn: centos8.cannolo.example.com
  consumer_uuid: 61ce9a9c-b579-4999-aca4-c6c07b262c2e
connection_options:
  retry_interval: 15
  retry_count: 4
  proxy_batch_triggering: true
proxy_url: https://centos8-stream-katello-4-6.cannolo.example.com:9090
proxy_action_name: Proxy::RemoteExecution::Ssh::Actions::RunScript
current_request_id: 1758b4c8-1e32-44b4-8877-459a24b161fb
current_timezone: America/New_York
current_organization_id: 1
current_location_id: 2
current_user_id: 4

```

**Comment by ianballou** [comment]
The hanging happens even though I can successfully run other things, like package installations or `uptime`.

**Comment by ianballou** [comment]
I'm seeing the `.bak` file, so the hanging is likely in `<%= snippet 'remote_execution_pull_setup' %>`

**Comment by ianballou** [comment]
I'm testing along with https://github.com/Katello/katello/pull/10286 since it also affects content source changes.

**Comment by ianballou** [comment]
In the job, right after changing the content source to my proxy, I'm seeing `proxy_url: https://centos8-stream-foreman-proxy-4-6.cannolo.example.com:9090`.  Should the job not run with the old proxy since it needs to change the yggdrasil config to point to the new proxy?

**Comment by ianballou** [comment]
Also, these issues aside, should the manual script that pops up after changing the content source also include the yggdrasil config change?

image

**Comment by jeremylenz** [comment]
> should the manual script that pops up after changing the content source also include the yggdrasil config change?

I'd vote yes to that!

**Comment by adamruzicka** [comment]
> Also, restrict registered smart proxies is set to No

What does this even do?

> In the job, right after changing the content source to my proxy, I'm seeing `proxy_url: https://centos8-stream-foreman-proxy-4-6.cannolo.example.com:9090`. Should the job not run with the old proxy since it needs to change the yggdrasil config to point to the new proxy?

I would blame https://github.com/Katello/katello/pull/10286 for that. If you change what proxy should be used before you update the client, then this is what you get and there's no sensible way around it

**Comment by ianballou** [comment]
Here are the logs when I run the job on the smart-proxy:

```
Sep 23 15:44:34 centos8-stream-katello-4-6 smart-proxy[5663]: 192.168.122.67 - - [23/Sep/2022:15:44:34 UTC] "GET /dynflow/tasks/count?state=running HTTP/1.1" 200 29
Sep 23 15:44:34 centos8-stream-katello-4-6 smart-proxy[5663]: - -> /dynflow/tasks/count?state=running
Sep 23 15:44:35 centos8-stream-katello-4-6 smart-proxy[5663]: 192.168.122.67 - - [23/Sep/2022:15:44:35 UTC] "POST /dynflow/tasks/launch HTTP/1.1" 200 80
Sep 23 15:44:35 centos8-stream-katello-4-6 smart-proxy[5663]: - -> /dynflow/tasks/launch
Sep 23 15:44:35 centos8-stream-katello-4-6 mosquitto[849]: 1663947875: New connection from 192.168.122.67:55056 on port 1883.
Sep 23 15:44:35 centos8-stream-katello-4-6 mosquitto[849]: 1663947875: New client connected from 192.168.122.67:55056 as auto-0B1B1FEF-28B9-E433-8E7B-4EE2B711695D (p2, c1, k15, u'centos8-stream-katello-4-6.cannolo.example.com').
Sep 23 15:44:35 centos8-stream-katello-4-6 mosquitto[849]: 1663947875: Client auto-0B1B1FEF-28B9-E433-8E7B-4EE2B711695D disconnected.
Sep 23 15:44:35 centos8-stream-katello-4-6 smart-proxy[5663]: 192.168.122.94 - - [23/Sep/2022:15:44:35 UTC] "GET /ssh/jobs/48a6f7d6-38cd-4a8f-93bd-8a8fb3f21cf4 HTTP/1.1" 200 5903
Sep 23 15:44:35 centos8-stream-katello-4-6 smart-proxy[5663]: - -> /ssh/jobs/48a6f7d6-38cd-4a8f-93bd-8a8fb3f21cf4
Sep 23 15:44:37 centos8-stream-katello-4-6 mosquitto[849]: 1663947877: Client 61ce9a9c-b579-4999-aca4-c6c07b262c2e closed its connection.
Sep 23 15:44:37 centos8-stream-katello-4-6 mosquitto[849]: 1663947877: New connection from 192.168.122.94:48324 on port 1883.
Sep 23 15:44:37 centos8-stream-katello-4-6 mosquitto[849]: 1663947877: New client connected from 192.168.122.94:48324 as 61ce9a9c-b579-4999-aca4-c6c07b262c2e (p2, c1, k30, u'61ce9a9c-b579-4999-aca4-c6c07b262c2e').
```

And here are the logs on the client:
```
Sep 23 15:44:35 centos8 yggdrasild[2805]: [yggdrasild] 2022/09/23 15:44:35 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/09/23 15:44:35 Starting job 48a6f7d6-38cd-4a8f-93bd-8a8fb3f21cf4
Sep 23 15:44:35 centos8 yggdrasild[2805]: [yggdrasild] 2022/09/23 15:44:35 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/09/23 15:44:35 started script process: 2819
Sep 23 15:44:36 centos8 subscription-manager[2831]: Added subscription for 'Content Access' contract 'None'
Sep 23 15:44:36 centos8 subscription-manager[2831]: Added subscription for product ' Content Access'
Sep 23 15:44:37 centos8 systemd[1]: Stopping yggdrasil daemon...
Sep 23 15:44:37 centos8 systemd[1]: yggdrasild.service: Succeeded.
Sep 23 15:44:37 centos8 systemd[1]: Stopped yggdrasil daemon.
Sep 23 15:44:37 centos8 systemd[1]: Started yggdrasil daemon.
Sep 23 15:44:37 centos8 yggdrasild[2865]: [yggdrasild] 2022/09/23 15:44:37 cannot start watching '/etc/yggdrasil/tags.toml': lstat /etc/yggdrasil/tags.toml: no such file or directory
```

The job seems to do something, but never finishes completely in Foreman.

**Comment by ianballou** [comment]
To fix the stuck task issue, I put 
```
systemd-run --on-active=10 --collect --no-block systemctl restart yggdrasild
```
after
```
...
systemctl enable --now yggdrasild
...
``` 

and removed

```
systemctl try-restart yggdrasild
```

So:

```
<%#
kind: snippet
name: remote_execution_pull_setup_delayed_ygg_restart
model: ProvisioningTemplate
snippet: true
description: |
  Snippet for installing and setting up a client to be reachable by remote execution in pull mode
-%>

echo "Starting deployment of REX pull provider"
# check if system is registered
subscription-manager identity > /dev/null
if [ $? -ne 0 ]; then
    echo "Please register with subscription-manager first, then re-run '$0'."
    exit 1
fi

set -e

<%= install_packages('foreman_ygg_worker') %>

echo "Getting configuration from subscription-manager..."
KPPTEMPFILE=$(mktemp kpp_tempfile_XXXXXXXX)
trap "rm -f $KPPTEMPFILE" ERR EXIT
subscription-manager config --list > $KPPTEMPFILE
CONSUMER_CERT_DIR=$(grep 'consumercertdir' $KPPTEMPFILE | cut -d= -f2 | xargs | sed 's/[][]//g')
CERT_FILE=$CONSUMER_CERT_DIR/cert.pem
KEY_FILE=$CONSUMER_CERT_DIR/key.pem
CA_FILE=$(grep 'repo_ca_cert = ' $KPPTEMPFILE | cut -d= -f2 | xargs | cut -d ' ' -f1)
SERVER_NAME=$(grep 'hostname = ' $KPPTEMPFILE | cut -d= -f2 | xargs | cut -d ' ' -f1)

# fail if no server name, cert dir, or ca file
if [ -z "$SERVER_NAME" ] || [ -z "$CONSUMER_CERT_DIR" ] || [ -z "$CA_FILE" ]; then
    echo "Unable to determine config from 'subscription-manager config --list'; exiting"
    exit 1
fi

# fail if client is not registered to a Katello
if ! grep -q 'prefix = \/rhsm' $KPPTEMPFILE; then
    echo "Client is registered to RHSM; exiting"
    exit 1
fi

# set SYSCONFDIR to /etc if it is not set
if [ -z "$SYSCONFDIR" ]; then
    SYSCONFDIR=/etc
fi

# see if /etc/yggdrasil/config.toml exists
CONFIGTOML=$SYSCONFDIR/yggdrasil/config.toml
if [ -f $CONFIGTOML ]; then
    # make a backup of CONFIGTOML
    cp $CONFIGTOML $CONFIGTOML.bak
    cat <<EOF > $CONFIGTOML
# yggdrasil global configuration settings written by katello-pull-transport-migrate
broker = ["mqtts://$SERVER_NAME:1883"]
cert-file = "$CERT_FILE"
key-file = "$KEY_FILE"
ca-root = ["$CA_FILE"]
log-level = "error"
EOF

else
    echo "$SYSCONFDIR/yggdrasil/config.toml not found! Did 'yum install yggdrasil' succeed?"
    exit 1
fi

# start the yggdrasild service
echo "Starting yggdrasild..."
#systemctl try-restart yggdrasild
systemctl enable --now yggdrasild
systemd-run --on-active=10 --collect --no-block systemctl restart yggdrasild

# check status of yggdrasild and fail if it is not running
# possible failure reason: incorrect protocol (should be tcp:// or mqtt://) or port (should be 1883)
# also, cert-file and key-file must be valid
# and broker must be running on the server
yggdrasil status

if ! systemctl is-active --quiet yggdrasild; then
    echo ""
    echo "yggdrasild failed to start! Check configuration in $CONFIGTOML and make sure the broker is running on the server."
    exit $?
fi

echo "Remote execution pull provider successfully configured!"
```

My test steps were:

1) Ensure the host could receive commands via the pull provider
2) Change the content source of the host to my other proxy
3) Run the new change_content_source job and see that it completes successfully
4) Change the registered-through proxy for the host to the other proxy
5) Try a pull provider job again like `uptime`
6) Try 1-5 again but back to the original proxy

**Comment by adamruzicka** [comment]
Alright, how about this together with https://github.com/theforeman/foreman/pull/9435 ?

**Review by ianballou — APPROVED** [review]
Works for me now!

**Review by ianballou — CHANGES_REQUESTED** [review]
Actually, I realized this exposed a bug in Katello.  Since you're using a provisioning template, the kickstart repo medium path wants to be loaded.  The host may not have one though depending on how it was registered.

Suggested change that I tested to `app/lib/katello/concerns/renderer_extensions.rb`:

```
        def kickstart_attributes
          super

          medium_provider = Katello::ManagedContentMediumProvider.new(host)
          content_view = host.try(:content_facet).try(:content_view) || host.try(:content_view)

          if content_view && host.operatingsystem.is_a?(Redhat) &&
                  host.operatingsystem.kickstart_repos(host).first.present? &&
                  host&.content_facet.kickstart_repository.present?        <<<<< Added a kickstart repo check on the content facet.
            @mediapath ||= host.operatingsystem.mediumpath(medium_provider)
          end
        end
```

**Review by ianballou — APPROVED** [review]
We'll fix up the other Katello bug in a new PR.

**Comment by adamruzicka** [comment]
Tracking the other issue as https://projects.theforeman.org/issues/35566

**Comment by ianballou** [comment]
Edit I forgot about the copy/paste script that pops up in the UI.  It's hardcoded with the methods in `app/helpers/katello/content_source_helper.rb`

**Comment by ianballou** [comment]
For the rendering issue: https://github.com/Katello/katello/pull/10288

**Comment by ianballou** [comment]
@adamruzicka it's looking good! One more thing -- the following line:
```
if systemctl is-enabled yggdrasild 2>/dev/null && [ "$YGGDRASIL_RESTART_DELAY" -gt 0 ]; then
```

throws:
```
./test: line 128: [: : integer expression expected
```

if YGGDRASIL_RESTART_DELAY isn't defined.  Is it alright that the error makes it through to the shell? It still works as intended.

**Review by ianballou — APPROVED** [review]
Both the job and the manual script are working well!

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
I'm going to wait for an official ACK on https://github.com/theforeman/foreman/pull/9435 before merging this.

**Pull request merged**
