### PR TITLE
Fixes #21562: add patternfly and patternfly-react to katello

### PR DESCRIPTION
**Pull request by waldenraines**
Add patternfly and patternfly-react to katello's package.json so
that we are explicit about what packages katello requires.

http://projects.theforeman.org/issues/21562

### CODE REVIEW

**Comment by waldenraines** [comment]
@ohadlevy we can continue the discussion on this here if you like.  @danseethaler and I are of the opinion that a project should describe what it requires and I'm hopeful that a solution to the version overlapping will be forthcoming.

**Comment by ohadlevy** [comment]
@waldenraines if we merge the foreman PR would you still require it? TBH I can't see a technical way out of both sharing webpack builds and having the dependencies declared multiple times...? does it make sense to create another package.json file ?

**Comment by danseethaler** [comment]
I was thinking these dependencies were included in #6992 but I guess they got missed. I think it definitely makes sense to include dependencies in Katello's own `package.json` for lots of reasons.

- It's clear what packages Katello requires
- We don't have to wait for packages to be added to Foreman before we can use them in Katello
- The semver system in npm is designed to handle this exact thing so we can be loose about the package version we need in Katello and if Foreman already has it we'll just use that.

Of course all of this is pending getting the bundling figured out with webpack so as to not have duplicate packages. My opinion is that we start with separate `package.json` files and figure out how to improve the bundling.

**Comment by akofink** [comment]
This fixes the issue for me during `rake webpack:compile`.

**Pull request merged**
