### PR TITLE
Fixes #31414 - use local tmp for minitest reports

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@jturel pinging you since you added this originally.  By default its saving/loading reports into /tmp/, and its a suspect of some of the recent jenkins issues we've been seeing

**Comment by jlsherrill** [comment]
and even though we're not sure if this will fix the problems we're seeing in jenkins, i think it makes sense to store these within foreman/tmp, and not the system wide /tmp/

**Comment by jlsherrill** [comment]
it also makes me wonder the value of mean time reporter if we can't rely on it to gather averages in CI.   
Couple of options:
*  We potentially could change this to support an ENV variable and store it in some file that is unique to the worker # (passed in via jenkins).  Then we'd at least have some averages to work with within each worker on each slave.  if we want to go that route i'd probably suggest we merge this temporarily in case it does solve the jenkins issues and do a followup to add support for ENV variables
* We stop using the meantime reporter and use a more simple reporter.  I'm not sure how useful the meantimes are over just the run time for that particular test run

**Comment by jlsherrill** [comment]
example of a failure, its very possible it has nothing to do with this, but seems somewhat likely:

```
Katello::TaskStatus::Package group uninstallation::Packages removed#test_0001_has a result description with packages 0.13 = .
Katello::UtilModelSpec::setup_label_from_name#test_0001_should populate label before validation 0.13 = .
Katello::TaskStatus::Package installation#test_0001_has a valid description 0.12 = .
Katello::TaskStatus::Package group installation#test_0001_has a valid description 0.12 = .
Katello::SyncManagementHelper::#collect_arches#test_0001_anonymous 0.13 = .
Katello::SyncManagementHelper::#collect_arches#test_0002_anonymous 0.13 = .
Katello::SyncManagementHelper::#collect_arches#test_0003_should group repositories by architecture 0.13 = .
Katello::ActivationKey::adding host collections#test_0001_should add host collections 0.45 = .
Katello::Provider::Provider in invalid state should not pass validation#test_0003_should be invalid to create two providers with the same name 0.15 = .
Katello::Provider::Provider in invalid state should not pass validation#test_0001_should be invalid without repository type 0.14 = .
Katello::Provider::Provider in invalid state should not pass validation#test_0002_should be invalid without name 0.14 = .
Katello::Provider::sync provider#test_0001_should create sync for all it's products 0.17 = .
Organization::update existing org name and create a new org using the original org name#test_0001_allows user to perform scenario 0.25 = .
Katello::TaskStatus::Package installation::Packages installed#test_0001_has a result description of with packages 0.12 = .
Katello::TaskStatus::Yum error#test_0001_has a valid result_description 0.39 = .
Katello::Product::#environments#test_0001_should contain a unique list of environments 0.20 = .
Katello::Provider::import_product_from_cp creates product with correct attributes#test_0002_anonymous 0.16 = .
Katello::Provider::import_product_from_cp creates product with correct attributes#test_0001_anonymous 0.16 = .

Finished tests in 38.000942s, 4.8683 tests/s, 8.3419 assertions/s.


185 tests, 317 assertions, 0 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:test:/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/test:spec:/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/spec" -I"/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib" "/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/spec/**/*_spec.rb" -v --ci-reporter]
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/testtask.rb:130:in `block (3 levels) in define'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/file_utils.rb:57:in `sh'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/file_utils.rb:104:in `ruby'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/testtask.rb:117:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/file_utils_ext.rb:58:in `verbose'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/testtask.rb:111:in `block in define'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/lib/katello/tasks/test.rake:16:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/lib/katello/tasks/test.rake:186:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/jenkins/workspace/test_develop_pr_katello@2/database/postgresql/ruby/2.5/slave/fast/plugin/lib/katello/tasks/jenkins.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.5.1@test_develop_pr_katello-0/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by ezr-ondrej** [comment]
I'm all in for testing it as it is better to have control over where the file is written, we could use jenkins artifacts to preserve the file throught the runs

**Comment by ezr-ondrej** [comment]
Would be probably good idea to get the current files for future reference though.

**Comment by ezr-ondrej** [comment]
> seems somewhat likely
Especially given it is observed on aws nodes, but not on osuosl nodes.

**Comment by jturel** [comment]
IMO it's probably not worth the future work to make it worker-specific. Since this defeats the mean time reporting across runs, maybe better to use the DefaultReporter which still shows the slowest tests - at the end of the day that's what I find the most useful.

**Comment by jturel** [comment]
Although I think I'm missing the background on how this is being correlated to randomly failing test runs

**Comment by jlsherrill** [comment]
@jturel we're not 100% sure it is the cause, but seems likely.  The tests fail fairly frequently after the spec tests have run, but before the mean times are reported.  The only thing i know that would happen there is reading/writing of this file.  The fact that these files are global with multiple test runs happening at the same time tends to point the finger at this.  

I actually don't see a reporter that reports the slowest time but doesn't do the average tracking and calculation, so i guess the solution as is will give us what we want?   (Average run will just always match current run)

**Comment by jturel** [comment]
> The tests fail fairly frequently after the spec tests have run, but before the mean times are reported

That is an interesting observation. Let's try this out then!

**Review by jturel — APPROVED** [review]
APJ

**Pull request merged**
