### PR TITLE
fixes #13733, #13734 - remove dir timestamp, update task info

### PR DESCRIPTION
**Pull request by thomasmckay**
+ export dir now does not include timestamp
+ content view and repository export tasks are more detailed

### CODE REVIEW

**Comment by ehelms** [comment]
Do these two need to be combined into a single PR? If yes, try `Fixes #, #` instead of double up on the Fixes.

**Comment by beav** [comment]
@thomasmckay if you run this 2x in a row with timestamps, you end up with the following tree:

```
Default_Organization
Default_Organization-repo-pulp-id
listing
```
the listing file does not have the 2nd dir listed, and the 2nd dir seems to have the relative path nested inside of it. I would expect that a 2nd run would just blow away the first run's export.

**Comment by thomasmckay** [comment]
@ehelms - updated commit message, keeping both issues here
@beav - updated w/ cp_r deleting destination

**Comment by beav** [comment]
@thomasmckay i found a very similar bug when testing this, but I think it may not be related to this PR.

If you delete your repo-exports dir (dir itself, not just the contents), and then export, the cp_r will create the repo-exports dir, but it will "lose" the first level of the tree. For example, the first dir inside `repo-exports` will be "Default_Organization" and not "Default_Organization-my_cv-v1.0".

The fix would be ensuring the repo exports dir exists before copying, and creating it if not (vs relying on the cp_r to do it)

**Comment by thomasmckay** [comment]
@beav opened http://projects.theforeman.org/issues/13885 to verify export dir

**Comment by beav** [comment]
@thomasmckay ACK from me

**Comment by ehelms** [comment]
ACK - as we discussed in IRC, try in the future to target 1 change per issue, that keeps diffs small and makes release and debugging easier

**Pull request merged**
