### PR TITLE
Fixes #18050: remove nutupane from task details.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/18050

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by waldenraines** [comment]
> The details box is getting cut off:

Hmm, that looks wrong.  Here is what mine looks like on bastion master and with this branch checked out:

screen shot 2017-01-19 at 10 19 15 am

**Comment by ehelms** [comment]
How wide is yourbrowser? Mine is half the width of my 1920 screen.

**Comment by waldenraines** [comment]
@ehelms updated.

**Pull request merged**
