### PR TITLE
[WIP] Adapt to locking changes made in foreman-tasks

### PR DESCRIPTION
**Pull request by adamruzicka**
This is till in its early stages, just opening it as a heads up

### CODE REVIEW

**Comment by adamruzicka** [comment]
foreman-tasks PR: https://github.com/theforeman/foreman-tasks/pull/379

**Comment by jturel** [comment]
@adamruzicka is this PR still relevant?

**Comment by adamruzicka** [comment]
Yes, definitely

**Comment by adamruzicka** [comment]
Oh, wait. I was looking at my local checkout which was somewhat stale. Turns out this is not needed anymore since the actual implementation was moved to tasks. Closing

**Pull request closed without merging**
