### PR TITLE
Fixes #34926 - Upgrade to Pulpcore 3.18

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
Updates Pulp binding gems to be up to date with Pulpcore 3.18

#### Considerations taken when implementing this change?
Some tests had to be fixed to make the VCR recording easier.

#### What are the testing steps for this pull request?
Try updating the bindings and updating to Pulpcore 3.18. Run some Katello actions if you'd like. Otherwise the tests here should cover all the testing needs.

### CODE REVIEW

**Review by wbclark — COMMENTED** [review]
Hey @ianballou ! Is it possible to separate the fixtures into a separate commit to make review easier, and then squash before merge?

**Comment by ianballou** [comment]
@wbclark it's split now.

**Comment by ianballou** [comment]
@wbclark you shouldn't be hitting issues when creating products, I'm not certain that's even related to this PR frankly.

But anyway, to fully test, you also need to update to Pulpcore 3.18.  The RPMs are having issues with upgrades at the moment so using pip seems to be the best way.

1) Take a snapshot of your dev environment because it's annoying to downgrade Pulp after upgrading

2) Use `sudo pip3.8 install ...` to match versions with what I have:
```
pulp-ansible                    0.13.0   
pulp-certguard                  1.5.2    
pulp-cli                        0.14.0   
pulp-container                  2.10.3   
pulp-deb                        2.18.0   
pulp-file                       1.10.2   
pulp-ostree                     2.0.0a5  
pulp-python                     3.6.0    
pulp-rpm                        3.17.4   
pulpcore                        3.18.4
```

3) Run:
```
sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py'  /usr/local/bin/pulpcore-manager migrate
sudo -u pulp PULP_SETTINGS='/etc/pulp/settings.py' DJANGO_SETTINGS_MODULE='pulpcore.app.settings' /usr/local/bin/pulpcore-manager reset-admin-password --random
```

Then you should be all set on Pulpcore 3.18.

**Comment by wbclark** [comment]
The issue I was seeing was due to having https://github.com/Dynflow/dynflow/commit/bd0b3d71c9403da553e98ed2c75bf1c568315cf9 but not rails 6.1.6. That was solved by checking out latest foreman devel branch and `bundle update`

To get pulpcore 3.18 working I needed to do

```
sudo dnf install epel-release
sudo dnf install cmake ninja-build bzip2-devel openssl-devel rpm-devel file-devel zchunk-devel libmodulemd-devel doxygen python38-devel
```

Then `sudo pip3.8 install --pre -r requirements.txt` succeeds with the requirements.txt I have created based on your instructions.

Now after starting the server with `bundle exec foreman start` I can create a custom product. I have started importing a manifest and will test syncing some small repository when that is complete.

**Comment by wbclark** [comment]
Tasks UI was failing to render, worked around that by applying the patch from https://github.com/theforeman/foreman-tasks/pull/684

I've uploaded a manifest, enabled SCA, and in the process of binding some entitlements. When that is done, I'll enable and sync a small repository.

**Review by wbclark — APPROVED** [review]
Works great for me

**Review by jeremylenz — APPROVED** [review]
ACK based on wbclark

thanks @ianballou !

**Comment by jeremylenz** [comment]
image

**Pull request merged**
