### PR TITLE
Fixes #8689 - scoped search for host collection

### PR DESCRIPTION
**Pull request by steveloranz**

### CODE REVIEW

**Comment by jlsherrill** [comment]
I think the failure is that @fake_search_service is not actually used, so 1 is probably not the correct count.  Let me know if you have any questions about that failure

**Comment by jlsherrill** [comment]
https://github.com/Katello/katello/blob/master/test/controllers/api/v2/host_collections_controller_test.rb#L43-L44   is what i'm referring to.

**Comment by steveloranz** [comment]
So, are we okay to prune it down to lines 46-49 

https://github.com/Katello/katello/blob/master/test/controllers/api/v2/host_collections_controller_test.rb#L46-L49

The only other test I see using fake_search_service is for ActivationKeys.

**Comment by jlsherrill** [comment]
@steveloranz I would just delete those 2 lines i mentioned. 

Most likely it should be returning 3, in fact the fixtures shows 3:  

https://github.com/Katello/katello/blob/master/test/fixtures/models/katello_host_collections.yml

so i'd zap those 2 lines and change: 

https://github.com/Katello/katello/blob/master/test/controllers/api/v2/host_collections_controller_test.rb#L52-L53

to support the fact that there are 3 content hosts.

**Comment by jlsherrill** [comment]
Apologies, this dropped off my radar, Hitting an error when trying to create a host collection, i think that

```
 base.send :include, Ext::IndexedModel
```

in app/katello/models/glue/elastic_search/host_collection.rb  needs to be removed.  that seemed to solve it for me.

**Comment by jlsherrill** [comment]
Otherwise everything looked good :+1:

**Comment by steveloranz** [comment]
Okay, will get this pushed once my connectivity is restored. I've been isolated this morning and saw this come in on my phone.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK, merging, thanks @steveloranz

**Pull request merged**
