### PR TITLE
fixes #11055 - remove enabling red hat repos from katello

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ehelms** [comment]
@stbenjam I am fine with it being taken out, however, I would ask the question of do we owe our users a 1 release deprecation cycle to update their infrastructure for this change?

**Comment by stbenjam** [comment]
I'd say no, we never told anyone to sync the Common repo, they always should've used upstream, and it's broken anyway, katello-agent and such in that repo hasn't worked with Katello since 2.0.

**Comment by ehelms** [comment]
So no one could provision RHEL with this snippet in 2.1 or 2.2?

**Comment by stbenjam** [comment]
I don't see how a community user would've ever known to sync a repo for Satellite to begin with.  But if for some reason they did, and tried to provision, katello-agent would've been installed but not worked.

Otherwise they would always get an error in the kickstart telling them there was no common repo, but it would've worked fine otherwise.

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
