### PR TITLE
Fixes #11348: Remove justified rubygem as a dependency.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Could I get some weigh in on this? I either need to take this route or keep this and add it to the packaging repository to continue forward with SCL work.

**Comment by stbenjam** [comment]
It seems useful, although I don't know if I ever referenced it's output when troubleshooting, normal stack traces work for me.

I have no strong opinion either way, but since this has been opened for 5 days no one's professed their undying love for `justified`, ACK from me

**Comment by jlsherrill** [comment]
Yeah, ACK from me too.  I think this was a lot more useful pre-dynflow days when exceptions would be gobbled up lower in the stack.

**Comment by ehelms** [comment]
We can visit adding this to core so logging is consistent if after this people feel strongly enough about having it. Thanks for the review and thoughts.

**Pull request merged**
