### PR TITLE
Fixes #17640: remove nutupane from puppet modules pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17640

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires Katello/bastion#159 and Katello/bastion#160

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
Things I noticed:

 * on the repositories page, for a puppet repository with 20+ puppet modules, when infinite scroll kicks in, the "Remove Puppet Modules" button has a spinner inside of it
 * the table columns are unaligned in the puppet modules table (see Screenshot 1)
 * the breadcrumbs are creating extra space underneath them at certain browser widths (see SS1)
 * on the repositories puppet module page, (SS1), when you infinite scroll the whole table disappears and then re-appears after loading (contrast to the puppet modules tab on environment page, everything is smooth)
 * tangential: the Library environment highlights on hover (see SS2)
 * the top level puppet module page appears to still be nutupane view
 * CV puppet module page, table is unaligned and search box is tiny (SS3)

screenshot from 2017-01-18 15-11-07

screenshot from 2017-01-18 15-12-57

screenshot from 2017-01-18 16-30-46

**Comment by waldenraines** [comment]
> on the repositories page, for a puppet repository with 20+ puppet modules, when infinite scroll kicks in, the "Remove Puppet Modules" button has a spinner inside of it

Fixed.

> the table columns are unaligned in the puppet modules table (see Screenshot 1)

This is due to changes in `nutupane-table.directive.js` which were removed as part of https://github.com/Katello/bastion/pull/158 (https://github.com/Katello/bastion/pull/158/files#diff-7a2db934779b53fa112766ea042ae95aL49).  I will have to fix the styling on the tables to make this look correct outside of this PR, see http://projects.theforeman.org/issues/18162

> the breadcrumbs are creating extra space underneath them at certain browser widths (see SS1)

This is related to the sub-header block being displayed when there is no sub-header.  This happens on all other details pages as well, it's just not as noticeable.  I will have to fix this outside of this PR.  See http://projects.theforeman.org/issues/18160

> on the repositories puppet module page, (SS1), when you infinite scroll the whole table disappears and then re-appears after loading (contrast to the puppet modules tab on environment page, everything is smooth)

I'd argue that the puppet modules environment page is wrong here because there is no indication of loading whatsoever.  At any rate this is the same behavior as is in master so I'd request that we figure that out outside of this PR.

> tangential: the Library environment highlights on hover (see SS2)

Does that happen in https://github.com/Katello/katello/pull/6540?  If so I will fix it as part of that PR, please check there.

> CV puppet module page, table is unaligned and search box is tiny (SS3)

Fixed.

**Comment by ehelms** [comment]
tangential: the Library environment highlights on hover (see SS2)
 Does that happen in #6540? If so I will fix it as part of that PR, please check there.

Yes it does.

**Pull request merged**
