### PR TITLE
Fixes #33571 - Add a PR template

### PR DESCRIPTION
**Pull request by ianballou**
Sample:

What is the context for this pull request?

This PR adds a PR template file to remind contributors to add context and test steps to PRs.

What are the testing steps for this pull request?

N/A

### CODE REVIEW

**Comment by ianballou** [comment]
I'm going back and forth on if the template lines should be formatted to stand out.  Perhaps bold, or larger font.  Doesn't seem completely necessary though,,,

**Review by rverdile — COMMENTED** [review]
I think it makes sense to add something to make the questions stand out, like you mentioned.

**Comment by jeremylenz** [comment]
+1 to @rverdile above, I'd recommend prepending `### `

Do you think it would be helpful to add "What are the changes introduced in this pull request?" as the first question, since we mostly include that anyway?

**Review by rverdile — COMMENTED** [review]
Would "context" here be like a narrative description of the problem/solution for the PR? Maybe that should be slightly more specific.

**Comment by ianballou** [comment]
I updated the template to ask for an explanation of the changes.  I think that's better than asking for context, which should hopefully be in the redmine and/or BZ anyway.

**Review by jeremylenz — APPROVED** [review]
ACK :+1:

**Review by rverdile — APPROVED** [review]
Looks good to me too :)

**Pull request merged**
