### PR TITLE
[wip] Update npm deps

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[2019-11-19T16:59:29.084Z] PhantomJS 2.1.1 (Linux 0.0.0): Executed 209 of 209 (16 FAILED) (1.935 secs / 1.853 secs)

:sob:

**Comment by waldenraines** [comment]
@jlsherrill what is the goal here?  Are we trying to actually update these libraries or just shut up the alert?  The changes above don't actually do anything except the latter and affect the tests.  The old versions will still be used in the application itself.  I can take this on but I need to know what the goal is.

**Comment by jlsherrill** [comment]
The goal is to update the app, but if this doesn't do that, then I guess I
really don't know how to do that.  I thought the files in the vendoring did
that.  If not, what does?

**Comment by waldenraines** [comment]
> I thought the files in the vendoring did that.

Oops, I missed those changes somehow.  Okay, well I was going to pick this up from you so I'll just run with these changes and work on the tests and regression testing the entire app :grimacing:

**Comment by waldenraines** [comment]
For what it's worth, this PR doesn't work at all.  Every page has JS errors and doesn't work:

```
bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:16873 Uncaught Error: [$injector:unpr] Unknown provider: $$HashMapProvider <- $$HashMap <- $$animateQueue <- $animate <- $compile <- $$animateQueue
https://errors.angularjs.org/1.7.9/$injector/unpr?p0=%24%24HashMapProvider%20%3C-%20%24%24HashMap%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:16873
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21661
    at Object.getService [as get] (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821)
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21666
    at getService (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821)
    at injectionArgs (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846)
    at Object.invoke (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21870)
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21667
    at getService (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821)
    at injectionArgs (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846)
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:16873
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21661
getService @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21666
getService @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821
injectionArgs @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846
invoke @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21870
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21667
getService @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821
injectionArgs @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846
invoke @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21870
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21667
getService @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821
injectionArgs @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846
invoke @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21870
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21667
getService @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821
injectionArgs @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21846
invoke @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21870
doBootstrap @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:18698
bootstrap @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:18718
(anonymous) @ bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:94577
fire @ jquery.js:3187
fireWith @ jquery.js:3317
ready @ jquery.js:3536
completed @ jquery.js:3552
VM168:1 GET https://centos7-katello-devel-stable.example.com/sockjs-node/info?t=1581539034653 net::ERR_NAME_NOT_RESOLVED
(anonymous) @ VM168:1
AbstractXHRObject._start @ sockjs.js:1605
(anonymous) @ sockjs.js:1494
setTimeout (async)
AbstractXHRObject @ sockjs.js:1493
XHRCorsObject @ sockjs.js:2871
InfoAjax @ sockjs.js:356
InfoReceiver._getReceiver @ sockjs.js:539
InfoReceiver.doXhr @ sockjs.js:556
(anonymous) @ sockjs.js:525
setTimeout (async)
InfoReceiver @ sockjs.js:524
SockJS @ sockjs.js:730
initSocket @ socket.js:9
(anonymous) @ client:211
527 @ vendor.js:2858
__webpack_require__ @ bootstrap 540c60ecc92df4f9fdc1:712
fn @ bootstrap 540c60ecc92df4f9fdc1:117
797 @ vendor.js:19433
__webpack_require__ @ bootstrap 540c60ecc92df4f9fdc1:712
(anonymous) @ bootstrap 540c60ecc92df4f9fdc1:761
(anonymous) @ bootstrap 540c60ecc92df4f9fdc1:761
bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:32305 Error: transition superseded
    at $StateProvider.$get (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:69391)
    at Object.invoke (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21878)
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21667
    at Object.getService [as get] (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21821)
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:70150
    at Object.invoke (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21878)
    at bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21677
    at forEach (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:17122)
    at createInjector (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:21677)
    at doBootstrap (bastion-6952b8f2e667e4d944f91fc02674746eb5c817d6b8c2bafcdbeb5dd11004ea4e.js:18697) "Possibly unhandled rejection: {}"
```

**Comment by jlsherrill** [comment]
Oh yeah, in not surprised at all.  I just opened it to see if tests would
pass.  I have tested zero percent of the app yet.

**Comment by waldenraines** [comment]
Can probably close this in favor of https://github.com/Katello/katello/pull/8565

**Pull request closed without merging**
