### PR TITLE
Fixes #25595 - don't log sensitive info

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
heads up: untested, just an idea how to prevent this

**Comment by jlsherrill** [comment]
I think this would only cover the responses from candlepin, it can also occur in the responses from pulp.  I think a catch there would need to go in runcible itself

**Comment by ares** [comment]
@jlsherrill does that mean :+1: or :-1: :-) I haven't seen report about pulp sensitive data yet

**Comment by ares** [comment]
oh, this was the only sensitive info I found in the report, I'm not aware of any secrets logged during pulp communication

**Pull request merged**
