### PR TITLE
Fixes #24868 - fix tooltip for some content settings

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by kgaikwad** [comment]
@jlsherrill, @sean797,

I can see most of the previous changes in this [file](https://github.com/Katello/katello/blob/master/app/helpers/katello/concerns/settings_helper_extensions.rb) added by you. I don't have rights to add reviewers so I would like to request you to review my PR.

Please feel free to add comments if any further changes required.

**Comment by sean797** [comment]
@kgaikwad thanks, this seems like a hugely inefficient way of doing this? Could we make title default to `setting.full_name_with_default` within Foreman instead?

**Comment by kgaikwad** [comment]
Thank you @sean797.

Sorry for delay in response. I have added [PR-6121](https://github.com/theforeman/foreman/pull/6121) in Foreman to handle default title.
It would be great to have your review for that PR. 

If everything works with that change, I can close this PR in favor of [PR-6121](https://github.com/theforeman/foreman/pull/6121) .

**Comment by kgaikwad** [comment]
Any updates on this?

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
need to re-run the tests, hopefully its green.

**Comment by jlsherrill** [comment]
Thanks @kgaikwad !

**Pull request merged**
