### PR TITLE
Fixes #13122 - intercept rhsm serial requests and update last_checkin

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by thomasmckay** [comment]
Wouldn't the last checkin time be updated on any call by the host through rhsm in the candlepin db, which would should then save in our AR for scoped search?

**Comment by jlsherrill** [comment]
@thomasmckay prior to host_unification I believe it was updated in candlepin during checkin (during this api call), but was not imported into elasticsearch unless some other update happened to the system.

**Comment by thomasmckay** [comment]
APJ

**Comment by ehelms** [comment]
Looks like these test failures are related to the PR and not from the previous round of brokenness FYI.

**Pull request merged**
