### PR TITLE
Fixes #36486 - Handle nil in registered content host report

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
Handle nil with & invocations
#### Considerations taken when implementing this change?
Only required for 4.7
#### What are the testing steps for this pull request?
On a 4.7 box, try generating an applicable Host - Registered Content Hosts report and make sure you don't hit the nil reference error.

### CODE REVIEW

**Comment by chris1984** [comment]
@sjha4 making me do another 4.7 release 😿

**Comment by sjha4** [comment]
Hmm..How do we get the tests green here? 😸

**Comment by chris1984** [comment]
Blah I have to pin the foreman-tasks, let me make a pr

**Comment by chris1984** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK, all green now :) ship it

**Pull request merged**
