### PR TITLE
Fixes #24727 - Include Deb packages in incremental updates

### PR DESCRIPTION
**Pull request by mdellweg**
This is only touching the API, since there seem to be no generic GUI for creating incremental content view versions.

### CODE REVIEW

**Comment by johnsonm325** [comment]
Thanks for this PR @mdellweg. Could you please provide a test scenario for this?

- I'm unfamiliar with how to test the Debian/Ubuntu portion of this.
- It would also be helpful if you could provide example commands for which you received the failure and the success.

Thanks, and let me know of any questions here.

**Comment by mdellweg** [comment]
This is more a feature, than a bug. And this api seems to only be used by the katello erratum installation frontend (which is a shame).
Therefore, you can use it via httpie:
`http --json --verify no --auth admin:secret_password POST https://your.server.here/katello/api/v2/content_view_versions/incremental_update 'content_view_version_environments:=[{"content_view_version_id": 2}]' 'description:="Made with HTTPie"' 'add_content:={"deb_ids": [3526]}'`
(with the proper id's in your system of course.)
As prerequisites, you need a deb-type repository, with a couple of packages, a content-view containing it in an old version (id=2 here) and a deb-package, that is only available in the newly synced version (here id=3526; you can utilise the remove package before publishing the 'old' version.).
After performing the incremental update, you should see the new cvv with an increased package count.

**Comment by mdellweg** [comment]
@johnsonm325 Let me try to clarify.
In katello the usage of Library is a little confusing (as far as i understand). There is Library-content (which is the newly synced or added Content of the repositories you find in the product section), and there is the always available content environment "Library" (containing the most recent published versions of all content views).
An incremental cv-version is one that has a minor version number. Say you have a content view with version 5 in Library and 3 in DEV. Then you can create a version 3.1 by adding a certain number of content units and promote it into DEV.
By now, you can add rpm's, rh-errata and puppet modules. This PR is adding debs to that list.
I think, the 'new' packages mus be available in the newly synced Library Content, but it may not hurt to have them in the published Library environment.
And the deb_id is the katello database primary key of the deb package. You can infer that i.e. from the url in the "deb Packages" view.

**Comment by johnsonm325** [comment]
@mdellweg Hey, there is now a conflict with this fix. Can you go in and update the PR?

I made some headway in understanding content views and incremental updates. Once this is done, I should be pretty close to getting this reviewed.

Thanks!

**Comment by mdellweg** [comment]
@johnsonm325 rebased.
Thanks for diving into this.

**Comment by johnsonm325** [comment]
@mdellweg Pinging you in case you didn't see the failing test.

**Comment by mdellweg** [comment]
ping @johnsonm325

**Comment by jturel** [comment]
One note: I see that this issue was triaged to Katello 3.9 for which RC1 is underway. With that in mind I've moved this to Katello 3.10. Let me know if that is problematic at all.

**Pull request merged**
