### PR TITLE
Fixes #19138: minor styling fixes on CV pages. 

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/19138

### CODE REVIEW

**Comment by waldenraines** [comment]
> move ticket #19138 from Bastion to the Katello project

Done!

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/186

**Comment by johnpmitsch** [comment]
@waldenraines Unsure what is happening, but I am seeing the checkbox as an input box :frowning: 
here

**Comment by waldenraines** [comment]
> @waldenraines Unsure what is happening, but I am seeing the checkbox as an input box 😦

Did you include the required bastion changes mentioned above?

**Comment by johnpmitsch** [comment]
@waldenraines yes, I checked that out as well... I'm using a local bastion checkout with the PR you mentioned. I've bundle installed and restarted my server. Unsure what is happening, the html says `type=checkbox` for that input in the debugger

I'm using `google-chrome-stable-54.0.2840.100-1.x86_64`

**Comment by waldenraines** [comment]
@johnpmitsch fixed, I had made a type in the html.

**Pull request merged**
