### PR TITLE
Fixes #31334 - fix export transient failure

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
no idea if this will actually fix it.... lets see

**Comment by jlsherrill** [comment]
i don't think this is on the right track

**Comment by jlsherrill** [comment]
[test katello]

**Review by jeremylenz — APPROVED** [review]
Thanks @jlsherrill, tests pass for me and the mocking seems much safer than redefining the method.  LGTM :+1:

**Pull request merged**
