### PR TITLE
Fixes #30939 - removed deprecated parameters, controllers, and methods

### PR DESCRIPTION
**Pull request by jjeffers**
This deprecations were marked for removal in katello 4.0.

### CODE REVIEW

**Comment by jjeffers** [comment]
[test katelllo]

**Comment by jjeffers** [comment]
[test katelllo]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jturel** [comment]
@jjeffers did you run the deprecation tracker on main branch? I'm asking 'cause I'm surprised that the katello-agent related controller methods and related code are being removed here. They're gonna be sticking around for a few more release due to https://github.com/Katello/katello/pull/9088

**Comment by jjeffers** [comment]
> @jjeffers did you run the deprecation tracker on main branch? I'm asking 'cause I'm surprised that the katello-agent related controller methods and related code are being removed here. They're gonna be sticking around for a few more release due to #9088

Ok - I'll need to re-run that tracker. I think I can undo the katello-agent removal without much trouble. Thanks for the catch!

**Comment by jjeffers** [comment]
Closing this to account for more recent deprecations checking.

**Pull request closed without merging**
