### PR TITLE
[CP] Katello 4.0.2 Cherry picks, version update.

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jjeffers** [comment]
[test katello]

**Comment by jturel** [comment]
Assumption: cherry-picks list from tool_belt is empty therefore the list of picks here is correct

LGTM but needs changelog + version bump

**Comment by jjeffers** [comment]
> Assumption: cherry-picks list from tool_belt is empty therefore the list of picks here is correct
> 
> LGTM but needs changelog + version bump

I was also thinking about squashing the VCR commits into one.

**Comment by jjeffers** [comment]
I believe the updates, CPs, and version changes are now in line and correct. The tests are passing. 

I'd like @jlsherrill to make a quick view of the changes too, especially given the number of conflicts that were manually resolved in the CP process.

Thanks @jturel for your review, note the version bump etc.

If approved I will move ahead with the release checklist.

**Review by jturel — APPROVED** [review]
ACK!

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
