### PR TITLE
Fixes #26361 - RABL template sync plan details

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
Hey @jjeffers looks like there is some rubocop lint (let me know if you can or can't see the results of the Jenkins build associated with this PR) and your commit message length is too long (I know, it's too restrictive - we've talked about relaxing that a bit)

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jturel** [comment]
Nice change and thanks for the tests!

The results look good querying the /katello/api/v2/repositories API with product_id

before your change:

```
"sync_plan": [
  "name",
  "description",
  "sync_date",
  "interval",
  "next_sync"
]
```

after change, product with a sync plan:
```
"sync_plan": {
  "name": "mysyncplan-zoo",
  "description": null,
  "sync_date": "2019-03-19 13:24:00 -0400",
  "interval": "hourly",
  "next_sync": "2019/03/19 14:24:00 -0400"
}
```

after change, no sync plan:
```
"sync_plan": null
```

**Comment by jjeffers** [comment]
[test katello]

**Pull request merged**
