### PR TITLE
Fixes #13918 - change bastion minimum version to 3.2

### PR DESCRIPTION
**Pull request by johnpmitsch**
Bastion has a new [Global Notification feature](https://github.com/Katello/bastion/pull/91) that [Katello uses now](https://github.com/Katello/katello/pull/5732)

### CODE REVIEW

**Comment by ehelms** [comment]
Nitpick: this isn't pinning bastion to 3.2, but rather requiring 3.2 as a minimum

**Comment by johnpmitsch** [comment]
@ehelms updated the title

**Comment by ehelms** [comment]
Needs updating here as well: https://github.com/Katello/katello/blob/master/katello.gemspec#L42

**Comment by johnpmitsch** [comment]
@ehelms updated katello.gemspec as well

**Comment by ehelms** [comment]
ACK

**Pull request merged**
