### PR TITLE
fixes #22501 - search docker tags by digest

### PR DESCRIPTION
**Pull request by thomasmckay**
Removed auto-complete since requires scoped-search change

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by thomasmckay** [comment]
[test katello]

**Comment by jlsherrill** [comment]
@thomasmckay i'm testing this out, can you add a simple scoped search test?  Especially being an external method, i think its important.  Should be simple to just an existing fixture and search for the digest

**Comment by thomasmckay** [comment]
@jlsherrill - Added tests, good call

**Pull request merged**
