### PR TITLE
Fixes #17642: remove nutupane from OSTree Branches.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17642

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/148

**Comment by waldenraines** [comment]
Requires Katello/bastion#159 and Katello/bastion#160

**Comment by waldenraines** [comment]
[test]

**Comment by thomasmckay** [comment]
ack

**Pull request merged**
