### PR TITLE
Fixes #33398 - translate host details tabs

### PR DESCRIPTION
**Pull request by amirfefer**
based on https://github.com/theforeman/foreman/pull/8695

### CODE REVIEW

**Review by jturel — APPROVED** [review]
LGTM - thanks @amirfefer !

**Comment by jturel** [comment]
Waiting on foreman PR merge

**Comment by amirfefer** [comment]
@jturel, the PR in foreman has been merged :)
rebased, could you please have another look?

**Comment by jturel** [comment]
still looks good. will merge once build finishes. thanks Amir!

**Pull request merged**
