### PR TITLE
Fixes #26185 - fix traces action when upgrading kernel

### PR DESCRIPTION
**Pull request by iNecas**
Calling reboot directly doesn't play nicely in SSH neither does in
Ansible.

In SSH scripts, we need to call the power template to let the rex know
we expect the reboot. Although, even after that the traces would not
be updated until katello-tracer-upload is called.

Ansible allows us to reboot and call katello-tracer-upload afterwards,
therefore it should be our default preference for performing the tracing
actions. For this reason, I've added a migration to use the Ansible
template.

After this, I was able to upgrade new kernel, see the traces and after
using the UI to restart, I've eventually saw getting the traces away.

### CODE REVIEW

**Comment by iNecas** [comment]
@jlsherrill mind having a look?

**Comment by sean797** [comment]
Since we have https://github.com/Katello/katello-host-tools/blob/master/extra/katello-agent-send.cron now this could be simpler, just reboot. But this is a little more sure that we will get the data back, I'm fine either way :-)

**Comment by iNecas** [comment]
@sean797 cool,  I was just too inpatient to wait for it to disappear. In that case, I will remove calling the tracer from the ansible and keep the default on SSH

**Comment by iNecas** [comment]
Updated

**Comment by jlsherrill** [comment]
Thanks @iNecas !

**Pull request merged**
