### PR TITLE
Fixes #17144: remove nutupane from GPG Key pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17144

Requires https://github.com/Katello/katello/pull/6312 for the product/repository links to work from the GPG pages.

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/136

**Comment by thomasmckay** [comment]
Issues:
+ creating a new gpg key, shouldn't that bring you to the key itself after it's created rather than back to the full list. (i didn't notice what the case was in the other PRs)
+ product count and repository count column values should be links to those pages (not links currently)
+ image below when no products for gpg key (same for empty repos)
repositories for abc aaa

**Comment by waldenraines** [comment]
> product count and repository count column values should be links to those pages (not links currently)

This won't work correctly until https://github.com/Katello/katello/pull/6312 is merged but everything else is fixed.

**Comment by thomasmckay** [comment]
ack pending typo fix

**Comment by ehelms** [comment]
Looks like this needs to be rebased

Now that there is more vertical space, would you be up for increasing the height of the paste box by default for GPG Keys? e.g. on the New page

On the New page for GPG key, I am not seeing the ability to upload a key.

**Comment by waldenraines** [comment]
> On the New page for GPG key, I am not seeing the ability to upload a key.

Can you please paste a screenshot.  This is what I see:

screen shot 2016-11-18 at 10 39 30 am

**Comment by ehelms** [comment]
@waldenraines If you notice in your own screenshot, the 'Or upload GPG key file' is in a weird place to me. Either it shouldn't be there or it should be above I feel. Maybe it would be cleaner to have two labels 'Paste GPG Key' and 'Upload GPG Key' to make them more distinct?

**Comment by waldenraines** [comment]
> @waldenraines If you notice in your own screenshot, the 'Or upload GPG key file' is in a weird place to me. Either it shouldn't be there or it should be above I feel. Maybe it would be cleaner to have two labels 'Paste GPG Key' and 'Upload GPG Key' to make them more distinct?

I disagree which is why I removed it 😄 

I think having two separate form groups is confusing because it makes it seem like you have to do both instead of one or the other.

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
I still think the 'Or upload gpg key' underneath the upload box is weird. Typically something follows an 'or' not precedes so this feels like it's dangling. Maybe just change the language? I still dislike that the upload is below the paste as its easy to miss it down there.

**Comment by waldenraines** [comment]
> I still think the 'Or upload gpg key' underneath the upload box is weird. Typically something follows an 'or' not precedes so this feels like it's dangling. Maybe just change the language? I still dislike that the upload is below the paste as its easy to miss it down there.

Changed the wording.

**Pull request merged**
