### PR TITLE
[CP] Katello 3.15.3 - cherry picks, changelog update, and version bump.

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
Looks like there are some issues on the react side and the db migrations, but in looks good in general

**Comment by jjeffers** [comment]
> Looks like there are some issues on the react side and the db migrations, but in looks good in general

`ArgumentError: Unknown migration version "6.0"; expected one of "4.2", "5.0", "5.1", "5.2"`
caused by
`[2020-07-02T15:30:06.805Z] /usr/local/rvm/gems/ruby-2.5.1@jenkins-katello-pr-test-4282-1/gems/foreman-tasks-1.1.2/db/migrate/20200611090846_add_task_lock_index_on_resource_type_and_task_id.rb:1:in `<top (required)>'`

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Pull request merged**
