### PR TITLE
Fixes #8920 : typo in apipie validator description

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by ehelms** [comment]
If you go here https://github.com/orgs/Katello/people?utf8=%E2%9C%93&query=cpeters and set your self to public your PRs will get tested automatically.

**Comment by daviddavis** [comment]
I think I like "containting" better.

**Comment by cpeters** [comment]
I set myself to public but I'm still seeing a message that I'm not whitelisted for testing.

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
ACK, thanks @cpeters !

**Pull request merged**
