### PR TITLE
Fixes #16499 - don't update sync plans inside CV publish

### PR DESCRIPTION
**Pull request by iNecas**
Otherwise, HUGE execution plan can be generated

### CODE REVIEW

**Comment by ehelms** [comment]
Do you think it possible to craft a test to ensure no regression for this particular case?

**Comment by beav** [comment]
Is a migration required to clean existing tasks?

**Comment by iNecas** [comment]
The cleanup scrip is really needed just when the tasks are too big to handle: it doesn't have to happen every time, therefore I would suggest to leave it as "use when needed" kind of things.

**Comment by iNecas** [comment]
I've attached the cleanup script to the redmine

**Comment by jlsherrill** [comment]
Tested and seemed to work fine.  Moving to waiting on contributor to address https://github.com/Katello/katello/pull/6305#issuecomment-245907239

**Comment by iNecas** [comment]
Tests added

**Comment by beav** [comment]
ack from me, due to https://github.com/Katello/katello/pull/6305#issuecomment-246778205 plus added tests.

@jlsherrill any additional comment?

**Comment by ehelms** [comment]
ACK - thanks @iNecas

**Pull request merged**
