### PR TITLE
Rails4 controller tests

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by komidore64** [comment]
are we switching to the `1.9.3` symbol hash styling? pretty sure rubocop is going to yell about that.

**Comment by cpeters** [comment]
I can switch it to 1.8 style if that's preferred

**Comment by komidore64** [comment]
let me doublecheck katello's rubocop config

```
loading, please wait...
```

**Comment by johnpmitsch** [comment]
@cpeters  do you think this is a change that could go in master?

**Comment by cpeters** [comment]
@johnpmitsch I *think* that this is not backwards compatible with rails 3.. specifically the "layout" keyword.

http://apidock.com/rails/v3.2.13/ActionController/TemplateAssertions/assert_template
http://apidock.com/rails/v4.1.8/ActionController/TemplateAssertions/assert_template

**Comment by cpeters** [comment]
@johnpmitsch Well maybe it is... inspecting the method source code shows a layout option

**Comment by cpeters** [comment]
closing because reopening on master

**Comment by komidore64** [comment]
ack

**Comment by johnpmitsch** [comment]
ack

**Pull request merged**
