### PR TITLE
Fixes #30255 - Add DSL docs for installed package

### PR DESCRIPTION
**Pull request by ofedoren**
Needs https://github.com/Katello/katello/pull/8801.

### CODE REVIEW

**Comment by ares** [comment]
[test katello]

**Comment by ares** [comment]
it seems rubocop is failing with this
```
[2020-07-17T14:20:30.040Z] /home/jenkins/workspace/katello-pr-test/app/models/katello/installed_package.rb:3:1: C: Layout/EmptyLinesAroundClassBody: Extra empty line detected at class body beginning.
```

**Comment by ofedoren** [comment]
@ares, fixed, thank you.

**Comment by jlsherrill** [comment]
Thanks @ofedoren !

**Pull request merged**
