### PR TITLE
Fixes #29480 -  module stream->rpm mapping

### PR DESCRIPTION
**Pull request by sjha4**

### CODE REVIEW

**Comment by jlsherrill** [comment]
running pulp-rpm (3.2.0), i'm not seeing these associations get populated, is that a new enough version?

**Comment by sjha4** [comment]
3.2 should be good enough although this morning I tested on master branches. Will test on 3.2 once and let you know.

**Comment by sjha4** [comment]
> 3.2 should be good enough although this morning I tested on master branches. Will test on 3.2 once and let you know.

It works on 3.2 for me. Synced https://partha.fedorapeople.org/test-repos/pteradactyl/ and then Katello::ModuleStream.first.rpms and Katello::ModuleStream.first.rpms.first.module_streams

**Comment by sjha4** [comment]
Merging..thanks @jlsherrill !

**Pull request merged**
