### PR TITLE
Fixes #20659 - make proxy labels bold

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@ares is there any context to this change? The bold labels look out of place to me
here

**Comment by ares** [comment]
It needs to be merged/tested with the referenced PR in core. See https://github.com/theforeman/foreman/issues/4760
Ideally they should be merged in sync with also OpenSCAP one.

**Comment by johnpmitsch** [comment]
@ares thanks for clarifying :+1:

**Comment by ares** [comment]
The core PR has been merged. Katello already requires Foreman >= 1.16 so I think this should be merged now (or soon :-)

**Comment by johnpmitsch** [comment]
@ares thanks!

**Pull request merged**
