### PR TITLE
Fixes #16833 - Use smart proxy factory on tests

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by dLobatog** [comment]
@shlomizadok :+1: , the only issue I see is that this is reusing the ticket number from a different project, can you change it please?

**Comment by shlomizadok** [comment]
@dLobatog - Opened a new issue and reworded this commit message.

**Comment by stbenjam** [comment]
Looks good, APJ

**Comment by stbenjam** [comment]
Thanks @shlomizadok, @dLobatog !

**Pull request merged**
