### PR TITLE
Fixes #28322 - upgrade jquery-ui dependency

### PR DESCRIPTION
**Pull request by ezr-ondrej**
After theforeman/foreman#7191 is merged, we will need this to get assets to compile.

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by evgeni** [comment]
[test katello]

**Comment by evgeni** [comment]
the failures look correct to me, as the tests are currently run with jquery-ui-assets 4.x, not 6.x which this change needs?

**Comment by mmoll** [comment]
@ezr-ondrej please rebase :)

**Comment by ezr-ondrej** [comment]
This is unblocked and rebased :)

**Comment by mmoll** [comment]
asset precompile fails

**Comment by ezr-ondrej** [comment]
> asset precompile fails

It's picking up the correct foreman develop commit :thinking:

**Comment by mmoll** [comment]
Hrm, then let's just wait a bit... :stopwatch:

**Comment by ezr-ondrej** [comment]
Got it, the file is actually really not there :thinking:
Let me check why's that.

**Comment by ezr-ondrej** [comment]
Right, this PR was for `jquery-ui-rails` 5, in version 6, they've rearanged the files a bit.
Should be fine now :blush:

**Comment by mmoll** [comment]
:green_heart:

**Pull request merged**
