### PR TITLE
Fixes #20280: Run package profile update and applicability in sequence

### PR DESCRIPTION
**Pull request by ehelms**
I could not see a way to write a test to ensure the sequence was respected.

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
@ehelms tests are green if you can fix the commit message

**Comment by ehelms** [comment]
@jlsherrill I don't honestly know how to fix it without it sounding like gibberish

**Comment by jlsherrill** [comment]
what is gibberish about 'Rn pkg prfl updt and appl in seq ' ?

**Pull request merged**
