### PR TITLE
fixes #24180 - UI for system purpose in activation key 

### PR DESCRIPTION
**Pull request by sseelam2**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
hi @sseelam2 i've sent you an invite to the katello org, once you accept it, you can make your membership public: https://help.github.com/en/articles/publicizing-or-hiding-organization-membership  

this will let the CI kick off automatically

**Comment by sseelam2** [comment]
Thank you @jlsherrill.

**Comment by jturel** [comment]
I was able to apply syspurpose attributes on a key using this UI and saw those same values on my registered content host! 

💯 💯💯💯💯💯💯💯💯💯

**Comment by sseelam2** [comment]
Thank you so much for reviewing @jturel :+1:

**Pull request merged**
