### PR TITLE
Fixes #35026 - As a user, I can edit ACS on the UI

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the testing steps for this pull request?
Screenshot from 2022-07-29 09-21-58

### CODE REVIEW

**Comment by ianballou** [comment]
Also, it would be good to add a blurb telling folks that ACSs affect all repository syncs on any particular smart proxy.

**Comment by sjha4** [comment]
> Some comments about smart proxies and products with respect to organizations:
> 
> We'll need to remove the filtering on smart proxies and products since organization scope doesn't apply here.
> 
> Smart proxy names can still be used, but product names cannot because product names aren't unique across organizations.

I will get the simplified ACS create and view PR in so we can get edits to work for both in this PR.

**Comment by sjha4** [comment]
> Also, it would be good to add a blurb telling folks that ACSs affect all repository syncs on any particular smart proxy.

Ian, can you give this a test now and also where do you think this notice is appropriate? On the create wizard > Smart proxy screen + Review screen and the edit smart proxy modal?

**Comment by ianballou** [comment]
> where do you think this notice is appropriate? On the create wizard > Smart proxy screen + Review screen and the edit smart proxy modal?

That sounds perfect to me!

**Review by ianballou — COMMENTED** [review]
One thing I noticed was how the edit wizard handled errors. The error popped up in the background and the wizard stayed open.  I tried adding a product to an yum ACS that had only a a file repo in it.

**Review by ianballou — COMMENTED** [review]
Everything is looking good to me now! Let me know when the last tests make it in.

**Comment by sjha4** [comment]
@ianballou : Added some more tests for simplified acs edits. Should be ready for re-review.

**Review by ianballou — APPROVED** [review]

**Pull request merged**
