### PR TITLE
Fixes #10044 - UI to remove/add ostree repos to CVs

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
ping @parthaa

**Comment by parthaa** [comment]
Code wise looks good to me.. Going to test soon

**Comment by daviddavis** [comment]
@parthaa rebased with the ostree branch. It should fix the problem you encountered.

**Comment by parthaa** [comment]
@daviddavis thanks

**Comment by parthaa** [comment]
apj

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Pull request merged**
