### PR TITLE
fixes #14120 - activation key: update host collections lists to be an unpaged query

### PR DESCRIPTION
**Pull request by bbuckingham**

### CODE REVIEW

**Comment by ehelms** [comment]
Reading through the issue, I wonder if a better solution would be to switch from a filter to a true search box that way users can use scoped search to trim the list.

**Comment by bbuckingham** [comment]
@ehelms, It would be ideal and allow users to provide more complex queries to narrow the result sets; however, it may also be more involved.  I chose this approach as it appeared to be used elsewhere in the UI.  

Do you know if we have any cases today where a List/Remove|Add supports scoped search queries?
Ideally, if we were to support scoped search on this case, it would be nice to do the same everywhere the List/Remove|Add is used.  This would be facilitated by the fact that they all use common bastion code; however, it may be more than we should do in the short-term.

**Comment by ehelms** [comment]
Sure, but that doesn't mean they are the right approach as they were done
back in the ES days and now we are telling users to expect scoped search. I
appreciate the smaller solution, I just think we should provide the best
experience instead of patching a broken one.

**Comment by bbuckingham** [comment]
@ehelms, In that case, I am surprised that reviewers allowed the current scoped search solution to get accepted if the current solution is a broken one.  I will close this PR since it appears that this solution will not get accepted.

**Comment by thomasmckay** [comment]
There are a number of pages that either a) don't have a search but only a filter on the subset of displayed results, or b) don't page at all and display everything for filter. Would be great to find a agreed upon pattern and apply it to all the pages.

**Comment by thomasmckay** [comment]
Just saw this closed... I would vote for the quick fix now and return to address the larger issue across multiple pages. I say this because if results are paged and only a filter is available there will be some that are not accessible at all.

**Comment by bbuckingham** [comment]
@thomasmckay, I'll re-open in case others share the opinion.

**Comment by ehelms** [comment]
I never said it wouldn't be accepted. I'm merely trying to do due diligence
for users based upon my opinion and reports I've seen

**Comment by bbuckingham** [comment]
Created http://projects.theforeman.org/issues/14138 for a long-term enhancement.

**Comment by jlsherrill** [comment]
ACK from me, but i do agree that the longer term solution would be to properly use details-nutupane with pagination and searching.

**Pull request merged**
