### PR TITLE
Fixes #37471 - Support Zeitwerk loader

### PR DESCRIPTION
**Pull request by ofedoren**
~WIP~

#### What are the changes introduced in this pull request?

This PR should make Katello plugin compatible with Zeitwerk autoloader, which will be enabled in Foreman instead of classic Rails' loader.

#### Considerations taken when implementing this change?

I was trying to change rather less than more. Although, some stuff (like CV acronym) can be introduced, but will require more changes and I'm not sure it'll be quite safe. It's up to maintainers.

#### What are the testing steps for this pull request?

Test with Foreman main PR (included in CI workflow) and hope for the best. Note: at first it'll be red, since some plugins, which are dependencies, should be updated as well. Additionally, after the tests are green I **strongly** recommend to test out basic/advanced content related workflows live.

### CODE REVIEW

**Comment by jeremylenz** [comment]
I had to check out:

* https://github.com/theforeman/foreman_remote_execution/pull/895
* https://github.com/theforeman/foreman-tasks/pull/752
* https://github.com/theforeman/foreman/pull/10131

I tested

- refreshing my manifest
- deleting a subscription from my manifest
- enabling a RH repository
- disabling a RH repository
- publish and promote a CV
- remove a package from a custom repository
- create new blank docker repo

Seems all good so far! I grepped development.log for `zeitwerk` and `"uninitialized constant"` and didn't see anything concerning.

**Comment by jeremylenz** [comment]
also notable: With the foreman-tasks PR checked out, I did not see this error

```
Zeitwerk::NameError: expected file /home/runner/work/katello/katello/vendor/bundle/ruby/2.7.0/gems/foreman-tasks-9.1.1/app/lib/actions/middleware/keep_current_request_id.rb to define constant Actions::Middleware::KeepCurrentRequestId, but didn't
```

which is currently failing in CI.

**Comment by ofedoren** [comment]
Ready to merge after https://github.com/theforeman/foreman/pull/10131 is merged, dropped the commit for testing with Foreman PR, the latest run was green:
Screenshot_20240903_143351

**Comment by ekohl** [comment]
@ofedoren any idea why the tests are failing?

**Comment by jeremylenz** [comment]
The failures in `test_show` and `test_show_uuid` are unrelated to Zeitwerk; we can merge without fixing those.

**Review by jeremylenz — APPROVED** [review]

**Pull request merged**
