### PR TITLE
Fixes #21019 - change content_type for specific actions

### PR DESCRIPTION
**Pull request by jlsherrill**
this commit removes the Params parser wrapper, replacing
it with middleware that modifies the content type for
certain requests to prevent json parsing of the content.

Rails 5 no longer uses the params parser middleware and
instead recommends you inherit from a different base
controller.  However this would require massive refactoring
of Foreman controllers, and seems less than ideal

### CODE REVIEW

**Comment by jlsherrill** [comment]
@ShimShtein curious your thoughts on this.  Its not ideal, however it works across rails versions and does not require refactoring of foreman's base controllers.  I imagine to do this the 'rails 5 way' would require moving most everything out of the foreman application_controller and into a module that could be included if needed

**Comment by ShimShtein** [comment]
@jlsherrill, we have some framework methods that are relying on proper request format, but as long as we know they won't work, it sounds OK to me. 
Foreman's `application_controller` shouldn't do any work related to json encoded parameters (they are request specific - can't be handled by generic methods), so I think it would be small refactoring to use the right methods on controller/request that won't parse the whole json once we deprecate rails 4.
My only request would be putting a deprecation error to remove this hack once we drop rails 4 support.

Also I didn't test this solution, but I think we already have a test method that ensures `JSON.parse` is not called during our requests.

**Comment by ShimShtein** [comment]
@ohadlevy @dLobatog I think you guys were dealing with similar issues (fact importing if I am not mistaken), can it be applicable there?

**Comment by jturel** [comment]
Good fix. I had something similar using the ActionDispatch::Request.parameter_parsers but I think they are basically equivalent.

Tested working against rails 4 and 5 by altering the settings.yaml. This also negates the need for https://github.com/Katello/katello/pull/6875/files and I'll mention that over there when this gets merged.

**Comment by jlsherrill** [comment]
@ShimShtein @ohadlevy @dLobatog any objections to this?  Last chance :)

**Comment by mmoll** [comment]
no objections then, I guess ;)

**Comment by jturel** [comment]
ACK

**Pull request merged**
