### PR TITLE
fixes #32524 - Removing rhsm parser and importer

### PR DESCRIPTION
**Pull request by domitea**
Since these components will be in Core, it's logic to remove them from
this repository.

Complementary PR for https://github.com/theforeman/foreman/pull/8508

### CODE REVIEW

**Comment by domitea** [comment]
PR updated according to requirements to new Foreman version

**Comment by tbrisker** [comment]
[test katello] core PR has been merged, this should turn green now

**Comment by tbrisker** [comment]
[test katello]

**Comment by tbrisker** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Thanks @domitea !

**Pull request merged**
