### PR TITLE
Fixes #15242 - add foreman and hammer packages to about page

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by beav** [comment]
jenkins should be green after rebasing

**Comment by tbrisker** [comment]
@beav thanks, rebased

**Comment by thomasmckay** [comment]
Can we get "satellite" added to the list too? There won't be any harm if this is simply an upstream install as it wouldn't have those packages.

**Comment by ehelms** [comment]
If a downstream distribution has its own packages then it can carry a patch
to add that here not us.

**Comment by thomasmckay** [comment]
The discussion on IRC was a bit more thoughtful than, "no". Thanks for considering.

**Comment by beav** [comment]
@tbrisker it should be OK to remove thumbslug I believe

**Comment by thomasmckay** [comment]
+1 thumbslug no longer relevant

**Comment by beav** [comment]
APJ

**Comment by ehelms** [comment]
Thanks @tbrisker !

**Pull request merged**
