### PR TITLE
Fixes #30235 - Trigger index content when srpm count is updated

### PR DESCRIPTION
**Pull request by hao-yu**
This patch is depending on https://github.com/pulp/pulp_rpm/pull/1758

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by hao-yu** [comment]
@jlsherrill any idea what is causing the react test error? seems not related to my change

**Comment by jlsherrill** [comment]
its unrelated, but a fix was merged upstream, lets see if it worked!

[test katello]

**Comment by hao-yu** [comment]
it works after rebasing the patch

**Comment by jlsherrill** [comment]
thanks @hao-yu !

**Pull request merged**
