### PR TITLE
Fixes #23000 - NoMethodError ssl_client_cert

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by akofink** [comment]
Hmm... isn't this really only valid `if SETTINGS[:katello][:use_pulp]`? Perhaps it should go in the pulp/repo glue?

**Comment by sbernhard** [comment]
Thanks @akofink. I had the same idea previously but @jlsherrill mentioned that the "content_view_puppet_environment.rb" should be removed someday.  He thought it's a better idea to put this code to "content_view_puppet_environment.rb" as the pulp/repo will be restructured then and this change shouldn't be necessary any longer.

**Comment by akofink** [comment]
Does this only apply to 3.5, or does nightly potentially have this same issue?

**Comment by sbernhard** [comment]
Should be the same issue on nightly.

**Comment by jlsherrill** [comment]
I believe this is in 3.6 as well.  Let me test real quick

**Pull request merged**
