### PR TITLE
fixes #9923 - replaced Author column with Description in cv versions

### PR DESCRIPTION
**Pull request by thomasmckay**
The Author column never showed a value (there is no .user in the json). The description seems to me to be a more valuable bit of information. User can be determined from Tasks tab

### CODE REVIEW

**Comment by jlsherrill** [comment]
I'm not sure we should show description in the table column to be honest.  there was a recent discussion and these description fields can go over 1024 characters.  If we do want to show the description, maybe trim the description to ~40 characters or something?

**Comment by thomasmckay** [comment]
@jlsherrill While I agree, only QE would enter 1024 characters. :) Real users are presented with a tiny little text box during publish or will do it via hammer. Since this is the only place the description is shown I'd prefer to show it all.

I will try trimming w/ ellipsis and adding a little "i" info to hover over for full description.

**Comment by ehelms** [comment]
I agree with trimming, that table will get ugly on larger descriptions. If you can provide screenshots of "real" descriptions and how they would look in the table, then I will accept the premise that showing the whole thing is generally ok.

**Comment by thomasmckay** [comment]
What about this algorithm: First line of comment, ellipsed at 40 characters, w/ hover to show full description.

(Note that I will close this PR and change the issue to an RFE for some future time. Although this sounds simple to do, it will likely take more time for me to accomplish than I have available now.)

**Comment by ehelms** [comment]
You could likely accomplish this with title attribute + css to do ellipsis

**Comment by thomasmckay** [comment]
Trying to model after this but the popup hint is without content
http://jsfiddle.net/tDQWN/129/

**Comment by thomasmckay** [comment]
@ehelms @jlsherrill - updated
Kept ellipsis but could not get title to render in a way that was visually useful. Instead I fixed the Details tab so the description is shown as entered originally by the user.

**Comment by thomasmckay** [comment]
[test]

**Comment by cfouant** [comment]
So I've been testing this, and it works for me pretty well, we have the shortened description in the table. However, in the version details view, the description line does not wrap, the line just runs off the page, so that would definitely need to get fixed.

**Comment by jlsherrill** [comment]
ACK from me from a behaviour perspective.

i could see putting 'description' in a more generic place though.  @ehelms may have an opinion.   If he is fine with the css you created, ACK

**Comment by ehelms** [comment]
ACK

**Comment by thomasmckay** [comment]
@cfouant created http://projects.theforeman.org/issues/10171 to address the textarea. Good catch spotting that issue as it is present other places using bst-edit-textarea (CV details, CV version details)

**Pull request merged**
