### PR TITLE
Fixes #25407 - always return HashWithIndifferentAccess

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
test failures look unrelated

**Comment by jturel** [comment]
You hit two of our transient failures :)

[test katello]

**Comment by evgeni** [comment]
@jturel do I get a 🍪 for that? ;)

**Comment by jturel** [comment]
coming right up! :man_cook:

**Comment by jturel** [comment]
Build shows red but everything passed ... merging

**Comment by jturel** [comment]
Actually - does this line from the test run mean anything to you @evgeni ?

```
Sending interrupt signal to process

sh: line 1:  5411 Terminated              JENKINS_SERVER_COOKIE=$jsc '/var/lib/workspace/workspace/katello-pr-test/foreman@tmp/durable-b08c66bb/script.sh' > '/var/lib/workspace/workspace/katello-pr-test/foreman@tmp/durable-b08c66bb/jenkins-log.txt' 2>&1

rake aborted!

SignalException: SIGTERM

```

**Comment by evgeni** [comment]
This *looks* like a timeout or something, but Amazon Prime Video has currently higher prio than Katello :p

**Comment by jturel** [comment]
Hah! Let's try again...

[test katello]

**Pull request merged**
