### PR TITLE
refs #9628 - change prior to prior_id, BZ1189478

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by jlsherrill** [comment]
but isn't the api taking the id?  https://github.com/Katello/katello/blob/master/app/controllers/katello/api/v2/environments_controller.rb#L186

**Comment by jlsherrill** [comment]
the apidoc even says 'Integer' for that field

**Comment by komidore64** [comment]
i attempted to fix this too quickly. @jlsherrill urite

**Comment by jlsherrill** [comment]
I wonder if we should still support 'prior' and just not document it to ensure backwards compatibility?  Or possibly document it as deprecated and ensure hammer excludes it?

**Comment by komidore64** [comment]
are you just wondering, or suggesting? :wink:

**Comment by komidore64** [comment]
that shouldn't be too hard to keep backwards compatibility, i wouldn't think

**Comment by komidore64** [comment]
@jlsherrill updated!

**Comment by komidore64** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by komidore64** [comment]
[test]

**Comment by komidore64** [comment]
will squash and label once test is green

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
