### PR TITLE
Refs #11500 - rename aspects to facets

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Used:
```
find . -name '.git' -prune -o -type f -exec sed -i 's/_aspect/_facet/g' {} +
find . -name '.git' -prune -o -type f -exec sed -i 's/Aspect/Facet/g' {} +

for i in `find  app/ lib/ test/ db/ -type d | grep aspect`; do mv $i `echo $i | sed -e 's/aspect/facet/g'` ; done

for i in `find app/ lib/ test/ db/  -type f | grep aspect`; do mv $i `echo $i | sed -e 's/aspect/facet/g'` ; done
```

**Comment by ehelms** [comment]
Assuming this is a change based on the overall design to move to the facet terminology?

**Comment by jlsherrill** [comment]
Yep, main aspect PR changed to facets https://github.com/theforeman/foreman/pull/2665/ to be more descriptive.

**Comment by ehelms** [comment]
ACK for me if tests are good

**Pull request merged**
