### PR TITLE
Fixes #31734 - New Api end points of sca enable/disable/eligible

### PR DESCRIPTION
**Pull request by parthaa**
Deprecating the existing routes

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
ACK, works good:

```bash
[root@nightly ~]# hammer simple-content-access enable --organization-id 1
Simple Content Access Enabled.
```

Screenshot of task:

https://1drv.ms/u/s!AmcYeL73Lgj6hQGBA9xyvleJyfQk?e=MHJKSr

```bash
[root@nightly ~]# hammer simple-content-access enable --organization-id 1
Simple Content Access Disabled.
```

Screenshot of task:

https://1drv.ms/u/s!AmcYeL73Lgj6hQJtYqoHBfeeEpnh?e=HtIavb

**Comment by chris1984** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Pull request merged**
