### PR TITLE
Fixes #31447 - Validate download policy for export

### PR DESCRIPTION
**Pull request by parthaa**
This commit validates and makes sure all the repos being exported are
immediate and not lazy synced.

### CODE REVIEW

**Comment by parthaa** [comment]
- Add a lazy synced repo to a content view and publish
- Try to export that version

```
$ hammer content-export complete version --id=30
Could not export the content view version:
  Unable to export the Content View Version 'new 1.0'. This version has several repositories with a non-immediate download policy. Please change the download policy to 'immediate', sync and republish version before exporting. 
   ["Product: 'Red Hat Enterprise Linux Advanced Virtualization (for RHEL Server for IBM Power LE)', Repository: 'Advanced Virtualization CodeReady Builder for RHEL 8 Power little endian RPMs'"]
```

**Comment by mccun934** [comment]
My ideal workflow for large exports (think, 1000+ repos in a view, eg: Library)

- Allow the export to proceed but message immediately upon initiating the export:

```
$ hammer content-export  library --organization-id=1
Export started. 
NOTE:  Unable to export all repos in this version, this version has several repositories with a non-immediate download policy. Please change the download policy to 'immediate', sync and republish if you wish these to be included in the export.
   ["Product: 'Red Hat Enterprise Linux Advanced Virtualization (for RHEL Server for IBM Power LE)', Repository: 'Advanced Virtualization CodeReady Builder for RHEL 8 Power little endian RPMs'"]
You can cancel the export task and update these repositories to immediate policy with the following command:
  # hammer repo update .... <SOME BULK UPDATE MECHANISM>
```
Now, this type of output with hammer may not be possible but I still think we should allow library exports to proceed even if a subset of repos are set to lazy. Customers may have thousands of repos and may not be able to force everything to be Immediate. I'd prefer not to have the situation where customers are 100% blocked from exporting Library until all repos are set to Immediate.

**Comment by parthaa** [comment]
```hammer repo update .... <SOME BULK UPDATE MECHANISM>```
doesn't exist today but I think for this task it makes sense to report the repos with the wrong sync policy and make the task ignore em.

**Comment by parthaa** [comment]
@mccun934 updated code to do

```
$ hammer content-export complete library --organization=export-20214 
NOTE:  Unable to export all repositories in the library of this organization. This library environment has several repositories with a non-immediate download policy. Please update the download policy to 'immediate' and sync if you wish these to be included in the export.
Use the following command to update the download policy of these repositories.
hammer repository update --id=<REPOSITORY_ID> --download-policy='immediate'

Id:           112
Name:         Advanced Virtualization CodeReady Builder for RHEL 8 Power little endian RPMs
Product:      Red Hat Enterprise Linux Advanced Virtualization (for RHEL Server for IBM Power LE)
Content Type: yum
Url:          https://cdn.redhat.com/content/dist/layered/rhel8/ppc64le/advanced-virt-crb/os

Id:           103
Name:         Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8
Product:      Red Hat Enterprise Linux for x86_64
Content Type: yum
Url:          https://cdn.redhat.com/content/dist/rhel8/8/x86_64/appstream/os

Id:           102
Name:         Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8
Product:      Red Hat Enterprise Linux for x86_64
Content Type: yum
Url:          https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os

[.....................................................................................................................................................................................................................................] [100%]
Generated /var/lib/pulp/exports/export-20214/Export-Library/13.0/2020-12-04T23-15-54-00-00/metadata.json

$ hammer content-export complete version --id=21
[.....................................................................................................................................................................................................................................] [100%]
Generated /var/lib/pulp/exports/export-20214/view/4.0/2020-12-04T23-24-33-00-00/metadata.json

```

**Comment by mccun934** [comment]
:+1: to the above output, looks great

**Review by chris1984 — APPROVED** [review]
ACK, works:

```bash
[vagrant@dhcp182-208 ~]$ hammer content-export complete library --organization-id=1
NOTE:  Unable to export all repositories in the library of this organization. This library environment has several repositories with a non-immediate download policy. Please update the download policy to 'immediate' and sync if you wish these to be included in the export.
Use the following command to update the download policy of these repositories.
hammer repository update --id=<REPOSITORY_ID> --download-policy='immediate'

Id:           1
Name:         Zoo
Product:      Custom
Content Type: yum
Url:          https://repos.fedorapeople.org/pulp/pulp/demo_repos/zoo/
[.....................................................................................................................................................................................................................................] [100%]
Generated /var/lib/pulp/exports/export-20214/Export-Library/1.0/2020-12-04T23-15-54-00-00/metadata.json
```

**Comment by jturel** [comment]
Code looks good to me! Wording suggestion for brevity+clarity (to me at least) and avoid usage of 'please' (prefer to just tell them what to do):

```
Unable to export this organization's library because it contains repositories without the 'immediate' download policy. Update the download policy and sync affected repositories to include them in the export. 
```

**Review by jturel — APPROVED** [review]
APJ

**Comment by parthaa** [comment]
[test katello]

**Comment by jturel** [comment]
Looks like this broke a couple tests!

**Comment by parthaa** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Pull request merged**
