### PR TITLE
Fixes #25010 - show clear error message with viewer role

### PR DESCRIPTION
**Pull request by amirfefer**
When user with Viewer role accesses Content -> Subscriptions page for organization with manifest, error with unhelpful message appears: "[object Object]".

### CODE REVIEW

**Comment by waldenraines** [comment]
@amirfefer ping

**Comment by johnsonm325** [comment]
@amirfefer Just pinging you again to keep this on your radar. Thanks.

**Comment by waldenraines** [comment]
@amirfefer do you mind updating this PR please?

**Comment by jturel** [comment]
Need a rebase here now :)

**Comment by waldenraines** [comment]
@amirfefer ping

**Comment by waldenraines** [comment]
Closing because the subscriptions page refactoring has made this difficult to rebase.  I will take on this issue and open a new PR.

**Pull request closed without merging**
