### PR TITLE
fixes #22293 - cleans up wrongly published repositories

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
Works great :+1: I'll re-review after tests are passing

**Comment by cfouant** [comment]
[test]

**Comment by cfouant** [comment]
[test default]

**Comment by cfouant** [comment]
[test rails-5]

**Comment by johnpmitsch** [comment]
I'm not sure if I am doing something wrong, but an empty directory still exists when I run the rake task and the bash script.

The steps I took were:

- Create a directory that doesn't exist anywhere in ` /var/lib/pulp/published/yum/master`
` [vagrant@ham yum_distributor]$ sudo mkdir /var/lib/pulp/published/yum/master/1-fake`
- Create a directory that does exist in `yum_distibutor` in `/var/lib/pulp/published/yum/master/`
```
[vagrant@ham yum_distributor]$ ls /var/lib/pulp/published/yum/master/yum_distributor/
1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5  1-hi-v2_0-574b925f-3b09-4ea6-befc-f1044c4ce6f5  ce96cb6f-bb97-414f-b692-ad7a640d637b
1-hi-v1_0-574b925f-3b09-4ea6-befc-f1044c4ce6f5     574b925f-3b09-4ea6-befc-f1044c4ce6f5            e76a0361-28fb-437d-8b27-8481f458d087
```
`sudo mkdir /var/lib/pulp/published/yum/master/1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5`
- Ran `rake katello:clean_published_repo_directories COMMIT=true`
- Ran bash script from output ` sudo bash /tmp/delete_repository_directories.sh`
- Empty published repo is still in /v/l/p/published/yum/master (if I am understanding the issue correctly, 1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5 should be removed)
```
[vagrant@ham yum_distributor]$ ls /var/lib/pulp/published/yum/master/
1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5  yum_distributor
```
Looks like the bash script didn't include the full file path for the 1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5
```
[vagrant@ham foreman{develop}]$ cat /tmp/delete_repository_directories.sh
rm -rf /var/lib/pulp/published/yum/master/1-fake \
 1-hi-Library-574b925f-3b09-4ea6-befc-f1044c4ce6f5
```

**Comment by cfouant** [comment]
@johnpmitsch thank you for that great catch! updating now

**Pull request merged**
