### PR TITLE
Fixes #25332 - Improve readability for content credentials

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Don't think that the rubocop issue is related to this change.

**Comment by beav** [comment]
[test katello]

**Comment by beav** [comment]
@sbernhard the change looks good and tested well for me. thanks!

One suggestion, can you make the field wrap on newline again? Right now it appears to not honor newlines

selection_023

**Comment by sbernhard** [comment]
Thanks @beav for your comment. I tested this again. For me, it looks like, that the line wrap doesn't happen because it's missing in our test data.:

image

A "enter" (on linux \n) does start a new line. In case there is no \n, it doesn't wrap. I guess, this is the same behavior as before. 

Do you expect to do a hard line wrap after 80 digits or so?

**Comment by beav** [comment]
@sbernhard can you try with https://getfedora.org/static/429476B4.txt ? That one should have `\n`, but I didn't see the wraps in the web UI when using it.

**Comment by sbernhard** [comment]
I have tested with https://getfedora.org/static/429476B4.txt ?
- line wraps OK for new content credentials using copy & paste
- line wraps OK for new content credentials using upload
- line wraps OK for in edit content credentials for the one I have copy & paste and the uploaded one
.... using Katello 3.7.1.1

Tried with Katello von git master and in this version its broken (as you say) but EVEN without this PR.
Maybe someone can find out which commit breaks it.

**Comment by sbernhard** [comment]
...test fail because something else but pretty sure not because of this PR.

**Comment by beav** [comment]
@sbernhard thanks for the investigation into the newlines. I am looking into the test failure now.

**Comment by jlsherrill** [comment]
@beav hrmm, i think i may have introduced that error, however it may not be easily reproducible.  I don't mind taking a look

**Comment by beav** [comment]
[test katello] just to see if the test error is transient

**Comment by jlsherrill** [comment]
attempting to resolve here: https://github.com/Katello/katello/pull/7796

**Comment by sbernhard** [comment]
Does someone fix the newline issue?

**Comment by beav** [comment]
@jlsherrill same error, I suppose that is a good thing :ghost: 

@sbernhard I'll create a redmine issue for the newlines. I think this PR is all set after we get jenkins happy

**Comment by jlsherrill** [comment]
[test katello]

**Comment by beav** [comment]
issue for newlines: https://projects.theforeman.org/issues/25357

**Comment by beav** [comment]
@jlsherrill jenkins is still running, but it looks like the error happened again

```
Katello::Service::Repository::DebVcrTest#test_create = 1.37 s = E


Error:
Katello::Service::Repository::DebVcrTest#test_create:
VCR::Errors::UnhandledHTTPRequestError: 

================================================================================
An HTTP request has been made that VCR does not know how to handle:
  POST https://slave01/pulp/api/v2/repositories/

There is currently no cassette in use. There are a few ways
you can configure VCR to handle this request:

  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].
  * If you want VCR to record this request and play it back during future test
    runs, you should wrap your test (or this portion of your test) in a
    `VCR.use_cassette` block [2].
  * If you only want VCR to handle requests made while a cassette is in use,
    configure `allow_http_connections_when_no_cassette = true`. VCR will
    ignore this request since it is made when there is no cassette [3].
  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [4].

[1] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/debug-logging
[2] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/getting-started
[3] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/allow-http-connections-when-no-cassette
[4] https://www.relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/ignore-request
================================================================================


    /var/lib/workspace/workspace/katello-pr-test@2/app/services/katello/pulp/repository.rb:62:in `create'
    /var/lib/workspace/workspace/katello-pr-test@2/test/services/katello/pulp/repository/deb_test.rb:31:in `test_create'
    /var/lib/workspace/workspace/katello-pr-test@2/test/support/vcr.rb:24:in `block in run'
    /var/lib/workspace/workspace/katello-pr-test@2/test/support/vcr.rb:23:in `run'

bin/rails test /var/lib/workspace/workspace/katello-pr-test@2/test/services/katello/pulp/repository/deb_test.rb:29
```

I'm running the full test suite locally to see if it repros. I was not able to repro when running just the one test.

**Comment by beav** [comment]
[test katello]

**Comment by beav** [comment]
thanks @sbernhard !

**Comment by jturel** [comment]
@sbernhard the issue described should be fixed with this PR: https://github.com/Katello/bastion/pull/238

**Pull request merged**
