### PR TITLE
fixes #14374 - fully specify PulpError class

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by thomasmckay** [comment]
Closing as this will be fixed in #5920

**Comment by ehelms** [comment]
This change, while happening to be fixed in #5920, is unrelated to the intent of that PR. I much prefer atomic changes that address specific problems where possible instead of coupling two unrelated issues together, especially when an issue has been raised specifically.

**Comment by johnpmitsch** [comment]
@thomasmckay +1 to @ehelms comment, that change was not related to my PR but rather a workaround and should probably go as a separate change.

**Comment by rauchrob** [comment]
This bug seems to be still present in a freshly installed Katello 2.4.1 (tested on CentOS7). Any suggestions on how to fix this?

**Comment by johnpmitsch** [comment]
@rauchrob you probably have to apply the change manually , I see that that https://github.com/Katello/katello/pull/5933 is going into 3.0, @jlsherrill or @ehelms do you know if this will be fixed in 2.4.2?

**Comment by rauchrob** [comment]
@johnpmitsch I've applied the patch manually. Repo Synchronization still fails every time, yet with another exception:

```
Exception:

Katello::Errors::PulpError: PLP0000: Importer indicated a failed response

Backtrace:

/opt/theforeman/tfm/root/usr/share/gems/gems/katello-2.4.2/app/lib/actions/pulp/abstract_async_task.rb:119:in `block in external_task='
/opt/theforeman/tfm/root/usr/share/gems/gems/katello-2.4.2/app/lib/actions/pulp/abstract_async_task.rb:117:in `each'
/opt/theforeman/tfm/root/usr/share/gems/gems/katello-2.4.2/app/lib/actions/pulp/abstract_async_task.rb:117:in `external_task='
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.10/lib/dynflow/action/polling.rb:98:in `poll_external_task_with_rescue'
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.10/lib/dynflow/action/polling.rb:21:in `run'
/opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-0.8.10/lib/dynflow/action/cancellable.rb:9:in `run'
...
```

**Comment by rauchrob** [comment]
@johnpmitsch I have solved the problem now. It seems I have used some wrong proxy settings in the first place.

**Pull request closed without merging**
