### PR TITLE
fixes #10428 - katello-service and related scripts shouldn't be symlinks

### PR DESCRIPTION
**Pull request by stbenjam**
The katello-service package was getting symlinks instead of the actual contents of the files

### CODE REVIEW

**Comment by stbenjam** [comment]
Scratch builds: http://ci.theforeman.org/job/katello_packaging_build_matrix_rpm_katello/1927/

This fixes the problem - no more symlinks in katello-service

```bash
stbenjam@origin /tmp/service $ rpm2cpio katello-service-2.3.0-1.201505191856git813b563.el6.noarch.rpm| cpio -idmv
./etc/sysconfig/service-wait
./usr/bin/katello-service
./usr/sbin/service-wait
./usr/share/katello/script/service-wait
./usr/share/man/man8/katello-service.8.gz
28 blocks
stbenjam@origin /tmp/service $ tree
.
├── etc
│   └── sysconfig
│       └── service-wait
└── usr
    ├── bin
    │   └── katello-service
    ├── sbin
    │   └── service-wait
    └── share
        ├── katello
        │   └── script
        │       └── service-wait
        └── man
            └── man8
                └── katello-service.8.gz

10 directories, 6 files
```

Except, one problem: it uses scl ruby because of https://github.com/Katello/katello/blob/master/deploy/katello.spec#L49.  Do capsules run SCL ruby too?

**Comment by ehelms** [comment]
They do not.

**Comment by ehelms** [comment]
It only uses SCL if it detects the SCL macro during build. Which, the Katello metapackage never gets built for the SCL so I am confident that block could actually get removed all together. The trick is whether those ruby scripts are 1.8.7 compatible for EL6.

**Comment by stbenjam** [comment]
That seems risky since this fix should go to a 2.2.1 release (and downstream), I just exclude it from the sed now - what do you think of that?

Scratch build: http://ci.theforeman.org/job/katello_packaging_build_matrix_rpm_katello/1930/

**Comment by ehelms** [comment]
Should be easy to check, bust open the rpm and see what's at the top of the
scripts :)

**Comment by stbenjam** [comment]
Yea, my fix works, katello-service doesn't require SCL anymore.  Was just curious if you think that's OK instead of de-SCL-ifying the entire spec.

**Comment by ehelms** [comment]
We don't have to do it in this PR, but the sed change shouldn't be necessary is more my point.

**Comment by stbenjam** [comment]
@ehelms Ok, thanks, do I need to do anything else for this PR?

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
