### PR TITLE
Fixes #15826: Don't ping backends if no systems during migration

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
ACK

**Comment by iNecas** [comment]
What was the motivation behind this change, I'm starting thinking about investing time to real solution for the data migrations, and I'm interested into the things related this topic http://projects.theforeman.org/issues/15866

**Comment by ehelms** [comment]
I'd been playing around with multi-host deployments and hit this issue trying to migrate the database without Pulp or Candlepin being active yet, which on a clean system, shouldn't be a requirement given there shouldn't be any systems.

**Comment by iNecas** [comment]
Thanks for clarification, I'm thinking now about ways how to get the data transformation that involve orchestration to outside of the schema migrations, as we've seen so many issues with that (+ other part, which is avoiding using active record in schema migrations). So far, I'm thinking about introducing another phase for the migrations dedicated for this kind of transformations. I will open an RFC for this sooner rather than later

**Pull request merged**
