### PR TITLE
Fixes #36996 - fix methods called by rebuild_config

### PR DESCRIPTION
**Pull request by m-bucher**
#### What are the changes introduced in this pull request?
Fix 'hammer host rebuild-config' always reporting an error:
```
# hammer host rebuild-config --id 2
Configuration rebuild failed for: Content_Host_Status and Refresh_Content_Host_Status.

### CODE REVIEW

**Comment by m-bucher** [comment]
[test katello]

**Comment by m-bucher** [comment]
[test katello]

**Review by sbernhard — APPROVED** [review]
Works as expected :-)

**Review by jeremylenz — APPROVED** [review]
```
Configuration successfully rebuilt.
```

Thanks @m-bucher !

ACK

**Pull request merged**
