### PR TITLE
Fixes #24635 - return a repository_set ID

### PR DESCRIPTION
**Pull request by sean797**

### CODE REVIEW

**Comment by sean797** [comment]
I was kind of surprised that this didn't break anything..

**Comment by jlsherrill** [comment]
This breaks the current RH repos page.  If you try to enable a repo it says: 'Couldn't find repository set with id '4604'.'   To include this, we probably would need to change the repository_sets_controller how it looks up the product_content.

**Comment by johnsonm325** [comment]
@sean797 As this is related to the 7628 fix, I think when that gets fixed, this will be an easy fix.

**Comment by jturel** [comment]
@sean797 thanks for creating https://projects.theforeman.org/issues/25416

Since v3 API isn't currently on our roadmap I'd like to suggest closing this PR. When we are actively working toward v3 we can revive it!

**Comment by sean797** [comment]
Sure, thanks @johnsonm325 :+1:

**Pull request closed without merging**
