### PR TITLE
Fixes #18116 - properly import all units

### PR DESCRIPTION
**Pull request by jlsherrill**
due to the added paging nature of the import
process, the repo associations were done in
a paged maner.  However each page would then
remove all the previously indexed units. This
change deletes the repo to unit entries, and
then does an additive repo association

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@jlsherrill the idea is we are now skipping [this line](https://github.com/jlsherrill/katello/blob/1a8b8a866d68a6a4699330626880d8ffa942c962/app/models/katello/concerns/pulp_database_unit.rb#L91)?

**Comment by johnpmitsch** [comment]
@jlsherrill any tips on testing this PR?

**Comment by jlsherrill** [comment]
@johnpmitsch we are skipping that line, but also clearing everything here: https://github.com/Katello/katello/pull/6553/files#diff-fba28d05fb7e1a2acbd868623ce31e1eR61

Had some reproducer steps in the bz: 

To reproduce, sync some large repo with ~1000 rpms, then run:
```
foreman-rake katello:upgrades:2.4:import_rpms
```
navigate to the UI and check the package count for that repo.

**Comment by mccun934** [comment]
any performance implications of this change?

**Comment by jlsherrill** [comment]
It shouldn't increase memory consumption.  There maybe some slight additional db access as it will delete all content unit <-> repo  associations and recreate them, but that only happens when doing a FULL import such as with a 'foreman-rake katello:reimport'.  

indexing during repo syncs and CV publishes shouldn't be affected.

**Comment by jlsherrill** [comment]
@johnpmitsch i changed .destroy_all to .delete_all here:  https://github.com/Katello/katello/pull/6553/files#diff-fba28d05fb7e1a2acbd868623ce31e1eR61

mind re-reviewing?  We usually have to use .delete for these because of the sheer number of entries:  Notice the :dependent => :delete_all here: https://github.com/Katello/katello/blob/master/app/models/katello/repository.rb#L44

**Comment by johnpmitsch** [comment]
Review stands! Works fine

**Comment by jlsherrill** [comment]
@johnpmitsch updated a 3rd time to greatly increase the speed with a large number of repos and units.  Mind re-reviewing again? :)

**Comment by johnpmitsch** [comment]
@jlsherrill sure thing

**Comment by johnpmitsch** [comment]
@jlsherrill works4me! approval stands once again

**Pull request merged**
