### PR TITLE
fixes #15185 - allow access to foreman org show api

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by jlsherrill** [comment]
I'm still able to try to DELETE the org:
```
jlsherri~/git/katello (stbenjam-15185)$ curl -X DELETE -u admin:changeme https://robot/api/v2/organizations/1  -k
{
  "error": {"id":1,"errors":{"base":["Default Organization is used by robot.example.com"]},"full_messages":["Default Organization is used by robot.example.com"]}
}
```

Any ideas on that?

**Comment by jlsherrill** [comment]
Also for some reason POST is still working:

```
curl -X POST -u admin:changeme https://robot/api/v2/organizations/  -k  -H 'Content-Type:application/json'
{
  "error": {"id":null,"errors":{"name":["can't be blank"],"title":["can't be blank"],"label":["can't be blank","can't be blank"]},"full_messages":["Name can't be blank","Title can't be blank","Label can't be blank","Label can't be blank"]}
}
```

but PUT is not:

```
 curl -X PUT -u admin:changeme https://robot/api/v2/organizations/1  -k  -H 'Content-Type:application/json'
{"message": "Route forbidden by Katello, check katello/config/routes/overrides"}
```

**Comment by stbenjam** [comment]
Updated, this seems to work.  The `*all` wasn't causing the POST to be caught.


POST

```
[vagrant@katello-dev katello]$ curl -X POST -u admin:changeme https://localhost/api/v2/organizations -k -H 'Content-Type:application/json' -d ""
{"message": "Route overriden by Katello, use the /katello API endpoint instead.  See /apidoc for more details."}
```

PUT

```
[vagrant@katello-dev katello]$ curl -X PUT -u admin:changeme https://localhost/api/v2/organizations/1 -k -H 'Content-Type:application/json' -d ""
{"message": "Route overriden by Katello, use the /katello API endpoint instead.  See /apidoc for more details."}
```

DELETE

```
[vagrant@katello-dev katello]$ curl -X DELETE -u admin:changeme https://localhost/api/v2/organizations/1  -k
{"message": "Route overriden by Katello, use the /katello API endpoint instead.  See /apidoc for more details."}
```

GET

```
[vagrant@katello-dev katello]$ curl -X GET -u admin:changeme https://localhost/api/v2/organizations/1  -k
{"select_all_types":[],"description":null,"created_at":"2016-04-27 13:28:16 UTC","updated_at":"2016-04-27 13:28:16 ...[snip]
```

**Comment by jlsherrill** [comment]
APJ  thanks for making this at least somewhat sensible :)

**Comment by stbenjam** [comment]
Failure was rubocop whitespace.

> APJ thanks for making this at least somewhat sensible :)

Ha, thanks :-) Not sure it's entirely sensible but at least works as intended on Rails 4 now.

**Pull request merged**
