### PR TITLE
[CP] Fixes #36609 - Fix linting errors from react/jsx-curly-brace-presence…

### PR DESCRIPTION
**Pull request by wbclark**
… (#10659)

(cherry picked from commit ecfb84a04a724fd5c906961a0a1dbd6247497065)

### CODE REVIEW

**Review by sjha4 — APPROVED** [review]
APJ 👍🏼

**Comment by sjha4** [comment]
[test katello]

**Comment by wbclark** [comment]
Opened https://github.com/theforeman/foreman/pull/9784 against Foreman 3.6 to resolve the test failures

**Comment by wbclark** [comment]
[test katello]

**Pull request merged**
