### PR TITLE
fixes #12123 - content_unit_class should be constantized

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I am getting http://www.clipular.com/c/5292171891572736.png?k=40WUMt3Q96o59Y2ugEQIDU94Xec when I try to upload an rpm to a repository, at first glance it seems like some leftover elastic search stuff here http://git.io/vC4f6 is interfering, and maybe can be removed?

**Comment by stbenjam** [comment]
Oh, I guess, thought it was simple enough  to fix to avoid the pipeline breakage.

Who's been removing the Elastic Search stuff? Maybe they should take over this issue because I'm not familiar with the details.

**Comment by johnpmitsch** [comment]
@stbenjam me! :) I can take a look at it. @jlsherrill  do we still need rpm elastic search for any reason? In particular, this file? http://git.io/vC4f6

**Comment by jlsherrill** [comment]
@johnpmitsch yes, that file is needed, although it should be moved out of the ./elasticsearch directory under actions to just ./katello . 

ACK to this change, i tested uploads i thought????

**Comment by johnpmitsch** [comment]
@jlsherrill something could be up with my dev box, you were able to upload an rpm to a repository?

**Comment by rplevka** [comment]
@johnpmitsch - hi, just wanted to point out, I'm only getting error with `yum` repos. Uploading files to `puppet` and `docker` repos works fine.

**Comment by jlsherrill** [comment]
Oh actually it was the backend objects change that actually broke this, and i probably did not test uploads after that.    @johnpmitsch current I cannot upload rpms locally because it is broken :)

@stbenjam what you have is close, needs to be:

```
diff --git a/app/models/katello/concerns/pulp_database_unit.rb b/app/models/katello/concerns/pulp_database_unit.rb
index af8d60b..19749a9 100644
--- a/app/models/katello/concerns/pulp_database_unit.rb
+++ b/app/models/katello/concerns/pulp_database_unit.rb
@@ -13,7 +13,7 @@ module Katello
 
     module ClassMethods
       def content_unit_class
-        "::Pulp::#{self.name.demodulize}".constantize
+        "::Katello::Pulp::#{self.name.demodulize}".constantize
       end
 
       def repository_association
diff --git a/app/services/katello/pulp/pulp_content_unit.rb b/app/services/katello/pulp/pulp_content_unit.rb
index beb1605..c268377 100644
--- a/app/services/katello/pulp/pulp_content_unit.rb
+++ b/app/services/katello/pulp/pulp_content_unit.rb
@@ -42,7 +42,7 @@ module Katello
       end
 
       def self.fetch(offset, page_size, uuids = nil)
-        fields = ::PULP_INDEXED_FIELDS if self.constants.include?(:PULP_INDEXED_FIELDS)
+        fields = self.const_get(:PULP_INDEXED_FIELDS) if self.constants.include?(:PULP_INDEXED_FIELDS)
         criteria = {:limit => page_size, :skip => offset}
         criteria[:fields] = fields if fields
         criteria[:filters] = {'_id' => {'$in' => uuids}} if uuids
```

I'd be happy to open a PR or you can update yours (will be a few hours before i can get the Pr open).  Up to you!

**Comment by stbenjam** [comment]
Oh thanks @jlsherrill! Updated

**Comment by johnpmitsch** [comment]
@stbenjam works for me! ACK from my end

**Comment by stbenjam** [comment]
Thanks all

**Pull request merged**
