### PR TITLE
Capsule granular repair

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
Add API/Actions to support repairing repositories, content view. environments on a capsule.
#### Considerations taken when implementing this change?
Draft PR. Waiting for capsule repair API to get merged(1st commit on this PR)

### CODE REVIEW

**Review by chris1984 — CHANGES_REQUESTED** [review]
A few issues that came up:

So far it looks fine, I did notice a few things though:

if I pass in a content view id that is not synced on the capsule the task still works


```bash
hammer capsule content verify-checksum --id 2 --organization-id 1 --content-view-id 3
[...............................................................................................................] [100%]

```

https://stream.satellite.lab.eng.rdu2.redhat.com/content_views/4/ is the only content view synced on the capsule

If I pass in a fake content view id, the validation works as expected
```bash
$ hammer capsule content verify-checksum --id 2 --organization-id 1 --content-view-id 200
Could not verify capsule content checksum:
  Couldn't find Katello::ContentView with 'id'=200
```
Also seeing this
```bash
$ hammer capsule content verify-checksum --repository-id 6 --id 2
[........................................................                                                        ] [50%]
Error: Missing the required parameter 'rpm_rpm_repository_version_href' when calling RepositoriesRpmVersionsApi.repair
```
If I pass in a random repo #, mine is 16

That goes to a paused task then :disappointed:
```bash
$ hammer capsule content verify-checksum --repository-id 16 --id 2
Could not verify capsule content checksum:
  Lifecycle environment 'Library' is not attached to this capsule.
```

**Comment by sjha4** [comment]
Added some validations to fail early if invalid cv/repos are passed..

**Comment by sjha4** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK code looks fine and the issues I put into the PR with the last round of testing have been addressed:

```bash
$ hammer capsule content verify-checksum --id 2 --organization-id 1 --content-view-id 3
Could not verify capsule content checksum:
Content view 'RHEL-8' is not attached to this capsule.
```

```bash
$ hammer capsule content verify-checksum --repository-id 6 --id 2
[........................................................                                                        ] [50%]
Error: Could not lookup a version_href for repo 6
```

```bash
$ hammer capsule content verify-checksum --repository-id 16 --id 2
Could not verify capsule content checksum:
  Lifecycle environment 'Library' is not attached to this capsule.
```

No more stuck tasks either after getting the `href` error.

**Comment by sjha4** [comment]
Thanks @chris1984 ! Merging..

**Comment by maximiliankolb** [comment]
@sjha4 Is there a way to "break" the meta data on Smart Proxy servers to test this command?

My current scenario:
Foreman 3.11 + Smart Proxy server; a single small CV in "prod" env synchronized to Smart Proxy server; running `hammer proxy content verify-checksum --id 2` only takes about 3 seconds and I assume it does not actually have to repair anything.

**Comment by sjha4** [comment]
@maximiliankolb : You could get something on the filesystem using the artifact endpoint and then at the /var/lib/pulp file location, either corrupt the file or rm the file to give the repair task something to work on..

**Pull request merged**
