### PR TITLE
Fixes #12552 - Update url helper spec to be 1.9.x and 2.0+ compatible

### PR DESCRIPTION
**Pull request by cpeters**
Adapting the test to support the URI class diferences between versions
- 1.9.x URI class is case-sensitive
- 2.0+ URI class is not case-sensitive

### CODE REVIEW

**Comment by johnpmitsch** [comment]
works on both 1.9 and 2.1 locally, ACK

**Comment by johnpmitsch** [comment]
works on both 1.9 and 2.1 locally, APJ

**Comment by dLobatog** [comment]
@cpeters How about making the helper support both? Otherwise Ruby 2.0+ will not validate urls with the wrong case.

**Comment by cpeters** [comment]
@dLobatog @daviddavis @johnpmitsch 

Updated. Thanks for the suggestion.

**Comment by ehelms** [comment]
ACK

**Comment by johnpmitsch** [comment]
thanks @cpeters!

**Pull request merged**
