### PR TITLE
Fixes #13045: Shorten index names to allow sqlite3 migrations

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This is currently preventing RPM packaging -- http://koji.katello.org/koji/getfile?taskID=402512&name=build.log

**Comment by daviddavis** [comment]
ACK

**Comment by jlsherrill** [comment]
I know index names aren't the most important thing in the world, but would we not want a migration?

**Comment by ehelms** [comment]
I assume you mean in addition to the current change given migrations on a clean sqlite database will fail without the name being initially set to this?

**Comment by jlsherrill** [comment]
Exactly

**Comment by ehelms** [comment]
Updated with separate migrations for each index rename.

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
You need rescues in the new migrations in case the old index doesn't exist.

**Comment by jlsherrill** [comment]
@ehelms want to start a manual CI build?

**Comment by ehelms** [comment]
Switched to use `index_exists?` instead of relying on exceptions.

**Comment by jlsherrill** [comment]
ACK from me, @daviddavis ?

**Comment by daviddavis** [comment]
APJ

**Comment by ehelms** [comment]
[test]

**Pull request merged**
