### PR TITLE
Refs #10970 - Fix controller tests that only fail on full suite run

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by daviddavis** [comment]
Is this related to the following Redmine? If so, care to attach it to this one instead of 10970?

http://projects.theforeman.org/issues/12331

**Comment by cpeters** [comment]
@daviddavis this is unrelated to that redmine issue

**Comment by daviddavis** [comment]
@cpeters what error are you seeing then?

**Comment by cpeters** [comment]
@daviddavis 

Numerous failures related to the test not being able to read the controller actions. Example below.

Katello::Api::V2::ContentUploadsControllerTest#test_create_upload_request_protected:
AbstractController::ActionNotFound: The action 'create' could not be found for Katello::Api::V2::ContentUploadsController
    /home/vagrant/katello/test/controllers/api/v2/content_uploads_controller_test.rb:40:in `test_create_upload_request_protected'

**Comment by daviddavis** [comment]
Ah ok. That's really weird. 

ACK

**Pull request merged**
