### PR TITLE
Fixes #33544 - update boostrap-select for RH repos error

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@evgeni  @Odilhao  ping for awareness

**Review by sjha4 — APPROVED** [review]
Test ACK since I saw this fix the issue on call... 😄

**Review by evgeni — APPROVED** [review]
packaging-only ack, this is a trivial bump, and I am sure you know how to do this in `foreman-packaging`? ;-)

**Comment by jlsherrill** [comment]
i've never packaged a javascript file, but i can give it a shot ;)

**Comment by evgeni** [comment]
> i've never packaged a javascript file, but i can give it a shot ;)

bump_rpm.sh is all you need 🎶

**Comment by jlsherrill** [comment]
https://github.com/theforeman/foreman-packaging/pull/7124

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
