### PR TITLE
fixes #11920 - add a name field to elasticsearch for default searching

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by ehelms** [comment]
Seems like we should just address http://projects.theforeman.org/issues/11753 instead of updating this code that will just be removed.

**Comment by thomasmckay** [comment]
This change is schedule for a downstream update. I'd prefer to do that via cherry-pick and keep the code related that way.

**Comment by jlsherrill** [comment]
Why would you use 'name' versus 'errata_id' ?

**Comment by ehelms** [comment]
Not sure I agree with the argument for this should go in only to be removed prior to our next release.

**Comment by ehelms** [comment]
The scoped search conversion PR (https://github.com/Katello/katello/pull/5541) would obsolete this change -- @thomasmckay would you be OK with closing this now that #5541 is open?

**Comment by thomasmckay** [comment]
Closing in favor of #5541 
Thanks @ehelms !

**Comment by jlsherrill** [comment]
@ehelms are you sure #5541 actually fixes this issue?

**Comment by ehelms** [comment]
@jlsherrill oh, ha, good call, don't know why I thought this was a system change, don't think I realized the rules even had searching capabilities (or names).

**Pull request closed without merging**
