### PR TITLE
Fixes 25283 - Add mirror_on_sync option to deb repos

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Change looks good at first glance, note that this will conflict with https://github.com/Katello/katello/pull/7746  quite a bit.    Does this need to wait for a specific pulp_deb release?

**Comment by mdellweg** [comment]
Thanks for the Heads up.
From the pulp_deb repo-tree, this seems to need 1.8.0 to function. No changes in runcible needed though. And i am quite sure it won't break anything before 1.8.0, just not function.

**Comment by mdellweg** [comment]
@jlsherrill Again, i do not see any reason caused by this change for the failing test. Do you?

**Comment by beav** [comment]
[test katello]

**Comment by beav** [comment]
[test katello]

**Comment by beav** [comment]
[test katello]

this PR needs a rebase as well

**Comment by sbernhard** [comment]
[test katello]

**Comment by mdellweg** [comment]
@jlsherrill rebased on #7746 and tests pass.

**Comment by beav** [comment]
I was able to create a repo successfully and it inherited the default value for the field. I then toggled the checkbox and confirmed it landed in Pulp (look for `remove_missing` below):

unchecked:
```
> db.repo_importers.find({repo_id: '57c9a49e-a6b4-4f52-ae21-6d21c893edbf'})
{ "_id" : ObjectId("5bf2d2adf4b684705b386118"),
  "repo_id" : "57c9a49e-a6b4-4f52-ae21-6d21c893edbf",
  "importer_type_id" : "deb_importer",
  "config" : {
    "feed" : "http://deb.theforeman.org/",
    "remove_missing" : false,
    "releases" : "xenial/stable/binary-amd64",
    "ssl_validation" : true,
    "architectures" : "binary-amd64",
    "components" : "stable"
   },
  "last_updated" : ISODate("2018-11-19T16:05:46.757Z"),
  "last_override_config" : {
    "num_threads" : 4,
    "validate" : true
  },
  "_ns" : "repo_importers",
  "last_sync" : "2018-11-19T16:05:55Z" }
```
checked:
```
> db.repo_importers.find({repo_id: '57c9a49e-a6b4-4f52-ae21-6d21c893edbf'})

{ "_id" : ObjectId("5bf2d2adf4b684705b386118"),
  "repo_id" : "57c9a49e-a6b4-4f52-ae21-6d21c893edbf",
  "importer_type_id" : "deb_importer",
  "config" : { "feed" : "http://deb.theforeman.org/",
    "remove_missing" : true,
    "releases" : "xenial/stable/binary-amd64",
    "ssl_validation" : true,
    "architectures" : "binary-amd64",
    "components" : "stable"
  },
  "last_updated" : ISODate("2018-11-19T16:49:08.200Z"),
  "last_override_config" :{
    "num_threads" : 4,
    "validate" : true
  },
  "_ns" : "repo_importers",
  "last_sync" : "2018-11-19T16:05:55Z"
}
```

**Comment by beav** [comment]
IMO this change is small enough to probably not need a test. ACK thanks @mdellweg ! also thanks @sbernhard and @jlsherrill for reviews

**Pull request merged**
