### PR TITLE
Fixes #27699 - update @theforeman/vendor to ^1.4.0

### PR DESCRIPTION
**Pull request by sharvit**
This should fix the broken nightly

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like test failure may be related. We also need the matching change in packaging.

**Comment by sharvit** [comment]
packaging update:
https://github.com/theforeman/foreman-packaging/pull/4035

**Comment by sharvit** [comment]
Jenkins failing because it is running `eslint` on node-6.

Therefore, this PR bring back Travis and run the `eslint` on Travis using node 6-12.
Created a PR in foreman-infra to remove eslint: https://github.com/theforeman/foreman-infra/pull/1116

**Comment by tbrisker** [comment]
i've re-enabled travis on the katello repo, closing and reopening to trigger build for this pr.

**Comment by sharvit** [comment]
Thanks @tbrisker,

tbw, I let `travis` to run the test as well, just because it will still finish before `Jenkins` so "why not?".

**Comment by tbrisker** [comment]
looks like this isn't a matter of node version this time :cry:

**Comment by sharvit** [comment]
Seems like updating `eslint` solves that issue but i'm still trying to figure out what went wrong.

**Comment by ekohl** [comment]
Looks like node 12 still fails on Travis.

**Comment by sharvit** [comment]
The issue is because version 0.2.0 of the vendor added `react-loading-skeleton` which uses an unmatched version of `@babel/types` to what the `babel-eslint` uses.
npm :-1: 

Anyway, I updating `babel-eslint` fixes the issue because it uses a newer version of `@babel/types`.
- Running `eslint` on node-6 won't work anymore.

**Pull request merged**
