### PR TITLE
Fixes #13955 - Removing ostree branch management

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by parthaa** [comment]
can ya take this one out too https://github.com/Katello/katello/blob/master/app/models/katello/candlepin/content.rb#L83 ...

and this fella too
https://github.com/Katello/katello/blob/master/app/models/katello/glue/pulp/repo.rb#L498

**Comment by daviddavis** [comment]
Done.

**Comment by daviddavis** [comment]
[test]

**Comment by parthaa** [comment]
apj

**Comment by parthaa** [comment]
ack

**Pull request merged**
