### PR TITLE
Fixes #25774 - Handle uniq errors when importing mod stream

### PR DESCRIPTION
**Pull request by johnpmitsch**
I believe the associated bug is a race condition because I can't
reproduce it syncing the same repos. If this is a race condition, the
active_record_retry method will help prevent errors by rescuing the
unique errors raised and retrying the transaction.

I also updated the tests to create multiple records for profiles
and artifacts. It also looks like the tests weren't working as
intended previously, they should be fixed now.

### CODE REVIEW

**Comment by johnpmitsch** [comment]
To test:
Sync at leaste both of these repos at the same time
- Red Hat Enterprise Linux 8 for x86_64 - AppStream Beta Kickstart
- Red Hat Enterprise Linux 8 for x86_64 - AppStream Beta RPMs
  
Sync should complete successfully

**Comment by beav** [comment]
I didn't test this but code looks good

**Comment by beav** [comment]
@johnpmitsch how did you determine where to wrap with `Katello::Util::Support.active_record_retry`? :gift: Did the bug have stacks from all 3 areas?

**Comment by johnpmitsch** [comment]
> @johnpmitsch how did you determine where to wrap with `Katello::Util::Support.active_record_retry`?  Did the bug have stacks from all 3 areas?

It only had the stack trace for the artifacts, but since the other parts were such similar transactions, I wrapped those too

**Comment by beav** [comment]
> > @johnpmitsch how did you determine where to wrap with `Katello::Util::Support.active_record_retry`?  Did the bug have stacks from all 3 areas?
> 
> It only had the stack trace for the artifacts, but since the other parts were such similar transactions, I wrapped those too

good call

I'm pretty sure I won't hit the race condition when testing if you didn't hit it yet, code looks good, and I'm assuming you no-break tested this and it passes unit tests.

ack!

**Pull request merged**
