### PR TITLE
Fixes #22769 - do not allow file:// repos with lazy sync types

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by akofink** [comment]
should be fixed by https://github.com/theforeman/foreman-infra/pull/515

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
