### PR TITLE
Fixes #32888 - correct missing errata from link repositories

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Steps to Reproduce:
1.  Create and sync some repo with errata
2.  Publish the repo in a content view
3.  run 'foreman-maintain content prepare'
4.  Note in 'foreman-maintain content migration-stats' that all errata are migrated

Next do one of the following:

5.  promote the CV to a new lifecycle environment
OR
5.  publish the CV in a composite content view

6.  Re-run the migration 'foreman-maintain content prepare'
7.  Re-run  'foreman-maintain content migration-stats'

Note that all errata are not migrated

**Comment by jjeffers** [comment]
After applying the patch to a 3.18 production system and recreating the steps as above:
```
2021-06-30T14:39:05 [I|app|] CONTENT_MIGRATION - Generating Migration plan duration=41.04
2021-06-30T14:39:05 [E|app|] Migration Plan: {"plugins":[{"type":"rpm","repositories":[{"name":"cv1-zoo","repository_versions":[{"pulp2_repository_id":"1-cv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734","pulp2_distributor_repository_ids":["1-ccv1-Library-d4ba7181-5527-45ff-b11b-15b50624e734","1-ccv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734","1-cv1-Library-d4ba7181-5527-45ff-b11b-15b50624e734","1-cv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734"]}]},{"name":"d4ba7181-5527-45ff-b11b-15b50624e734","repository_versions":[{"pulp2_repository_id":"d4ba7181-5527-45ff-b11b-15b50624e734","pulp2_distributor_repository_ids":["d4ba7181-5527-45ff-b11b-15b50624e734"]}],"pulp2_importer_repository_id":"d4ba7181-5527-45ff-b11b-15b50624e734"}]}]}
2021-06-30T14:39:05 [I|app|] Migration Plan: {"plugins"=>[{"type"=>"rpm", "repositories"=>[{"name"=>"cv1-zoo", "repository_versions"=>[{"pulp2_repository_id"=>"1-cv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734", "pulp2_distributor_repository_ids"=>["1-ccv1-Library-d4ba7181-5527-45ff-b11b-15b50624e734", "1-ccv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734", "1-cv1-Library-d4ba7181-5527-45ff-b11b-15b50624e734", "1-cv1-v1_0-d4ba7181-5527-45ff-b11b-15b50624e734"]}]}, {"name"=>"d4ba7181-5527-45ff-b11b-15b50624e734", "repository_versions"=>[{"pulp2_repository_id"=>"d4ba7181-5527-45ff-b11b-15b50624e734", "pulp2_distributor_repository_ids"=>["d4ba7181-5527-45ff-b11b-15b50624e734"]}], "pulp2_importer_repository_id"=>"d4ba7181-5527-45ff-b11b-15b50624e734"}]}]}
2021-06-30T14:39:07 [I|app|] CONTENT_MIGRATION - Importing Repository type=yum duration=499.45
2021-06-30T14:39:07 [I|app|] CONTENT_MIGRATION - Importing Content type=rpm duration=2.47
2021-06-30T14:39:07 [I|app|] CONTENT_MIGRATION - Importing Content type=modulemd duration=2.0
2021-06-30T14:39:08 [E|bac|] undefined method `target' for #<Katello::Repository:0x000000001524da50> (NoMethodError)
 | /opt/theforeman/tfm/root/usr/share/gems/gems/activemodel-6.0.3.4/lib/active_model/attribute_methods.rb:432:in `method_missing'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/audited-4.9.0/lib/audited/auditor.rb:99:in `method_missing'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:320:in `block in correct_missing_errata'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:317:in `each'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:317:in `correct_missing_errata'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:313:in `import_errata'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:341:in `import_content_type'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:116:in `block (4 levels) in import_pulp3_content'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/katello/logging.rb:6:in `time'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:115:in `block (3 levels) in import_pulp3_content'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:114:in `each'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:114:in `block (2 levels) in import_pulp3_content'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:109:in `each'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:109:in `block in import_pulp3_content'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/katello/logging.rb:6:in `time'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/services/katello/pulp3/migration.rb:108:in `import_pulp3_content'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/pulp3/import_migration.rb:11:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:571:in `block (3 levels) in execute_run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:32:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/middleware/remote_action.rb:16:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/middleware/remote_action.rb:40:in `block in as_remote_user'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/models/katello/concerns/user_extensions.rb:21:in `cp_config'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/middleware/remote_action.rb:27:in `as_cp_user'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/middleware/remote_action.rb:39:in `as_remote_user'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.18.3.1/app/lib/actions/middleware/remote_action.rb:16:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/rails_executor_wrap.rb:14:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/rails_executor_wrap.rb:13:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action/progress.rb:31:in `with_progress_calculation'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action/progress.rb:17:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_request_id.rb:15:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_request_id.rb:49:in `restore_current_request_id'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_request_id.rb:15:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_timezone.rb:15:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_timezone.rb:44:in `restore_curent_timezone'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_timezone.rb:15:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_user.rb:15:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_user.rb:44:in `restore_curent_user'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_user.rb:15:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `block in run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_taxonomies.rb:45:in `restore_current_taxonomies'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.6/app/lib/actions/middleware/keep_current_taxonomies.rb:15:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:27:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:19:in `pass'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware.rb:32:in `run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/stack.rb:23:in `call'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/middleware/world.rb:31:in `execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:570:in `block (2 levels) in execute_run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:569:in `catch'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:569:in `block in execute_run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:472:in `block in with_error_handling'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:472:in `catch'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:472:in `with_error_handling'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:564:in `execute_run'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/action.rb:285:in `execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:18:in `block (2 levels) in execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/execution_plan/steps/abstract.rb:167:in `with_meta_calculation'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:17:in `block in execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:32:in `open_action'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:16:in `execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/director.rb:68:in `execute'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:11:in `block (2 levels) in perform'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors.rb:18:in `run_user_code'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:9:in `block in perform'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:25:in `with_telemetry'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors/sidekiq/worker_jobs.rb:8:in `perform'
 | /opt/theforeman/tfm/root/usr/share/gems/gems/dynflow-1.4.8/lib/dynflow/executors/sidekiq/serialization.rb:27:in `perform'
 | [ sidekiq ]
 | [ concurrent-ruby ]
2021-06-30T14:39:08 [I|bac|] Task {label: Actions::Pulp3::ContentMigration, id: 65e8bb91-e8a0-4c6c-906f-0f4f718c282f, execution_plan_id: a30a7af9-ace9-47a1-828b-94cc8c4b37fd} state changed: stopped  result: warning
2021-06-30T14:39:08 [I|bac|] Task {label: Actions::Pulp3::ContentMigration, id: 65e8bb91-e8a0-4c6c-906f-0f4f718c282f, execution_plan_id: a30a7af9-ace9-47a1-828b-94cc8c4b37fd} state changed: stopped  result: warning
```

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
now i'm wondering how i tested this!

**Comment by jlsherrill** [comment]
this should be good now, double checked and tested :)

**Review by jjeffers — APPROVED** [review]
Lookin' good!
```
[vagrant@centos7-katello-3-18 katello-3.18.3.1]$ sudo foreman-maintain content migration-stats
Running Retrieve Pulp 2 to Pulp 3 migration statistics
================================================================================
Retrieve Pulp 2 to Pulp 3 migration statistics: 
============Migration Summary================
Migrated/Total RPMs: 32/32
Migrated/Total errata: 4/20
Migrated/Total repositories: 1/5

Estimated migration time based on yum content: fewer than 5 minutes

Note: ensure there is sufficient storage space for /var/lib/pulp/published to triple in size before starting the migration process.
Check the size of /var/lib/pulp/published with 'du -sh /var/lib/pulp/published/'
                                                                      [OK]
--------------------------------------------------------------------------------

[vagrant@centos7-katello-3-18 katello-3.18.3.1]$ sudo foreman-maintain content prepare
Running Prepare content for Pulp 3
================================================================================
Prepare content for Pulp 3: 
Checking for valid Katello configuraton.
Starting task.
2021-06-30 14:27:55 +0000: Content migration starting. 
Content Migration completed successfully

Script started on Wed 30 Jun 2021 02:27:41 PM UTC
Checking for valid Katello configuraton.
Starting task.
2021-06-30 14:27:55 +0000: Content migration starting. 
Content Migration completed successfully
                            [OK]
--------------------------------------------------------------------------------

[vagrant@centos7-katello-3-18 katello-3.18.3.1]$ sudo foreman-maintain content migration-stats
Running Retrieve Pulp 2 to Pulp 3 migration statistics
================================================================================
Retrieve Pulp 2 to Pulp 3 migration statistics: 
============Migration Summary================
Migrated/Total RPMs: 32/32
Migrated/Total errata: 20/20
Migrated/Total repositories: 5/5

Estimated migration time based on yum content: fewer than 5 minutes

Note: ensure there is sufficient storage space for /var/lib/pulp/published to triple in size before starting the migration process.
Check the size of /var/lib/pulp/published with 'du -sh /var/lib/pulp/published/'
                                                                      [OK]
--------------------------------------------------------------------------------
```
APJ

**Comment by jjeffers** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
