### PR TITLE
Fixes #33480 - drop jQuery-ui sortable

### PR DESCRIPTION
**Pull request by ezr-ondrej**
`jquery-ui/sortable` doesn't appear to be used anywhere in the project

### CODE REVIEW

**Review by jlsherrill — APPROVED** [review]
Thanks!

**Comment by jlsherrill** [comment]
This now needs a rebase

**Comment by jturel** [comment]
ping @ezr-ondrej :)

**Comment by ezr-ondrej** [comment]
Oh... done :)

**Pull request merged**
