### PR TITLE
Fixes #16559 - propagate repo info to cv copies

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by bbuckingham** [comment]
With the PR changes applied, attempting to publish a new version of a content view that uses the repo that has had checksum changed is resulting in the following error:

```
^foreman-tasks/dynflow^[[0m] [D] ExecutionPlan e7f06088-87ba-4e55-b7fa-148bbd20a2fd     planning >>   stopped
ArgumentError: wrong number of arguments (1 for 2)
 | /home/vagrant/katello/app/models/katello/glue/pulp/repo.rb:822:in `distributors_match?'
 | /home/vagrant/katello/app/models/katello/glue/pulp/repo.rb:75:in `block in needs_distributor_updates'
 | /home/vagrant/katello/app/models/katello/glue/pulp/repo.rb:72:in `select'
 | /home/vagrant/katello/app/models/katello/glue/pulp/repo.rb:72:in `needs_distributor_updates'
 | /home/vagrant/katello/app/lib/actions/katello/repository/clone_to_environment.rb:18:in `block in plan'
```

**Comment by jlsherrill** [comment]
@bbuckingham fixed!

**Comment by bbuckingham** [comment]
@jlsherrill, Confirmed that the error above is fixed.

With these changes, if the user has Library configured to sync to the capsule and they change the checksum type on a repository, should the repository in the default organization view be updated?  (Referring to the pulp data, as I do not see it updated there for either the server or capsule).  If I publish a new version of a content view or promote it, I do see that version of the repository updated.

e.g. Output of a repo in default org view that was updated from (sha256 to sha1)
```
Id:                  Default_Organization-zoo-zoo
Display Name:        zoo
Description:         None
Content Unit Counts:
  Erratum:          4
  Package Category: 1
  Package Group:    2
  Rpm:              32
Notes:
Scratchpad:
  Checksum Type: sha256
...
```

**Comment by bbuckingham** [comment]
@jlsherrill, Per our discussion, it does look like it is only the 'scratchpad' and the pulp repo is getting updated properly on both server and capsule.

ACK

**Pull request merged**
