### PR TITLE
Fixes #20703 - fix host traces page

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by bbuckingham** [comment]
@jlsherrill, Are there additional scenarios involving a 'CollectionProxy' where we should apply the same change?  Should we cover those with this issue or a separate?

**Comment by jlsherrill** [comment]
@bbuckingham i don't know of any easy of figuring that out without reading through every controller and hoping that i catch some sort of association being used.  I'm open to ideas but I don't have many beyond that.

**Comment by bbuckingham** [comment]
@jlsherrill, Unfortunately, the scenario you describe is likely the only way to determine it (review/inspect/test/fix) on each controller that is using the 'uniq' construct.  It was found in another case that 'uniq!' will not convert the CollectionProxy to an Array.  That might be the easiest way (s/uniq/uniq!/), but means we could still have 'uniq!' usage in places that it may not be fully needed.

**Comment by jlsherrill** [comment]
opened http://projects.theforeman.org/issues/20935

**Pull request merged**
