### PR TITLE
Fixes #33278 - ignore orphaned root repos on migration

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test:

1.  create a repository on 3.18 in the ui/hammer
2. find the id of the repository and run in the console:  Katello::Repository.find(15).destroy!
3. try to run a migratoin, it will error
4. apply patch, restart services: ``` systemctl restart foreman dynflow*```
5. re-run the migration

**Comment by lfu** [comment]
Does this mean a root repository should be deleted too when its last child is deleted? Just curiosity.

**Comment by jlsherrill** [comment]
@lfu great question!  yes, a root repository object should be deleted when its last child (which should always be the library instance) is deleted.  Thats how it works today, but we've seen user databases where they have an orphaned root repository, and haven't ever been able to figure out what causes (possibly some manual rails console commands?)

**Review by jjeffers — APPROVED** [review]
LGTM, resolved issue as shown in reproduction steps:
```
[root@centos7-katello-3-18 katello-3.18.4]# foreman-maintain content prepare
Running Prepare content for Pulp 3
================================================================================
Prepare content for Pulp 3: 
Checking for valid Katello configuraton.
Starting task.
2021-08-18 21:04:54 +0000: Initial Migration steps complete.
Content Migration completed successfully

Script started on Wed 18 Aug 2021 09:04:28 PM UTC
Checking for valid Katello configuraton.
Starting task.
2021-08-18 21:04:54 +0000: Initial Migration steps complete.
Content Migration completed successfully
                            [OK]
--------------------------------------------------------------------------------

[root@centos7-katello-3-18 katello-3.18.4]# foreman-maintain content migration-stats
Running Retrieve Pulp 2 to Pulp 3 migration statistics
================================================================================
Retrieve Pulp 2 to Pulp 3 migration statistics: 
============Migration Summary================
Migrated/Total RPMs: 7178/7178
Migrated/Total errata: 1466/1466
Migrated/Total repositories: 7/7

Estimated migration time based on yum content: fewer than 5 minutes

Note: ensure there is sufficient storage space for /var/lib/pulp/published to triple in size before starting the migration process.
Check the size of /var/lib/pulp/published with 'du -sh /var/lib/pulp/published/'
                                                                      [OK]
--------------------------------------------------------------------------------
```

**Pull request merged**
