### PR TITLE
Fixes #25405 - Use PaginationRow from core

### PR DESCRIPTION
**Pull request by xprazak2**
Needs https://github.com/theforeman/foreman/pull/6208

### CODE REVIEW

**Comment by waldenraines** [comment]
@xprazak2 looks like there are some react test failures here.

**Comment by tstrachota** [comment]
@xprazak2 thank you for taking care about cleaning Katello too!

This needs a rebase. Would you mind removing the file `components/PaginationRow/index.js` if it isn't used in Katello any more?

**Comment by xprazak2** [comment]
It happens during the asset compilation, because the component cannot be found in core. I do not expect this to turn green until the component is merged in core.

**Comment by tstrachota** [comment]
The dependency has been merged into the core.

**Comment by xprazak2** [comment]
[test katello]

**Comment by xprazak2** [comment]
@tstrachota, @waldenraines, all green now.

**Pull request merged**
