### PR TITLE
Show download_policy in rabl only for yum repos

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
I am confused by this PR and https://github.com/Katello/katello/pull/5749

**Comment by cfouant** [comment]
@ehelms I've never worked off another person's branch before. I thought I was doing it correctly? Perhaps not.

**Comment by cfouant** [comment]
Okay, trying this again

**Comment by daviddavis** [comment]
k97szns

**Pull request closed without merging**
