### PR TITLE
[CP] Katello 4.1 GA cherry-picks (take 2)

### PR DESCRIPTION
**Pull request by jeremylenz**
Unmerged issues to be picked:
- [x] https://github.com/Katello/katello/pull/9391
- [x] https://github.com/Katello/katello/pull/9387

- [x] re-run tool with 4.0.2 correctly in tool_belt config and pick those issues

- [x] bump version
- [x] changelog :)

### CODE REVIEW

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
```
Cherry Picks for repository: katello
----------------------------------------------
Pick All: git cherry-pick -x 


```

**Comment by jturel** [comment]
As far as the content goes this looks perfect!

I have one matter of correctness to ask you to change: There are several commits that come *after* the version bump to 4.1 but are meant to be part of the release. Remember that the *last* (HEAD) commit on this branch is what's going to get tagged with `4.1.0`. It means that some commit which doesn't correspond to the version bump would be the final commit for 4.1 GA and that makes the git history misleading and wrong in my opinion.

The fix is simple - interactive rebase. `git rebase -i origin/KATELLO-4.1` and in the editor, just move the 4.1 version bump to be the HEAD of your branch, then force push. Done! You can make sure you didn't mess anything up by diffing your local copy to the remote copy - there should be absolutely no difference in the contents (just the commit order).

**Comment by adamruzicka** [comment]
```
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/smart_proxy_dynflow-0.5.1/lib/smart_proxy_dynflow/task_launcher_registry.rb:1:in `<top (required)>'
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/smart_proxy_dynflow-0.5.1/lib/smart_proxy_dynflow.rb:3:in `<top (required)>'
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/foreman-tasks-core-0.4.0/lib/foreman_tasks_core.rb:4:in `<top (required)>'
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/foreman-tasks-4.1.1/lib/foreman_tasks/engine.rb:1:in `<top (required)>'
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/foreman-tasks-4.1.1/lib/foreman_tasks.rb:3:in `<top (required)>'
[2021-06-16T18:42:26.988Z] /usr/local/rvm/gems/ruby-2.7.0@katello-pr-test-7397/gems/foreman-tasks-4.1.1/lib/foreman-tasks.rb:1:in `<top (required)>'
```

Since jenkins pull gems from rubygems and `foreman-tasks-core` is unbounded, it pulls in `foreman-tasks-core-0.4.0` which will not be available for foreman 2.5 and is the thing that causes this breakage. Either I can release foreman-tasks-4.1.2 which would limit `foreman-tasks-core` to `<= 0.3.5` or you can do it here. I wanted to handle it only in packaging by not making newer `foreman-tasks-core` available, but apparently that's not as good solution as I hoped. Do you prefer either of the two options?

**Comment by jeremylenz** [comment]
@adamruzicka Before https://github.com/Katello/katello/pull/9409/commits/c1f1822e797418423f778293241e488b88eb7dcd, I think we were using 4.1.2 and getting the same issue.  But I'm fine pinning `foreman-tasks-core` if that's what's needed.

**Comment by jeremylenz** [comment]
@adamruzicka the only thing is, we don't explicitly require `foreman-tasks-core` so I'm not sure how to pin it..

**Comment by adamruzicka** [comment]
Right, by 4.1.2 I meant whatever is (latest-2.5-compatible + 0.0.1). For some reason I thought 4.1.1 is the last one in the 2.5-copmatible line, sorry about the noise.

**Comment by jturel** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello] one more time for good measure :D

**Review by jturel — APPROVED** [review]
APJ

**Pull request merged**
