### PR TITLE
Opt-in email notifications when {repo sync, cv promote, cv publish, proxy sync} fails

### PR DESCRIPTION
**Pull request by adamruzicka**
#### What are the changes introduced in this pull request?
Opt-in email notifications when {repo sync, cv promote, cv publish, proxy sync} fails

#### What are the testing steps for this pull request?
1) Subscribe to each of the things mentioned above
2) Make them fail. In general `raise "HALT"` somewhere in the action works pretty well, but it cannot happen before action_subject is called

TODO:
- [x] redmine

### CODE REVIEW

**Comment by adamruzicka** [comment]
Do these four actions always fail hard or do they go into paused?

**Comment by sjha4** [comment]
IIRC syncs fail and go to stopped/error state.. Promote/Publish pause upon errors.

**Comment by adamruzicka** [comment]
Changed to send the emails out when things either fail or get paused just to be extra sure

**Comment by adamruzicka** [comment]
Is your db seeded? If you run `MailNotification[:capsule_sync_failure]` in rails console, what does it give you?

**Review by sjha4 — APPROVED** [review]
Able to see emails on repo sync, capsule sync, cv publish and promote failures.
Ack 👍🏼 

Repo_sync_failure_email
Cv_promote_fail_email
CV_publish_failure_email
Capsule_sync_failure_email

**Pull request merged**
