### PR TITLE
Fixes #22195 - use setSuccessMessage when adding subs

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by beav** [comment]
APJ, easy enough 😸

**Comment by evgeni** [comment]
that rails5 failure looks unrelated :)

**Comment by jlsherrill** [comment]
I've seen this a few times in the past month or so, i filed:   http://projects.theforeman.org/issues/22204

**Comment by jlsherrill** [comment]
[test rails-5]

**Comment by jlsherrill** [comment]
Thanks @evgeni

**Pull request merged**
