### PR TITLE
Fixes #17169: Remove nutupane from host collection pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17169

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires Katello/bastion#136

**Comment by thomasmckay** [comment]
host collections

Should those tabs be there when in the copy action view? I would say no. (Note the missing outlines around the tabs themselves too.)

**Comment by thomasmckay** [comment]
What do you think about moving the action links that switch over to the content hosts page to the kebab menu? I know it goes to another page but perhaps when content hosts goes to non-pain it would just feel like a host collection action.

**Comment by waldenraines** [comment]
> What do you think about moving the action links that switch over to the content hosts page to the kebab menu? I know it goes to another page but perhaps when content hosts goes to non-pain it would just feel like a host collection action.

I know it's a little different from the other pages but I personally like it where it is because they are long sentences instead of single words like most other actions.  Also, they were a separate page before but I thought having them on the details page would work well since there isn't many details associated with a host collection.

Thoughts?

> Should those tabs be there when in the copy action view? I would say no. (Note the missing outlines around the tabs themselves too.)

I decided to set the details tab to active in this case, what do you think of that?

**Comment by thomasmckay** [comment]
ack

**Comment by ehelms** [comment]
The content host discoverable link, where the number of content hosts is displayed on the details page links to the 'Add Content Hosts' page and tab. I would have expected that link to take me to the list of content hosts.

**Comment by ehelms** [comment]
The tabs here seem a little weird given the form is presented that does not relate to those tabs.

screenshot from 2016-11-22 09-41-55

**Comment by waldenraines** [comment]
> The content host discoverable link, where the number of content hosts is displayed on the details page links to the 'Add Content Hosts' page and tab. I would have expected that link to take me to the list of content hosts.

It does if you have hosts in the Host Collection, otherwise it takes you to the add page.

Fixed the other issues.

**Comment by waldenraines** [comment]
[test]

**Pull request merged**
