### PR TITLE
Fixes #34929 - ACS details UI

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
Add details view for ACS.
#### What are the testing steps for this pull request?
Create an ACS and click on ACS on the index page:

image

PS: We need to upgrade PF4 to add badges to expandable section toggle. That is not part of this PR. Edit is also a separate task.

### CODE REVIEW

**Review by ianballou — COMMENTED** [review]
Some notes:

The bullet points next to the smart proxies look a little strange, they remind me of a word document. I wonder how it'd look without them.

When I mouse over the last refresh time, a popup appears saying "Invalid Date".

What do you think about doing some formatting on the subpaths? Mine show up like "rpm-zchunk/,rpm-advisory-diff-repo/" without a space after the comma. Should we do a newline list like smart proxies?

**Comment by sjha4** [comment]
Without the bullet points:
image

> What do you think about doing some formatting on the subpaths? Mine show up like "rpm-zchunk/,rpm-advisory-diff-repo/" without a space after the comma. Should we do a newline list like smart proxies?

We will convert that into a textarea input field in a follow-up PR for editing ACSs. It should change then.

> When I mouse over the last refresh time, a popup appears saying "Invalid Date".

Looking..

**Comment by ianballou** [comment]
image

**Comment by ianballou** [comment]
I created an ACS with a password and it's crashing the page:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {username}). If you meant to render a collection of children, use an array instead.
    in dd (created by TextListItem)
    in TextListItem (created by ACSExpandableDetails)
    in dl (created by TextList)
    in TextList (created by ACSExpandableDetails)
    in div (created by TextContent)
    in TextContent (created by ACSExpandableDetails)
    in div (created by ExpandableSection)
    in div (created by ExpandableSection)
    in ExpandableSection (created by ACSExpandableDetails)
    in ACSExpandableDetails (created by PanelContent)
    in span (created by PanelContent)
    in div (created by DrawerHead)
    in div (created by DrawerPanelBody)
    in DrawerPanelBody (created by DrawerHead)
    in DrawerHead (created by PanelContent)
    in div (created by DrawerPanelContent)
    in DrawerPanelContent (created by PanelContent)
    in PanelContent (created by ACSTable)
    in div (created by DrawerMain)
    in DrawerMain (created by DrawerContent)
    in DrawerContent (created by ACSTable)
    in div (created by Drawer)
    in Drawer (created by ACSTable)
    in ACSTable (created by ACSIndexPage)
    in div (created by GridItem)
    in GridItem (created by ACSIndexPage)
    in div (created by Grid)
    in Grid (created by ACSIndexPage)
    in ACSIndexPage (created by Context.Consumer)
    in withRouter(ACSIndexPage) (created by Headers)
    in Headers (created by CheckOrg)
    in CheckOrg (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by _default)
    in div (created by _default)
    in _default (created by Application)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Application)
    in Application (created by ConnectFunction)
    in ConnectFunction (created by I18nProviderWrapper(Connect(Application)))
    in IntlProvider (created by I18nProviderWrapper(Connect(Application)))
    in I18nProviderWrapper(Connect(Application)) (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in Provider (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in StoreProvider(I18nProviderWrapper(Connect(Application))) (created by DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application)))))
    in DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application))))
    React 13
    unstable_runWithPriority scheduler.development.js:653
    React 4
    Redux 4
    routerMiddleware middleware.js:22
    Redux 5
    tryCatch bundle.js:15665
    _invoke bundle.js:15665
    defineIteratorMethods bundle.js:15665
    asyncGeneratorStep bundle.js:15673
    _next bundle.js:15675
[react-dom.development.js:13413](webpack:///.-core/node_modules/react-dom/cjs/react-dom.development.js)
The above error occurred in the <dd> component:
    in dd (created by TextListItem)
    in TextListItem (created by ACSExpandableDetails)
    in dl (created by TextList)
    in TextList (created by ACSExpandableDetails)
    in div (created by TextContent)
    in TextContent (created by ACSExpandableDetails)
    in div (created by ExpandableSection)
    in div (created by ExpandableSection)
    in ExpandableSection (created by ACSExpandableDetails)
    in ACSExpandableDetails (created by PanelContent)
    in span (created by PanelContent)
    in div (created by DrawerHead)
    in div (created by DrawerPanelBody)
    in DrawerPanelBody (created by DrawerHead)
    in DrawerHead (created by PanelContent)
    in div (created by DrawerPanelContent)
    in DrawerPanelContent (created by PanelContent)
    in PanelContent (created by ACSTable)
    in div (created by DrawerMain)
    in DrawerMain (created by DrawerContent)
    in DrawerContent (created by ACSTable)
    in div (created by Drawer)
    in Drawer (created by ACSTable)
    in ACSTable (created by ACSIndexPage)
    in div (created by GridItem)
    in GridItem (created by ACSIndexPage)
    in div (created by Grid)
    in Grid (created by ACSIndexPage)
    in ACSIndexPage (created by Context.Consumer)
    in withRouter(ACSIndexPage) (created by Headers)
    in Headers (created by CheckOrg)
    in CheckOrg (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by _default)
    in div (created by _default)
    in _default (created by Application)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Application)
    in Application (created by ConnectFunction)
    in ConnectFunction (created by I18nProviderWrapper(Connect(Application)))
    in IntlProvider (created by I18nProviderWrapper(Connect(Application)))
    in I18nProviderWrapper(Connect(Application)) (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in Provider (created by StoreProvider(I18nProviderWrapper(Connect(Application))))
    in StoreProvider(I18nProviderWrapper(Connect(Application))) (created by DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application)))))
    in DataProvider(StoreProvider(I18nProviderWrapper(Connect(Application))))

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Comment by sjha4** [comment]
> I created an ACS with a password and it's crashing the page:

Fixed.. 👍🏼

**Review by ianballou — APPROVED** [review]
This is looking good to me now! With all this testing I'm wondering if we should do some kinda validation before closing the wizard, it can get frustrating having to type in the values all over again. Also it is kinda weird that firefox at least isn't showing drop down suggestions on text boxes.

**Pull request merged**
