### PR TITLE
Fixes #24018 - search all instances of packages in all repos

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by kgaikwad** [comment]
@akofink,

Created pull-request for package search.

Yesterday, while discussing I forgot to mention one point that I have skipped existing [organization scope](https://github.com/Katello/katello/pull/7641/files#diff-4a58e16252386909489b00a2f4451879L141) that's why it was returning all results. 

But after removing that code, it applies organization scope when environment and content_view filters are blank which results into only single record. I think it's incorrect behavior. 
So I would like to confirm that for my changes do I need to keep this organization scope or should I add condition using available_for to skip this `if..else` block.

**Comment by akofink** [comment]
I believe we want to honor the current organization scope in the search.

**Comment by kgaikwad** [comment]
@akofink,

Yeah, I agree with your opinion.
In the method  `index_relation_product` only, it considers [organization](https://github.com/Katello/katello/pull/7641/files#diff-4a58e16252386909489b00a2f4451879L118) filter while fetching results. 
When some values are selected for environment and content_view. In this case, it only considers `organization` in `index_relation_product` method.

So, total records mismatches when we performs below scenarios:
1. Both environment, content_view = ALL and 
2. when environment, content_view = some values selected 

On my DEV setup, 
With environment values i.e Library, Dev  and Content_view = ALL, it gives me two records per environment value and
When environment = ALL and  content_view = ALL gives me only one record due to this [organization](https://github.com/Katello/katello/pull/7641/files#diff-4a58e16252386909489b00a2f4451879L143) scope.

**Comment by beav** [comment]
This patch behaves oddly in some cases. I synced "zoo" repo, promoted it to a CV, then deleted the "bear" rpm from the Library version of the repo :bear: 

I then went to the packages list, clicked on the bear package, then selected "all lifecycle envs" and "all content views". No bears were found (incorrect)

I then changed the CV dropdown to "Default Organization View" and no bears were found (correct). I changed it to my CV, and two bears were found (also incorrect) :bear: :bear:

**Comment by kgaikwad** [comment]
@beav,
Could you please share `Published At` paths from output repos from the scenario that you shared.
i.e when you changed it to your CV with selected "all lifecycle envs" gives you two records.

**Comment by kgaikwad** [comment]
@akofink,
Thank you,
I have updated PR with two test cases and resolved review comments.

**Comment by beav** [comment]
where do I go in the web UI to do the errata part?

**Comment by akofink** [comment]
Content -> Errata -> click an erratum -> Repositories tab

**Comment by beav** [comment]
It may make sense to add a "Content View" field here, since you can select "All Content Views". This would allow the user to see which CV each erratum is referring to, so it doesn't look like the same thing 3x. Also this is fine as a new issue, doesn't need to be this PR.

selection_020

**Comment by kgaikwad** [comment]
@akofink, @beav,
Thank you for inputs.
I have added it while testing filters. Please check below image and let me know that is that ok? as I have updated API response for repositories with new key i.e `:content_view` which is inherited by `content_view_version`.
If you guys ok with this change, I will commit and push it to same pull-request.

zoo_repo_cvs

**Comment by akofink** [comment]
I'm fine with it adding the change (though I think this PR is ready to merge as is, today). It'd help speed review if you could put the change in an additional commit.

**Comment by kgaikwad** [comment]
@akofink,
Added `content_view` column change in separate commit.

**Comment by beav** [comment]
no additional comment from me, looks good

**Pull request merged**
