### PR TITLE
Fixes #21051: warn on unregistering of host if delete enabled.

### PR DESCRIPTION
**Pull request by waldenraines**
If the setting 'unregister_delete_host' is set then we should warn users
upon unregistering a host and selecting 'delete host record' that the
action could remove the VM.

http://projects.theforeman.org/issues/21051

### CODE REVIEW

**Comment by jlsherrill** [comment]
Hrmmm, i wonder if 'unregistering' via the UI should actually unregister even if this setting is set?   Either that, or we should just hide the unregsiter button in the UI if that setting is set and only show the delete button.

This setting was really meant for 'subscription-manager unregister'

**Comment by waldenraines** [comment]
> Hrmmm, i wonder if 'unregistering' via the UI should actually unregister even if this setting is set? Either that, or we should just hide the unregsiter button in the UI if that setting is set and only show the delete button.
> 
> This setting was really meant for 'subscription-manager unregister'

You have more context than me so I'll let you decide 😄

**Comment by waldenraines** [comment]
@jlsherrill thoughts on the above?

**Comment by jlsherrill** [comment]
I think i prefer to just hide the unregister link, since it will delete the host anyways.

**Comment by waldenraines** [comment]
@jlsherrill updated.

**Comment by waldenraines** [comment]
[test default]

**Comment by waldenraines** [comment]
The build won't pass until https://github.com/Katello/bastion/pull/211 is merged.

**Comment by waldenraines** [comment]
[test]

**Comment by jlsherrill** [comment]
[test default]
[test rails-5]

**Comment by waldenraines** [comment]
> [test default]
> [test rails-5]

@jlsherrill see https://github.com/Katello/katello/pull/7084#issuecomment-348563413

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test default]
[test rails-5]

**Comment by waldenraines** [comment]
@jlsherrill ready to review

**Pull request merged**
