### PR TITLE
fixes #15239 - fix content host and system migration errors

### PR DESCRIPTION
**Pull request by bbuckingham**
During testing of PR 6066, additional errors were found with the
migrations after the PR was merged.  This commit is to address those
errors.

References:
https://github.com/Katello/katello/pull/6066#issuecomment-222348357
https://github.com/Katello/katello/pull/6066#issuecomment-222349268

### CODE REVIEW

**Comment by bbuckingham** [comment]
[test]

**Comment by waldenraines** [comment]
The changes look good to me and everything I tested worked.  APJ.

**Comment by beav** [comment]
jenkins should be green after rebasing

**Comment by bbuckingham** [comment]
@waldenraines, @beav, Thanks guys!

**Pull request merged**
