### PR TITLE
Fixes #35063 - Allow copying activation keys with create_activation_keys permissions

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the testing steps for this pull request?
Create a user with view and create activation keys permissions.
Go to Activation key > your activation_key > 
1. You should be able to see a copy action in the action dropdown
2. You should be able to successfully copy the key without any permissions issues.

### CODE REVIEW

**Comment by sjha4** [comment]
> With only permissions for activation keys, got this error when clicking Content - Activation Keys. Screenshot from 2022-06-21 15-35-48

Was this on the branch or master? I can click on Content > Activation keys in master and on this branch. I added all activation key permissions, edit/create/view and create Activation keys to the role.

**Comment by lfu** [comment]
> Was this on the branch or master? 

This happens when Any Organization is used and I think it is by default. 
After selecting a specific organization, the issue didn't occur.

**Review by lfu — APPROVED** [review]
I think the issue I hit is not related to this PR.
LGTM 👍🏻

**Comment by lfu** [comment]
The routing issue was caused by missing permissions to view and assign organizations for the limited user.

**Pull request merged**
