### PR TITLE
Fixes #23928 - Migrate Pulp Sync Plans

### PR DESCRIPTION
**Pull request by sjha4**
**Cleaned commit from https://github.com/Katello/katello/pull/7479. Follow the discussion and reviews there for more context.**
***
**Tasks:**
- [x] Migrate Sync Plan logic from Pulp repo schedules to Recurring Logic
- [x] Fix timezone issues when creating recurring logic
- [x] Support Updating sync plans
- [x] Modify Product Add/Remove to remove pulp sync plan calls
- [x] Optimizations
- [x]  Tests
*** 
**Data Migration:**
- [x] Create and start recurring logics for existing sync plans
- [x] Delete repo schedules in Pulp

*****
**To Review and test:**

1. Pull the PR locally and checkout
2. Run `rails db:migrate`
3. Run `rake katello:upgrades:3.9:migrate_sync_plans `

_To test data migration, make sure you have existing sync plan records before migrating._

### CODE REVIEW

**Comment by jlsherrill** [comment]
actually, hold off on merging, i need to test a few things

**Comment by jlsherrill** [comment]
@sjha4 i see one issue when deleting a sync plan.  The recurring logic gets deleted, but the task in dynflow is still 'scheduled'.  I think we need a before_destroy that calls cancel on the recurring logic before it gets deleted.

**Comment by sjha4** [comment]
@jsherrill: Seems more natural for that to happen on all recurring logics..Should we add that to recurring logics?

**Comment by sjha4** [comment]
@jsherrill: The task for delete was not needed anymore since we are not processing products on sync plan delete any more. Removed the action for delete.

**Comment by sjha4** [comment]
Thanks @jlsherrill , @akofink !

**Pull request merged**
