### PR TITLE
Fixes #15891 - lookup existing hosts with lowercase

### PR DESCRIPTION
**Pull request by jlsherrill**
name

### CODE REVIEW

**Comment by ehelms** [comment]
Assuming by this all hosts are put into database with lowercased hostnames?

**Comment by jlsherrill** [comment]
@ehelms yep!

**Comment by ehelms** [comment]
What about a test for this?

**Comment by jlsherrill** [comment]
@ehelms test added

**Comment by ehelms** [comment]
ACK

**Pull request merged**
