### PR TITLE
Fixes #29355 - allow CVE id in safe mode

### PR DESCRIPTION
**Pull request by ares**
to test, apply [this](https://github.com/theforeman/community-templates/pull/709) to your report template and generate, cves column will contain CVE identifiers instead of internal AR object id

### CODE REVIEW

**Comment by ares** [comment]
Please also let me know if this hits Katello 3.17, I'll need to update the report template accrodingly

**Comment by jlsherrill** [comment]
@ares apologies, this fell through the cracks.

**Comment by jlsherrill** [comment]
@ares this will make 3.16 (foreman 2.1)

**Comment by ares** [comment]
thanks Justin, redmine still says 3.17 but I'll udpate the template so it requires 3.16+

**Pull request merged**
