### PR TITLE
Fixes #37187 - Update ACS refresh Pulp fixtures + fix repository_test test

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
Fixes failing testes on master (hopefully)

#### Considerations taken when implementing this change?
This will need to be backported to 4.11.1 and 4.12.0.

#### What are the testing steps for this pull request?
See that the tests pass.

### CODE REVIEW

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
This PR should fix the broken tests: https://github.com/theforeman/jenkins-jobs/pull/419

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Review by sjha4 — APPROVED** [review]
Ack.. 🎉

**Pull request merged**
