### PR TITLE
Refs #11500 - merging host_unification to master

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by waldenraines** [comment]
ACK from me, but we may want to get someone not on the host unification team to review.

**Comment by johnpmitsch** [comment]
I see some minor changes that will have to be made wrt rails4 but nothing that can't be done on after merging master into rails4 branch, so I do not think you need to change anything in this PR

**Comment by cpeters** [comment]
@johnpmitsch agreed.

ACK

**Comment by jlsherrill** [comment]
@ehelms you good with this?

**Comment by ehelms** [comment]
Are there upgrade instructions for this work? Does it require just a DB migrate?

**Comment by jlsherrill** [comment]
@ehelms just db:migrate

let me rebase to master

**Comment by ehelms** [comment]
ACK for me, passed basic testing and assumptions

**Comment by jlsherrill** [comment]
Merged master back in, only conflicts were vcr cassettes for pulp repo & consumer cassettes.  Rerecorded those.

**Comment by ehelms** [comment]
:+1:

**Comment by waldenraines** [comment]
@ehelms is that an ACK?

**Comment by ehelms** [comment]
ACK

**Pull request merged**
