### PR TITLE
Revert "fixes #12297 - removes max of 5 limit on selector value, BZ1266310

### PR DESCRIPTION
**Pull request by cfouant**
Reverts Katello/katello#5545

### CODE REVIEW

**Comment by ehelms** [comment]
@thomasmckay @cfouant what about just fixing the actual issue instead of reverting this change? Given we are in the development cycle for 2.5, I don't see this change having an impact until release. Alternatively, devise some way to indicate in the code this is done for a specific reason and not arbitrarily to avoid this issue in the future.

**Comment by thomasmckay** [comment]
@ehelms why is revert the wrong path? The fix is not appropriate and I think we're agreeing to fix it properly without introducing a new issue.

**Comment by ehelms** [comment]
I never said it was wrong -- I simply asked about a different tactic based upon why this occurred in the first place. If we want the revert, that's fine, however, this should be updated to reference the issue in the standard PR format so our tooling picks it up properly.

**Comment by cfouant** [comment]
I'm fine with not reverting and starting a new PR - I just don't think I'll have time to get to it this week and I think Tom doesn't want this going in. Please advise :)

**Comment by ehelms** [comment]
Just update the commit and PR message and then we can get this in -- as well please re-open the issue.

**Comment by cfouant** [comment]
@thomasmckay FYI don't use the "Revert" button in the Github UI.

**Comment by cfouant** [comment]
Closed for https://github.com/Katello/katello/pull/5549

**Pull request closed without merging**
