### PR TITLE
Fxies #15116 - lay down ssh keys as non-root for cloudinit

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@stbenjam is this change okay for REX?

**Comment by stbenjam** [comment]
Eh, I don't really know.  I don't get the `admin` user at all, since cloud images come with a user already, and I kind of expected most people to use that.

I think the best solution would be to attach the REX keys to the remote_execution_ssh_user (available as a param).  You could file that as a separate bug if you don't want to take care of it here, as it's already broken.

**Comment by ehelms** [comment]
@jlsherrill planning to revisit this PR?

**Comment by beav** [comment]
@jlsherrill is this PR still needed? the diff appears to be whitespace changes at this point

**Comment by jlsherrill** [comment]
Closing!

**Pull request closed without merging**
