### PR TITLE
Fixes #25475: Use default proxy for nil capsule_id

### PR DESCRIPTION
**Pull request by akofink**
Caused by https://github.com/Katello/katello/pull/7762/files#diff-39454af49e2756358c14bc834489beaeL10

### CODE REVIEW

**Comment by sjha4** [comment]
We reverted falling back to default proxy in https://github.com/Katello/katello/commit/802c35f543140893936e8735f45bc563b85762cb
I think we might want to pass default smart proxy id to the refresh action instead.

**Comment by akofink** [comment]
Updated. Is this what you were thinking?

**Comment by jlsherrill** [comment]
is there some better way to test this?  maybe adding a scenario test?

**Comment by akofink** [comment]
I've added a test. What were you thinking by a scenario test, @jlsherrill?

**Comment by jlsherrill** [comment]
I was actually referring to https://github.com/Katello/katello/blob/master/test/scenarios/scenario_test.rb, which is a larger integration effort.  But the test you have i think is fine.

[test katello]

**Comment by beav** [comment]
@akofink this fix is needed for some other PRs, so I am going to merge. If you add more scenario tests, just add w/ a "Refs" PR.

**Pull request merged**
