### PR TITLE
Refs #15013 - Content uploads endpoint works properly.

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by beav** [comment]
This does not seem to work for me, I still do not see the org options. I applied the patch, then ran `FOREMAN_APIPIE_LANGS=en rake apipie:cache`, deleted my `.hammer` dir and re-ran `hammer -s http://localhost:3000 repository  upload-content --help`.

**Comment by zjhuntin** [comment]
This PR will only help  the repository content-upload command succeed. https://github.com/Katello/hammer-cli-katello/pull/398 This PR is the one that will add the organization option to the repository commands.

**Comment by beav** [comment]
ACK

**Pull request merged**
