### PR TITLE
Fixes #37140 - Update web UI for SCA-only

### PR DESCRIPTION
**Pull request by jeremylenz**
#### What are the changes introduced in this pull request?

1. Update the Organization list page to remove the 'Simple Content Access' column
2. Update the Organization Create and Edit pages to remove the SCA checkbox and banner
3. Update `Katello::OrganizationCreator` to no longer accept an `sca:` keyword on initialization.
4. Remove the non-SCA codepaths from RepositorySets Tab on the new host details UI
5. Remove the SCA toggle React components from the SubscriptionsPage, which was already dead code anyway

#### Considerations taken when implementing this change?

I'm trying to keep this PR to only removing visual elements that users would see in the web UI, rather than API endpoints or other backend code. But I did have to touch a few places that weren't strictly UI code.

I'm not bothering to surgically remove things from the legacy content host Angular UI, since that entire UI is going away soon anyway, and is already not displayed to users since all organizations now use SCA.

#### What are the testing steps for this pull request?

Check all the locations above and confirm that UI elements are removed
Poke around and make sure nothing is broken
Make sure CI tests pass and make sense

### CODE REVIEW

**Comment by jeremylenz** [comment]
Many test failures should be fixed when https://github.com/Katello/katello/pull/10861 is merged.

**Comment by chris1984** [comment]
@jeremylenz Do you want me to make a pr to pull stuff out of the old UI or say just leave like you said since it's going away.

**Comment by jeremylenz** [comment]
> Do you want me to make a pr to pull stuff out of the old UI or say just leave like you said since it's going away.

The cleanup is in a future epic; I think it will be fine until then

**Comment by chris1984** [comment]
So far it looks good, still checking a few pages and hammer for the api param removal, then will look at the code. I found this column on the host page, should we remove Subscription Status?

hostsub

**Comment by jeremylenz** [comment]
> I found this column on the host page, should we remove Subscription Status?

That's covered in https://github.com/Katello/katello/pull/10882 :)

**Review by chris1984 — APPROVED** [review]
Works fine with hammer and checked the UI and all of the pages you touched are updated correctly and poked around on some other pages and found an issue on the all hosts page - see comment below.

Update the Organization list page to remove the 'Simple Content Access' column - Pass
Update the Organization Create and Edit pages to remove the SCA checkbox and banner - Pass
Update Katello::OrganizationCreator to no longer accept an sca: keyword on initialization - Pass

As we discussed I found this with your other pr when testing this one on the all hosts page:

hostsub

dbissue

Which you will fix in your other PR. Thanks for getting this fixed up and when we get to the other epic for the old UI, I will get a PR for that going. Code looks fine too from a Ruby/JS standpoint.

**Comment by chris1984** [comment]
Tested with https://github.com/Katello/katello/pull/10882 and I do not hit the DB error anymore and the `Subscription Status` column is gone.

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Pull request merged**
