### PR TITLE
Fixes #32626 - Ignore empty upstream authentication

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by chris1984** [comment]
@sbernhard can I test this with Microsoft Edge based on Chromium, or do you prefer straight Chrome?

**Comment by sbernhard** [comment]
We had the issue with Chrome and Chromium. Maybe the same happens on Edge with Chromium but I don't know.

**Comment by chris1984** [comment]
> We had the issue with Chrome and Chromium. Maybe the same happens on Edge with Chromium but I don't know.

Fine, I will install Chrome :P

**Review by chris1984 — APPROVED** [review]
ACK, works good on Google Chrome and Microsoft Edge. I was able to create the repo.

**Pull request merged**
