### PR TITLE
Cherry picks 3.2 rc3

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
APJ

**Comment by johnpmitsch** [comment]
[test]

**Comment by ehelms** [comment]
This should fix the test runs -- https://github.com/Katello/bastion/pull/135

**Comment by johnpmitsch** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by johnpmitsch** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Pull request merged**
