### PR TITLE
Fixes #32936 - use bulk_host_ids parameter for traces

### PR DESCRIPTION
**Pull request by jturel**
The host_ids parameter was changed to bulk_host_ids on the controller side but the supporting code for traces never got the memo!

### CODE REVIEW

**Comment by jjeffers** [comment]
> The host_ids parameter was changed to bulk_host_ids on the controller side but the supporting code for traces never got the memo!

Mea culpa! We thought we caught all uses of this controller, but we clearly did not. :(

**Comment by jturel** [comment]
> > The host_ids parameter was changed to bulk_host_ids on the controller side but the supporting code for traces never got the memo!
> 
> Mea culpa! We thought we caught all uses of this controller, but we clearly did not. :(

It's too easy to introduce bugs in the angular app :-1:

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Review by jeremylenz — APPROVED** [review]
:heavy_check_mark: Checking out this change avoids the referenced Rails error

Didn't test with a full working REX setup, but otherwise LGTM :+1:

**Review by chris1984 — APPROVED** [review]
ACK, works great

**Pull request merged**
