### PR TITLE
fixes #9566 - only destroy repo in finalize for direct repo deletes

### PR DESCRIPTION
**Pull request by jlsherrill**
not for things like content view publish and destroys

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
If destroying in the finalize is the default or standard operation for a repository destroy, how about inverting so the special cases have to pass a parameter to destroy outside of finalize?

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
APJ

**Pull request merged**
