### PR TITLE
Fixes #31403 - Change short-date-to-long-date

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
This fixed it for the table, but not for the details:   https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/content-hosts/details/views/content-host-info.html#L326

**Comment by anandkumaragrawal** [comment]
@jlsherrill Thank you.

I have made the suggested changes. Please review.

**Review by jlsherrill — APPROVED** [review]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jturel** [comment]
@jlsherrill I added a card to the board for this before seeing that you've reviewed and acked. Go ahead and assign yourself to it!

**Review by parthaa — APPROVED** [review]
ACK

**Pull request merged**
