### PR TITLE
Cherry Picks for 3.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
ACK

**Comment by stbenjam** [comment]
Do we need to include #15114? https://github.com/Katello/katello/pull/6084/commits/2f63f5b4149d37f572cf50cd0c9c824f3c48eca6

I've confirmed it's the source of my db:migrate troubles in production.

**Comment by ehelms** [comment]
I assume without it, things might break on upgrade. However, we could leave it out for now.

**Comment by stbenjam** [comment]
It's up to you, I don't really know the background other than it was preventing me from running the content hosts migration.

**Comment by ehelms** [comment]
@stbenjam removed the commit, please double check me

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
