### PR TITLE
refs #8861 - adding layout_helper to use trunc with tooltip helper

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by orrabin** [comment]
In https://github.com/theforeman/foreman/pull/2082 long organization names where truncated in the organization dropdown using a helper in `layout_helper.rb` that truncates and adds a tooltip with the original value.

**Comment by orrabin** [comment]
[test]

**Comment by ehelms** [comment]
While the tests pass, the UI is messed up on pages that still use the old UI (Red hat Repositories, Content Search, Sync Plan) as this seems to be overriding our similar layout methods.

**Comment by orrabin** [comment]
@ehelms for now I'll copy the trunc_with_tooltip to katello layout helper but I'll open a refactoring issue to sort out what should be in katello and foreman layout_helper so they can both be used.

Looks like the original error was caused by deface of action buttons for organization that caused the index page to be re-rendered looking for the helper. 
If the layout_helper for foreman isn't used in katello we will need to add each new helper that is used in index twice.

Also, please do not merge until working with 1.8 as this helper is named `trunc` in foreman 1.7 and `trunc_with_tooltip` in 1.8 and I don't want it to break something.

**Comment by orrabin** [comment]
@ehelms I opened: http://projects.theforeman.org/issues/9128

**Comment by jlsherrill** [comment]
@orrabin  added "Blocked by another PR" label, as it looks like its waiting on the foreman change to be merged.  Please correct if this incorrect. thanks!

**Comment by orrabin** [comment]
@ehelms the foreman change is actually blocked by this, katello tests are failing since the trunc_with_tooltip helper doesn't exist.

**Comment by orrabin** [comment]
@jlsherrill the foreman PR is the one that's blocked,
https://github.com/theforeman/foreman/pull/2082 can't be merged before this PR is merged

**Comment by orrabin** [comment]
@ehelms, @jlsherrill ping?

**Comment by ehelms** [comment]
ACK, thanks @orrabin, sorry for letting this slip past us

**Pull request merged**
