### PR TITLE
[CP] 3.17.0 version bump and updated changelog

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by jturel** [comment]
Looks good! Were there any merge conflicts? Just asking as I'd consider that "risky" as this point in the release, so want to take special care there

**Comment by chris1984** [comment]
> Looks good! Were there any merge conflicts? Just asking as I'd consider that "risky" as this point in the release, so want to take special care there

Just the two I was telling you about, when I added them to the ignores, the rest of these picked clean.

**Comment by jturel** [comment]
OK everything is good but I Just noticed the changelog is duplicated. I think you need to remove changelog.md and regenerate it again

**Review by jturel — APPROVED** [review]
APJ

**Comment by chris1984** [comment]
> OK everything is good but I Just noticed the changelog is duplicated. I think you need to remove changelog.md and regenerate it again

Fixed and regenerated, no longer showing the August date

**Pull request merged**
