### PR TITLE
Fixes #32786 - fix pulp task group cancel

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
There isn't a great way to test this as nothing that i know of in master uses task groups, maybe export?

You could test it on 3.18 with the migration, you would need a few large repos synced (1 large repos published a bunch of times in a cv).

**Comment by mdellweg** [comment]
> There isn't a great way to test this as nothing that i know of in master uses task groups, maybe export?

The only thing I know of is the import part of PIE (Pulp Import Export).

**Comment by jturel** [comment]
Experimenting via rails console:

```
[5] pry(main)> tg = Katello::Pulp3::TaskGroup.new(SmartProxy.pulp_primary!, {})
2021-06-21T19:11:07 [E|app|] Got empty pulp_href on {}
=> #<Katello::Pulp3::TaskGroup:0x000000000dc50578
 @href=nil,
 @pulp_data={},
 @smart_proxy=
  #<SmartProxy:0x000000000dc98cd8
   id: 1,
   name: "centos7-katello-devel.jturel.example.com",
   url: "https://centos7-katello-devel.jturel.example.com:9090",
   created_at: Wed, 19 May 2021 01:56:30 UTC +00:00,
   updated_at: Tue, 25 May 2021 14:47:16 UTC +00:00,
   pubkey:
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+fPfX7YgfIWj1e97/HlhHMsSOR2TKxyVjPNbIJOT72dUoKjvF3THA4zxAAQL9lPU3Mi89ltNrLSTfvXJxqjl1PCClz9Wd+ibHzoDxJoTSjhY+nAoiuH/LP+5czx9luhYYN6w1yTsYbFZ1boWTG3jNw06qn7exkEkC0RQnR8S6ryQtlx/sxaIFCNDqiBj6OVznCekjNOaKztQm01eWWVBGzyLtLw3ZgxlJ6ZrpcMKteEB0VaBAnws122j1imrL7g5eIJJm2DOP8rJx7zlzOY3pA5zLJHOYgeCiEiAwdKAblE/AmJnXhMhsSlTd+i4NZdzKRA6hcbr4KOCzmifPBZiZ foreman-proxy@centos7-katello-devel.jturel.example.com",
   expired_logs: "1621389954",
   puppet_path: nil,
   download_policy: "on_demand">>
[6] pry(main)> tg.cancel
NoMethodError: undefined method `all?' for "running,waiting":String
from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/pulpcore_client-3.11.2/lib/pulpcore_client/api/tasks_api.rb:160:in `list_with_http_info'
```

=> https://github.com/Katello/katello/blob/124b6559901a64accf05a63b413e5cbbdb46a869/app/services/katello/pulp3/task_group.rb#L89

Should it be:

```
-          tasks_api.list(page_opts.merge(task_group: task_group_data['pulp_href'], state__in: 'running,waiting'))
+          tasks_api.list(page_opts.merge(task_group: task_group_data['pulp_href'], state__in: [RUNNING, WAITING]))
```

**Comment by jlsherrill** [comment]
Yep, you're right! sadly 3.18 bindings are different and needs 'running,waiting' :/

I guess i'll open a 2nd pr for 3.18 itself

**Comment by jlsherrill** [comment]
3.18 pr opened here: https://github.com/Katello/katello/pull/9420

**Review by jturel — APPROVED** [review]
```
Jun 22 18:18:48 centos7-katello-devel.jturel.example.com pulpcore-api[657]: pulp [2dff63fb0e0047e9bef4a694f03c51ff]:  - - [22/Jun/2021:18:18:48 +0000] "GET /pulp/api/v3/tasks/?limit=2000&offset=0&state__in=running%2Cwaiting HTTP/1.1" 200 635 "-" "OpenAPI-Generator/3.11.2/
ruby"                                                               
Jun 22 18:18:49 centos7-katello-devel.jturel.example.com pulpcore-api[657]: pulp [c6f9d183ed7e44c5bc1504ee33eff13c]: pulpcore.tasking.util:INFO: Canceling task: c441c7cf-4c3f-4bf0-a11d-13d54d82859b    
```

ACK

**Pull request merged**
