### PR TITLE
Fixes #29838 - Add Red Hat Subscriptions Consumed macro

### PR DESCRIPTION
**Pull request by jturel**
This PR resumes the work started by @snagoor in https://github.com/Katello/katello/pull/8714

It adds a macro for reporting templates that sums up the consumed quantities of red hat subscriptions for a host. It does so by refactoring the `HostSubscriptionPresenter` and introducing a `HostSubscriptionsPresenter` (note the plurality difference). My main design choices around `HostSubscriptionsPresenter` were:
- One interface to be used by the report template macro and subscriptions controller
- avoid 1 DB query per host pool. load them all at once instead
- avoid querying candlepin if there are no subscription facet pools (and therefore no candlepin entitlements)

There should be a small performance improvement for the `HostSubscriptionsController`, although the macro implies that there will be a candlepin call for each host in the report. Not ideal but there's no other way right now, since we don't track the consumed quantity of the entitlements in our DB.

**To test**

1. Verify the hammer output for subscriptions listing isn't broken:
```
hammer subscription list --host-id=1
---|----------------------------------|-----------------------------------------------------------------------|----------|----------|---------|----------|---------------------|---------------------|-----------|---------
ID | UUID                             | NAME                                                                  | TYPE     | CONTRACT | ACCOUNT | SUPPORT  | START DATE          | END DATE            | QUANTITY  | CONSUMED
---|----------------------------------|-----------------------------------------------------------------------|----------|----------|---------|----------|---------------------|---------------------|-----------|---------
6  | 4028fa6e76cea5f00176d47d80ae32e0 | MyProduct                                                             | Physical |          |         |          | 2021/01/05 21:39:23 | 2049/12/01 00:00:00 | Unlimited | 1       
5  | 4028fa6e76cea5f00176d2f1431532ca | Red Hat Enterprise Linux Server, Standard (Physical or Virtual Nodes) | Physical | 12156828 | 941133  | Standard | 2020/03/11 04:00:00 | 2021/03/11 04:59:59 | 1         | 1       
---|----------------------------------|-----------------------------------------------------------------------|----------|----------|---------|----------|---------------------|---------------------|-----------|---------
```

2. Verify the macro works as expected
- clone one of the host report templates
- add a new column to show the macro output -> `host_redhat_subscriptions_consumed(host)`
- see that only the redhat subscriptions are summed up, and custom ones are ignored

### CODE REVIEW

**Comment by jturel** [comment]
@snagoor can you verify that this PR meets your expectations? If so, please close your original PR. Thank you!

**Comment by snagoor** [comment]
Will test this and share my feedback. BTW thank you for working on it.

**Comment by snagoor** [comment]
@jturel :tada: it works flawlessly :thumbsup:. Tested from both rake console and using report template 

~~~
# hammer subscription list --host-id=2
---|----------------------------------|----------------------------------------------------------------------|----------|----------|---------|--------------|---------------------|---------------------|-----------|---------
ID | UUID                             | NAME                                                                 | TYPE     | CONTRACT | ACCOUNT | SUPPORT      | START DATE          | END DATE            | QUANTITY  | CONSUMED
---|----------------------------------|----------------------------------------------------------------------|----------|----------|---------|--------------|---------------------|---------------------|-----------|---------
41 | 8aca03c076d779300176db3c09b03840 | CentOS 8 PowerTools                                                  | Physical |          |         |              | 2021/01/07 05:05:13 | 2049/12/01 00:00:00 | Unlimited | 1       
33 | 8aca03c076d779300176d7824ae23682 | Employee SKU                                                         | Physical | 11977720 | 6038690 | Self-Support | 2019/09/26 04:00:00 | 2022/01/01 04:59:59 | 1         | 1       
30 | 8aca03c076d779300176d7824bcc3687 | Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes) | Physical | 12142726 | 6038690 | Premium      | 2020/02/26 05:00:00 | 2021/02/26 04:59:59 | 3         | 1       
---|----------------------------------|----------------------------------------------------------------------|----------|----------|---------|--------------|---------------------|---------------------|-----------|---------
~~~

Rake console 

~~~
# foreman-rake console
Loading production environment (Rails 6.0.3.1)

irb(main):001:0> host = Host.last
=> #<Host::Managed id: 2, name: "client.example.com", last_compile: "2021-01-07 08:45:08", last_report: nil, updated_at: "2021-01-07 08:45:08", created_at: "2021-01-07 05:12:36", root_pass: nil, architecture_id: 1, operatingsystem_id: 2, environment_id: nil, ptable_id: nil, medium_id: nil, build: false, comment: nil, disk: nil, installed_at: nil, model_id: 1, hostgroup_id: nil, owner_id: 4, owner_type: "User", enabled: true, puppet_ca_proxy_id: nil, managed: false, use_image: nil, image_file: nil, uuid: nil, compute_resource_id: nil, puppet_proxy_id: nil, certname: nil, image_id: nil, organization_id: 1, location_id: 2, type: "Host::Managed", otp: nil, realm_id: nil, compute_profile_id: nil, provision_method: nil, grub_pass: "", discovery_rule_id: nil, global_status: 2, lookup_value_matcher: [FILTERED], openscap_proxy_id: nil, pxe_loader: nil, initiated_at: nil, build_errors: nil>

irb(main):002:0> presenter = ::Katello::HostSubscriptionsPresenter.new(host)
=> #<Katello::HostSubscriptionsPresenter:0x00000000163e8238 @pools={"8aca03c076d779300176db3c09b03840"=>[#<Katello::Pool id: 41, cp_id: "8aca03c076d779300176db3c09b03840", created_at: "2021-01-07 05:05:13", updated_at: "2021-01-07 05:14:40", subscription_id: 12, account_number: nil, contract_number: nil, virtual: nil, quantity: -1, start_date: "2021-01-07 05:05:13", pool_type: "NORMAL", end_date: "2049-12-01 00:00:00", ram: nil, multi_entitlement: nil, consumed: 1, virt_only: false, unmapped_guest: false, virt_who: false, hypervisor_id: nil, stacking_id: nil, organization_id: 1, upstream_pool_id: nil>], "8aca03c076d779300176d7824bcc3687"=>[#<Katello::Pool id: 30, cp_id: "8aca03c076d779300176d7824bcc3687", created_at: "2021-01-06 11:44:05", updated_at: "2021-01-07 05:15:09", subscription_id: 9, account_number: 6038690, contract_number: 12142726, virtual: nil, quantity: 3, start_date: "2020-02-26 05:00:00", pool_type: "NORMAL", end_date: "2021-02-26 04:59:59", ram: nil, multi_entitlement: true, consumed: 1, virt_only: false, unmapped_guest: false, virt_who: false, hypervisor_id: nil, stacking_id: "RH00003", organization_id: 1, upstream_pool_id: "8a85f9997078001801708214636328f0">]}, @subscriptions=[#<Katello::Pool id: 41, cp_id: "8aca03c076d779300176db3c09b03840", created_at: "2021-01-07 05:05:13", updated_at: "2021-01-07 05:14:40", subscription_id: 12, account_number: nil, contract_number: nil, virtual: nil, quantity: -1, start_date: "2021-01-07 05:05:13", pool_type: "NORMAL", end_date: "2049-12-01 00:00:00", ram: nil, multi_entitlement: nil, consumed: 1, virt_only: false, unmapped_guest: false, virt_who: false, hypervisor_id: nil, stacking_id: nil, organization_id: 1, upstream_pool_id: nil>, #<Katello::Pool id: 30, cp_id: "8aca03c076d779300176d7824bcc3687", created_at: "2021-01-06 11:44:05", updated_at: "2021-01-07 05:15:09", subscription_id: 9, account_number: 6038690, contract_number: 12142726, virtual: nil, quantity: 3, start_date: "2020-02-26 05:00:00", pool_type: "NORMAL", end_date: "2021-02-26 04:59:59", ram: nil, multi_entitlement: true, consumed: 1, virt_only: false, unmapped_guest: false, virt_who: false, hypervisor_id: nil, stacking_id: "RH00003", organization_id: 1, upstream_pool_id: "8a85f9997078001801708214636328f0">]>

irb(main):003:0> presenter.subscriptions.select(&:redhat?).sum(&:quantity_consumed)
=> 2

irb(main):004:0> exit
~~~

**Comment by jturel** [comment]
Awesome!! Thank you for confirming and for opening this RFE @snagoor

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Review by jeremylenz — COMMENTED** [review]
When I generate the cloned report template I'm getting an error
```
Safemode doesn't allow to access 'host_redhat_subscriptions_consumed' on #<Safemode::ScopeObject>
```

**Comment by jturel** [comment]
> When I generate the cloned report template I'm getting an error
> 
> ```
> Safemode doesn't allow to access 'host_redhat_subscriptions_consumed' on #<Safemode::ScopeObject>
> ```

Hmm ... try stopping spring and restarting the rails server

**Comment by jeremylenz** [comment]
@jturel thanks, that fixed the error!

The new method works as expected in Rails console:
```
[6] pry(main)> host_subscriptions_names(host)
=> ["Red Hat Developer Subscription", "Custom product"]
[7] pry(main)> include Katello::Concerns::BaseTemplateScopeExtensions
=> Object
[8] pry(main)> host_redhat_subscriptions_consumed(host)
=> 1

```

I added this line to two cloned report templates:
```rb
'Rh consumed': host_redhat_subscriptions_consumed(host),
```

It works as expected on `Host - Statuses clone`:
```yaml
---
- Name: katello-client-2.redhatlaptop.example.com
  Global: 1
  RH Consumed: 1
  Addons: 3
  Build: 0
  Configuration: 0
  Errata: 1
  Role: 3
  Service Level: 3
  Subscription: 0
  System Purpose: 3
  Traces: 0
  Usage: 3
```

But on `Host - Registered Content Hosts clone`, the field is blank:
```yaml
---
- Name: katello-client-2.redhatlaptop.example.com
  Ip: 192.168.122.58
  Operating System: CentOS 7
  Subscriptions:
  - Red Hat Developer Subscription
  - Custom product
  Applicable Errata: 1
  Owner: []
  Kernel: Admin User
  Latest kernel available: 3.10.0-957.12.2.el7.x86_64
  Rh consumed:
```

I'm not sure why yet.. will keep investigating.

**Comment by jeremylenz** [comment]
:see_no_evil: In the template I had added the new field to `report_row` but neglected to add it to `report_headers`.

**Review by jeremylenz — APPROVED** [review]
@jturel thanks for a great addition!

Several hours of confusion on my part led to some inspired learning about Ruby's `SimpleDelegator` and Foreman's report rendering.  After this journey I have come around to the realization that this code works exactly as expected.  (Which, also, is exactly as expected ;)

ACK

**Comment by jturel** [comment]
> 🙈 In the template I had added the new field to `report_row` but neglected to add it to `report_headers`.

Ah! That'll get ya

**Pull request merged**
