### PR TITLE
fixes #18634 - set Nutupane controllerName

### PR DESCRIPTION
**Pull request by thomasmckay**
The controllerName is required for bookmark searches

### CODE REVIEW

**Comment by waldenraines** [comment]
@thomasmckay I don't know much about bookmark searches are there any changes to the API that are needed to support bookmarked search? @cfouant?

**Comment by thomasmckay** [comment]
As long as the controllerName is set then the bookmark searches all work

**Comment by waldenraines** [comment]
Doesn't this also address http://projects.theforeman.org/issues/18577?

Seems like that should maybe be marked as a duplicate.

**Comment by waldenraines** [comment]
> As long as the controllerName is set then the bookmark searches all work

Ah okay, they worked for the ones I tested but wasn't sure if there were some lower level changes needed.

**Pull request merged**
