### PR TITLE
fixes #23737 - fixes incorrect REST API doc for tracer 

### PR DESCRIPTION
**Pull request by snagoor**
fixes incorrect REST API doc for tracer.

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by akofink** [comment]
Needs to update https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-traces.factory.js#L13, right?

**Comment by sean797** [comment]
I think the API should be `traces` the UI has a "Traces" tab. I think the plural version makes a lot more sense.

**Comment by snagoor** [comment]
Thanks @sean797, Modified PR per your suggestion.

**Pull request merged**
