### PR TITLE
[CP] Katello 4.0.1 cherry-picks, changelog update, etc

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
@jjeffers how soon do ya wanna get this in? asking since there are still a number of open issues on 4.0.1 in Redmine. Do you intend to move those to 4.0.2?

Otherwise this PR looks fine *except* two of my 4.0.1 prs for katello-agent got merged in today and I'd love for them to not be bumped to 4.0.2 - do ya mind re-running the cherry picks?

**Comment by jjeffers** [comment]
> @jjeffers how soon do ya wanna get this in? asking since there are still a number of open issues on 4.0.1 in Redmine. Do you intend to move those to 4.0.2?
> 
> Otherwise this PR looks fine _except_ two of my 4.0.1 prs for katello-agent got merged in today and I'd love for them to not be bumped to 4.0.2 - do ya mind re-running the cherry picks?

No problem!

**Comment by jjeffers** [comment]
[test katello]

**Review by jturel — APPROVED** [review]
APJ

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
