### PR TITLE
Fixes #8632 - Redoing docker tables/fields

### PR DESCRIPTION
**Pull request by daviddavis**
Requires https://github.com/theforeman/foreman-docker/pull/50

### CODE REVIEW

**Comment by parthaa** [comment]
I tested out this PR with the latest foreman docker. I am having trouble creating a docker repo. Steps to repro

```
1) Create Product in UI
2) Create a Repository of type docker
```

Error I got

```
undefined local variable or method `docker_repository' for #<Katello::Repository:0x0000000fa21bb0> (NameError)
/home/paji/.rvm/gems/ruby-2.0.0-p598/gems/activemodel-3.2.21/lib/active_model/attribute_methods.rb:407:in `method_missing'
/home/paji/.rvm/gems/ruby-2.0.0-p598/gems/activerecord-3.2.21/lib/active_record/attribute_methods.rb:149:in `method_missing'
/home/paji/centos/projects/katello/app/models/katello/repository.rb:470:in `create_docker_repo'
```

from git grep I do not see any method defining it..

**Comment by daviddavis** [comment]
I just tried and am not getting that error. Moreover, I don't see a create_docker_repo method in repository.rb. Do you maybe have some other changes in your branch/checkout?

**Comment by daviddavis** [comment]
```
❯ http :3000/katello/api/repositories/3/docker_tags -a admin:changeme
HTTP/1.1 200 OK
Apipie-Checksum: 637b51f78a677f785c5d7143111fc1da
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
ETag: "74cb9853582987107fcdd78b47b87e24"
Foreman_api_version: 2
Foreman_version: 1.8.0-develop
Set-Cookie: _session_id=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJTQ2NWY4M2RmYjRlNTYwZGIxN2Q2MTAxM2EwZWZkYzllBjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AEY%3D--135bb76740f22938d5e3dd4bd710d1f1aca921f5; path=/; HttpOnly
Transfer-Encoding: chunked
X-Request-Id: 95f30732dda0cfc5da175d846c30a0de
X-Runtime: 2.333649
X-UA-Compatible: IE=Edge

{
    "page": 1,
    "per_page": 20,
    "results": [
        {
            "id": 19,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
        {
            "id": 18,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
        {
            "id": 17,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
        {
            "id": 16,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
        {
            "id": 15,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
        {
            "id": 14,
            "image": {},
            "repository": {
                "id": 3,
                "name": "redis"
            }
        },
```

**Comment by parthaa** [comment]
@daviddavis 
So you are right about the first one (create_docker_repo no method error).. Sounds like I had a botched update. But on the 2 nd one, I am still having issues. Check this hammer output
```
[hammer-cli-katello{master}]$ hammer docker tag list
---|-----|--------------
ID | TAG | REPOSITORY ID
---|-----|--------------
6  |     |              
5  |     |              
4  |     |              
3  |     |              
2  |     |              
1  |     | 
```

My guess is that the ids are being returned correctly but not the name of the tag.

**Comment by daviddavis** [comment]
@partha, pull the PR and try again.

**Comment by daviddavis** [comment]
[test]

**Pull request merged**
