### PR TITLE
Fixes #9927:  add missing no row messages, BZ 1206611.

### PR DESCRIPTION
**Pull request by waldenraines**
A few of the messages for tables without rows were missing,
this commit adds the messages.

http://projects.theforeman.org/issues/9927
https://bugzilla.redhat.com/show_bug.cgi?id=1206611

### CODE REVIEW

**Comment by waldenraines** [comment]
See also https://github.com/Katello/bastion/pull/58

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
> See also Katello/bastion#58

Make that See also https://github.com/Katello/bastion/pull/59

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
