### PR TITLE
Fixes #16171 - Update to foreman-tasks 0.8.0

### PR DESCRIPTION
**Pull request by daviddavis**
This is needed to fix the pipeline which is currently broken.

### CODE REVIEW

**Comment by stbenjam** [comment]
This should get bumped to 1.13 too: https://github.com/Katello/katello/blob/master/lib/katello/plugin.rb#L2

Seems like we don't really do a good job of updating that in general. Katello's definitely not compatible with foreman 1.9 :open_mouth:

**Comment by daviddavis** [comment]
👍.  updated.

**Comment by stbenjam** [comment]
APJ

**Comment by daviddavis** [comment]
[test]

**Pull request merged**
