### PR TITLE
Fixes #15144 - update dependencies on foreman-tasks

### PR DESCRIPTION
**Pull request by iNecas**
Change 28cb3ef requires https://github.com/theforeman/foreman-tasks\
/commit/22d5999950c15f73dd06c49e88bf7af7eda3e29e

### CODE REVIEW

**Comment by stbenjam** [comment]
Would it be better to reference the original issue 15144 so it's more obvious what introduced the requirement and the two commits would get pulled together in a cherry-pick?

**Comment by iNecas** [comment]
Not really preference here: updated

**Comment by stbenjam** [comment]
APJ

**Comment by beav** [comment]
jenkins should be green after rebasing

**Comment by iNecas** [comment]
jenkins is gren

**Comment by akofink** [comment]
ACK

**Comment by lzap** [comment]
Just for the record, I believe 15144 is wrong ticket number.

**Comment by stbenjam** [comment]
Oh, it's actually 15114

**Pull request merged**
