### PR TITLE
Fixes #25080 - update VCR after digest algorithm change

### PR DESCRIPTION
**Pull request by iNecas**
Requires https://github.com/theforeman/foreman/pull/6098

### CODE REVIEW

**Comment by iNecas** [comment]
Required after https://github.com/theforeman/foreman/pull/6098 gets merged. Will be red before that.

**Comment by iNecas** [comment]
[test katello]

**Comment by iNecas** [comment]
The foreman part got merged, this PR will be needed to get katello tests green. @jlsherrill mind review?

**Comment by iNecas** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Thanks @iNecas !

**Pull request merged**
