### PR TITLE
Fixes #21933 - fix host collection links

### PR DESCRIPTION
**Pull request by ares**
not sure why links are not generated using rails helpers, anyway /actions does not seem to work, host collection show page contains actions list, so this should work

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test default]
[test rails-5]

**Comment by jlsherrill** [comment]
They aren't using rails helpers because these are not rails routes.  Thanks @ares !!

**Comment by ares** [comment]
ok, I understand now, thanks for quick merge

**Pull request merged**
