### PR TITLE
Fixes #14949 - Fail on import upload failures

### PR DESCRIPTION
**Pull request by daviddavis**
Calling import_upload in the API was returning 200 which caused the CLI to report that the upload was successful.

### CODE REVIEW

**Comment by daviddavis** [comment]
I need to do some more investigation since this action is also used by other actions.

**Comment by daviddavis** [comment]
[test]

**Comment by beav** [comment]
@daviddavis I believe JS tests should pass after rebasing

**Comment by daviddavis** [comment]
[test]

**Comment by beav** [comment]
ACK

**Pull request merged**
