### PR TITLE
Fixes #9206: Remove border-radius mixin that was removed in Foreman.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
APJ

**Comment by waldenraines** [comment]
I'll save you some clicking:

```
"#contents #package_filter #product_list .product_entry .collapsed" failed to @extend ".icon-caret-right".
The selector ".icon-caret-right" was not found.
Use "@extend .icon-caret-right !optional" if the extend should be able to fail.
  (in /builddir/build/BUILDROOT/ruby193-rubygem-katello-2.2.0-1.201502031912gitae38cf0.el7.noarch/opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0/app/assets/stylesheets/katello/katello.scss)
/builddir/build/BUILDROOT/ruby193-rubygem-katello-2.2.0-1.201502031912gitae38cf0.el7.noarch/opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0/app/assets/stylesheets/katello/contents.scss:268
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/tree/visitors/extend.rb:65:in `block in check_extends_fired!'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/util/subset_map.rb:106:in `block in each_value'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/util/subset_map.rb:106:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/util/subset_map.rb:106:in `each_value'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/tree/visitors/extend.rb:50:in `check_extends_fired!'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/tree/visitors/extend.rb:16:in `visit'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/tree/root_node.rb:39:in `css_tree'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/tree/root_node.rb:20:in `render'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-3.4.9/lib/sass/engine.rb:268:in `render'
/opt/rh/ruby193/root/usr/share/gems/gems/sass-rails-3.2.5/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/opt/rh/ruby193/root/usr/share/gems/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/context.rb:197:in `block in evaluate'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `evaluate'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:12:in `initialize'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `new'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `block in build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:395:in `circular_call_protection'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:373:in `build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/bundled_asset.rb:16:in `initialize'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:377:in `new'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:377:in `build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/environment.rb:75:in `find_asset'
/opt/rh/ruby193/root/usr/share/gems/gems/actionpack-3.2.8/lib/sprockets/static_compiler.rb:23:in `block in compile'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:341:in `block in each_logical_path'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:324:in `block (2 levels) in each_file'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:314:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:314:in `each_entry'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:322:in `block in each_file'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:321:in `each'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:321:in `each_file'
/opt/rh/ruby193/root/usr/share/gems/gems/sprockets-2.10.1/lib/sprockets/base.rb:335:in `each_logical_path'
/opt/rh/ruby193/root/usr/share/gems/gems/actionpack-3.2.8/lib/sprockets/static_compiler.rb:18:in `compile'
/builddir/build/BUILDROOT/ruby193-rubygem-katello-2.2.0-1.201502031912gitae38cf0.el7.noarch/opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0/lib/katello/tasks/asset_compile.rake:34:in `compile_assets'
/builddir/build/BUILDROOT/ruby193-rubygem-katello-2.2.0-1.201502031912gitae38cf0.el7.noarch/opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0/lib/katello/tasks/asset_compile.rake:76:in `compile_javascript_stylesheets'
/builddir/build/BUILDROOT/ruby193-rubygem-katello-2.2.0-1.201502031912gitae38cf0.el7.noarch/opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0/lib/katello/tasks/asset_compile.rake:81:in `block in <top (required)>'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:205:in `call'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:205:in `block in execute'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `each'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `execute'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:158:in `block in invoke_with_call_chain'
/opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:151:in `invoke_with_call_chain'
/opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:144:in `invoke'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:116:in `invoke_task'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block (2 levels) in top_level'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `each'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block in top_level'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:88:in `top_level'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:66:in `block in run'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
/opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:63:in `run'
/opt/rh/ruby193/root/usr/bin/rake:32:in `<main>'
Tasks: TOP => assets:precompile:katello
```

**Comment by ehelms** [comment]
@waldenraines updated, green now

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
