### PR TITLE
Fixes #17168: remove nutupane from content host pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17168

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/158, https://github.com/Katello/bastion/pull/159 and https://github.com/Katello/bastion/pull/160

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
* the hostnames are bleeding over in the table (see SS1)
 * not sure if this is a symptom of this change, but the browser titles don't change when changing states (e.g. go to Puppet Modules then to Content Host and it still says Puppet Module)
 * the subscriptions table appears off (SS2)
 * Seeing this in the console:
```
TypeError: Cannot read property 'replaceRow' of undefined
    at content-host-details.controller.self.js?body=1:90
    at angular-resource.self.js?body=1:727
    at processQueue (angular.self.js?body=1:15962)
    at angular.self.js?body=1:15978
    at Scope.$eval (angular.self.js?body=1:17230)
    at Scope.$digest (angular.self.js?body=1:17046)
    at Scope.$apply (angular.self.js?body=1:17338)
    at done (angular.self.js?body=1:11573)
    at completeRequest (angular.self.js?body=1:11779)
    at XMLHttpRequest.requestLoaded (angular.self.js?body=1:11712)
```

screenshot from 2017-01-18 16-53-12

screenshot from 2017-01-18 16-58-11

**Comment by waldenraines** [comment]
> the hostnames are bleeding over in the table (see SS1)

This is likely the case on all non-nutupane tables and the change will be required to be in bastion so I opened http://projects.theforeman.org/issues/18158

> not sure if this is a symptom of this change, but the browser titles don't change when changing states (e.g. go to Puppet Modules then to Content Host and it still says Puppet Module)

See http://projects.theforeman.org/issues/18156

> the subscriptions table appears off (SS2)

Fixed.

> Seeing this in the console:

Fixed

**Comment by sean797** [comment]
It not like it in @ehelms image but in mine the Content Hosts name (centos7.example.com) could benefit from being a little bigger imo. My screen is 1920x1080 if that make an difference.

Also sometimes the table headers collapse into one. I can reproduce by:
1. Go to tasks tab
2. ctl+F5 (clean refresh)
3. go to another tab, maybe Traces or Host Collections.
4. go back to tasks.

screenshot from 2017-01-19 19-48-43

**Comment by waldenraines** [comment]
> Also sometimes the table headers collapse into one.

I filed an issue for this as I have seen it outside this PR, see http://projects.theforeman.org/issues/18183

**Pull request merged**
