### PR TITLE
Fixes #17160: remove nutupane from Activation Key pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17160

### CODE REVIEW

**Comment by waldenraines** [comment]
Relies on https://github.com/Katello/bastion/pull/136

**Comment by thomasmckay** [comment]
Issues:
+ the 'new activation key' page still has area for list (though no list is displayed)
+ saving act key gives "Cannot read property 'addRow' of undefined" js error
+ edit act key name gives "Cannot read property 'replaceRow' of undefined" js error

**Comment by waldenraines** [comment]
@thomasmckay fixed issues.

**Comment by thomasmckay** [comment]
ack

**Comment by ehelms** [comment]
The table appears off center from the tabs, the filter box for example being far left almost up against the far edge of the page.

screenshot from 2016-11-22 10-53-58

**Comment by waldenraines** [comment]
> The table appears off center from the tabs

That will be fixed as part of http://projects.theforeman.org/issues/17452

>the filter box for example being far left almost up against the far edge of the page.

Fixed.

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
@waldenraines can you rebase this one?

**Comment by waldenraines** [comment]
> @waldenraines can you rebase this one?

Done.

**Comment by ehelms** [comment]
I am not seeing any subscriptions show up on the Activation Key -> Subscriptions add tab

**Comment by ehelms** [comment]
Hrmm, seems like maybe this is just my environment vs a code change in the branch. Sorry for the noise.

**Pull request merged**
