### PR TITLE
Fixes #20020 - add task to look for unpublished repos

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test, you can run this in the rails console:
```
ForemanTasks.sync_task(::Actions::Pulp::Repository::Sync, :pulp_id => Katello::Repository.find(2).pulp_id, :options => {:auto_publish => false} )

```

That will cause a sync to occur but no publish.  Then simply run the rake task:

```
 rake katello:publish_unpublished_repositories
```

You should see something like:  `[E] Repository metadata for testproduct (2) is out of date, regenerating.`

**Comment by akofink** [comment]
I didn't expect my other repos to be regenerated. Could you explain why this happened?

https://paste.fedoraproject.org/paste/kiV9F1X2anGhiICGLPDvag

**Comment by jlsherrill** [comment]
@bbuckingham @akofink i updated this pr to skip repos that may throw an error (if not pulp for example), if you could take a quick peak, that would be appreciated !

**Comment by akofink** [comment]
Still works as expected. ACK from me!

**Pull request merged**
