### PR TITLE
Fixes #34000 - update deprecated registry name

### PR DESCRIPTION
**Pull request by tbrisker**
`medium_providers` was renamed to `medium_providers_registry`.

### CODE REVIEW

**Comment by tbrisker** [comment]
See https://github.com/theforeman/foreman/pull/8951#discussion_r756094392 for explanation of the failing tests, looks like a mistake was made while deprecating this method that doesn't allow for a clean gradual merge but rather will require breaking katello for an intermediate period until both prs are merged.

**Comment by tbrisker** [comment]
Even better, once https://github.com/theforeman/foreman/pull/8952 is merged this should become green and unblock the deprecation cleanup with no breakage.

**Comment by tbrisker** [comment]
[test katello]

**Review by ezr-ondrej — APPROVED** [review]
Thanks @tbrisker !
I'll give katello maintainers some time to react, but given this is now ready to merge, I'll go ahead and merge the core cleanup regardless of the status here tomorrow.

**Comment by ezr-ondrej** [comment]
This is :green_apple: I'd like to go ahead and merge the core PR as it is quite straighforward PR.

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
