### PR TITLE
Fixes #30884 - Products controller permissions

### PR DESCRIPTION
**Pull request by sjha4**
To test:
1. Create a product with name test_product1
2. Create a user and a role with the Product filter with name = test_product1
3. Impersonate the user and go to products page.
4. You should see the product test_product1 but not test_product2

### CODE REVIEW

**Comment by sjha4** [comment]
Trying to figure out why I am getting a 204 instead on 404 in the test..Works on the API.. :confused:

**Comment by ianballou** [comment]
> Trying to figure out why I am getting a 204 instead on 404 in the test..Works on the API.. confused

Yeah it's working for me too!

**Comment by ianballou** [comment]
There's a rubocop failure alongside the last problematic test.

**Comment by ianballou** [comment]
[test katello]

**Comment by sjha4** [comment]
@parthaa : Need some help with the test here returning 204 instead of 404..

```
404 expected for show, got 204 instead. 
permission -> ---
- :name: :view_products
  :search: name="some_name"
.
Expected: 404
  Actual: 204 (Minitest::Assertion)
/home/jenkins/workspace/katello-pr-test/test/controllers/api/v2/products_controller_test.rb:157
```

**Review by ianballou — APPROVED** [review]
ACK!

**Pull request merged**
