### PR TITLE
Fixes #31802 - Includes All Status in Applied Errata Report.

### PR DESCRIPTION
**Pull request by JaskaranNarula**
Issue: https://projects.theforeman.org/issues/31802

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
Thanks for the PR @JaskaranNarula - someone will review this soon!

**Review by jlsherrill — APPROVED** [review]
ACK, will merge once https://github.com/theforeman/foreman/pull/8378 is merged

**Comment by jlsherrill** [comment]
[test katello]

**Review by ezr-ondrej — APPROVED** [review]
LGTM :+1:

**Pull request merged**
