### PR TITLE
Refs #14971 - Remove RHEL6 support in dev environments

### PR DESCRIPTION
**Pull request by akofink**
This removes some redirection warnings from service to systemctl.

### CODE REVIEW

**Comment by ehelms** [comment]
This will only work on EL7 which I'd be fine with confining our development setup to, however, we should do so more broadly so as not to break or leave loose ends. Would you mind sending a foreman-dev thread about dropping EL6 support for dev environments only to get feedback?

**Comment by stbenjam** [comment]
What's the benefit of changing this? 

If we're refactoring this, I'd probably prefer if we refactored the whole thing to be more idiomatic ruby.  The way it's replacing strings is odd.

And while we're here, I'd also prefer if we were consistent about using `katello-service` (which calls systemd commands if available) by making it available on dev installs

**Comment by ehelms** [comment]
This should probably be 'Refs' given this does not entirely remove EL6 dev support. To finish it, we need to remove the centos6-dev box from katello-deploy.

**Comment by akofink** [comment]
This PR represents a whole discussion/plan we should probably have as a team, so I'm going to go ahead and close this until it becomes more of a priority.

**Pull request closed without merging**
