### PR TITLE
Refs #10970 - Fix provider model to throw exception on dependent destroy

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by cpeters** [comment]
This resolves the following error:

Katello::Provider#test_0001_should be destroyable [/home/vagrant/katello/spec/models/provider_spec.rb:383]:
ActiveRecord::DeleteRestrictionError expected but nothing was raised.

**Comment by johnpmitsch** [comment]
It seems to me that restrict_with_exception would work fine here, but maybe someone from @Katello/katello-core would take a look and double check that

**Comment by daviddavis** [comment]
I'm a bit ambivalent here. On the one hand, it shouldn't really matter as we're deleting models mostly in dynflow and if anything, we should be using `restrict_with_exception` everywhere. However, all our other restricted relationships use `restrict_with_error` and this would be inconsistent.

I'm tempted to say that we should update the test to call `destroy!` for now and then decide whether or not we want to move all our restricted has_many relationships to `restrict_with_exception`.

**Comment by daviddavis** [comment]
Actually, maybe we can open a Redmine issue to examine whether we should/could change restrict_with_error to restrict_with_exception everywhere in our code and then just merge this?

**Comment by johnpmitsch** [comment]
[test]

**Comment by cpeters** [comment]
http://projects.theforeman.org/issues/12526

**Comment by cpeters** [comment]
@daviddavis are you cool with merging this?

**Pull request merged**
