### PR TITLE
Fixes #10857: Ensure DestroyMedium filename and action name are the s…

### PR DESCRIPTION
**Pull request by ehelms**
…ame.

### CODE REVIEW

**Comment by ehelms** [comment]
This is what is currently blocking the pipeline from passing.

**Comment by stbenjam** [comment]
@ehelms RPM scratch build is failing:

`Error: No Package found for ruby193-rubygem-bastion < 2.0.0`

Just a fluke? [test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@stbenjam  It needed a PR from walden to have been merged, re-running now to see if it is fixed.

**Comment by stbenjam** [comment]
This actual change itself looks good so APJ

**Pull request merged**
