### PR TITLE
Fixes #37145 - Ruby 3 support

### PR DESCRIPTION
**Pull request by ofedoren**
#### What are the changes introduced in this pull request?

Updates for kwargs usage across the code base to comply with Ruby 3.0.

Please, review carefully, since there might be a lot of unnecessary changes as well as some breaking changes (such as changing signatures for action planning methods).

#### Considerations taken when implementing this change?

Depends on
 - https://github.com/Katello/katello/pull/10780
 - https://github.com/theforeman/foreman/pull/9989
 - https://github.com/theforeman/foreman-tasks/pull/739 (including Dynflow changes)

#### What are the testing steps for this pull request?

Run CI and hope for the best.

### CODE REVIEW

**Comment by ofedoren** [comment]
Still red... I think it doesn't pull tasks/dynflow from git?..

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
Merge conflicts now, something about rubocop.. :thinking:

**Comment by jeremylenz** [comment]
The 1 React Tests failure is due to https://github.com/patternfly/patternfly-react/issues/10064, unrelated

**Comment by ofedoren** [comment]
Closing in favor of https://github.com/Katello/katello/pull/10885.

**Pull request closed without merging**
