### PR TITLE
Fixes #17369 - fix puppet_path error on capsule sync

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
This was resolved in master via https://github.com/Katello/katello/commit/2824830a0295f3bfad994c91284651e3ead4a0b7#diff-f6aa9601a7c1afa89d06151a45d30777R75

but still seems present in 3.2

**Comment by ehelms** [comment]
Possibility for a regression test?

**Comment by ehelms** [comment]
Oh I totally missed you were opening this up for 3.2

**Comment by johnpmitsch** [comment]
LGTM but haven't tested

**Comment by jlsherrill** [comment]
pinned bastion

**Comment by jlsherrill** [comment]
[test]

**Comment by johnpmitsch** [comment]
ACK with the assumption that the jenkins errors are expected

**Pull request merged**
