### PR TITLE
Fixes #14172 - Mailer: Host Advisory Summary Reports should sort hosts alphabetically

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by stbenjam** [comment]
@ranjan Thanks! A couple of comments:

- Don't reference Satellite in upstream commits, should say Katello or omit it
- I might use `.order('name DESC')` to be more explicit about the field to sort on.  Not sure `sort` will default to using the name.

**Comment by ranjan** [comment]
Thanks for info @stbenjam 
Updated commit message. Default sorting by name is already defined here https://github.com/theforeman/foreman/blob/develop/app/models/host/managed.rb#L223  so sorting on array will sort by name.

**Comment by jlsherrill** [comment]
[test]

**Comment by stbenjam** [comment]
[test]  Looks unrelated to the change

**Comment by ehelms** [comment]
@stbenjam assigned you to finish the review

**Comment by stbenjam** [comment]
Thanks for the reminder, forgot to come back and check on the tests.  Looks good to me, thanks @ranjan.

**Pull request merged**
