### PR TITLE
Fixes #9839: show no rows message if table isn't working BZ 1203851.

### PR DESCRIPTION
**Pull request by waldenraines**
Only show the message about not having any items on a nutupane table
if the table isn't currently working.

http://projects.theforeman.org/issues/9839
https://bugzilla.redhat.com/show_bug.cgi?id=1203851

Requires Katello/bastion#55

### CODE REVIEW

**Comment by jlsherrill** [comment]
would it be possible to implement this logic in nutupane/details_nutupane so anything using that would get the logic automatically?

I know we have a lot of places that don't use details_nutupane that should, but it would be nice for this to be handled automatically if you are

**Comment by waldenraines** [comment]
I suppose we could use an angular-block for the places that use nutupane and details nutupane but we'd still have to specify the message on each page.  Thoughts on that approach?

**Comment by jlsherrill** [comment]
@waldenraines yeah, i'm find with the message specified on each page, i'd just prefer the logic to show it be somewhere else.  Otherwise I think it will get lost

**Comment by waldenraines** [comment]
@jlsherrill updated, see also https://github.com/Katello/bastion/pull/55

**Comment by jlsherrill** [comment]
ACK pending new release of bastion and version requirement bump in the katello.gemspec

**Comment by jlsherrill** [comment]
Nevermind, cherry picked to 0.30
ACK

**Pull request merged**
