### PR TITLE
Fixes #31110 - Run rake reimport as dynflow client

### PR DESCRIPTION
**Pull request by sbernhard**
Thanks to Adam Růžička!

Similar to https://github.com/theforeman/foreman/pull/7871/commits/794746613473787962915788f195e672c1a71192

### CODE REVIEW

**Review by adamruzicka — APPROVED** [review]

**Comment by sbernhard** [comment]
As this affects Katello 3.16, it should be cherry picker to this release branch, too.

**Comment by chris1984** [comment]
@tbrisker starting to review

**Comment by chris1984** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]

**Comment by chris1984** [comment]
APJ

**Comment by chris1984** [comment]
[test katello]

**Review by tbrisker — APPROVED** [review]
Test failures unrelated, merging. @chris1984 and @ianballou please cherry-pick to the stable branches

**Pull request merged**
