### PR TITLE
Katello 3.5.1 cherry picks

### PR DESCRIPTION
**Pull request by akofink**

### CODE REVIEW

**Comment by akofink** [comment]
[test]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
@akofink Ok, I think this ran for real now

**Comment by akofink** [comment]
I had to re-record a VCR cassette.

**Comment by akofink** [comment]
s/FactoryBot/FactoryGirl/ in 6c54a7fa6f538b920c94baa0b8a891401888b283

**Comment by akofink** [comment]
@ehelms rails-5 build passed

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
@akofink The default test is running properly now and throwing a real rubocop error. Up to you how you want to handle it.

**Comment by akofink** [comment]
I disabled the MethodLength cop for that method.

**Comment by akofink** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Pull request merged**
