### PR TITLE
fixes #11447 - improve performance of product and repo index lists

### PR DESCRIPTION
**Pull request by jlsherrill**
alongside https://github.com/theforeman/foreman-tasks/pull/129 this has shown to improve
a particular users product page load from ~10 minutes down to ~4 seconds

### CODE REVIEW

**Comment by ehelms** [comment]
I see one case where it just says `successfully synced repositories` with no number attached in the UI

**Comment by jlsherrill** [comment]
@ehelms any idea on the circumstances to reproduce that?

**Comment by ehelms** [comment]
This is the JSON of the offending product:

```
{  
         "id":1,
         "cp_id":"1434401276379",
         "name":"Katello",
         "label":"Katello",
         "description":null,
         "provider_id":1,
         "sync_plan_id":1,
         "sync_status":{  
            "id":1,
            "product_id":1,
            "progress":{  
               "progress":100.0
            },
            "sync_id":"3447",
            "state":"Sync Incomplete",
            "raw_state":"error",
            "start_time":"12 days ago",
            "finish_time":"12 days ago",
            "duration":"less than a minute",
            "display_size":"Yum Metadata: ('Connection aborted.', gaierror(-2, 'Name or service not known'))",
            "size":"Yum Metadata: ('Connection aborted.', gaierror(-2, 'Name or service not known'))",
            "is_running":false,
            "error_details":{  

            }
         },
         "sync_summary":{  
            "warning":1
         },
         "gpg_key_id":null,
         "redhat":false,
         "sync_state":"Sync Incomplete",
         "last_sync":"2015-08-12 07:23:11 -0400",
         "last_sync_words":"12 days",
         "organization":{  
            "name":"Default Organization",
            "label":"Default_Organization",
            "id":1
         },
         "sync_plan":{  
            "id":1,
            "organization_id":1,
            "name":"My new Sync Plan",
            "description":null,
            "sync_date":"2015-07-28T11:18:00-04:00",
            "interval":"hourly",
            "next_sync":"2015-08-24T15:18:00Z",
            "created_at":"2015-07-13T03:39:48-04:00",
            "updated_at":"2015-07-13T16:30:09-04:00",
            "enabled":true,
            "products":[  
               {  
                  "id":1,
                  "cp_id":"1434401276379",
                  "name":"Katello",
                  "label":"Katello",
                  "description":null,
                  "sync_state":"Sync Incomplete",
                  "last_sync":"2015-08-12 07:23:11 -0400",
                  "last_sync_words":"12 days",
                  "repository_count":49
               }
            ],
            "permissions":{  
               "view_sync_plans":true,
               "edit_sync_plans":true,
               "destroy_sync_plans":true
            }
         },
         "repository_count":1
      },
```

**Comment by jlsherrill** [comment]
@ehelms i believe that is now fixed

**Comment by ehelms** [comment]
In the screenshot, 2 of the products show sync data but no repository counts. Is that expected?

screenshot from 2015-08-24 13 01 33

**Comment by jlsherrill** [comment]
@ehelms could you provide the json for that product?

**Comment by jlsherrill** [comment]
a lot of this is exposing existing issues with the page :)

**Comment by ehelms** [comment]
The JSON should be the same as I posted before -- however I am not seeing my previous comment with the JSON?

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
APJ

**Pull request merged**
