### PR TITLE
Fixes #27661 - stop stripping cars from product name

### PR DESCRIPTION
**Pull request by jlsherrill**
on initial import

### CODE REVIEW

**Comment by chris1984** [comment]
Starting to test

**Comment by chris1984** [comment]
Works great :)

Before:
```bash
[root@centos7-katello-nightly ~]# hammer product list --organization-id 1
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------
ID | NAME                                                                             | DESCRIPTION | ORGANIZATION         | REPOSITORIES | SYNC STATE
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------        
26 | Red Hat Enterprise Linux Server                                                  |             | Default Organization | 0            |                 
29 | Red Hat Satellite                                                                |             | Default Organization | 0            |                   
21 | Red Hat Software Collections Beta for RHEL Server                                |             | Default Organization | 0            |           
16 | Red Hat Software Collections for RHEL Server                                     |             | Default Organization | 0            |           
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------
```
After:
```bash
[root@centos7-katello-nightly ~]# hammer product list --organization-id 1
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------
ID | NAME                                                                             | DESCRIPTION | ORGANIZATION         | REPOSITORIES | SYNC STATE
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------
13 | dotNET on RHEL Beta (for RHEL Server)                                            |             | Default Organization | 0            |           
11 | dotNET on RHEL (for RHEL Server)                                                 |             | Default Organization | 0            |           
36 | JBoss Enterprise Application Platform                                            |             | Default Organization | 0            |           
14 | Oracle Java (for RHEL Server)                                                    |             | Default Organization | 0            |           
18 | Oracle Java (for RHEL Server) - Extended Update Support                          |             | Default Organization | 0            |           
15 | Oracle Java (for RHEL Workstation)                                               |             | Default Organization | 0            |               
9  | Red Hat Enterprise Linux for x86_64                                              |             | Default Organization | 0            |           
44 | Red Hat Enterprise Linux High Availability (for RHEL Server) - Extended Updat... |             | Default Organization | 0            |           
43 | Red Hat Enterprise Linux High Availability for x86_64                            |             | Default Organization | 0            |           
31 | Red Hat Enterprise Linux High Performance Networking (for RHEL Server) - Exte... |             | Default Organization | 0            |           
45 | Red Hat Enterprise Linux Load Balancer (for RHEL Server)                         |             | Default Organization | 0            |           
46 | Red Hat Enterprise Linux Load Balancer (for RHEL Server) - Extended Update Su... |             | Default Organization | 0            |           
10 | Red Hat Enterprise Linux Resilient Storage (for RHEL Server) - Extended Updat... |             | Default Organization | 0            |           
12 | Red Hat Enterprise Linux Scalable File System (for RHEL Server) - Extended Up... |             | Default Organization | 0            |           
26 | Red Hat Enterprise Linux Server                                                  |             | Default Organization | 0            |                    
35 | Red Hat EUCJP Support (for RHEL Server) - Extended Update Support                |             | Default Organization | 0            |                      
29 | Red Hat Satellite                                                                |             | Default Organization | 0            |                    
21 | Red Hat Software Collections Beta (for RHEL Server)                              |             | Default Organization | 0            |           
16 | Red Hat Software Collections (for RHEL Server)                                   |             | Default Organization | 0            |                
---|----------------------------------------------------------------------------------|-------------|----------------------|--------------|-----------
```

**Comment by jturel** [comment]
@chris1984 *just checking* your before and after are switched around, right ?

**Comment by jturel** [comment]
@jlsherrill LGTM - curious why we ever did this? *grabs popcorn*

**Comment by chris1984** [comment]
@jturel yeah After was with the patch applied.

**Comment by jlsherrill** [comment]
@jturel i have no idea:  20e820b013ce401f42eafee95ee217560ce22649 is the commit that added it 

We don't even have 'marketing products' in the products table anymore (we import them into the subscriptions table).  But even then i don't really get why this was required at that time.

**Comment by jturel** [comment]
> @jturel yeah After was with the patch applied.

whoops, ignore me

**Pull request merged**
