### PR TITLE
Fixes #15034 - Remove old script files

### PR DESCRIPTION
**Pull request by daviddavis**
RIP Katello ASCII art

### CODE REVIEW

**Comment by ehelms** [comment]
Want to make this a general "get rid of old scripts" PR and clean out more of that directory?

**Comment by daviddavis** [comment]
Sure. Are any of the scripts there still being used? It looks like they're all really old.

**Comment by ehelms** [comment]
None that I know of

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
Depends on https://github.com/theforeman/foreman-infra/pull/222

**Comment by daviddavis** [comment]
I had to update the jobs in Jenkins as they were still needlessly copying script/ci/katello.yml to config/. Should be good to go now.

**Comment by jlsherrill** [comment]
plz to move ascii art somewhere else?  CONTRIBUTORS?  CONTRIBUTING?

**Comment by daviddavis** [comment]
@jlsherrill moved ascii art to CONTRIBUTING 😄

**Comment by ehelms** [comment]
ACK

**Pull request merged**
