### PR TITLE
Refs #18288 - Add missing Notification dependency

### PR DESCRIPTION
**Pull request by jturel**
@waldenraines This one's for you! Saw some errors in the js console and other odd behavior ... simple fixes.

### CODE REVIEW

**Comment by jturel** [comment]
[test]

**Comment by waldenraines** [comment]
@jturel thanks!  I'm not sure if @ehelms requires a new bug in this case since the code for [#18288](http://projects.theforeman.org/issues/18288) has already been merged.

**Comment by jlsherrill** [comment]
I'm fine including it in the existing issue, since it completes that work.

**Comment by ehelms** [comment]
This has the potential to be missed by our tooling given the originating issue was already marked against a release that has been branched and is being cherry picked.

**Comment by jlsherrill** [comment]
if cherry picks have been done already, would a new issue actually help?   Wouldn't our tooling pick up on the new commit regardless?

**Comment by waldenraines** [comment]
> This has the potential to be missed by our tooling given the originating issue was already marked against a release that has been branched and is being cherry picked.

> if cherry picks have been done already, would a new issue actually help? Wouldn't our tooling pick up on the new commit regardless?

I don't really care either way so I'll let y'all decide before merging this.

**Comment by jturel** [comment]
@jlsherrill @ehelms - shall I open a new issue or not? I personally feel like it shouldn't be necessary but I see valid points above.

**Comment by ehelms** [comment]
You can leave it as is, but, to avoid issues I would generally always recommend 1:1 correspondence of PR to Redmine especially after branching.

**Comment by waldenraines** [comment]
> You can leave it as is, but, to avoid issues I would generally always recommend 1:1 correspondence of PR to Redmine especially after branching.

Let's consider this a test to see what happens if you merge without a new issue 😄

**Pull request merged**
