### PR TITLE
Fixes #34294 - container resync tags test failing on VCR

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
Adds a proper VCR for a new docker limit sync tags test.

#### Considerations taken when implementing this change?
Nope.

#### What are the testing steps for this pull request?
See that the tests pass.

### CODE REVIEW

**Comment by ianballou** [comment]
[test katello]

**Comment by jlsherrill** [comment]
💚💚
[test katello]

**Comment by jlsherrill** [comment]
i just realized this didn't have a code change, what's the cause?

**Comment by ianballou** [comment]
@jlsherrill maybe something merged in that caused my test to need a new VCR, but the test didn't re-run and got merged in in a broken state?

**Comment by ianballou** [comment]
[test katello]

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
