### PR TITLE
Refs #7096 - Fix migration and tests using old model

### PR DESCRIPTION
**Pull request by ares**
parity PR for https://github.com/theforeman/foreman/pull/2405, it should contain viable minimum so that Katello can work with the Foreman change

### CODE REVIEW

**Comment by ares** [comment]
Here's the test with required Foreman PR http://ci.theforeman.org/job/test_katello_core/13354/ merging must be done in the same time.

**Comment by ares** [comment]
Updated run with foreman PR - http://ci.theforeman.org/job/test_katello_core/13411/

**Comment by ares** [comment]
Foreman PR was merged, test with that branch was run here - http://ci.theforeman.org/job/test_katello_core/13555/
re [test] should make this PR green and it should be merged ASAP

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
Manually kicked off the test: http://ci.theforeman.org/view/Katello/job/test_katello_pull_request/6491/

**Comment by stbenjam** [comment]
All green.

Thanks  @ares

**Pull request merged**
