### PR TITLE
Fixes #16728 - do not create installation media

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by bbuckingham** [comment]
Should we have a migration or upgrade task to remove any of the old media?

**Comment by jlsherrill** [comment]
@bbuckingham i considered that, but they don't harm anything being there and I'd rather err on the side of caution.  If a user is using them today we wouldn't want to break re-provisioning of their hosts.

**Comment by bbuckingham** [comment]
ACK

**Comment by stbenjam** [comment]
I was actually using installation media as a hack because the "synced content" wasn't configurable via hammer for a host group.   I fixed that in a PR if one of you have a second to look: https://github.com/Katello/katello/pull/6370

**Pull request merged**
