### PR TITLE
Fixes #32005 - consider /pulp/content for repo profile

### PR DESCRIPTION
**Pull request by jlsherrill**
uploading

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test, you can:

1.  install the bootstrap rpm as you normally would
2. verify that /etc/rhsm/rhsm.conf  has:
```
baseurl = https://HOSTNAME/pulp/content/
```

if it has /pulp/repos, change it to /pulp/content
3.  register the client
4. sync https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/
5. yum install walrus-0.71
6. verify that errata shows up

**Review by ehelms — APPROVED** [review]
Tested this on my nightly EL8 Katello setup and the failing bats test passed. Approving from a functional testing perspective.

**Review by jturel — APPROVED** [review]
Code looks good - simpler too. ACK per Eric's testing

**Comment by jjeffers** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
