### PR TITLE
Fixes #35025 - Use task hooks for capsule sync

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
Use after action hooks to trigger Capsule sync upon publish/promote
#### What are the testing steps for this pull request?
1. Have a smart proxy tied to Library and one more environment.
2. Publish + Promote a CV to Library and the other environment.
3. Notice logs and make sure the Capsule Sync task doesn't create logs with RecordNotFound errors like it does on master.
4. Make sure the capsule sync happens correctly.

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
@adamruzicka : Let me know if it makes sense as far as the use of hooks for triggering the task goes..

**Comment by adamruzicka** [comment]
Makes sense to me.

Just out of curiostiy, which part does raise the `::Katello::Errors::CapsuleCannotBeReached` exception that is rescued at the end of `trigger_capsule_sync`?

**Comment by sjha4** [comment]
> Makes sense to me.
> 
> Just out of curiostiy, which part does raise the `::Katello::Errors::CapsuleCannotBeReached` exception that is rescued at the end of `trigger_capsule_sync`?

The `def` serves as the `begin` in this case. I refactored the code as is to keep that rescue.

**Comment by adamruzicka** [comment]
Well I know that, but I don't see anything in there that would raise such exception.

**Comment by sjha4** [comment]
> Well I know that, but I don't see anything in there that would raise such exception.

That was all I knew about it. 😄  
Went digging a little and it seems we added it here: https://github.com/Katello/katello/pull/6005 
It might be redundant at this point based on refactoring we have done in other code. We also have 
```
def rescue_strategy
    Dynflow::Action::Rescue::Skip if self.state == 'error'
end
```
in the capsule content sync task so I think we should be safe removing the rescue here. I will test a little more.

**Comment by sjha4** [comment]
Updated to remove the unnecessary rescue block as the async task invocation itself doesn't fail for an unreachable proxy.
2 task results, bottom 3 with rescue and top 3 without rescue with same results.

Screenshot from 2022-06-07 10-00-18

**Review by adamruzicka — COMMENTED** [review]
I don't have a katello environment at hand so I can't test it right now, but from code and Dynflow perspective this is good :+1:

**Comment by sjha4** [comment]
[test katello]

**Review by tazhibaevaaliya — APPROVED** [review]
ACK : +1

**Comment by tazhibaevaaliya** [comment]
To test, I've run through all the steps described on the PR by @sjha4. 
On master: able to see "Record not found" error on the logs
On this branch: "Record not found" error is no longer on the logs

**Review by parthaa — APPROVED** [review]
ACK

**Pull request merged**
