### PR TITLE
[CP] 3.8 cherrypicks

### PR DESCRIPTION
**Pull request by sjha4**

### CODE REVIEW

**Comment by sjha4** [comment]
@jturel : Are the errors because of a missing commit? I can't seem to locate where the root cause here..

**Comment by jturel** [comment]
@sjha4 I think we should defer to @johnpmitsch and/or @waldenraines - they can probably pinpoint a missing commit or whatever else the issue might be

**Comment by johnpmitsch** [comment]
My guess is difference in jest versions between [master](https://github.com/Katello/katello/blob/master/package.json#L43) and [@sajha's branch](https://github.com/sjha4/katello/blob/3.8-cherrypicks/package.json#L41). You can try pulling in [this change](https://github.com/Katello/katello/pull/7555) which upgrades jest

**Comment by sjha4** [comment]
@johnpmitsch: Can we move [24336](https://projects.theforeman.org/issues/24336) to 3.8 then?

**Comment by jturel** [comment]
If it fixes the build and since it's testing related I think we can definitely move it to 3.8 :)

**Comment by jturel** [comment]
@sjha4 error is different now - I think that's a good thing. I think you now need https://github.com/Katello/katello/pull/7574 present here

**Comment by sjha4** [comment]
@jturel..getting closer!! @johnpmitsch :+1: for all the React fixes!

**Comment by sjha4** [comment]
The 2 commits fixed the React-UI issue..Pulling them into 3.8.. :fireworks:
Also, do we ignore katello/webpack?

**Comment by ehelms** [comment]
Yes, ignore katello/webpack for now -- looks all good, gonna merge it

**Pull request merged**
