### PR TITLE
Fixes #14909 - CV filters will be searched like CVs.

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by zjhuntin** [comment]
Before this CV filters, would always return filters if given something like an empty name.

**Comment by zjhuntin** [comment]
This will make it so content-view filters index will be more in line with the way most of the APIs indexes return information.

**Comment by zjhuntin** [comment]
To test, try sending a get request looking for content-view filters with the name param is blank. Before you would get all of the filters back, now it should return nothing.

**Comment by daviddavis** [comment]
ACK

**Pull request merged**
