### PR TITLE
Fixes #28096 - add help-text to ignorable content

### PR DESCRIPTION
**Pull request by m-bucher**

### CODE REVIEW

**Comment by quba42** [comment]
This is a nifty little integrated documentation that makes the usage crystal clear. :+1:

**Comment by sjha4** [comment]
This is helpful..Maybe something shorter like `Use Ctrl-click to multi-select/deselect items` makes for easier reading?

**Comment by m-bucher** [comment]
Yes, thanks for the input @sjha4
Changed it.

**Comment by sjha4** [comment]
[test katello]
Jenkins error seems unrelated..

**Pull request merged**
