### PR TITLE
fixes #16331 - content view version - show description in list

### PR DESCRIPTION
**Pull request by bbuckingham**
Updating based upon user feedback to show content view
version descriptions when viewing them on the list.

### CODE REVIEW

**Comment by bbuckingham** [comment]
Below is an example of the UI with the descriptions shown:

content_view_version_descriptions

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
Since there is no limit on this field, shouldn't there be some limit on the UI column display?

**Comment by bbuckingham** [comment]
@jlsherrill, We can.  Suggestions or opinions?   We could limit to N characters or use ellipsis with title for more details...etc.

**Comment by jlsherrill** [comment]
paging Doctor @waldenraines for some UI assistance

**Comment by waldenraines** [comment]
@jlsherrill I tend to prefer just showing what the user entered rather than shortening it.  If a user enters several hundred characters and makes the table unusable then it's somewhat of a Garbage In, Garbage Out situation.

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
