### PR TITLE
Fixes #24255 - Ignore engines directory for jest

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by ehelms** [comment]
[test katello/webpack

**Comment by ehelms** [comment]
[test katello/webpack]

**Comment by waldenraines** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
