### PR TITLE
docker v1 - remove Content -> Docker Tags UI

### PR DESCRIPTION
**Pull request by bbuckingham**
This is the first of a series of PRs that will be coming to the docker_v1_removal branch to remove docker functionality that will not apply when we move to docker v2.

### CODE REVIEW

**Comment by ehelms** [comment]
I will encourage, since a branch is being used, to think about:

 1) Plan to squash the branch into a single commit for master
 2) Ensure every commit going in follows standard formatting for commit messages

I caution thinking about this now, given this ends up in master and we have a tendency when using a collaborative branch to "break" the rules and commits end up in master that don't follow the rules a direct PR to master would have to follow.

**Comment by bbuckingham** [comment]
@ehelms, Totally agree.  Yesterday, we actually talked about using the separate branch as means to allow multiple devs to contribute to the removal and that we could squash before going to master.  

That said, after creating this PR, we have decided to first focus on migrating from v1 to v2 versus the initial recommendation of deleting v1.  So, I am going to leave this PR open for a bit, but we may ultimately close it out as we see how much we can reuse during the migration.

**Comment by ehelms** [comment]
excellent

**Comment by komidore64** [comment]
The workflow I think that would work best for separate branch teamwork would be:

1. Create PRs to the topic branch
2. Manually merge and push to topic branch (to avoid a merge commits)
3. PR finished topic branch into master once topic feature is complete

The advantage to this is that there aren't a million merge commits (like what was present in the rails4 topic branch effort). I dislike the idea of squashing this topic branch into one commit prior to merging into master. Doing so removes credit from all who contributed to this effort, sans the one doing the squashing.

**Comment by ehelms** [comment]
Sounds like a reasonable idea -- if we had a strategy to avoid the merge master into commits that sometimes pile up as well, that be a grand slam.

**Comment by bbuckingham** [comment]
For now, I am going to close out this PR.   Rather than remove this code, I'd like to see if we can reuse/migrate it to the new concepts that are coming with Docker v2.  If we find that it is a total re-write, I will still have these changes in a branch.

**Pull request closed without merging**
