### PR TITLE
[WIP] Fixes #25113 - switching between orgs in subs details page

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by beav** [comment]
[test katello]

**Comment by waldenraines** [comment]
@amirfefer any updates on this?

**Comment by waldenraines** [comment]
@amirfefer do you mind updating this PR please?

**Comment by jturel** [comment]
this needs a rebase :)

**Comment by beav** [comment]
@amirfefer can you take a look at this PR? it has been 2 months since last update.

If you aren't able to get to it in the near future, you can always close it out. As long as the branch isn't deleted from your fork, the PR can be reopened whenever.

**Comment by waldenraines** [comment]
@amirfefer ping

**Comment by waldenraines** [comment]
Closing because the subscriptions page refactoring has made this difficult to rebase.  I will take on this issue and open a new PR.

**Pull request closed without merging**
