### PR TITLE
Fixes #12622 - undefined method candlepin_consumer_info for <Katello::System>

### PR DESCRIPTION
**Pull request by ranjan**
In certain cases rake tasks # foreman-rake katello:reindex throws exception 
```
Re-indexing Katello::System
The following Katello::System items could not be indexed due to various reasons.
Please check /usr/share/foreman/log/reindex.log for more detailed information.
Object: #<Katello::System id: 21, uuid: nil, name: "katello.example.com", description: "Initial Registration Params", location: "None", environment_id: 11, created_at: "2015-07-06 14:31:41", updated_at: "2015-07-06 14:31:41", type: "Katello::System", content_view_id: 12, host_id: nil>
rake aborted!
undefined method `candlepin_consumer_info' for #<Katello::System:0x0000000d4361d0>
```

### CODE REVIEW

**Comment by jlsherrill** [comment]
I don't think this method actually exists at all anymore.  You might change it to:

```
            candlepin_consumer_info = fetch_resource { Resources::Candlepin::Consumer.get(object.uuid) } 
```

**Comment by ehelms** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK, thanks @ranjan !

**Comment by ehelms** [comment]
This PR did not have it's commits squashed when merged -- please be mindful of this in the future.

**Comment by jlsherrill** [comment]
Arg, i swore i check it, but I must have looked at a different PR

**Pull request merged**
