### PR TITLE
fixes #9344 - Actkey description <= 1000 characters, BZ1177158

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by jlsherrill** [comment]
We are using validates_lengths_from_database to validate the lengths, and I am guessing from the bug that we used to limit it to 1000 specifically.  I'm not sure we should limit it and I would probably push back against the bug.  There is no harm in allowing more than 1000 characters and if we change it for activation key, we should probably change it for all the other objects and ensure its done in foreman for all objects too.   It doesn't seem worth it to me.

**Comment by jlsherrill** [comment]
but feel free to keep this pr open until the the bz is either closed or the reporter provides more reasoning behind why it should be limited to 1000

**Comment by daviddavis** [comment]
:+1: from me. I'd probably change the description fields in the database to 1000 chars over modifying the validations everywhere.

**Comment by cfouant** [comment]
Okay, pushed back on the BZ will wait to hear back. Thanks!

**Comment by daviddavis** [comment]
FYI, I noticed that foreman was mixed on this issue (they were using a combination of strings which are limited to 255 chars and text fields which is what we use) but I opened a PR to change them to text fields:

https://github.com/theforeman/foreman/pull/2155

**Comment by cfouant** [comment]
Bug changed to significantly different feature

**Pull request closed without merging**
