### PR TITLE
fixes #23190 - replace .uniq with .distinct

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
@jturel I'm +1 on adding tests but will need to wait a couple weeks

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jturel** [comment]
@thomasmckay couple weeks won't work if we want to include it in 3.7 as indicated by the issue since we are branching on the 19th

**Comment by jlsherrill** [comment]
@jturel i think tom is out for a while (until after the 19th), if we want tests and want to include it in 3.7, we may need to open our own pr with tests

**Comment by jlsherrill** [comment]
Closing in favor of https://github.com/Katello/katello/pull/7308  with test!

**Comment by jlsherrill** [comment]
So that merged the pr and did not close, test is still here: https://github.com/Katello/katello/pull/7308

**Comment by jturel** [comment]
lol :)

**Pull request merged**
