### PR TITLE
Fixes #17163: remove nutupane from errata pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17163

### CODE REVIEW

**Comment by akofink** [comment]
There seems to be an issue with Errata#Show from content hosts bulk actions (content_hosts/bulk-actions/errata/RHBA-2016:2862)

image

**Comment by waldenraines** [comment]
> There seems to be an issue with Errata#Show from content hosts bulk actions (content_hosts/bulk-actions/errata/RHBA-2016:2862)

@akofink good catch, fixed.

**Comment by akofink** [comment]
@waldenraines Here's another place: `content_views/:id/versions`

image

**Comment by akofink** [comment]
Also, when publishing a new content view version:

image

**Comment by waldenraines** [comment]
@akofink I believe those changes to be related to https://github.com/Katello/katello/pull/6520.  Can you see if you get those same issues in master?

**Comment by akofink** [comment]
Ah yes, you're right. Let me continue testing with #6520 included.

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/159 and https://github.com/Katello/bastion/pull/160

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
Clicking an errata on the Errata page results in no transition with:

```
1angular.self.js:13551 Error: Could not resolve 'erratum.info' from state 'errata'
    at Object.transitionTo (angular-ui-router.self.js:3181)
    at Object.go (angular-ui-router.self.js:3109)
    at angular-ui-router.self.js:4160
    at angular.self.js:19158
    at completeOutstandingRequest (angular.self.js:5870)
    at angular.self.js:6146
```

**Comment by waldenraines** [comment]
> Clicking an errata on the Errata page results in no transition with:

Are you sure you have the latest?  I cannot reproduce this on bastion master and waldenraines/17163

**Comment by ehelms** [comment]
Ahh, sorry for the churn, working now.

On the Errata > Details > Repositories page the product link in the table doesn't go anywhere (the repository link works just fine).

**Comment by waldenraines** [comment]
> On the Errata > Details > Repositories page the product link in the table doesn't go anywhere (the repository link works just fine).

Fixed

**Pull request merged**
