### PR TITLE
Fixes #17966 - Change buttons to primary for top level pages

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by waldenraines** [comment]
I replaced all the `.btn-primary` in "New _______" buttons with `.btn-default` specifically because it's only a primary action when you're first setting up or when you are developing katello.  I wouldn't imagine our users are constantly creating new things.  

Maybe @Rohoover has thoughts on this?  Maybe there is some guidance from patternfly on button colors?

**Comment by johnpmitsch** [comment]
@waldenraines The guidelines that were mentioned on the foreman-dev mailing list ("Foreman Button Proposals") were:

> Each page should have one clear call to action, where the primary action button is always blue, but all others are the secondary buttons(gray). There is an accessibility reason being that on enter the primary button should be enacted. It's possible that there could be no primary action button on a page.

I would think the "New ___ " button would be the primary action of our top level pages, I'm not sure how often a user actually uses the primary button factors in here, but curious to hear @Rohoover's thoughts

Looking at a repo page in Github, I see "Clone or Download" is made the primary action (in github's case its green) and that is not my usual reason for vising a repo page.

If we decide we need to make this change, I'll make it for all "New __ " buttons where appropiate

**Comment by waldenraines** [comment]
> Looking at a repo page in Github, I see "Clone or Download" is made the primary action (in github's case its green) and that is not my usual reason for vising a repo page.
> 
> If we decide we need to make this change, I'll make it for all "New __ " buttons where appropiate

Good point and thanks for digging up the guidelines.  I'm find changing them back but as you say above we would need to do so for all pages I have converted to non-nutupane.  

I think part of the reason for me changing them was that in Nutupane we had multiple levels of primary action buttons which was confusing.  Now that we only have one level it will probably look okay.

**Comment by Rohoover** [comment]
@johnpmitsch @waldenraines 

It's possible that something other than "New _____" would be the primary action depending on what a users primary task may be. 

Based on the screen John sent me, your implementation of a primary button creating a New Product looks correct.

It should draw the users eye to the top level action on the page. And the patternfly primary blue is the correct color.

**Comment by johnpmitsch** [comment]
@waldenraines @Rohoover thanks all, I'll go through the list and make the change where necessary (double checking there is only one primary action per page)

**Comment by johnpmitsch** [comment]
@waldenraines updated

**Comment by waldenraines** [comment]
@johnpmitsch looks good.  I will go back and update my open PRs to use `.btn-primary` as well.

**Pull request merged**
