### PR TITLE
Fixes #22705 - ImporterRegistry to be used for initialization

### PR DESCRIPTION
**Pull request by rahulbajaj0509**

### CODE REVIEW

**Comment by rahulbajaj0509** [comment]
related to pr : https://github.com/theforeman/foreman/pull/5010

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by beav** [comment]
@rahulbajaj0509 it looks like https://github.com/theforeman/foreman/pull/5010 is still being worked on, can you take a look at that PR? Once it's merged, we can remove the "blocked by another PR" label and re-review this one.

**Comment by beav** [comment]
no worries, thanks!

**Comment by jturel** [comment]
[test katello]

**Comment by rahulbajaj0509** [comment]
something seems to be weird with this branch, closing this pr and creating a new one.

**Pull request closed without merging**
