### PR TITLE
fixes #24024 - increases default bulk_load_size for pulp

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by beav** [comment]
200 looks good to me :rabbit2: . Did it fall over at higher numbers?

**Comment by cfouant** [comment]
@beav @jlsherrill - thought I'd posted results, I'll get them up here. I found that it did fail starting around 250 and the savings between 200 and 250 weren't great. It seemed to double the speed, which is good, but not as great as I'd liked.

**Comment by jlsherrill** [comment]
@cfouant when it failed, how did it fail exactly?  What was the error?

**Comment by beav** [comment]
@jlsherrill @cfouant 2000 seems fine to me, and 6m is a major improvement over 20+.

**Comment by cfouant** [comment]
@beav - well, it's just this step that takes 6m, not the entire sync process - but this does take the index content step down from about 10 min to 6!

**Pull request merged**
