### PR TITLE
Fixes #22306 - Don't pass AC::Params into actions

### PR DESCRIPTION
**Pull request by jturel**
Rails 5 stuff. I don't think we should be passing ActionController::Params beyond controllers since they don't provide a superset of the Hash API.

### CODE REVIEW

**Comment by thomasmckay** [comment]
fixes _hammer repository upload-content_ param errors

**Comment by adamruzicka** [comment]
Looks good to me, however the tests are not happy about this change.

**Comment by danseethaler** [comment]
@jturel ah perfect - thanks.

**Comment by jturel** [comment]
[test]

**Comment by jturel** [comment]
I don't think the failure in default build is related..

**Comment by jturel** [comment]
@jlsherrill any thoughts on this before I merge?

**Comment by jlsherrill** [comment]
[test default]

**Comment by jlsherrill** [comment]
APJ from me too!

**Comment by jlsherrill** [comment]
[test default]

**Pull request merged**
