### PR TITLE
Fixes #32943 - Appropriately update module stream actions

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by parthaa** [comment]
Steps to Test
 
1. Register a centos8 / rhel8 client
2. Navigate `All Hosts ->  <host> -> Module Streams`
3. Select a module action on one of the modules

Before PR:
```
leads to "Oops, we're sorry but something went wrong 783: unexpected token at ''"

2021-07-06T11:54:29 [I|app|972c4a96] Started POST "/katello/remote_execution" for XXX at 2021-07-06 11:54:29 +0200
2021-07-06T11:54:29 [I|app|972c4a96] Processing by Katello::RemoteExecutionController#create as HTML
2021-07-06T11:54:29 [I|app|972c4a96] Parameters: {"remote_action"=>"module_stream_action", "module_stream_action"=>"enable", "module_spec"=>"ant:1.10", "bulk_host_ids"=>"", "customize"=>"", "authenticity_token"=>"XXX"}
2021-07-06T11:54:29 [W|app|972c4a96] 783: unexpected token at ''
2021-07-06T11:54:29 [I|app|972c4a96] Backtrace for '783: unexpected token at ''' error (JSON::ParserError): 783: unexpected token at ''
972c4a96 | /usr/share/ruby/json/common.rb:156:in `parse'
```

After PR:
Takes you to the job invocation page correctly.

**Comment by parthaa** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK, works good

**Comment by jlsherrill** [comment]
merging as github check seems stuck?

**Pull request merged**
