### PR TITLE
[CP] Updates, cherry-picks, etc, for 3.13.1

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jturel** [comment]
nice! any merge conflicts encountered?

**Comment by jjeffers** [comment]
> nice! any merge conflicts encountered?

Yes, there was a merge conflict in 1 cherry-pick, and another 3 in subsequent cherry-picks. I omitted the later ones until I better understand the conflicts.

**Comment by jjeffers** [comment]
@jturel The remaining CP I have not included was https://github.com/Katello/katello/commit/07265e019def1b48771b4726d544dd9c01bd7b6b

It looks like it depends on a prior commit that was for pulp3 features. I'm not sure if that's sufficient cause to pull that commit in just for this CP. Let me know what you think.

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
From the katello side this looks good. I think there should be a few hammer-cli-katello picks as well according to the 3.13.1 redmine release. Will merge this one when the build goes green though!

**Pull request merged**
