### PR TITLE
Fixes #19119 - Refresh host collection nutupane after changes

### PR DESCRIPTION
**Pull request by johnpmitsch**
This shows the proper hosts in the list/add pages in host
collections

### CODE REVIEW

**Comment by jlsherrill** [comment]
hrmm, this solution seems like its just masking an issue in bastion.  we also use searchTransform in other places in the app, i'm guessing they are all broken?

**Comment by johnpmitsch** [comment]
@jlsherrill let me check if the other searchTransform's have refreshes afterwards

**Comment by johnpmitsch** [comment]
maybe @waldenraines can comment if a `refresh()` is expected after modifying any functions of a Nutupane instance.

**Comment by waldenraines** [comment]
> maybe @waldenraines can comment if a refresh() is expected after modifying any functions of a Nutupane instance.

Yes, if you want to see any changes displayed then you need to `refresh()`.

**Comment by johnpmitsch** [comment]
[test]

**Pull request merged**
