### PR TITLE
[CP] 4.4.0 GA cherry-picks

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
Cherry-picks for Katello 4.4.0 GA, version bump, and CHANGELOG update.

#### Considerations taken when implementing this change?
I had to remove 
```javascript
import SortableColumnHeaders from '../../../../Table/components/SortableColumnHeaders';
``` 
from a couple places when cherry-picking in 34320 because it was introduced by some other PR not in the 4.4 branch.

#### What are the testing steps for this pull request?
Ensure the tests pass.

### CODE REVIEW

**Comment by jeremylenz** [comment]
For the lint error about HostCollectionsCard, it's probably safe to remove that import. The card was added in https://github.com/Katello/katello/pull/9990, targeted to 4.5.

**Comment by jeremylenz** [comment]
```
Test suite failed to run

    Cannot find module '../../hostDetailsHelpers' from 'PackagesTab.js'
```

`PackagesTab.js` was moved to its own folder recently; I think it should pass if you just add another `../`

**Comment by ianballou** [comment]
@jeremylenz looking at the current errors, I'm wondering if another host-details-related PR needs to be pulled in.

**Comment by jeremylenz** [comment]
https://github.com/Katello/katello/pull/9982 perhaps?

**Review by jeremylenz — APPROVED** [review]
clicked around, nothing seems broken!

ACK :+1:

**Comment by jeremylenz** [comment]
Remember to rebase and merge ;)

**Pull request merged**
