### PR TITLE
Fixes #25135 - use i18n from webpack

### PR DESCRIPTION
**Pull request by amirfefer**
i18n (jed) is moving to webpack in [foreman](https://github.com/theforeman/foreman/pull/5342)

`__()`, `sprintf()` and other functions should be imported

### CODE REVIEW

**Comment by waldenraines** [comment]
Relevant foreman PR: https://github.com/theforeman/foreman/pull/5342

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
@amirfefer this has some linting failures.

**Comment by amirfefer** [comment]
@waldenraines - test failures + linting has been fixed

**Pull request merged**
