### PR TITLE
Fixes #21697 - restrict cvv delete if part of composite cvv

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test:

1.  Create a regular content view, add a repo and publish it
2.  Create a composite content view, add the version from step 1) to the composite and publish it
3.  Remove the version from the actual composite view (but the version will still be published with it)
4.  Attempt to delete the version you created in 1)

**Comment by parthaa** [comment]
Wondering if you should add something here to disable if the version belongs to Composite
remove version 2 0

More over have you thought about the Org Delete scenario. Don't see us destroying composites before deleting content view versions

**Comment by jlsherrill** [comment]
@parthaa good point on org delete, i will check that case.  I think the warning at that stage is okay, there about 3 cases where error on deletion at this stage.

**Comment by parthaa** [comment]
I am going to APJ. I tested org delete with the following scenario and it looked ok
```
hammer organization create --name=CoolOrg
hammer content-view create --name=componentCV --organization=CoolOrg
hammer content-view create --composite --name=compositeCV --organization=CoolOrg
hammer content-view publish --name=componentCV --organization=CoolOrg
hammer content-view component add --composite-content-view=compositeCV --component-content-view=componentCV --organization=CoolOrg --latest
hammer content-view publish --name=compositeCV --organization=CoolOrg
hammer organization delete --name=CoolOrg
```

**Comment by parthaa** [comment]
APJ

**Comment by jlsherrill** [comment]
ahh yeah, i realized the org delete is handled https://github.com/Katello/katello/blob/master/app/models/katello/content_view_version.rb#L311

**Comment by parthaa** [comment]
ACK

**Pull request merged**
