### PR TITLE
Fixes #5325 - adds search favorites and bookmarks

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
Requires https://github.com/Katello/bastion/pull/81

**Comment by cfouant** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK pending new bastion release after https://github.com/Katello/bastion/pull/81 is merged

**Comment by ehelms** [comment]
Going to merge this as bastion-2.1.0 has been released

**Pull request merged**
