### PR TITLE
Fixes #9796: fix translations for subscription loading screens.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/9796

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Pull request merged**
