### PR TITLE
Fixes #24577 - Use EmptyState component from the Foreman

### PR DESCRIPTION
**Pull request by tstrachota**
The `EmptyState` mock is a workaround to make sure tests are running until we create a proper foreman npm package. I wanted to keep at least the `EmptyState`'s props in snapshots.

### CODE REVIEW

**Comment by tstrachota** [comment]
[test]

**Comment by beav** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by tstrachota** [comment]
This is no longer blocked. https://github.com/theforeman/foreman/pull/5968 has been merged into the Foreman.

**Comment by tstrachota** [comment]
@waldenraines may I ask you to test & review this one?

**Pull request merged**
