### PR TITLE
Fixes #34697 - update to Pulpcore 3.17

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?

Updates bindings and VCRs to use Pulpcore 3.17

#### Considerations taken when implementing this change?

The bindings need to be updated first in packaging before merging

#### What are the testing steps for this pull request?
Do the tests all pass?

### CODE REVIEW

**Comment by sjha4** [comment]
Sorry about the conflicts.. 😁 
The test failure could be related..Rerunning the tests..

**Comment by sjha4** [comment]
[test katello]

**Comment by ianballou** [comment]
VCRs may need to  be re-recorded due to changes in pulp_rpm_client 3.17.5

**Comment by ianballou** [comment]
I can't try pulp_rpm_client 3.17.5 and rerecord the VCRs until pulp_deb gets a new release. The required versions of faraday are conflicting.

**Review by sjha4 — APPROVED** [review]

**Pull request merged**
