### PR TITLE
fixes #22951 - support docker v2 api

### PR DESCRIPTION
**Pull request by thomasmckay**
This feature is not enabled unless the following is in _config/settings.plugins.d/katello.yml_
```
:katello:
   :registry:
     :url: https://devel.example.com:5000
     :ca_cert_file: /etc/pki/katello/certs/katello-default-ca.crt
```

To test, create a docker repository. The source url and upstream name can be garbage values since this is just a placeholder repo to push new images to. In my example I made a repo with label "builds" in org with label "examplecorp". Some commands I ran during devel are below.

To test permission scoping, users must have personal access token permissions (view_personal_access_tokens, create_personal_access_tokens, revoke_personal_access_tokens). Limiting the user to a specific lifecycle environment will also reduce their scope of search and pulling images.

```

sudo yum install -y skopeo

# Copy an image from remote registry to foreman
skopeo copy --dest-creds admin:changeme docker://registry-1.docker.io/alpine:latest docker://devel.example.com/examplecorp-builds-alpine:latest

# Get image info
skopeo inspect --creds admin:changeme docker://devel.example.com/examplecorp-builds-alpine

# Copy image from foreman to local docker daemon
sudo skopeo copy --src-creds admin:changeme docker://devel.example.com/examplecorp-builds-alpine:latest docker-daemon:pulled-alpine:latest

# Copy image from foreman to foreman
sudo skopeo copy --src-creds admin:changeme --dest-creds admin:changeme docker://devel.example.com/examplecorp-builds-alpine:latest docker://devel.example.com/examplecorp-builds-alpine:pushed

# Docker commands
docker login -u admin -p changeme devel.example.com
docker search devel.example.com/builds

```

### CODE REVIEW

**Comment by thomasmckay** [comment]
@parthaa @jlsherrill @JacobCallahan - This is ready for testing and code review. The docker push functionality will continue to be a find-and-fix effort but it's time to get more users involved in the "find" part of that. There is an upcoming pulp feature that will greatly simplify the push logic https://pulp.plan.io/issues/3497 .

If you find issues with push let me know tooling version (either docker or skopeo) as well as the image used so I can repro and work on. Let's not hold up the PR for failed pushes, though.

**Comment by thomasmckay** [comment]
test failure incoming

**Comment by thomasmckay** [comment]
Should I skip the katello.yaml conf and go with existing server values?

https://github.com/Katello/katello/blob/master/app/models/katello/glue/pulp/repo.rb#L206

Maybe the cert is also a value already I can use?

**Comment by thomasmckay** [comment]
@parthaa @jlsherrill - ack?

**Comment by parthaa** [comment]
@thomasmckay few things worked well and few didnt.

The following worked great

```
$ docker login -u admin -p changeme  alpha.partello.example.com```
Login Succeeded

$ skopeo copy --dest-creds admin:changeme docker://docker.io/busybox:latest docker://alpha.partello.example.com/default_organization-aaa-kd
Getting image source signatures
Copying blob sha256:07a152489297fc2bca20be96fab3527ceac5668328a30fd543a160cd689ee548
 706.20 KB / 706.20 KB [====================================================] 1s
Copying config sha256:8c811b4aec35f259572d0f79207bc0678df4c736eeec50bc9fec37ed936a472a
 1.46 KB / 1.46 KB [========================================================] 1s
Writing manifest to image destination
Storing signatures

$ hammer repository info --id=6
ID:                        6
Name:                      kd
Label:                     kd
Organization:              Default Organization
.....
Published At:              alpha.partello.example.com:5000/default_organization-aaa-kd
Relative Path:             default_organization-aaa-kd
Container Repository Name: default_organization-aaa-kd
Product:                   
    ID:   1
......
Content Counts:            
    Container Image Manifest Lists: 0
    Container Image Manifests:      1
    Container Image Tags:           1

$ docker search alpha.partello.example.com/default_organization-aaa-kd
INDEX         NAME                                                     DESCRIPTION   STARS     OFFICIAL   AUTOMATED
example.com   alpha.partello.example.com/default_organization-aaa-kd                 0                    
```

What did not work well for me
```
$ docker pull alpha.partello.example.com/default_organization-aaa-kd
Using default tag: latest
Trying to pull repository alpha.partello.example.com/default_organization-aaa-kd ... 
error parsing HTTP 404 response body: no error details found in HTTP response body: "{\"message\":\"sha256:b0528a860667c51e50a835570d6e30a7eac3443cd8b209b2f024abf5e6020e43\"}"

$ docker login -u admin -p changeme  alpha.partello.example.com
Login Succeeded

$ docker tag docker.io/busybox alpha.partello.example.com/default_organization-aaa-kd
$ docker push alpha.partello.example.com/default_organization-aaa-kd
The push refers to a repository [alpha.partello.example.com/default_organization-aaa-kd]
432b65032b94: Pushing [==================================================>]  1.36 MB

just waits for ever.....
```

Were the pull and push expected to work? I am ok acking this if you can create issues for push and pull specifically. 

One last suggestion. Can you remove the use of  ```pulp_docker_registry_port``` https://github.com/Katello/katello/blob/961148c07b550096bd8ec9b57dd5b3cc5a8bbed3/app/models/katello/glue/pulp/repo.rb#L206 and https://github.com/Katello/katello/blob/961148c07b550096bd8ec9b57dd5b3cc5a8bbed3/app/models/katello/glue/pulp/repo.rb#L785
I am guessing if docker pull direct will work, there is no need for the port. 
Optionally you can add this to the above "pull" issue you might create.

Nice work!.

**Comment by parthaa** [comment]
ack

**Pull request merged**
