### PR TITLE
refs #19056 - include port in candlepin uri

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@akofink that is actually still okay:

```
irb(main):004:0> URI("https://foobar").port
=> 443
```

**Comment by akofink** [comment]
Sorry, I meant "neither a scheme nor a port".

```
URI("centos7-devel.akofink-desktop/candlepin").port
=> nil
```

**Comment by stbenjam** [comment]
I don't think that'd have ever worked, and it'd probably never happen with the installer anyway:

https://github.com/theforeman/puppet-katello/blob/master/manifests/params.pp#L63

**Comment by akofink** [comment]
I was just trying to say how it *could* break. :) Not that it's a likely scenario. Even if a user changed their config outside the installer, they'd probably have bigger problems. (still APJ'd)

**Comment by stbenjam** [comment]
[test katello]

**Pull request merged**
