### PR TITLE
[WIP] - Move bastion_katello to webpack

### PR DESCRIPTION
**Pull request by johnpmitsch**
We have been using the rails asset pipeline for handing the angular part of our application. This made sense in the pre-webpack/rails 3 days, but since then we have added webpack to handle managing javascript.

This commit moves the angular code to be handled by the webpack server rather than the rails asset pipeline. This is helpful for two reasons:
- It appears to be significantly faster in a development environment
- The majority of our javascript code would be handled by webpack.

I'm not sure how this affects how we manage production assets or there are implications to this change that I am missing. Please comment if you have any concerns

### CODE REVIEW

**Comment by johnpmitsch** [comment]
To test this, you should only have to restart the dev server, but let me know if you hit any strange errors

**Comment by johnpmitsch** [comment]
we would probably move the react part of `webpack/` to `webpack/react_app` or something similar, but this is currently for demonstrative purposes

**Comment by ehelms** [comment]
A few questions jump out at me right away:

 * Can this be done without moving all this code into the /webpack directory? Can you just add another load path to webpack config?
 * This doesn't handle any assets coming from bastion itself correct? So it's kind a mix of loading between rails asset pipeline and webpack for Angular pages?
 * Is this intended for dev only or are you also wanting to move production handling of Angular assets to webpack?

**Comment by johnpmitsch** [comment]
@ehelms 
> * Can this be done without moving all this code into the /webpack directory? Can you just add another load path to webpack config?

My understanding of this is the [rails assets pipeline uses `app/assets/`](https://guides.rubyonrails.org/asset_pipeline.html#how-to-use-the-asset-pipeline), and the [webpack-rails gem uses `webpack/`](https://github.com/mipearson/webpack-rails)

To keep the code in the same folder, we would have to exclude `app/assets/bastion_katello` from the assets pipeline and include it in wepback (maybe by way of webpack-rails?). It may be possible to do both of these things, I have to look into it to say for sure.

> * This doesn't handle any assets coming from bastion itself correct? So it's kind a mix of loading between rails asset pipeline and webpack for Angular pages?

No, this doesn't handle bastion assets, I'm guessing bastion is using the rails assets pipeline as its using `app/assets/javascripts` folder structure. I'm open to bastion assets moving to webpack as well, but the biggest performance gain seems to be from moving `bastion_katello`. To answer your question, it seems yes, its a mix of both. So far I haven't seen any problems in the order that the scripts are loaded.

> * Is this intended for dev only or are you also wanting to move production handling of Angular assets to webpack?

I have no idea :) What do you think is best?

**Comment by johnpmitsch** [comment]
> > * Can this be done without moving all this code into the /webpack directory? Can you just add another load path to webpack config?
> 
> My understanding of this is the [rails assets pipeline uses `app/assets/`](https://guides.rubyonrails.org/asset_pipeline.html#how-to-use-the-asset-pipeline) (I guess it looks inside engines as well), and the [webpack-rails gem uses `webpack/`](https://github.com/mipearson/webpack-rails).

@ehelms Looks like we are using `webpack/` in the plugin directories here to create the entry point for the webpack config https://github.com/theforeman/foreman/blob/develop/script/plugin_webpack_directories.rb#L28

**Comment by jlsherrill** [comment]
Would a symlink work to make bastion_katello appear in /webpack?

**Comment by waldenraines** [comment]
> * Can this be done without moving all this code into the /webpack directory? Can you just add another load path to webpack config?

+1 to this.  But I'm also okay with how it is in this PR because at least it's separated into a subdirectory within `webpack/`

> No, this doesn't handle bastion assets, I'm guessing bastion is using the rails assets pipeline as its using `app/assets/javascripts` folder structure. I'm open to bastion assets moving to webpack as well, but the biggest performance gain seems to be from moving `bastion_katello`. To answer your question, it seems yes, its a mix of both. So far I haven't seen any problems in the order that the scripts are loaded.

I would be a big supporter of moving bastion into webpack and then removing bastion as a dependency.  Any idea how difficult of a task this would be?

**Comment by johnpmitsch** [comment]
@jlsherrill possibly, but we have to make sure that 

> I would be a big supporter of moving bastion into webpack and then removing bastion as a dependency. Any idea how difficult of a task this would be?

I can look into it, it doesn't seem hard from a code change perspective, but I can't speak for packaging

**Comment by johnpmitsch** [comment]
> Would a symlink work to make bastion_katello appear in /webpack?

probably, but then we would have tell the rails asset pipeline to ignore the current location as well. IMO we should try to avoid a symlink, but I'm not ruling out anything yet :)

Let me ask this - what are the arguments against moving bastion_katello to webpack? Is it because it complicates cherry-picks, releases, etc..?

**Comment by jlsherrill** [comment]
@johnpmitsch yeah it makes cherry picks very difficult, causes any open Prs that touch any of those files to require a rebase (not super critical),  and makes tracking history more difficult.    I'm not 100% against moving all the files, but we should try to avoid it if its easy, doesn't complicate our lives, and won't end up being a support nightmare down the road IMO

**Comment by johnpmitsch** [comment]
> @johnpmitsch yeah it makes cherry picks very difficult, causes any open Prs that touch any of those files to require a rebase (not super critical), and makes tracking history more difficult. I'm not 100% against moving all the files, but we should try to avoid it if its easy, doesn't complicate our lives, and won't end up being a support nightmare down the road IMO

That is fair, I'm looking into if we can keep everything in engines/bastion_katello. I'm ramping up on webpack configs and foreman's management of webpack for plugins, I'll try to reach out to those who know more about this and see if they have any ideas as well.

**Comment by akofink** [comment]
@johnpmitsch I think it'd be wise to consult Foreman about this. Don't they also have this same problem? It seems to me that they also have assets split between Rails asset pipeline and webpack, don't they? What's stopping us from moving everything to webpack (turning off Rails asset pipeline completely)? I'm not making suggestions, just asking questions. :)

**Comment by johnpmitsch** [comment]
@akofink I think the difference is they don't use angular, so the javascript that is associated with erb templates makes sense to keep in the rails asset pipeline. (This is just my guess, I could be wrong) I can check with them to be sure, thanks for suggesting

**Comment by johnpmitsch** [comment]
Some updates on this PR from an off-thread discussion

- In general, we would like to move all (or the vast majority) of our JS code to webpack, both in development in production.
- This will take time, especially moving production assets, so we would like to make smaller incremental changes. The first step is trying to get the dev environment to load JS with webpack, but keep production using the rails asset pipeline. This is most likely what the scope of this PR will become.
- I'm currently trying to figure out a way to do this without moving the actual `engines/bastion_katello` directory.

**Comment by beav** [comment]
[test katello]

looks like this needs a rebase too

**Comment by johnpmitsch** [comment]
There is still tentative plans on moving bastion_katello to webpack, but its going to require more changes than this. I'm closing this PR for now

**Pull request closed without merging**
