### PR TITLE
Fixes #26385 - Expand the gemspec

### PR DESCRIPTION
**Pull request by ekohl**
This removes two warnings on gem build.

### CODE REVIEW

**Comment by ehelms** [comment]
[test katello]

**Comment by ekohl** [comment]
Updated to also set it in package.json and created an issue.

**Comment by ehelms** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Thanks @ekohl

**Pull request merged**
