### PR TITLE
Fixes #24411: List module_streams in an environment

### PR DESCRIPTION
**Pull request by akofink**
Adds the UI for listing module streams in an environment.

Content -> Lifecycle Environments -> Select Environment (i.e. Library) -> Module Streams tab

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
@akofink : looks really good 

**Scenario's Passed:**

1. Module stream tab is shown in Life Cycle Environment.
2. Module Stream tab-> Search, Filters works as expected depends on a content view's for life cycle. 
3. Module Stream tab does not show modules if life cycle environment does not have a content view.
4. Adding and Deleting content view, get updated the filters in the module streams tab in Life Cycle environment.

**Issue:**
1. One Small issue of listing duplicate options in the filter

issue_1

**Comment by akofink** [comment]
The issue is because those repos that look like duplicates are actually different repositories with the same name, published in different content views. This issue is not caused by this PR, as you can see with the other content types (i.e. Packages); I think it's caused by https://github.com/Katello/katello/pull/7641.

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
I've reported [this issue](https://projects.theforeman.org/issues/25034) to address the duplicate repositories in the drop down.

**Pull request merged**
