### PR TITLE
[CP] 3.11 cherry-picks

### PR DESCRIPTION
**Pull request by jturel**
These didn't make RC1 but since https://github.com/Katello/katello/pull/7930 is required for RC1 they may make it after all. This can stay open until #7930 is merged and picked here.

### CODE REVIEW

**Comment by jturel** [comment]
@jlsherrill please take a look at the build output here. Asset precompile is failing .. is that expected for whatever reason? It appears it's related to your recent foreman change

**Comment by jlsherrill** [comment]
Fixed here: https://github.com/theforeman/foreman/pull/6429

**Comment by ehelms** [comment]
[test katello]

**Comment by jturel** [comment]
Not going to pass b/c https://github.com/theforeman/foreman/commit/92a0079a93c5552f8fb4d18aa7cd23984149a48e has not arrived on 1.12-stable

**Comment by ehelms** [comment]
[test katello]

**Comment by jturel** [comment]
It's green!!

**Pull request merged**
