### PR TITLE
Fixes #36489 - Change the field id of activation key field

### PR DESCRIPTION
**Pull request by girijaasoni**
The field id was named incorrectly, it was reg_katello_ak but it can't include "katello" in it.

### CODE REVIEW

**Comment by jeremylenz** [comment]
[test katello]

**Comment by girijaasoni** [comment]
[test katello]

**Comment by stejskalleos** [comment]
[test katello]

**Review by stejskalleos — APPROVED** [review]
:green_apple: **LGTM**

**Comment by stejskalleos** [comment]
@jeremylenz can we merge? It's blocking some of the QA automation jobs.

**Review by jeremylenz — APPROVED** [review]

**Pull request merged**
