### PR TITLE
Fixes #18897: add filtering to host subscriptions.

### PR DESCRIPTION
**Pull request by waldenraines**
Add support for the ability to filter subscriptions for hosts when
adding subscriptions.

http://projects.theforeman.org/issues/18897

### CODE REVIEW

**Comment by jlsherrill** [comment]
The UI bits look fine, seeing some rails issues though (auto complete is broken, clicking 'products not covered' throws an error.  I can open up a 2nd PR if you prefer, but this seems to fix it:

```
diff --git a/app/controllers/katello/api/v2/subscriptions_controller.rb b/app/controllers/katello/api/v2/subscriptions_controller.rb
index 604dab6..23b3370 100644
--- a/app/controllers/katello/api/v2/subscriptions_controller.rb
+++ b/app/controllers/katello/api/v2/subscriptions_controller.rb
@@ -3,7 +3,7 @@ module Katello
     include Katello::Concerns::FilteredAutoCompleteSearch
 
     before_action :find_activation_key
-    before_action :find_host, :only => :index
+    before_action :find_host, :only => [:index, :auto_complete_search]
     before_action :find_optional_organization, :only => [:index, :available, :show]
     before_action :find_organization, :only => [:upload, :delete_manifest,
                                                 :refresh_manifest, :manifest_history]
diff --git a/app/services/katello/candlepin/consumer.rb b/app/services/katello/candlepin/consumer.rb
index 93f5473..fe332a3 100644
--- a/app/services/katello/candlepin/consumer.rb
+++ b/app/services/katello/candlepin/consumer.rb
@@ -67,8 +67,8 @@ module Katello
           pools = pools.select do |pool|
             pool['providedProducts'].all? do |provided_product|
               self.entitlements.all? do |consumed_entitlement|
-                consumed_entitlement.providedProducts.all? do |consumed_product|
-                  consumed_product.cp_id != provided_product['productId']
+                consumed_entitlement['pool']['providedProducts'].all? do |consumed_product|
+                  consumed_product['cp_id'] != provided_product['productId']
                 end
               end
             end
```

**Comment by waldenraines** [comment]
> The UI bits look fine, seeing some rails issues though (auto complete is broken, clicking 'products not covered' throws an error. I can open up a 2nd PR if you prefer, but this seems to fix it:

I will try to add this patch but if tests fail I am reverting it 😄

**Comment by waldenraines** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
I don't fully understand the current test failure, and can't reproduce it locally

**Comment by waldenraines** [comment]
> I don't fully understand the current test failure, and can't reproduce it locally

Yeah, me either.  I just tried rebasing from master (as this was a little behind) to see if that helps.  :crossed_fingers:

**Comment by waldenraines** [comment]
> Yeah, me either. I just tried rebasing from master (as this was a little behind) to see if that helps.

No such luck.  Any ideas?

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
