### PR TITLE
re-enable recursive content view package filters

### PR DESCRIPTION
**Pull request by roysjosh**
fixes #12440

### CODE REVIEW

**Comment by roysjosh** [comment]
This should maybe revert d0efffd also.

**Comment by jlsherrill** [comment]
@roysjosh what was the performance like when turning it back on?

**Comment by roysjosh** [comment]
@jlsherrill A 30K RPM RHEL6 CV slowed from ~9m to ~18m.  A 32K RPM RHEL7 CV slowed from ~7m to ~14m.  Seems to be doubling the time.  Something to discuss, I'm sure.

**Comment by jlsherrill** [comment]
@roysjosh yeah, i'm hesitant to turn this on by default with that big of a performance penalty. 

Couple of thoughts on how to enhance it:

a)  Add setting to turn it on or off globally
b)  Add a UI and API option to enable dep solving at publish time for an individual publish
c)  Add an attribute on content views to dictate whether dep solving is performed when publishing
d)  both a) and b) where the setting sets the default value for b)

I think i'd be okay with c) or d), probably leaning towards c)

**Comment by ehelms** [comment]
@roysjosh @jlsherrill  any plan for this change?

**Comment by roysjosh** [comment]
I haven't had time to look into this yet.  Even with my change here, pulp doesn't recursively pull in deps that don't match name for name Requires to Provides.  I'm fixing that now, actually.

**Comment by bbuckingham** [comment]
@roysjosh, Hi!  Any updates on this one?  Were you able to resolve the issue you mentioned regarding Requires to Provides?  Any thoughts on updating for @jlsherrill's comment regarding introducing more configurability in to it?

I am quite interested in seeing this feature/capability move forward.  If you do not have time, I may be interested in cloning the PR and adding to it, if that is Ok.

**Comment by roysjosh** [comment]
I have some WIP for this.  I'll see if I can push it up this week.

**Comment by ehelms** [comment]
@roysjosh any updates for this? 

@jlsherrill @bbuckingham any opinion on what we do with this PR? I'd prefer not to keep it open if we aren't going to address it.

**Comment by roysjosh** [comment]
Ah, sorry.  I haven't had the time at work to make any progress on this.  I'll leave it to you what you want to do with this PR.

**Comment by jlsherrill** [comment]
I'm okay with closing

**Pull request closed without merging**
