### PR TITLE
Fixes #26716 - stop using pulp3 publishers

### PR DESCRIPTION
**Pull request by jlsherrill**
pulp3 no longer is emphasizing publishers and instead
is enhancing the publication endpoint to take all options.
Thus publishers really aren't useful for us any longer

### CODE REVIEW

**Comment by sjha4** [comment]
Changes look good to me..Works well with a version old gem but there's an issue with creating publication in the latest gem which should probably be fixed next monday..

Error message on publication create with latest gem:
```
Error message: the server returns an error
14:23:53 rails.1   |  | HTTP status code: 400
14:23:53 rails.1   |  | Response headers: {"Server"=>"nginx/1.12.1", "Date"=>"Fri, 17 May 2019 14:23:53 GMT", "Content-Type"=>"application/json", "Content-Length"=>"33", "Connection"=>"keep-alive", "Vary"=>"Accept, Cookie", "Allow"=>"GET, POST, HEAD, OPTIONS", "X-Frame-Options"=>"SAMEORIGIN"}
14:23:53 rails.1   |  | Response body: {"manifest":["Unexpected field"]} (PulpFileClient::ApiError)
```

**Comment by sjha4** [comment]
[test katello]

**Comment by jlsherrill** [comment]
re-recorded cassettes with latest pulp gems

**Comment by jlsherrill** [comment]
the correct ci run is here: https://ci.theforeman.org/blue/organizations/jenkins/katello-pr-test/detail/katello-pr-test/502/pipeline/

lets go ahead and merge this.  Ci is accidentally updating all prs from a different job, should be fixed here: https://github.com/theforeman/foreman-infra/pull/1060

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
