### PR TITLE
Fixes #32660 - adds an authentication token for SLES repositories

### PR DESCRIPTION
**Pull request by jjeffers**
This PR adds an explicit auth token field to support remote URLs that happen to have query parameters, but are interpreted as SLES auth tokens. Currently any query params are considered to be auth tokens, even when this is not the case.

### CODE REVIEW

**Comment by jjeffers** [comment]
[test katello]

**Comment by jlsherrill** [comment]
+1 to the overall strategy, i wonder if we should encrypt it like we do the upstream_password in root_repository?

**Comment by jjeffers** [comment]
> +1 to the overall strategy, i wonder if we should encrypt it like we do the upstream_password in root_repository?

I was wondering the same thing. I don't know how sensitive the auth token is, but based on what I've read, the SLES provisioning seems to be similar to a protected value, like an API key.

**Comment by jjeffers** [comment]
> > +1 to the overall strategy, i wonder if we should encrypt it like we do the upstream_password in root_repository?


I am also not sure about the tip text on repository creation. Is there a better way to explain the new field?

**Comment by jjeffers** [comment]
@m-bucher I noticed back last year you helped @jlsherrill with testing SLES authentication tokens in Katello. This PR modifies how those tokens are specified (we make it more explicit on repo creation, etc). I don't have a SLES account to test this with, so I am wondering if you can help with that?

**Review by ianballou — COMMENTED** [review]
I tried syncing http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock and Pulp errored out with "An invalid remote URL was provided: http://mirrorlist.centos.org/".

~Looking on the remote, it was shortened to http://mirrorlist.centos.org/.  I'm guessing we still need those query params there?  Without this PR, the repo syncs fine.~

Edit:  This doesn't make sense to me, but I cannot sync the repo unless there is "sles_auth_token": "release=7&arch=x86_64&repo=os&infra=stock on the remote.

**Comment by ianballou** [comment]
Also @jjeffers do you have a starting place for testing out the new "Upstream Authentication Token" field?

**Review by ianballou — COMMENTED** [review]
It appears that the download policy field has disappeared from the new repo creation page.

**Comment by m-bucher** [comment]
> I don't have a SLES account to test this with, so I am wondering if you can help with that?

@jjeffers, sorry, I missed this :sweat_smile: 

I just tested this and it worked with an SCC-Token.

We will have to make changes for this in https://github.com/ATIX-AG/foreman_scc_manager as well, so please open an issue there, too.

**Comment by jjeffers** [comment]
> Also @jjeffers do you have a starting place for testing out the new "Upstream Authentication Token" field?

I can send you an auth token, but keep it secret, keep it safe!

**Comment by jjeffers** [comment]
> It appears that the download policy field has disappeared from the new repo creation page.

I noticed I omitted a `div`, should be corrected now.

**Comment by ianballou** [comment]
I noticed that you get an error if you include the question mark at the beginning of the upstream auth token. Should we be removing those for people?

**Comment by jjeffers** [comment]
> I noticed that you get an error if you include the question mark at the beginning of the upstream auth token. Should we be removing those for people? I'm not sure if it should be obvious or not that the `?` shouldn't be there, but I can see people making that mistake.

AFAIK you should not include the query parameter delimeter (`?`). Perhaps we should change the help text or provide an example?

**Comment by ianballou** [comment]
> AFAIK you should not include the query parameter delimeter (`?`). Perhaps we should change the help text or provide an example?

We're probably fine then.

**Review by ianballou — APPROVED** [review]
This is working fine for me! Code looks fine too. Just need a fix for the master test issue.

**Comment by jjeffers** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
