### PR TITLE
Fixes #32882 - consider pulp3 for download policy

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by vsedmik** [comment]
Patch tested downstream on Sat 6.10.0 snap 5 (katello-4.1.0-0.6.rc2.el7sat.noarch) - the download policy is back and configurable. :+1:

**Review by chris1984 — APPROVED** [review]
ACK, works for me i can see the policy back

**Review by chris1984 — COMMENTED** [review]
Do we have unit tests for this?

**Comment by jlsherrill** [comment]
We don't really have tests for templates, thanks for the review!

**Pull request merged**
