### PR TITLE
Fixes #12091 - Disable length checks for procedural classes and methods

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by ehelms** [comment]
I agree on the database migrations, but I am less convinced on 'actions'. Those can be complex, multi-branch pieces of code that I wouldn't want to get complex by us relaxing certain rubocop requirements.

**Comment by daviddavis** [comment]
@ehelms we are already relaxing the restrictions already by adding rubocop disables to methods that are over the limit. Are you saying we shouldn't do this either?

**Comment by ehelms** [comment]
There are going to be some exceptions to the rules at times, I just don't like the idea of a blanket exception to a class of code unless it makes sense. Since I don't recall the ones from the `actions` section I can't recall why they would have gotten through that test.

**Comment by daviddavis** [comment]
The one thing I would prefer to avoid is disabling these checks capriciously. If there's some reason here (like you say) as to whether or not to disable a length check for a method, then that's fine. Looking through the git history though, not sure if I can infer what that is...?

Also, pinging @jlsherrill since he added all but one action rubocop disable here.

**Comment by jlsherrill** [comment]
Having worked on a lot of these tasks, splitting them into methods tends to make them harder to read and I think ends up introducing more issues.  

Not to say that none of the code can be refactored into other methods, but keeping all the action planning in a single method makes it easier to see what exactly is going on.

**Comment by ehelms** [comment]
I agree in general. The addition of a length check, should, as reviewers cause us to pause and ask whether or not there is too much being piled on. Are there methods and logic that could be moved out into another method? Are there too many steps being handled by this single action? The answer won't always be yes, but disabling the check for all of actions category won't remind us to think about and check that when reviewing in my opinion.

**Comment by daviddavis** [comment]
What about if we disable the check but keep an out for method complexity in katello actions when reviewing PRs? Would that be an option?

**Comment by ehelms** [comment]
Assuming the missing word was `eye` -- which I am reluctant to agree to because it requires remembering on the reviewers part versus an automated check that flags a failure. I realize we are bike-shedding a bit here; historically, things checked by automated tooling has had more impact from my experience.

**Comment by daviddavis** [comment]
Fair enough. I'm not happy with this solution as I think we'll be adding more disables to our actions over to time but I'll go along with it. Closing.

**Pull request closed without merging**
