### PR TITLE
Refs #22909 - use correct messaging format

### PR DESCRIPTION
**Pull request by jturel**
I've seen issues with interpolation and gettext in the past, for example, when variable names change. This will keep things working.

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by ehelms** [comment]
[test katello]

**Comment by jturel** [comment]
@ehelms is this PR cursed?

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@jlsherrill you good with me merging? tests didn't seem to get run here now, but the action tests are good for me locally

**Pull request merged**
