### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by jlsherrill** [comment]
ACK

**Comment by thomasmckay** [comment]
@jlsherrill Merge even w/ the javascript errors? The core failures will be fixed by my PR.

**Comment by jlsherrill** [comment]
@thomasmckay the javascript errors are a transient failure.  Since the host_unification branch has no  js changes so i'm certain there isn't an actual issue.  But feel free to re-test if you'd like!

**Comment by thomasmckay** [comment]
[test]

**Pull request merged**
