### PR TITLE
Fixes #9908 - install passenger so installer doesn't have to

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by ehelms** [comment]
I hate to say this, but I feel like this should be up to Foreman because Katello doesn't care or do anything with the application server.

**Comment by jmontleon** [comment]
Foreman doesn't require passenger to run. You don't need to run foreman-installer to set up foreman either, though I guess it might be encouraged. Even if you do you can change foreman-passenger to false.

They also provide documentation for using nginx+passenger, etc.
http://projects.theforeman.org/projects/foreman/wiki/Setting_up_Nginx_+_Passenger_

So I don't think this is likely to end up on foreman.

**Comment by ehelms** [comment]
Wouldn't the same be true of Katello? We only piggy-back off of what Foreman setups up web-server and application server wise. I see the goal, I just feel like we are doing this due to other concerns. I suppose, if anything, we would put this requirement on the installer.

**Comment by jmontleon** [comment]
I agree, and to be honest, I'm not sure where else it would go. katello-installer in addition to showing foreman-passenger also has katello-use-passenger so installer requires it no more than katello itself. I'm not sure it really belongs anywhere - this is originating from the downstream BZ, where I guess some other arguments can be added, but it doesn't really make sense in either from a packaging standpoint.

**Comment by ehelms** [comment]
@jlsherrill thoughts on the above?

**Comment by jlsherrill** [comment]
I'm quite torn about this.  We should probably ask ourselves:

* Do we (katello) support running with things other than passenger? (i'm gonna say no)?
* Will we in the future?

Even the foreman instructions seem to imply you install foreman first and then switch to  nginx, so it may not be an issue to require passenger?

**Comment by ehelms** [comment]
One thought I had, is that if we are going to do this, doing it on the installer means the Capsules also benefit from this since puppet runs under passenger.

**Comment by ehelms** [comment]
I'd like to propose closing this issue. I still believe this is outside Katello's responsibility.

**Comment by ehelms** [comment]
Packaging has been moved to katello-packaging and given this has had no further activity I am closing for now.

**Pull request closed without merging**
