### PR TITLE
Fixes #13943 - Disable synchronize button when no repos selected

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ehelms** [comment]
Needs rebase after merging your previous fix

**Comment by jlsherrill** [comment]
Clicking select all/deselect all doesn't seem to affect the button being enabled or disabled.

**Comment by adamruzicka** [comment]
@jlsherrill fixed

**Comment by jlsherrill** [comment]
ACK thanks @adamruzicka !

**Pull request merged**
