### PR TITLE
Fixes #25744 - do not seed org in test env

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
requires https://github.com/theforeman/foreman-infra/pull/892

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by beav** [comment]
:christmas_island: 

:christmas_tree: 

:santa:

**Comment by jlsherrill** [comment]
[test katello]

**Comment by beav** [comment]
@jlsherrill 

```

Katello::ContentViewComponentTest#test_latest_versions = 0.55 s = E
Error:
Katello::ContentViewComponentTest#test_latest_versions:
ActiveRecord::RecordInvalid: Validation failed: Minor , must be unique to major and version id version.
    test/factories/disable_auditing.rb:13:in `block (3 levels) in <top (required)>'
    test/factories/disable_auditing.rb:13:in `block (2 levels) in <top (required)>'
    /var/lib/workspace/workspace/katello-pr-test/test/models/content_view_component_test.rb:125:in `test_latest_versions'
```

I'm not sure if this is affected by the change or not

**Comment by jlsherrill** [comment]
[test katello]

transient error!

**Pull request merged**
