### PR TITLE
fixes #11125 - display any error messages in toast on manifest import

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by beav** [comment]
rubocop errors should be fixed by rebasing once https://github.com/Katello/katello/pull/6086 is merged

**Comment by komidore64** [comment]
rebased

**Comment by beav** [comment]
@komidore64 you may have rebased a wee bit early, try again now

**Comment by komidore64** [comment]
rebase 2.0

**Comment by daviddavis** [comment]
🍞

**Comment by jlsherrill** [comment]
So these errors are already being sent to the browser in the humanized['errors'] structure.  Any reason to not just fix the UI to use that?

Otherwise it looks like:

blah


```
[
   {
      "search_params":{
         "type":"task",
         "task_id":"5add40a4-b3b8-4470-8935-b53e941d9b15",
         "search_id":"3"
      },
      "results":[
         {
            "id":"5add40a4-b3b8-4470-8935-b53e941d9b15",
            "label":"Actions::Katello::Provider::ManifestImport",
            "pending":false,
            "username":"admin",
            "started_at":"2016-06-01T09:52:44.000-04:00",
            "ended_at":"2016-06-01T09:52:44.000-04:00",
            "state":"stopped",
            "result":"warning",
            "progress":1,
            "input":{
               "provider":{
                  "id":2,
                  "name":"Red Hat"
               },
               "organization":{
                  "id":1,
                  "name":"Default Organization",
                  "label":"Default_Organization"
               },
               "path":"/home/vagrant/git/foreman/tmp/import_4bdfb1033f897c510f3d.zip",
               "force":null,
               "remote_user":"admin",
               "remote_cp_user":"admin",
               "locale":"en"
            },
            "output":{

            },
            "humanized":{
               "action":"Import Manifest",
               "input":[
                  [
                     "organization",
                     {
                        "text":"organization 'Default Organization'",
                        "link":"/organizations/1/edit"
                     }
                  ]
               ],
               "output":"",
               "errors":[
                  "Import is older than existing data\nOwner has already imported from another subscription management application."
               ]
            },
            "cli_example":null
         }
      ]
   }
]
```

**Comment by komidore64** [comment]
Main reason was that I'm more comfortable altering Ruby as opposed to JS haha! I can change the [javascript](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/subscriptions/manifest/manifest-import.controller.js#L65-L74) if that is preferred.

**Comment by komidore64** [comment]
@jlsherrill updated.

**Comment by beav** [comment]
works as advertised, ACK

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
