### PR TITLE
Fixes #30409 - Require Remote Execution

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jturel** [comment]
we need a packaging pr too right?

**Comment by jlsherrill** [comment]
we do! although it looks like there is a react failure, ping @johnpmitsch !

**Comment by jlsherrill** [comment]
But to clarify for something simple like this, usually we merge the gemspec change and then open a packaging pr

**Comment by johnpmitsch** [comment]
> we do! although it looks like there is a react failure, ping @johnpmitsch !
Since we hit this [here](https://github.com/Katello/katello/pull/8813) too, I opened up a PR to address this everywhere https://github.com/Katello/katello/pull/8838

I believe the `waitFor` function should be the end of the road for the timeouts, its the only ones I've seen recently, we've increased the jest one and the  *knocks on wood*

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
