### PR TITLE
fixes #16867 - update args to find_or_create_host

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by thomasmckay** [comment]
[test]

**Comment by daviddavis** [comment]
FYI, there's a rubocop failure on your PR but HoundCI doesn't catch it since it only checks lines that you've changed. You need to remove line 72 to fix this.

**Comment by thomasmckay** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
