### PR TITLE
CP - cherrypick 26447

### PR DESCRIPTION
**Pull request by sjha4**
This is CP PR for https://github.com/Katello/katello/pull/8045

### CODE REVIEW

**Comment by sjha4** [comment]
We probably need to cherry-pick https://github.com/Katello/katello/pull/8038 to resolve jenkins errors on 3.11. I remember seeing these failures upstream on PRs and these were resolved by this PR. However, I do not have much context around the same.

**Comment by jturel** [comment]
@sjha4 👍  pick it over to this branch and let's see what happens

**Comment by jturel** [comment]
one thing - I think the commit message should match master but the pr can be called whatever

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
Re-recorded cassettes and manually addign change from 06457a8024e7500c1644a30873c0d0012f3f39f2 since the other commit (Part of squash commit) is hopefully not needed.

**Comment by jturel** [comment]
This should have been two separate commits - one to pick over the the ostree PR, and another for the test fixes. Now this won't pick cleanly into the 3.10 branch :-/

**Pull request merged**
