### PR TITLE
Refs #25300 - Update Rubocop config to 0.59.x

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by beav** [comment]
@jlsherrill this looks OK to me, but I'm not sure why this stanza from https://github.com/Katello/katello/pull/7789/files is not needed:

```yml
rubocop:
  config_file: .rubocop.yml
  version: 0.59.2
```

Is it pulling the rubocop config from elsewhere in your PR?

**Comment by jlsherrill** [comment]
@beav we don't use hound_ci anymore.  I considered removing the entire file, and maybe i should just go ahead and do that.

**Comment by beav** [comment]
@jlsherrill I'm happy with the PR as it stands now if the robots are happy :robot:

**Comment by jlsherrill** [comment]
@beav enabled 2 cops that seemed trivial

**Comment by beav** [comment]
@jlsherrill mildly unhappy rubocop

```
/var/lib/workspace/workspace/katello-pr-test/Gemfile:1:1: C: Naming/FileName: The name of this source file (Gemfile) should use snake_case.

source 'https://rubygems.org'

^

/var/lib/workspace/workspace/katello-pr-test/engines/bastion_katello/Rakefile:1:1: C: Naming/FileName: The name of this source file (Rakefile) should use snake_case.

spec = Gem::Specification.find_by_name("bastion")

^



```

**Comment by jlsherrill** [comment]
@beav updated

**Comment by beav** [comment]
@jlsherrill rubocop is green, APJ!

:robot:

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
asset compile timed out :(  rerunning

**Comment by jlsherrill** [comment]
@beav all green, i need an actual approval though :)

**Pull request merged**
