### PR TITLE
Fixes #19371 - Hammer and API ignores noncomposite boolean value

### PR DESCRIPTION
**Pull request by anandkumaragrawal**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by anandkumaragrawal** [comment]
Test case failure seems to be irrelevant of my changes.

**Comment by jlsherrill** [comment]
Correct, it was a transient failure that is now resolved

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK, merging  Thanks @anandkumaragrawal for the patience while we fixed the unit test error in master! and thanks for this PR!

**Pull request merged**
