### PR TITLE
Fixes #10227: remove tipsy to fix tooltip issues, BZ 1213556.

### PR DESCRIPTION
**Pull request by waldenraines**
There was a conflict between tipsy and bootstrap 3's tooltip
library which caused tooltips to be displayed incorrectly.  This
commit fixes the issue by removing the tipsy library and its uses.

http://projects.theforeman.org/issues/10227
https://bugzilla.redhat.com/show_bug.cgi?id=1213556

### CODE REVIEW

**Comment by waldenraines** [comment]
While removing tipsy I uncovered a couple of neat features that had went missing under the cruft.  There were several info icons on the content search page that were not being displayed so I brought those back.  Also, at the bottom of the weird tooltip/flyout thing for packages there were links to display the package files and the package changelog.  Not sure if we want to keep the latter but I left them in there just in case.

**Comment by ehelms** [comment]
Is all of the deletions need to fix the tipsy issue? If not, I'd prefer two separate commits to reduce the impact and risk of each.

**Comment by waldenraines** [comment]
> Is all of the deletions need to fix the tipsy issue? If not, I'd prefer two separate commits to reduce the impact and risk of each.

It was either delete unused files or fix the references of tipsy in unused files.

**Comment by ehelms** [comment]
On the content search page with these updates, I see the letter "i" being used in some places, and the question mark with a circle around it being used in other places. Also, when I click on a tooltip next to a package name it appear well off to the right, and if I then click on another one they start stacking on top of each other and never go away. Even if I collapse the package list and re-expand it, the tooltip is still there.

**Comment by waldenraines** [comment]
> On the content search page with these updates, I see the letter "i" being used in some places, and the question mark with a circle around it being used in other places.

Do you have a preference between the two?  I prefer the circle with the question mark myself.

> Also, when I click on a tooltip next to a package name it appear well off to the right, and if I then click on another one they start stacking on top of each other and never go away. Even if I collapse the package list and re-expand it, the tooltip is still there.

Will fix.

**Comment by ehelms** [comment]
I tend to prefer the same, and I think we use that in other places as well.

**Comment by waldenraines** [comment]
@ehelms updated.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
