### PR TITLE
Fixes #24926 - update react to 16.4

### PR DESCRIPTION
**Pull request by amirfefer**
foreman has been updated to 16.4 - https://github.com/theforeman/foreman/pull/6012

### CODE REVIEW

**Comment by amirfefer** [comment]
rebaesd.
@waldenraines  could you have a look on it?

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Comment by waldenraines** [comment]
[test katello]

**Pull request merged**
