### PR TITLE
Fixes #33394 - Correctly indexes file units on import

### PR DESCRIPTION
**Pull request by parthaa**
Before;
When importing a version with file repos, the indexing operation didn't
do a full index but rather just indexed via id in library.
It showed incorrect counts with respect to the number of files in the
version etc.

After'
When importing a version with file repos, the indexing operation
does a full index.
File counts are accurately reflected in the versions page

### CODE REVIEW

**Comment by parthaa** [comment]
To test this;

- Export a content view version with file repos

On master
- `rake katello:reset`
- Create a new org
- Import from the dump to the new org.
- Go to the content view versions page in the new org
- Notice that no file units are listed in the version.

Checkout PR
- `rake katello:reset`
- Create a new org
- Import from the dump to the new org.
- Go to the content view versions page in the new org
- Notice that file units are correctly listed in the version.

**Comment by parthaa** [comment]
[test katello]

**Comment by jturel** [comment]
Works well! I'm a little confused by `import_for_repository` as I'm seeing different method signatures:

```
app/lib/actions/katello/repository/filtered_index_content.rb:            ::Katello::DockerManifest.import_for_repository(repo)
app/lib/actions/katello/repository/filtered_index_content.rb:            ::Katello::DockerTag.import_for_repository(repo)
app/lib/actions/katello/repository/filtered_index_content.rb:            ::Katello::DockerManifestList.import_for_repository(repo)
app/lib/actions/katello/repository/filtered_index_content.rb:            ::Katello::FileUnit.import_for_repository(repo)
app/lib/actions/katello/repository/filtered_index_content.rb:              type.model_class.import_for_repository(repo, type.content_type)
app/lib/actions/katello/repository/index_errata.rb:          ::Katello::Erratum.import_for_repository(repo)
app/lib/actions/katello/repository/index_module_streams.rb:          ::Katello::ModuleStream.import_for_repository(repo)
app/lib/actions/katello/repository/index_package_groups.rb:          ::Katello::PackageGroup.import_for_repository(repo)
app/models/katello/concerns/pulp_database_unit.rb:      def import_for_repository(repository, generic_content_type = nil, full_index: false)
app/models/katello/docker_tag.rb:    def self.import_for_repository(repository, options = {})
app/models/katello/repository.rb:              type.model_class.import_for_repository(self, type.content_type, full_index: full_index)
app/models/katello/repository.rb:              type.model_class.import_for_repository(self, full_index: full_index)
app/models/katello/yum_metadata_file.rb:    def self.import_for_repository(repository, options = {})
```

See that some have (repo, options) and others have (repo, generic_content_type, options) are these just two different methods with the same name?

**Comment by parthaa** [comment]
> Works well! I'm a little confused by `import_for_repository` as I'm seeing different method signatures:

Good call. I am going to make `generic_content_type` an option instead of a parameter.

**Comment by parthaa** [comment]
> Good call. I am going to make `generic_content_type` an option instead of a parameter.

check my latest commit

**Pull request merged**
