### PR TITLE
Fixes #35323 - CV Version Compare - add view by different/same

### PR DESCRIPTION
**Pull request by tazhibaevaaliya**
#### What are the changes introduced in this pull request?
Added the functionality for the dropdown for viewing by "Different/Same/All" for the content types comparison
#### What are the testing steps for this pull request?
**"View by Different"**
1. Select two versions to compare
2. Hit "Compare" button
3. Select "Different" in the dropdown "View by" 
4. Check that all the tabs show the content which is in either of the versions but not both 

**"View by Same"**
1. Select two versions to compare
2. Hit "Compare" button
3. Select "Same" in the dropdown "View by" 
4. Check that all the tabs show the content which is in common for both versions

**"View by All"**
1. Select two versions to compare
2. Hit "Compare" button
3. Select "All" in the dropdown "View by" 
4. Check that all the tabs show the all the content comparison for both versions

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by tazhibaevaaliya** [comment]
There are two test check commented out (Lines 569 and 642-644 ) that I could not figure out how to pass. Checking for an empty Files and Errata when selecting "Same" and "Different" respectively in the "View by" dropdown. Other than that, the functionality is working. 

@sjha4  and @jeremylenz handing off my work. Thank you for all your support!

**Comment by sjha4** [comment]
Well, it's all green.. 😸 Nice work @tazhibaevaaliya! 

[test katello]

**Comment by sjha4** [comment]
Closing and copying this commit to: https://github.com/Katello/katello/pull/10227

**Pull request closed without merging**
