### PR TITLE
refs #10970 - 'location' was colliding with a named something...

### PR DESCRIPTION
**Pull request by komidore64**
so I renamed it to 'source_code_location'

### CODE REVIEW

**Comment by daviddavis** [comment]
Not sure if I like the name `kt_location`. Seems like it should be source_code_location or something.

**Comment by cpeters** [comment]
I'm good with source_code_location

**Comment by komidore64** [comment]
@daviddavis, @cpeters okay, yeah. i'm cool with `source_code_location`.

**Comment by cpeters** [comment]
ACK

**Comment by daviddavis** [comment]
ACK from me

**Pull request merged**
