### PR TITLE
Fixes #27152: fix js error on the repo page.

### PR DESCRIPTION
**Pull request by waldenraines**
https://projects.theforeman.org/issues/27152

### CODE REVIEW

**Comment by jlsherrill** [comment]
I'm still seeing this when i load the page (after having a repository already enabled).   
```
Warning: Failed prop type: Invalid prop `enabledRepositories.search` of type `object` supplied to `RedHatRepositoriesPage`, expected `string`.
    in RedHatRepositoriesPage (created by Connect(RedHatRepositoriesPage))
    in Connect(RedHatRepositoriesPage) (created by Headers)
    in Headers (created by CheckOrg)
    in CheckOrg (created by Connect(CheckOrg))
    in Connect(CheckOrg) (created by Route)
    in Route
    in div
    in Unknown (created by Application)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Application)
    in Application (created by Connect(Application))
    in Connect(Application) (created by I18nProviderWrapper(Connect(Application)))
```

**Comment by jlsherrill** [comment]
errr actually, my browser may have been using a cached version which is strange since i thought the webpack server would solve that ...

**Comment by jlsherrill** [comment]
errr, no i am still seeing this

**Comment by waldenraines** [comment]
@jlsherrill sorry about that, I fixed the wrong place (which also needed to be fixed).  Should work now.

**Comment by sjha4** [comment]
I see a different issue upon enabling the repo. The API call made to get enabled repos is possibly malformed and looks like `/katello/api/v2/repositories?organization_id=1&enabled=true&page=0&per_page=NaN&search=(redhat+%3D+true)`
with the response: `{"displayMessage":"invalid page: 0","errors":["invalid page: 0"]}`

Works ok after refresh with the API call `/katello/api/v2/repositories?organization_id=1&enabled=true&search=(redhat+%3D+true)`

**Comment by waldenraines** [comment]
> I see a different issue upon enabling the repo.

@sjha4 do you see this same issue in master?

**Comment by sjha4** [comment]
@waldenraines : Yes, I see this on master as well..

**Comment by sjha4** [comment]
I've filed an issue https://projects.theforeman.org/issues/27198 to document the behavior I was seeing.

**Comment by waldenraines** [comment]
@sjha4 @jlsherrill what else needs to be done here?

**Comment by jlsherrill** [comment]
@waldenraines i think since @sjha4 opened a  2nd issue for that, this is good to go.  You agree @sjha4 ?

**Comment by sjha4** [comment]
I have not seen the reported issue on the branch. So this looks good to me. :+1:

**Pull request merged**
