### PR TITLE
Fixes #14537 - unable to register with sub-man after puppet registration

### PR DESCRIPTION
**Pull request by beav**
The previous commit for this did not fix the issue properly.

### CODE REVIEW

**Comment by beav** [comment]
@ehelms thanks for your help with finding where to grab the org from

from a clean bats install, after applying patch and restarting `httpd` and `foreman-tasks`:
```
# USE_KOJI_REPOS=true katello-bats content
 ✓ create a product
 ✓ create package repository
 ✓ upload package
 ✓ sync repository
 ✓ create puppet repository
 ✓ upload puppet module
 ✓ create lifecycle environment
 ✓ create content view
 ✓ add repo to content view
 ✓ add puppet module to content view
 ✓ publish content view
 ✓ promote content view
 ✓ create activation key
 ✓ disable auto-attach
 ✓ add subscription to activation key
 ✓ install subscription manager
 ✓ register subscription manager
 ✓ check content host is registered
 ✓ enable content view repo
 ✓ install katello-agent
 ✓ start katello-agent
 ✓ install package remotely (katello-agent)
 ✓ install package locally
 - add puppetclass to host (skipped)
 - puppet run applies dummy module (skipped)
 ✓ collect important logs

26 tests, 0 failures, 2 skipped
```

**Comment by ehelms** [comment]
ACK

**Comment by ehelms** [comment]
Merging to let the pipeline run - thanks @beav!

**Comment by stbenjam** [comment]
@beav Does this mean the Foreman host isn't in any org or location? If so that's an actual bug that needs fixing

**Pull request merged**
