### PR TITLE
refs #13453 - removing ability for docker content upload

### PR DESCRIPTION
**Pull request by komidore64**
was originally #5736

### CODE REVIEW

**Comment by daviddavis** [comment]
It might be nice to eventually encapsulate the logic around whether a repo accepts content uploads but this works for now.

ACK for me.

**Comment by komidore64** [comment]
@daviddavis something more like this?
```ruby
@repository.accepts_uploaded_content? # => true or false
```

**Comment by daviddavis** [comment]
@komidore64 yea although I think we would need to propagate that to the UI which I think is maybe outside the scope of this PR.

**Comment by komidore64** [comment]
makes sense.

**Comment by komidore64** [comment]
@daviddavis, created redmine refactor issue [#13469](http://projects.theforeman.org/issues/13469)

**Pull request merged**
