### PR TITLE
Fixes #16645 - force https for initial capsule sync

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@jlsherrill This is probably a dumb question, but why sync with https? Is it just because its more secure?

**Comment by jlsherrill** [comment]
@johnpmitsch yes, when configured properly, it provides:

* The knowledge that the server you are syncing against is who they said they were (and who we think they are).  You wouldn't want attacker propping up a fake server to get bad content onto a capsule.
* prevents people snooping on the wire from seeing the traffic between the two server (not as important here)

A lot of users do not allow non-ssl'd http traffic through their networks or between servers.

**Comment by johnpmitsch** [comment]
@jlsherrill 

Thanks for the explanation :+1:  will give it a test later

**Comment by jlsherrill** [comment]
@johnpmitsch there's some instructions in the issue for how to monitor as well.

**Comment by johnpmitsch** [comment]
ACK

I'm seeing request to ssl access log on a newly promoted repo to capsule environment
```
192.168.121.245 - ff80808157056a9201570a629061010e [27/Sep/2016:15:19:47 -0400] "GET /pulp/repos/Default_Organization/Dev/cv3/custom/prod1/needed-errata/wolf-9.4-2.noarch.rpm HTTP/1.1" 200 2439 "-" 
"python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-229.1.2.el7.x86_64"
```

**Pull request merged**
