### PR TITLE
Fixes #24314 - reload enabled repos on enable/disable

### PR DESCRIPTION
**Pull request by tstrachota**
- adds possibility to reload enabled repos "silently" (without
  displaying the spinner)
- adds proper actions for enabling/disabling repos
- loading and error flag moved from components' state to Redux store
- enabled repos are reloaded silently after each enable/disable request -> correct pagination and total numbers are displayed

**TODO:**
- [x] fix failing and add more tests

### CODE REVIEW

**Comment by tstrachota** [comment]
This is now ready for review.

**Comment by bbuckingham** [comment]
@tstrachota, looks like this one may need a rebase

**Comment by tstrachota** [comment]
Rebased. It was a tough one. I hope I didn't miss anything.

**Comment by waldenraines** [comment]
> Rebased. It was a tough one. I hope I didn't miss anything.

@tstrachota looks like the snapshots need updating.

**Comment by tstrachota** [comment]
I always forget to remove obsolete snapshots. Updated.

**Comment by waldenraines** [comment]
@tstrachota sorry but this needs another rebase :frowning_face:

**Comment by tstrachota** [comment]
@waldenraines rebased

**Comment by waldenraines** [comment]
@tstrachota sorry, looks like a snapshot test failed.

**Comment by tstrachota** [comment]
Ooops, updated, sorry for that!

**Comment by waldenraines** [comment]
[test katello]

**Pull request merged**
