### PR TITLE
Fixes #15159 - Api request fails for GET /katello/api/organizations/organization_id/environments/:id/repositories

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by daviddavis** [comment]
Any chance we can point `/katello/api/organizations/:organization_id/environments/:env_id/repositories` to repositories#index and just drop this action? It looks like repositories#index [already has the necessary params](https://git.io/vrorS).

**Comment by ranjan** [comment]
@daviddavis Yes we can, but instead pointing to repositories#index we should remove this api from documentation and just improve the current documentation of repositories.

**Comment by daviddavis** [comment]
I think if you just add the route [here](https://git.io/vrPK4) then the api documentation will be unaffected.

**Comment by daviddavis** [comment]
Here's what I had in mind: https://gist.github.com/daviddavis/f21df62c1a7adc0beee92f76500ea827

**Comment by ranjan** [comment]
Thanks @daviddavis, Updated PR with required changes.

**Comment by jlsherrill** [comment]
ACK thanks @ranjan !!

**Pull request merged**
