### PR TITLE
Fixes #13222 - Adds pulp status and pulp storage to proxy show page

### PR DESCRIPTION
**Pull request by shlomizadok**
(cherry picked from commit 75193a493788f9c6641ff343b1380286145747b2)
Replaces #5716

### CODE REVIEW

**Comment by ehelms** [comment]
You could just push this to your previous branch so that we can maintain the PR history and conversation:

```
git push upstream fix_13222b:fix_13222
```

Also, so you know for the future, you don't need to cherry pick with `-x` in this case because the commit is not an upstream commit that you want to be able to reference the previous commit hash for.

**Comment by shlomizadok** [comment]
Oh, I didn't know that I don't have to cherry-pick with `-x`.
Anyhow, It won't let me re-open the previous PR  (with error: `The fix_13222 branch was force-pushed or recreated.`)

**Comment by ehelms** [comment]
OK - you live and you learn. I'll merge this if all is green.

**Comment by shlomizadok** [comment]
@ehelms, @jlsherrill - fyi, https://github.com/theforeman/foreman-packaging/pull/997

**Comment by ehelms** [comment]
Thanks @shlomizadok !

**Pull request merged**
