### PR TITLE
fixes #33439 - Update settings explanation according to settings options

### PR DESCRIPTION
**Pull request by domitea**
Setting has now "Yes" and "No" options for boolean options. Explanations for these settings doesn't reflect that. This PR fix that.

### CODE REVIEW

**Comment by domitea** [comment]
PR updated after discussion at similar PR (https://github.com/theforeman/foreman/pull/8773)

**Comment by ezr-ondrej** [comment]
I think the bot believes the commit message is too long

**Comment by domitea** [comment]
@ezr-ondrej Thanks! Tests are green and badge was removed. I think it's ready to merge.

**Review by jlsherrill — APPROVED** [review]
Thanks @domitea sorry this got missed.

**Pull request merged**
