### PR TITLE
Fixes #20569: show success/error message on upload.

### PR DESCRIPTION
**Pull request by waldenraines**
Be sure to show a success and error message on repository package
upload.

http://projects.theforeman.org/issues/20569

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by waldenraines** [comment]
> Works for me! Do you see any problem in making the assertions on the messaging a little more precise?
> 
> expect(GlobalNotification.setErrorMessage).toHaveBeenCalled() vs expect(GlobalNotification.setErrorMessage).toHaveBeenCalledWith('whatever') is what I'm referring to.

I can do that.  I thought about it as being a tradeoff to make the test less rigid (and fragile) but I don't have a strong preference either way.

**Comment by jturel** [comment]
> I can do that. I thought about it as being a tradeoff to make the test less rigid (and fragile) but I don't have a strong preference either way.

Cool. My main concern was whether hose strings were being tested anywhere at all. I have a suspicion they aren't but I don't know for sure. If that's the case then I definitely see value in testing them here - but point taken on the coupling between the behavior and the exact message.

**Comment by waldenraines** [comment]
@jturel updated.

**Comment by jturel** [comment]
[test]

**Pull request merged**
