### PR TITLE
Fixes 30832: Do not upload package profile to Pulp 3

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ianballou** [comment]
The redmine bot is unhappy, the commit should be "Fixes #30832 -- Do not upload package profile to Pulp 3

**Comment by ehelms** [comment]
I'll let tests finish before pushing a commit to fix the message in case I need to also fix something.

**Comment by ehelms** [comment]
Fixed broken test and updated commit message

**Review by ianballou — APPROVED** [review]
Looks good to me! Now we just have to get the tests to not time out.

**Comment by ianballou** [comment]
[test katello]

**Comment by evgeni** [comment]
:green_apple:

**Comment by jturel** [comment]
I think this PR is the culprit in the nightly failure around errata installation via katello agent. Since we triaged it to 3.18 it's now also blocking the 3.18 pipeline :(

In the logs I see stuff like below, presumably because we never sent a package profile to pulp2

```
2020-11-19T21:38:23 [I|bac|] Task {label: Actions::Katello::Host::Erratum::Install, id: 5c59f64d-0045-4293-83dd-62ed3cb85c13, execution_plan_id: 9b0cb1c6-6caf-4141-87c5-631662bf10a0} state c
hanged: running                                                                                                                                                                               
2020-11-19T21:38:23 [E|kat|] POST: https://centos7-katello-devel.jturel.example.com/pulp/api/v2/consumers/622d8956-fec7-4d72-abc2-90afc992d3e4/actions/content/install//: {"units":[{"type_id"
:"erratum","unit_key":{"id":"RHEA-2012:0055"}}],"options":{"importkeys":true}}: {"content_type"=>"application/json", "accept"=>"application/json"}                                            
 | 400 Bad Request: {"http_request_method": "POST", "exception": null, "error_message": "Consumer has no RPM unit profile", "_href": "/pulp/api/v2/consumers/622d8956-fec7-4d72-abc2-90afc992d
3e4/actions/content/install//", "http_status": 400, "error": {"code": "PLP0000", "data": {}, "description": "Consumer has no RPM unit profile", "sub_errors": []}, "args": ["Consumer has no R
PM unit profile"], "traceback": null}                                                                                                                                                         
2020-11-19T21:38:23 [E|bac|] 400 Bad Request (RestClient::BadRequest)   
```

The best thing to do may be a revert, but let's discuss. I'll be OOO tomorrow and through next week, so my participation here will be limited, and I assume that's the case for several others.

**Comment by jturel** [comment]
Chatted w/ Justin and came up with this: https://github.com/Katello/katello/pull/9045

**Pull request merged**
