### PR TITLE
Fixes #28715 - Correct permission for reports

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
@ranjan : Could you test this with the permission view_tasks from miscellaneous list? Would be interesting to see if that work today?

**Comment by ranjan** [comment]
@sjha4, No it doesn't work for view-tasks(miscellaneous)

**Pull request merged**
