### PR TITLE
Fixes #27776 - Run metadata generation on right capsule

### PR DESCRIPTION
**Pull request by sjha4**

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Why is this being opened against 3.12 exactly?

**Comment by sjha4** [comment]
> Why is this being opened against 3.12 exactly?

Must have needed coffee..From what I checked earlier seemed to me that master is fixed and we only needed this downstream..Checking this again, it is needed on master so I'll reopen this against master..

**Comment by sjha4** [comment]
Closing this..

**Pull request closed without merging**
