### PR TITLE
Fixes #21706 - add option to bypass global proxy for syncing

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by akofink** [comment]
[test]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test rails-5]

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Comment by ehelms** [comment]
[test default]

**Comment by jlsherrill** [comment]
test comment

**Comment by jlsherrill** [comment]
[test default]

**Pull request merged**
