### PR TITLE
Fixes #25912 - Move js test-helpers to npm

### PR DESCRIPTION
**Pull request by sharvit**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@johnpmitsch @waldenraines ping

**Comment by johnpmitsch** [comment]
@sharvit can you give a little background on this? The test helper functions are now a package on npm?

**Comment by waldenraines** [comment]
> @sharvit can you give a little background on this? The test helper functions are now a package on npm?

@sharvit created a set of [test utils](https://github.com/sharvit/react-redux-test-utils) from common things we had in katello and foreman.  This PR updates katello to use this npm.

**Comment by johnpmitsch** [comment]
@sharvit @waldenraines thanks for clarifying, the code looks fine and moving the logic to a separate package seems like a good idea. My only concern is having the repo under a personal github account, have we considered moving it to the foreman org?

**Pull request merged**
