### PR TITLE
Fixes #33045 - cancel both parent and child migration tasks

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jturel** [comment]
Easy way to validate this? Looks like the last open PR for 3.18.5!

**Comment by ianballou** [comment]
@jturel I'm on it.

**Comment by jlsherrill** [comment]
I believe if you:

1.  sync some repos with a decent amount of content
2.  perform the 'foreman-maintain content prepare'  command
3. restart pulpcore-api which should cause the dynflow migration task to fail (but the task still keeps running)
4. run foreman-rake katello:pulp3_migration_abort

confirm that the tasks cancel in pulp by polling the pulp3 tasks api  /pulp/api/v3/tasks/
Bonus points if you can do this while the migration is running during the initial phase and also  the 2nd phase where it spawns other tasks to generate publications

**Comment by ianballou** [comment]
It's weird, the task is cancelled but I see "running" in the progress reports at the bottom:

{
  "pulp_href": "/pulp/api/v3/tasks/68212e14-1c59-475c-ad2a-3d0caef9ce48/",
  "pulp_created": "2021-09-09T19:34:03.474566Z",
  "state": "canceled",
  "name": "pulp_2to3_migration.app.tasks.migrate.migrate_from_pulp2",
  "started_at": "2021-09-09T19:34:03.590782Z",
  "finished_at": null,
  "error": null,
  "worker": "/pulp/api/v3/workers/0559b798-e80c-4c56-b123-7115626645a1/",
  "parent_task": null,
  "child_tasks": [],
  "task_group": "/pulp/api/v3/task-groups/2e20794d-40da-4c0a-9c5f-09816d21c344/",
  "progress_reports": [
    {
      "message": "Processing Pulp 2 repositories, importers, distributors",
      "code": "processing.repositories",
      "state": "completed",
      "total": 4,
      "done": 4,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb content (general info)",
      "code": "premigrating.content.general",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb content (detail info)",
      "code": "premigrating.content.detail",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb_release content (general info)",
      "code": "premigrating.content.general",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb_release content (detail info)",
      "code": "premigrating.content.detail",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb_component content (general info)",
      "code": "premigrating.content.general",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 deb_component content (detail info)",
      "code": "premigrating.content.detail",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 iso content (general info)",
      "code": "premigrating.content.general",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 iso content (detail info)",
      "code": "premigrating.content.detail",
      "state": "completed",
      "total": 0,
      "done": 0,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 rpm content (detail info)",
      "code": "premigrating.content.detail",
      "state": "running",
      "total": 13723,
      "done": 11000,
      "suffix": null
    },
    {
      "message": "Pre-migrating Pulp 2 rpm content (general info)",
      "code": "premigrating.content.general",
      "state": "running",
      "total": 13723,
      "done": 12000,
      "suffix": null
    }
  ],
  "created_resources": [
    "/pulp/api/v3/task-groups/2e20794d-40da-4c0a-9c5f-09816d21c344/"
  ],
  "reserved_resources_record": [
    "pulp_2to3_migration"
  ]
}

**Comment by ianballou** [comment]
The distribution related tasks seemed to cancel fine:

```json
{
  "pulp_href": "/pulp/api/v3/tasks/0011d275-246a-4b9e-94bb-e961adbba88a/",
  "pulp_created": "2021-09-09T19:28:43.648949Z",
  "state": "canceled",
  "name": "pulp_2to3_migration.app.migration.complex_repo_migration",
  "started_at": "2021-09-09T19:28:43.764242Z",
  "finished_at": null,
  "error": null,
  "worker": "/pulp/api/v3/workers/77f36197-56c3-47cf-80a4-facad587fea1/",
  "parent_task": "/pulp/api/v3/tasks/17cde0f6-4b3d-4320-8fc6-6db055e5c96a/",
  "child_tasks": [],
  "task_group": "/pulp/api/v3/task-groups/829cd3ef-29cf-49d6-9a9a-6eab6ac601d5/",
  "progress_reports": [],
  "created_resources": [
    "/pulp/api/v3/repositories/rpm/rpm/1f624110-d720-4913-926c-f6a33085b42d/versions/1/"
  ],
  "reserved_resources_record": [
    "/pulp/api/v3/repositories/rpm/rpm/1f624110-d720-4913-926c-f6a33085b42d/"
  ]
}

...

{
  "pulp_href": "/pulp/api/v3/task-groups/829cd3ef-29cf-49d6-9a9a-6eab6ac601d5/",
  "description": "Migration Sub-tasks",
  "all_tasks_dispatched": true,
  "waiting": 0,
  "skipped": 0,
  "running": 0,
  "completed": 1,
  "canceled": 1,
  "failed": 0,
  "group_progress_reports": [
    {
      "message": "Repo version creation",
      "code": "create.repo_version",
      "total": 1,
      "done": 1,
      "suffix": null
    },
    {
      "message": "Distribution creation",
      "code": "create.distribution",
      "total": 1,
      "done": 0,
      "suffix": null
    }
  ]
}
```

**Comment by jlsherrill** [comment]
> It's weird, the task is cancelled but I see "running" in the progress reports at the bottom:

might be worth asking the pulp team if thats expected, but since state is cancelled i think its okay?

**Review by ianballou — APPROVED** [review]
Looks good! The running bit is a Pulp bug: https://pulp.plan.io/issues/9369

**Pull request merged**
