### PR TITLE
Fixes #17162: remove nutupane from content view pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17162

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/142

**Comment by thomasmckay** [comment]
issues:
+ created new cv, then chose kebab to copy: js error bastion.js:13551 Error: Could not resolve 'content-view.copy' from state 'content-view'
+ when no cv in ccv yet the empty message is a blank info box
+ "add" list of cv to ccv does not show list entries (no js errors, api returning correct info)
+ hitting "search" button on above empty list gives js error "bastion.js:13551 Nutupane closeItem not implemented. If you are using Nutupane functionality with master-detail please pass 'masterOnly' to your Nutupane declaration"
+ empty history list (no publish/promote yet) has blank info box
+ empty task list has no info box at all (just blank list)
+ cv ostree tab js error "Error: [$compile:ctreq] Controller 'bstTable', required by directive 'bstTableHead', can't be found!"
+ imo, all "Details" tabs should be the first tab, not buried somewhere in amongst the others

**Comment by waldenraines** [comment]
> created new cv, then chose kebab to copy: js error bastion.js:13551 Error: Could not resolve 'content-view.copy' from state 'content-view'
> hitting "search" button on above empty list gives js error "bastion.js:13551 Nutupane closeItem not implemented. If you are using Nutupane functionality with master-detail please pass 'masterOnly' to your Nutupane declaration"
> empty task list has no info box at all (just blank list)
> cv ostree tab js error "Error: [$compile:ctreq] Controller 'bstTable', required by directive 'bstTableHead', can't be found!"
> imo, all "Details" tabs should be the first tab, not buried somewhere in amongst the others
This has all been fixed.

> "add" list of cv to ccv does not show list entries (no js errors, api returning correct info)
> empty history list (no publish/promote yet) has blank info box
I cannot reproduce these.  Will you kindly try again?

**Comment by thomasmckay** [comment]
I don't like that the "Publish New Version" is buried in the kebab; I believe it belongs on the Versions tab. This pattern would match the "Remove Repositories" button or the Puppet Module's "Add New Module" button. It's a pretty common action and deserves easier access and visibility, plus it is an action that will add an entry to the Versions list.

I have four CVs and one CCV, all unpublished. Visiting the CCV Content Views page, the Add list is blank. The api is returning results. The List/Remove tab info box is missing the empty list message.

The Tasks list has all the column headers overlaying each other to the left. Tasks list does not have borders around its cells.

The Docker tab has a filter instead of a search, is that just legacy? Its style looks different than the search UIs. Whether it's a search or a filter it would be nice to have the same pattern of "Showing 12 of 12" next to the filter field and move the "0 Selected" up to the same row.

**Comment by thomasmckay** [comment]
After publishing one of my CVs, it showed up in the CCV add list. The logic to show an "empty list" message for the CVs could indicate that there are no published CVs available to add.

**Comment by waldenraines** [comment]
> I don't like that the "Publish New Version" is buried in the kebab; I believe it belongs on the Versions tab. This pattern would match the "Remove Repositories" button or the Puppet Module's "Add New Module" button. It's a pretty common action and deserves easier access and visibility, plus it is an action that will add an entry to the Versions list.

Fixed.

> I have four CVs and one CCV, all unpublished. Visiting the CCV Content Views page, the Add list is blank. The api is returning results. The List/Remove tab info box is missing the empty list message.

This is likely handled by https://github.com/Katello/katello/pull/6416.

> The Tasks list has all the column headers overlaying each other to the left. Tasks list does not have borders around its cells.

Fixed.

> The Docker tab has a filter instead of a search, is that just legacy? Its style looks different than the search UIs. Whether it's a search or a filter it would be nice to have the same pattern of "Showing 12 of 12" next to the filter field and move the "0 Selected" up to the same row.

Fixed.

**Comment by thomasmckay** [comment]
Issues:

- "new filter" should be "publish new version" on the versions page
- tasks table headers are all squashed together to left
- composite cv "content views" tab, list/remove has empty info message when list empty. same for add info message
- remove content view gives js error: TypeError: $scope.reloadVersions is not a function

**Comment by waldenraines** [comment]
> tasks table headers are all squashed together to left

This happens elsewhere and will require some more investigation (and likely a fix in bastion), filed 
http://projects.theforeman.org/issues/17537

> "new filter" should be "publish new version" on the versions page
> composite cv "content views" tab, list/remove has empty info message when list empty. same for add info message
> remove content view gives js error: TypeError: $scope.reloadVersions is not a function

Fixed.

I also fixed the issue you brought up on IRC about the sub-header on the composite content views page.

**Comment by ehelms** [comment]
I think that the area below the tabs could use some more whitespace. They feel on top of each other.

screenshot from 2016-12-01 15-48-37

**Comment by waldenraines** [comment]
> I think that the area below the tabs could use some more whitespace. They feel on top of each other.

Update to use [patternfly tabs](http://www.patternfly.org/pattern-library/widgets/#tabs).

**Comment by thomasmckay** [comment]
ack

**Comment by ehelms** [comment]
The styling is messed up on forms. The `katello.gemspec` needs to be updated similarly to https://github.com/Katello/katello/pull/6492/files#diff-7ea0cda8f94296226df02897d5824ca6R19

**Comment by waldenraines** [comment]
> The styling is messed up on forms. The katello.gemspec needs to be updated similarly to https://github.com/Katello/katello/pull/6492/files#diff-7ea0cda8f94296226df02897d5824ca6R19

@ehelms updated.

**Pull request merged**
