### PR TITLE
fixes #23181 - don't use port :9090 to pulp

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by thomasmckay** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by adamruzicka** [comment]
Without this fix I wasn't able to sync content to a capsule on nightly from last friday, with this fix it seems to work. However I'm still getting another error on the smart-proxy details page.

```
2018-04-11T07:53:59 [I|app|b42cd]   Rendered /opt/theforeman/tfm/root/usr/share/gems/gems/katello-3.7.0/app/views/katello/api/v2/capsule_content/sync_status.json.rabl (420.7ms)                                                            
2018-04-11T07:53:59 [E|app|b42cd] ActionView::Template::Error: undefined method `enabled' for #<Array:0x0000000009e5cd98>                                                                                                                   
 | (eval):40:in `block (3 levels) in eval_source'                                                                                                                                                                                           
 | /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'                                                                                                              
 | /opt/theforeman/tfm-ror51/root/usr/share/gems/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'                                                                                                              
 | (eval):31:in `map'                                                                                                                                                                                                                       
 | (eval):31:in `block (2 levels) in eval_source'                                                                                                                                                                                           
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:152:in `node'                                                                                                                                               
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:114:in `block in compile_settings'                                                                                                                          
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:113:in `each'                                                                                                                                               
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:113:in `compile_settings'                                                                                                                                   
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:58:in `block in to_hash'                                                                                                                                    
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:248:in `cache_results'                                                                                                                                      
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/builder.rb:49:in `to_hash'                                                                                                                                             
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/multi_builder.rb:27:in `map'                                                                                                                                           
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/multi_builder.rb:27:in `to_a'                                                                                                                                          
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/engine.rb:88:in `to_hash'                                                                                                                                              
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/engine.rb:48:in `block in render'                                                                                                                                      
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/engine.rb:380:in `cache_results'                                                                                                                                       
 | /opt/theforeman/tfm/root/usr/share/gems/gems/rabl-0.13.1/lib/rabl/engine.rb:47:in `render'                                                                                                                                               
 | /usr/share/foreman/config/initializers/rabl_init.rb:49:in `render'
```

**Comment by adamruzicka** [comment]
Ok, fine by me

**Pull request merged**
