### PR TITLE
Fixes #24005 - add scrolling to provided products

### PR DESCRIPTION
**Pull request by amirfefer**
Using `ListGroup` component from patternfly react, with scrolling:

provided-products

### CODE REVIEW

**Comment by akofink** [comment]
For reference, here's what I'm seeing (using a portrait mode display) 
image

**Comment by amirfefer** [comment]
@rohoover any suggestion about the `max-height` ?

**Comment by Rohoover** [comment]
@amirfefer 

Maybe a couple few rows, but I'm not too worried about. Will control+f still work on this scroll?

**Comment by amirfefer** [comment]
control+f works well

**Comment by akofink** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by waldenraines** [comment]
> Works well. Should we include a note if there are no provided products (not sure that's possible though)?

Never mind, I have been told this isn't a realistic scenario.

**Pull request merged**
