### PR TITLE
Fixes #26501 updated broken links for product and errata

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
Added correct navigation for errata on the content-view-version page and product on the packages page

### CODE REVIEW

**Comment by chris1984** [comment]
ok to test

**Comment by chris1984** [comment]
[test katello]

**Comment by omkarkhatavkar** [comment]
> * to 'Content -> OSTree Branches'
> 
> We could add a lot more, this is just giving a more consistent cross-link from the content type the lowest level source included in the table.

let me look at them.

**Comment by chris1984** [comment]
[test katello]

**Comment by omkarkhatavkar** [comment]
@bbuckingham added some more links as mentioned https://github.com/Katello/katello/pull/8058#pullrequestreview-221876958

**Comment by bbuckingham** [comment]
@omkarkhatavkar, Excellent!  Thank you for those additions.  I think it makes for a more complete/consistent behavior when navigating through the content view version details.

Looks good!

**Pull request merged**
