### PR TITLE
Fixes #29395 - Address cops for rubocop-minitest

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by mmoll** [comment]
@jturel For the auto-correct to work better you'd need rubocop-minitest 0.8 (relased today)

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
> @jturel For the auto-correct to work better you'd need rubocop-minitest 0.8 (relased today)

Thanks, I did see that. I decided to change a lot of those to user assert_equal instead because it looked so ugly

**Pull request merged**
