### PR TITLE
fixes #9800 - allow newer ruby193-rubygem-qpid_messaging

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by dustints** [comment]
APJ

**Comment by ehelms** [comment]
I assume this obsoletes - https://github.com/Katello/katello/pull/4950 . However, that PR updates more places than yours does.

**Comment by jlsherrill** [comment]
Oh didn't realize that pr existed!  good eye!

**Comment by jlsherrill** [comment]
Closing this pr

**Pull request closed without merging**
