### PR TITLE
Refs #33292 - enable ostree tests

### PR DESCRIPTION
**Pull request by evgeni**
#### What are the changes introduced in this pull request?

test all the things

#### Considerations taken when implementing this change?

more tests is better
fewer tests is worse

#### What are the testing steps for this pull request?

CI will tell

### CODE REVIEW

**Comment by evgeni** [comment]
oh wait, this probably needs recording all the fixtures new? I'll be damned.

**Comment by evgeni** [comment]
"nice"

**Comment by jlsherrill** [comment]
Thanks @evgeni !!  i wanted to take this a bit further and opened this pr: https://github.com/Katello/katello/pull/9867
which also adds tests for python support.

**Comment by evgeni** [comment]
Nice! Yeah, this was more of a playground for me, to see how far (not too far)I can get after I realized the repo controller issue I was fixing was having a test, but it was skipped.

Closing un favor of yours!

**Pull request closed without merging**
