### PR TITLE
Fixes #27878 - hide Registered Through for hypervisor profiles

### PR DESCRIPTION
**Pull request by snagoor**
hide Registered Through option for hypervisor profiles on the Content Hosts page

### CODE REVIEW

**Comment by jturel** [comment]
Couldn't a Hypervisor be registered through a Capsule / Foreman Proxy w/ Content ?

**Comment by snagoor** [comment]
@jturel agreed, when virt-who used in VDSM mode, we register the hypervisor directly to either Satellite/Capsule which indeed has a `registered_through` value set. So, to satisfy both these conditions can I tweak the condition as below?
~~~
ng-show="!host.subscription_facet_attributes.hypervisor && host.subscription_facets.registered_through == null"
~~~

**Comment by jturel** [comment]
I'm still not sure what you're trying to solve.

Is it that, for cases where the hypvervisor is created by the virt-who checkin, you want to hide "Registered Through: Unknown" completely (rather than showing 'Unknown')?

**Comment by snagoor** [comment]
> I'm still not sure what you're trying to solve.
> 
> Is it that, for cases where the hypvervisor is created by the virt-who checkin, you want to hide "Registered Through: Unknown" completely (rather than showing 'Unknown')?

Yes, that's what I am trying to accomplish. +1:

**Comment by jturel** [comment]
> > I'm still not sure what you're trying to solve.
> > Is it that, for cases where the hypvervisor is created by the virt-who checkin, you want to hide "Registered Through: Unknown" completely (rather than showing 'Unknown')?
> 
> Yes, that's what I am trying to accomplish. +1

Cool, thank you. Got it! How about this:

```
ng-show="host.subscription_facet_attributes.registered_through || !host.subscription_facet_attributes.hypervisor"
```

**Comment by snagoor** [comment]
@jturel, I think one of the condition is enough to hide `Registered Through` this from showing up on UI? 
~~~
ng-show="!host.subscription_facet_attributes.hypervisor"
~~~
should be sufficient IMHO, Correct me if I am wrong.

**Comment by jturel** [comment]
> @jturel, I think one of the condition is enough to hide `Registered Through` this from showing up on UI?
> 
> ```
> ng-show="!host.subscription_facet_attributes.hypervisor"
> ```
> 
> should be sufficient IMHO, Correct me if I am wrong.

I think we need both checks because if a hypervisor is registered directly with subscription-manager we should still show registered-through, since the value will be set

**Comment by snagoor** [comment]
@jturel modified PR as per your suggestion. Please review and let me know if any further changes are required.

**Pull request merged**
