### PR TITLE
Fixes #24519 - Sync Plan saved with incorrect date/time

### PR DESCRIPTION
**Pull request by sjha4**
### Steps to Reproduce:

Go to Sync Plans > New 
Enter a date and time for the new sync plan

**Actual Behavior:** The saved sync plan has a different time than what was set by the user

**Expected Behavior:** The dates should be correct

### CODE REVIEW

**Comment by jturel** [comment]
Maybe I'm not testing this properly but I don't see any difference (but the code makes me think I should)

```
irb(main):005:0> Katello::SyncPlan.all
+----+-------------+-------------+-------------------------+----------+-----------------+-------------------------+-------------------------+---------+                     
| id | name        | description | sync_date               | interval | organization_id | created_at              | updated_at              | enabled |                     
+----+-------------+-------------+-------------------------+----------+-----------------+-------------------------+-------------------------+---------+                     
| 6  | plan_master |             | 2018-08-10 15:41:00 UTC | hourly   | 1               | 2018-08-10 15:41:57 UTC | 2018-08-10 15:41:57 UTC | true    |                     
| 7  | plan_samir  |             | 2018-08-10 15:45:00 UTC | hourly   | 1               | 2018-08-10 15:45:46 UTC | 2018-08-10 15:45:46 UTC | true    |                     
+----+-------------+-------------+-------------------------+----------+-----------------+-------------------------+-------------------------+---------+         

```

**Comment by sjha4** [comment]
@jturel:..I am not able to reproduce this on my local environment anymore. I was seeing this before I opened the PR. I still see this on the 6.3 box: https://sat-r220-07.lab.eng.rdu2.redhat.com/

Let me test this on some of my other local branches and check what changed.

**Comment by sjha4** [comment]
@waldenraines : I am able to reproduce this in 6.3 boxes, but not in master branch. I don't see anything changed. Tested by changing timezones on my system and the browser. It works with and without the timezoneoffset part. Any thoughts?

**Comment by jlsherrill** [comment]
Actually, hold off, testing a few more things.

**Comment by sjha4** [comment]
Ran into this again and recorded it this time cause I have no idea why this happens sometimes.. :smile: 
***** 
#### Issue:

issue
*****
#### Fix:
fix
*****

**Comment by jturel** [comment]
That's so strange. I'll see if I can reproduce it exactly as you did - mouse movements and all 😆

**Comment by jturel** [comment]
Since this code is tested and there seems to be no difference in the behavior I'm good with this change. Less code, same result!

**Pull request merged**
