### PR TITLE
Fixes #31911 - fix transient bulk_host_extensions test

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by jturel — APPROVED** [review]
APJ

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
