### PR TITLE
Fixes #36686 - temporarily patch out Pulp dist hidden field

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?

Removes the hidden field from Pulpcore 3.28 supported clients so that n-1 smart proxy syncing works.

#### Considerations taken when implementing this change?
This should be removed as soon as possible.

#### What are the testing steps for this pull request?
Try syncing an n-1 smart proxy (that has Pulpcore 3.22) with varying repository types.

### CODE REVIEW

**Comment by sjha4** [comment]
I am seeing this on an ansible collection repo sync on capsule:
https://gist.github.com/sjha4/7497317c51d01dc63d026dce207064ee

**Comment by ianballou** [comment]
@sjha4 this is all good now.

**Comment by sjha4** [comment]
We could pin the gems to the versions in koji.

**Comment by ianballou** [comment]
> We could pin the gems to the versions in koji.

That's alright, we should be able to take in whatever the latest z version is. However, there really shouldn't be major API changes. I'll see if I find any suspicious changes.

**Review by sjha4 — APPROVED** [review]
Ack..One known issue of collections we can get to later once the patch is out, This looks good to go!

**Pull request merged**
