### PR TITLE
Fixes #9586: Content view comparison will provide results again.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@ehelms the issue # here seems wrong?

**Comment by jlsherrill** [comment]
@ehelms also, I can't seem to click on the compare button very easily.  Is this a development issue?

**Comment by ehelms** [comment]
@jlsherrill I haven't seen a production bug on it personally.

**Comment by jlsherrill** [comment]
ACK then

**Pull request merged**
