### PR TITLE
Fixes #16069: fix manifest upload link on RH repositories page.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/16069

### CODE REVIEW

**Comment by daviddavis** [comment]
This sounds like a duplicate of http://projects.theforeman.org/issues/15803

**Comment by waldenraines** [comment]
> This sounds like a duplicate of http://projects.theforeman.org/issues/15803
> 
> Edit: I'd probably open up a new issue for this fix and close 16069 as a dupe.

Potentially but I think it's good to be specific about the link we're going to regardless.  I can open a new issue for this and close out the old one if you prefer that approach.

**Comment by daviddavis** [comment]
👍  from me. 

ACK pending new issue and jenkins 🍏 .

**Comment by waldenraines** [comment]
Closing in favor of https://github.com/Katello/katello/pull/6243.

**Pull request closed without merging**
