### PR TITLE
Fixes #31608 - Update Pulpcore client bindings to 3.9

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Comment by ianballou** [comment]
Blocked on:
- https://github.com/theforeman/puppet-pulpcore/pull/162
- https://pulp.plan.io/issues/8091

**Comment by ianballou** [comment]
Since Pulpcore 3.9 should be fixed soon, we're skipping the broken tests and carrying on.

**Review by jlsherrill — APPROVED** [review]
ACK pending 3.9.1 being released and packaged

**Comment by jlsherrill** [comment]
oh and can you go ahead and open an issue to re-enable those tests?

**Comment by ianballou** [comment]
https://projects.theforeman.org/issues/31704

**Pull request merged**
