### PR TITLE
[CP] Katello 4.0.0.rc3 updates

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Review by jturel — APPROVED** [review]
LGTM!

**Comment by jturel** [comment]
Oh! You'll want to update your tool_belt PR to include 3.18.2.1 and re-run the cherry-picks. Guessing there are a few more that'll get added. See mine: https://github.com/theforeman/tool_belt/pull/339

**Review by jturel — APPROVED** [review]
ACK

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Pull request merged**
