### PR TITLE
Fixes #29080 - content migration progress reporting 

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note, this depends on https://github.com/Katello/katello/pull/9039, which hasn't been merged but included here

**Comment by jlsherrill** [comment]
To test:

1.  configure katello.yaml to use pulp2 for yum:
```
  :use_pulp_2_for_content_type:
    :yum: true
```

2.  create and sync some repos, ideally ones with errata 
3.  Turn most logging to error:
```
:loggers:
  :app:
    :enabled: true
    :level: error
  :audit:
    :enabled: true
    :level: error
  :taxonomy:
    :enabled: true
    :level: error
  :dynflow:
    :enabled: true
    :level: error
```
4.  run 'rake katello:pulp3_migration'
5.  watch the output from the script

```

To test the cancellation aspect, run through the same scenario, but:

1.  run ```reimport_all=true rake katello:pulp3_migration```
2.  when its running, and gets to the 'import' part of the migration, you can run: ``` rake katello:pulp3_migration_abort```

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Review by ianballou — COMMENTED** [review]
Regarding the content count here: 
```
Importing migrated content type rpm: 3690/20231
```

Should that count also be available on the task page?

**Review by ianballou — COMMENTED** [review]
I noticed that `katello:pulp3_migration_abort` still reports `Cancelled 0 tasks.` when the import migration task is indeed cancelled.  It seems that 
```ruby
::Katello::ContentMigrationProgress.where(:task_id => task.id).update_all(:canceled => true)
```
is marking the task to be cancelled but isn't updating the cancelled task count.

**Comment by jlsherrill** [comment]
updated to better show cancelled task count

**Review by ianballou — APPROVED** [review]
Works for me!

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
