### PR TITLE
Fixes #11394: Revert Logging additions that don't exist in 2.2/1.9 yet.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
APJ

**Comment by stbenjam** [comment]
I was hoping the packages in Koji would be 2.3 RC3 and then GA in a couple of days, whenever SCL.org is back up.

If you do 2.2.4, can you open a cherry-pick PR to KATELLO-2.3 as well?

**Comment by stbenjam** [comment]
Or at least let me know what else is going in, so I can  keep track of what to CP in 2.2x so it's not a regression in 2.3.

**Comment by ehelms** [comment]
@stbenjam 2.3 should be OK given it has the new logging in it.

**Comment by stbenjam** [comment]
Ah ok, sorry, I understand now, thanks

**Pull request merged**
