### PR TITLE
WIP: Fixes #31395 - Debian filter in Content View without version comparison

### PR DESCRIPTION
**Pull request by Manisha15**
Add a Debian Filter in Content View to filter deb packages on basis of name and architecture.

### CODE REVIEW

**Comment by sbernhard** [comment]
[test katello]

**Comment by m-bucher** [comment]
[test katello]

**Comment by m-bucher** [comment]
[test katello]

**Comment by jlsherrill** [comment]
Taking a look at this, any planned support for pulp3?

**Comment by quba42** [comment]
> Taking a look at this, any planned support for pulp3?

The key word here is "planned". To be more precise we plan to do a more full featured version of filters for the pulp 3 implementation (that also includes version comparisons). However, to do that I believe we need to add "advanced copy" features similar to those in `pulp_rpm` to `pulp_deb` as well. And to add those we need to add a psql postgres extension for Debian version comparisons (which we also need for the Debian errata story for Katello). This is high on our internal priority list, but the actual implementation has not yet started...

**Comment by jlsherrill** [comment]
Hitting a couple issues:

1) filter didnt' seem to work:
I synced http://deb.theforeman.org/ buster nightly and got 159 debs
I then created an exclude filter to exlude 'foreman'.  Publishing i still get 159 debs.  Setting arch to 'amd64' didn't seem to change it at all.
I also checked the filesystem to see if it was an indexing issue, but the generated metadata seemed to have that same number

2) showing matching content seems to be missing info:
image


Also, katello 3.18 has released, which is the last release with pulp2.  ~90% of this code would be useful for pulp3 filteringi'm wondering though if it makes sense to include this in 4.0 when it doesn't work?  I'm not necessarily opposed to merging it, but might it make more sense to merge with pulp3 support to some degree?

**Comment by Manisha15** [comment]
I have fixed the issue in separate commit for better visibility of changes. If the functionality is approved I can squash the commits into one.

The Apt Repositories in CV Version is not showing correct number of packages. It is showing all packages instead of filtered ones.  Other than this GUI issue, the filter works correctly.

**Comment by jlsherrill** [comment]
Hey sorry, i meant to ask again and reiterate about the dropping of pulp2.  I don't think it makes sense to merge this into master without pulp 3 support, as master is now tracking the 2nd release of katello without pulp2.   If we merged this now (or even when this pr was opened) for the following katello release it wouldn't have worked because there was no pulp2 in 4.0 or 4.1.  The simplest path forward would be to get pulp3 support (and i know there were pulp-debian chnges needed).

**Comment by Manisha15** [comment]
Changing the status to WIP as we are working on adding pulp3 support.

**Pull request closed without merging**
