### PR TITLE
Refs #25973 - errata macro working if REX is not present

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
can't tell what happend, jenkins says
```
Sending interrupt signal to process
After 10s process did not stop
```
but I see no failure. Also I'd expect this is not breaking anything.

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by ares** [comment]
[test katello]

**Comment by ares** [comment]
[test katello]

**Comment by ares** [comment]
@jlsherrill finally got green color, mind to take a look?

**Comment by jlsherrill** [comment]
@ares apologies, i was away for ~6 weeks and missed your update, mind rebasing?

**Comment by ares** [comment]
sure thing, rebased

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
