### PR TITLE
Fixes #36323 - Add eslint rule to check ouiaId prop

### PR DESCRIPTION
**Pull request by lfu**
#### What are the changes introduced in this pull request?
Enable `require-ouiaid` eslint rule for Katello
Depends on https://github.com/theforeman/foreman-js/pull/465.

#### What are the testing steps for this pull request?
`npx eslint webpack`

### CODE REVIEW

**Comment by sjha4** [comment]
Able to run eslint and see all the errors with the 1st commit. ✅ 
```
[vagrant@centos8-katello-devel-stable katello]$ npx eslint webpack/
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

/home/vagrant/katello/webpack/components/Bookmark/AddBookmarkModal.js
  31:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  40:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  51:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  62:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  79:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  80:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/Content/ContentTable.js
  22:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/Content/Details/ContentDetailInfo.js
  21:3  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/Content/Details/ContentDetails.js
  13:7   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  43:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  48:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/RoutedTabs/index.js
  36:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/SelectOrg/SetOrganization.js
  61:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  75:19  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/Table/MainTable.js
   99:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  109:5  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/TooltipButton/TooltipButton.js
   9:44  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  17:29  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/ActionsBar/index.js
  16:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  23:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ChangeHostCVModal.js
  149:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/DetailsTabCards/HwPropertiesCard.js
  22:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/Tabs/ContentTab/SecondaryTabsRoutes.js
  10:3  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/Tabs/ErrataTab/ErratumExpansionDetail.js
  41:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  50:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/HostDetails/Tabs/TracesTab/TracesEnabler.js
  33:3  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/RegistrationCommands/fields/ActivationKeys.js
  55:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/RegistrationCommands/fields/Force.js
  11:5  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/RegistrationCommands/fields/IgnoreSubmanErrors.js
  11:5  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/extensions/RegistrationCommands/fields/LifecycleEnvironment.js
  21:5  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/components/pf3Table/components/Table.js
  45:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/AlternateContentSources/ACSIndexPage.js
  11:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/AlternateContentSources/Create/Steps/ACSCredentials.js
  121:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  145:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  197:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/AlternateContentSources/Create/Steps/SelectSource.js
  109:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  131:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/AlternateContentSources/Details/EditModals/ACSEditCredentials.js
  133:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  145:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  169:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  189:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  207:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  221:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  240:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  268:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  292:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/AlternateContentSources/Details/EditModals/ACSEditURLPaths.js
  70:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Content/Details/ContentDetails.js
  43:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  57:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Content/GenericContentPage.js
  76:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Content/Table/ContentTable.js
  61:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  68:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/AffectedRepositories/AffectedRepositoryTable.js
  185:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  236:21  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/CVDebFilterContent.js
  187:21  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  192:21  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  197:25  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/MatchContentModal/CVDebMatchContentModal.js
  37:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  61:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  72:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/Rules/ContainerTag/AddEditContainerTagRuleModal.js
  46:5  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/Rules/DebPackage/AddEditDebPackageRuleModal.js
   62:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
   75:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
   86:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
   96:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  104:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Filters/Rules/Package/AddEditPackageRuleModal.js
  129:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  164:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  179:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  190:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  201:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Versions/BulkDelete/ActionSummary.js
  25:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Versions/Delete/RemoveSteps/CVEnvironmentSelectionForm.js
   56:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
   68:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
   70:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  122:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Versions/Delete/RemoveSteps/CVVersionRemoveReview.js
  31:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Details/Versions/VersionDetails/ContentViewVersionDetails.js
  90:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/ContentViews/Publish/CVPublishFinish.js
  104:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Hosts/ChangeContentSource/components/ContentSourceForm.js
  154:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  163:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  207:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Hosts/ChangeContentSource/components/ContentSourceTemplate.js
  44:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Hosts/ChangeContentSource/components/FormField.js
  16:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Hosts/ChangeContentSource/components/HostsModal.js
  21:5   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  37:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Hosts/ChangeContentSource/index.js
  124:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  133:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/RedHatRepositories/RedHatRepositoriesPage.js
  51:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  98:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/RedHatRepositories/components/RecommendedRepositorySetsToggler.js
  21:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/RedHatRepositories/components/RepositorySetRepositories.js
  56:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/RedHatRepositories/helpers.js
  36:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  66:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Details/SubscriptionDetailAssociations.js
  13:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Details/SubscriptionDetailInfo.js
  40:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  59:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Details/SubscriptionDetails.js
  84:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  85:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  88:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  93:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Manifest/CdnConfigurationTab/NetworkSyncForm.js
  119:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  129:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Manifest/ManageManifestModal.js
  131:9   warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  197:31  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  200:31  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  215:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  237:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/Manifest/SimpleContentAccess.js
  66:11  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/SubscriptionsPage.js
  223:7  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/UpstreamSubscriptions/UpstreamSubscriptionsPage.js
  134:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  146:17  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  242:15  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/components/SubscriptionsTable/SubscriptionsTable.js
  273:9  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

/home/vagrant/katello/webpack/scenes/Subscriptions/components/SubscriptionsToolbar/SubscriptionsToolbar.js
  79:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid
  83:13  warning  ouiaId property is missing  @theforeman/rules/require-ouiaid

```

No errors with the second commit applied that adds ouia-ids to the components ✅ 

Able to run eslint as usual to detect any linting errors: ✅ 

```
/home/vagrant/katello/webpack/components/Content/ContentTable.js
  22:7  warning  ouiaId property is missing      @theforeman/rules/require-ouiaid
  38:1  error    Trailing spaces not allowed     no-trailing-spaces
  39:5  error    Prop type "array" is forbidden  react/forbid-prop-types

```

**Review by sjha4 — APPROVED** [review]
Wait to merge this till after the foreman-js PR goes in. 👍🏼 
Ack. Works great! Thanks @lfu !

**Comment by sjha4** [comment]
@lfu It seems we need a `jest -u` on some of the snapshot tests..

**Comment by Ron-Lavi** [comment]
Hey @lfu, I think there are some PF3 components that don't have the `ouiaId` prop,
and there can be a warning shown in the console, e.g:

```
react-dom.development.js:88 Warning: React does not recognize the `ouiaId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ouiaid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by Button)
    in Button (created by SubscriptionsToolbar)
```

maybe it could be also a good opportunity to replace some of them to PF4,
or for now, we could replace the `ouiaId` with `id` to avoid that warning.
@jeremylenz do you think this could be an easy task for Trevor? if he has the capacity for it of course.

**Pull request merged**
