### PR TITLE
Fixes #19741 - Undefined method split for nil on tests

### PR DESCRIPTION
**Pull request by dLobatog**
Due to a bug on minitest that is being currently fixed, our tests are
broken when they run as the "test_develop_pr_katello" job in Jenkins.

The fix is published as https://github.com/seattlerb/minitest/pull/696
however there is no version of minitest with it yet. A possible
workaround is to prevent these assertions like this PR does.

### CODE REVIEW

**Comment by dLobatog** [comment]
There is a job http://ci.theforeman.org/job/test_develop_pr_katello/2894/ running the affected Jenkins job with this PR, it should hopefully confirm that the workaround is valid.

**Comment by dLobatog** [comment]
Apparently the job needs a PR in Foreman to work too, not sure how to verify this.

**Comment by dLobatog** [comment]
@sean797 How do you reproduce it locally?

**Comment by sean797** [comment]
Sorry @dLobatog when I said locally I meant with another Jenkins.. At the moment I have access to lots of massively overspec'ed and underutilized Jenkins workers so I setup jobs from https://github.com/theforeman/foreman-infra while I was testing another PR. My laptop sounds like an airplane taking off if I run the whole tests suit locally ✈️ 

This also for example fixes:

```
DEPRECATED: Use assert_nil if expecting nil from /home/vagrant/katello/test/models/sync_plan_test.rb:35. This will fail in Minitest 6.

**Comment by lzap** [comment]
Finally, thanks!

**Comment by lzap** [comment]
Quick merge anyone? This is bugging me for weeks now! Thanks. @ehelms @jlsherrill @parthaa

**Comment by jlsherrill** [comment]
ACK thanks @lzap !

**Comment by dLobatog** [comment]
\o/

**Pull request merged**
