### PR TITLE
Fixes #16505 - Unable to create a repository as non-admin user

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by bbuckingham** [comment]
@ranjan, Thanks for the PR!

Were you able to successfully test the non-admin repo creation scenario with this PR? 

I have a basic role defined (shown in pic below) and I do see the error message (i.e. ' You are not authorized to perform this action.').  This PR definitely fixes an error with 'repository_types'; however, it appears that we may have another retrieving the 'default_download_policy' setting (or I may not have my role set properly).

non-admin-repo-create

**Comment by ranjan** [comment]
@bbuckingham Yes i can create repo using non-admin role with thi PR.

The seperate permission called view_gpg_keys is required only if you want to create repo using gpg_key.

The download policy get loaded successfully but still display message ' You are not authorized to perform this action.' looks like angular js making foreman api call  

> "/api/v2/settings?search=name+%3D+default_download_policy"

 which is not required. I think we should tack this as a separate issue.

**Comment by jlsherrill** [comment]
@ranjan i agree, that can be a separate issue, especially since its in foreman. ACK from me

**Comment by jlsherrill** [comment]
@ranjan mind opening another issue for the  `"/api/v2/settings?search=name+%3D+default_download_policy"`  problem in foreman ? (about it not respecting the settings read permissions.)

**Comment by bbuckingham** [comment]
@ranjan, Apologies for the delay.  ACK from me as well, provided that there is an issue to track the second issue.  Otherwise, when the fix goes through QE, it'll likely fail as user is presented with an error.

**Comment by ranjan** [comment]
@bbuckingham , @jlsherrill  created new issue at  [#16687](http://projects.theforeman.org/issues/16687)

**Comment by jlsherrill** [comment]
Merging thanks ranjan!

**Pull request merged**
