### PR TITLE
Fixes #32976 - revert monkey patch missing enum

### PR DESCRIPTION
**Pull request by jlsherrill**
This reverts commit 01cb7b3f613b7099b3ec3246f19d4907858f52df.

#### What are the changes introduced in this pull request?
Revert a monkey patch added due to a pulp bug

#### Considerations taken when implementing this change?
Bad Monkey, Bad!

#### What are the testing steps for this pull request?
tests pass

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test katello]

**Comment by rverdile** [comment]
does this just need an ack?

**Comment by jlsherrill** [comment]
yep!

**Review by rverdile — APPROVED** [review]
:)

**Pull request merged**
