### PR TITLE
Fixes #26908 - subscription group toggle error

### PR DESCRIPTION
**Pull request by Laviro**
JS error when opening subscription group
```
Table.js:33 Uncaught TypeError: Cannot read property 'toggleSubscriptionGroup' of undefined
    at Object.toggle (Table.js:33)
    at onClick (collapseableAndSelectionCellFormatter.js:14)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:270)
    at executeDispatch (react-dom.development.js:561)
    at executeDispatchesInOrder (react-dom.development.js:583)
    at executeDispatchesAndRelease (react-dom.development.js:680)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:688)
```

cc @waldenraines @johnpmitsch

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@Laviro the toggle error is now gone, but the toggled row collapses when you select the subscription

**Comment by johnpmitsch** [comment]
Here is a screencast demonstrating what I found: 
togglesubs

**Comment by Laviro** [comment]
Looks like this bug happened before #7971.. 
maybe we can merge this small fix
and than investigate more on the other bug?

**Comment by johnpmitsch** [comment]
@Laviro Sure thing, I filed [here](https://projects.theforeman.org/issues/26954). Looks like there is a linting fix needed and we can get this merged

**Comment by johnpmitsch** [comment]
@waldenraines Could the UI team look at the follow-up issue: https://projects.theforeman.org/issues/26954?

**Comment by Laviro** [comment]
Thanks @johnpmitsch, fixed that missing proptype

**Pull request merged**
