### PR TITLE
Fixes #16505 - do not use api for download policy setting

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Related issue: http://projects.theforeman.org/issues/16687

**Comment by daviddavis** [comment]
When I switched the default from 'immediate' to 'on_demand' and then tried to create a new repo, the default was 'immediate'. It was only when I restarted katello that it took effect. Is that intended?

**Comment by jlsherrill** [comment]
@daviddavis i think that's how BastionConfig works right now, so I guess it is intended.  @ehelms might have some insight.

**Comment by daviddavis** [comment]
Yea originally when I wrote this code I used BastionConfig but changed it because of that problem.

**Comment by jlsherrill** [comment]
@daviddavis yeah, i agree and would prefer to use settings as well.  i don't necessarily feel strongly enough to argue against http://projects.theforeman.org/issues/16687

I think we likely could switch BastionConfig to be generated dynamically

**Comment by daviddavis** [comment]
Another alternative might be to create an api endpoint that doesn't check permissions and whitelist a set of settings that can be viewed by any user. Either works though.

**Pull request merged**
