### PR TITLE
Fixes #33971 - CVV Import fails due to new Pulp 3.16 task return

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
This PR allows for the polling of Pulp tasks that return only a task group.  The import and the ACS refresh endpoints do this now.

https://docs.pulpproject.org/pulpcore/changes.html#removals

#### Considerations taken when implementing this change?
I tried to make the smallest change possible to allow for task groups only. It seems to be working fine since the BATS tests pass successfully.  I've been learning the tasking code as I go, so please let me know if you think there's a better way to do this.

#### What are the testing steps for this pull request?
1) Perform a content view version import in any way you see fit
2) Ensure it errors out
3) Patch in my PR here
4) Try another content view version import on a different organization
5) Ensure that the import completes successfully
6) Check that other tasks are not broken by these changes

### CODE REVIEW

**Comment by ianballou** [comment]
This fixes the current BATS failures.

**Review by jlsherrill — APPROVED** [review]
ACK,  it would be nice if we could test this, but maybe when we get into the ACS work, that will be a lot easier

**Comment by jlsherrill** [comment]
went ahead and merged to get the pipeline flowing

**Comment by ianballou** [comment]
Yeah, ACS refresh should be a lot easier to test than Import.

**Pull request merged**
