### PR TITLE
Refs #35873 - add ouiaIDs to ACS edit modals

### PR DESCRIPTION
**Pull request by jeremylenz**
#### What are the changes introduced in this pull request?

Add OUIA-IDs to ACS edit modals.

#### What are the testing steps for this pull request?

Create a custom ACS
Edit the ACS's details > check that the modal has a non-generated ouiaID
Edit the ACS's products > check that the modal has a non-generated ouiaID

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
Can we add this to all modals under `katello/webpack/scenes/AlternateContentSources/Details/EditModals/`

There's also the Switch : `id:"use-http-proxies-switch"` in webpack/scenes/AlternateContentSources/Details/EditModals/ACSEditSmartProxies.js that needs an ouiaId.

**Comment by jeremylenz** [comment]
> Looking at supported components for ouiaId, we can add ouiaIds to components

Not sure I'm understanding this?

**Comment by jeremylenz** [comment]
@sjha4 Added those, thanks!

**Comment by sjha4** [comment]
> > Looking at supported components for ouiaId, we can add ouiaIds to components
> 
> Not sure I'm understanding this?

Meant Text components..So if a link can't have ouiaId, we wrap the text in <Text> instead..

**Comment by jeremylenz** [comment]
> That would help with adding OuiaId to the expansion texts like Show Products on the ACS details..

That's a great idea! Added. :+1:

**Review by sjha4 — APPROVED** [review]
Awesome..The expandable sections can be selected with ouia-Ids now. 
Ack 👍🏼

**Pull request merged**
