### PR TITLE
Fixes #34711 - Search hosts by repository

### PR DESCRIPTION
**Pull request by rverdile**
#### What are the changes introduced in this pull request?
Adds scoped search for host based on repository name and content label

#### Considerations taken when implementing this change?
shrug

#### What are the testing steps for this pull request?
1. Subscribe some product with a repository to a host.
2. Log into your host and do `yum repolist all`.
3. In the rails console, search for the host by repository name using `Host.search_for('repository=[repository_name]')`. It should return the host that your repository is on. Don't forget the single quotes :) 
4. Search by content label with `Host.search_for('repository_content_label=[content_label]')`. You can get the content label with `Katello::Repository.find([id]).content.label`

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
Ack works well:

```ruby
[8] pry(main)> Host.search_for('repository="Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"')
=> [#<Host::Managed:0x00000000150f7638
  id: 4,
  name: "rhel7.vault419.example.com",
  last_compile: Wed, 30 Mar 2022 17:03:07 UTC +00:00,
  last_report: nil,
  updated_at: Wed, 30 Mar 2022 17:05:52 UTC +00:00,
  created_at: Wed, 30 Mar 2022 17:03:04 UTC +00:00,
  root_pass: nil,
  architecture_id: 1,
  operatingsystem_id: 4]
```

```ruby
Host.search_for('repository=[Red Hat Enterprise Linux 7 Server (RPMs)]')

[5] pry(main)> Host.search_for('repository_content_label=rhel-7-server-rpms')
=> [#<Host::Managed:0x000000000ffe8530
  id: 4,
  name: "rhel7.vault419.example.com",
  last_compile: Wed, 30 Mar 2022 17:03:07 UTC +00:00,
  last_report: nil,
  updated_at: Wed, 30 Mar 2022 17:05:52 UTC +00:00,
  created_at: Wed, 30 Mar 2022 17:03:04 UTC +00:00,
  root_pass: nil]
```

**Comment by parthaa** [comment]
Can you add some unit tests ? Some thing simple like https://github.com/Katello/katello/blob/master/test/models/activation_key_test.rb#L109-L112

**Comment by parthaa** [comment]
Also the issue is about adding a reporting template -> https://projects.theforeman.org/issues/34711

That part still needs to be added for the PR to be complete ?

**Comment by jeremylenz** [comment]
@parthaa the PR adding the template is in Foreman (and also needs review ;) https://github.com/theforeman/foreman/pull/9173

**Comment by jeremylenz** [comment]
Is this related to https://github.com/theforeman/foreman/pull/9173 ?

**Comment by rverdile** [comment]
> Is this related to [theforeman/foreman#9173](https://github.com/theforeman/foreman/pull/9173) ?

This looks like the inverse of my PR. Instead of "get hosts by repository" (my PR), this is "get repositories by host".

**Comment by rverdile** [comment]
I got an idea for this so I pushed it as a second commit. What do we think of it?

Auto complete and web UI search wasn't working before. This makes it so that you can search for hosts by repository in the web UI, with autocomplete. I think this is an improvement over making report template.

**Comment by parthaa** [comment]
> There are actually several Host searched_scope fields that error when using auto complete, but I made it work for these two.

Happy with the approach. Planning to add a template ?

**Comment by rverdile** [comment]
> > There are actually several Host searched_scope fields that error when using auto complete, but I made it work for these two.
> 
> Happy with the approach. Planning to add a template ?

I thought just this would be fine since the issue description asks for template or search. Should I do both?

**Comment by chris1984** [comment]
@rverdile the search is fine so we will go with that. APJ

**Comment by chris1984** [comment]
[test katello]

**Comment by parthaa** [comment]
Yeh decided search is enough. ACK :)

**Review by parthaa — APPROVED** [review]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
@rverdile looks like 2 tests are failing, once those are in should be good for a merge.

**Comment by rverdile** [comment]
thanks. i'll figure out how to fix those tests.

**Pull request merged**
