### PR TITLE
refs #8213 - add sam-installer to comps

### PR DESCRIPTION
**Pull request by mccun934**

### CODE REVIEW

**Comment by dustints** [comment]
looks good! ack per ci!

**Comment by komidore64** [comment]
is there going to be a `sam-devel-installer` ?

**Comment by ehelms** [comment]
@mccun934 I am ok if this is merged, given its a rubocop failure, and this is just a comps update.

**Comment by mccun934** [comment]
@komidore64 at some point perhaps, but not currently

**Comment by mccun934** [comment]
@ehelms thanks, merging

**Pull request merged**
