### PR TITLE
Refs #32955 - Remove old export from repositories controller

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by jturel** [comment]
lib/katello/permission_creator.rb probably needs an update too!

**Comment by jlsherrill** [comment]
here it is:  https://github.com/Katello/katello/blob/master/lib/katello/permission_creator.rb#L320-L325

we also need a db migration to remove it i think?

**Comment by chris1984** [comment]
sounds good, will update it

**Comment by chris1984** [comment]
@jlsherrill updated with a migration and permissins_creator fixed. Migration went well:

```bash
== 20210714140440 RemoveRepoExportPermission: migrating =======================
== 20210714140440 RemoveRepoExportPermission: migrated (0.0371s) ==============
```

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
