### PR TITLE
[CP] 3.15 RC2

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jlsherrill** [comment]
lets try not to squash cherry pick commits :(   I know it feels like we're damned if we do, damned if we don't

**Comment by jturel** [comment]
> lets try not to squash cherry pick commits :( I know it feels like we're damned if we do, damned if we don't

This is unfortunate. I bet he'd squashed on a previous PR and that was the default selection when this was merged. I wish it would always revert back to 'rebase and merge'

**Comment by jturel** [comment]
I haven't released the gem yet, nor tagged it. Do we want to force push this branch back in time and redo to preserve commit history of this PR?

**Comment by jlsherrill** [comment]
I think thats a great idea!

**Pull request merged**
