### PR TITLE
Fixes #27824 - handle race cond with profile upload

### PR DESCRIPTION
**Pull request by jlsherrill**
when two package profile updates come in at the same time
for the same system. This resolves it by calling our support
active_record_retry method, but also reloading the installed_package_ids
on each iteration

### CODE REVIEW

**Comment by jlsherrill** [comment]
How  i reproduced:

1) spin up a production server
2) install katello host tools on some client (could be same prod server)
3) if you've got a newer sub-man featuring a combine report, you'll want to apply https://github.com/Katello/katello-host-tools/pull/101/files to katello host tools
4) register your client to the production server
5) in a rails console run:  ```Katello::InstalledPackage.destroy_all```
6) open two terminals on your client run:  ```katello-package-upload --force```  at roughly the same time
7) check production.log for the mentioned traceback, if you don't see the error repeat step 5 & 6 until you do
8)  apply the patch, restart httpd and dynflowd
9) repeat step 5 and 6 a few times

**Comment by sjha4** [comment]
@jlsherrill : How do I do this: 

> apply https://github.com/Katello/katello-host-tools/pull/101/files to katello host tools

on a client m/c with katello-host-tools-3.5.1-2.el7.noarch?

**Comment by jlsherrill** [comment]
@sjha4 so i cheated a little bit in just modified that constants.py file to set PACKAGE_CACHE_FILE to '/var/lib/rhsm/cache/profile.json'

**Comment by sjha4** [comment]
**Without patch:**
```
2019-09-11T19:29:34 [E|bac|] PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "katello_host_installed_packages_h_id_ip_id"
19:29:34 rails.1   |  | DETAIL:  Key (host_id, installed_package_id)=(1, 2247) already exists.
19:29:34 rails.1   |  | : INSERT INTO katello_host_installed_packages (installed_package_id, host_id) VALUES (2247, 1), (2226, 1), (2215, 1), (2258, 1), (2268, 1), (2234, 1), (2251, 1), (2250, 1), (2243, 1), (2274, 1), (2267, 1), (2242, 1), (2252, 1), (2216, 1), (2240, 1), (2257, 1), (2259, 1), (2249, 1), (2253, 1), (2248, 1), (2227, 1), (2231, 1), (2239, 1), (2246, 1), (2238, 1), (2263, 1), (2270, 1), (2256, 1), (2264, 1), (2273, 1), (2236, 1), (2255, 1), (2218, 1), (2271, 1), (2269, 1), (2245, 1), (2241, 1), (2217, 1), (2224, 1), (2228, 1), (2229, 1), (2223, 1), (2220, 1), (2221, 1), (2225, 1), (2232, 1), (2262, 1), (2222, 1), (2235, 1), (2237, 1), (2275, 1), (2261, 1), (2266, 1), (2233, 1), (2265, 1), (2230, 1), (2272, 1), (2260, 1), (2244, 1), (2254, 1), (2219, 1), (2276, 1), (2277, 1), (2278, 1), (2280, 1), (2282, 1), (2284, 1), (2286, 1), (2288, 1), (2290, 1), (2292, 1), (2294, 1), (2296, 1), (2297, 1), (2298, 1), (2299, 1), (2301, 1), (2302, 1), (2304, 1), (2306, 1), (2308, 1), (2310, 1), (2312, 1), (2314, 1), (2316, 1), (2318, 1), (2320, 1), (2322, 1), (2324, 1), (2326, 1), (2328, 1), (2330, 1), (2332, 1), (2334, 1), (2336, 1), (2338, 1), (2340, 1), (2342, 1), (2344, 1), (2346, 1), (2348, 1), (2350, 1), (2352, 1), (2353, 1), (2355, 1), (2357, 1), (2359, 1), (2361, 1), (2363, 1), (2365, 1), (2367, 1), (2369, 1), (2371, 1), (2373, 1), (2375, 1), (2377, 1), (2379, 1), (2381, 1), (2383, 1), (2385, 1), (2387, 1), (2389, 1), (2391, 1), (2393, 1), (2395, 1), (2397, 1), (2399, 1), (2400, 1), (2402, 1), (2404, 1), (2406, 1), (2408, 1), (2410, 1), (2412, 1), (2414, 1), (2415, 1), (2417, 1), (2419, 1), (2420, 1), (2422, 1), (2423, 1), (2425, 1), (2427, 1), (2429, 1), (2431, 1), (2433, 1), (2435, 1), (2437, 1), (2439, 1), (2441, 1), (2443, 1), (2445, 1), (2447, 1), (2449, 1), (2451, 1), (2453, 1), (2455, 1), (2457, 1), (2459, 1), (2461, 1), (2463, 1), (2465, 1), (2467, 1), (2469, 1), (2470, 1), (2472, 1), (2474, 1), (2476, 1), (2478, 1), (2480, 1), (2482, 1), (2484, 1), (2486, 1), (2488, 1), (2490, 1), (2492, 1), (2494, 1), (2496, 1), (2498, 1), (2500, 1), (2502, 1), (2504, 1), (2506, 1), (2508, 1), (2510, 1), (2512, 1), (2514, 1), (2516, 1), (2518, 1), (2520, 1), (2522, 1), (2524, 1), (2526, 1), (2528, 1), (2530, 1), (2532, 1), (2533, 1), (2535, 1), (2537, 1), (2539, 1), (2541, 1), (2543, 1), (2545, 1), (2547, 1), (2549, 1), (2551, 1), (2553, 1), (2555, 1), (2557, 1), (2559, 1), (2561, 1), (2563, 1), (2565, 1), (2567, 1), (2569, 1), (2571, 1), (2573, 1), (2574, 1), (2576, 1), (2578, 1), (2580, 1), (2582, 1), (2584, 1), (2586, 1), (2588, 1), (2590, 1), (2592, 1), (2594, 1), (2596, 1), (2598, 1), (2600, 1), (2602, 1), (2604, 1), (2606, 1), (2608, 1), (2610, 1), (2612, 1), (2614, 1), (2616, 1), (2618, 1), (2620, 1), (2622, 1), (2624, 1), (2626, 1), (2628, 1), (2630, 1), (2632, 1), (2634, 1), (2636, 1), (2638, 1), (2640, 1), (2642, 1), (2644, 1), (2646, 1), (2648, 1), (2650, 1), (2652, 1), (2654, 1), (2656, 1), (2658, 1), (2660, 1), (2662, 1), (2664, 1), (2666, 1), (2668, 1), (2670, 1), (2672, 1), (2673, 1), (2676, 1), (2678, 1), (2680, 1), (2682, 1), (2684, 1), (2686, 1), (2688, 1), (2690, 1), (2692, 1), (2694, 1), (2696, 1), (2698, 1), (2700, 1), (2702, 1), (2704, 1), (2706, 1), (2708, 1), (2710, 1), (2712, 1), (2714, 1), (2716, 1), (2718, 1), (2720, 1), (2722, 1), (2724, 1), (2726, 1), (2728, 1), (2730, 1), (2731, 1), (2733, 1), (2735, 1), (2737, 1), (2739, 1), (2741, 1), (2743, 1), (2745, 1), (2747, 1), (2748, 1), (2750, 1), (2752, 1), (2754, 1), (2755, 1), (2757, 1), (2759, 1), (2761, 1), (2763, 1), (2765, 1), (2767, 1), (2769, 1), (2770, 1), (2772, 1), (2774, 1), (2776, 1), (2778, 1), (2780, 1), (2782, 1), (2784, 1), (2786, 1), (2788, 1), (2790, 1), (2792, 1), (2794, 1), (2796, 1), (2798, 1), (2800, 1), (2801, 1), (2802, 1), (2803, 1), (2804, 1), (2805, 1), (2807, 1), (2809, 1), (2811, 1), (2813, 1), (2815, 1), (2817, 1), (2819, 1), (2821, 1), (2823, 1), (2825, 1), (2827, 1), (2829, 1), (2831, 1), (2833, 1), (2835, 1), (2837, 1), (2839, 1), (2841, 1), (2843, 1), (2845, 1), (2847, 1), (2849, 1), (2851, 1) (ActiveRecord::RecordNotUnique)
```
**With patch:**
I didn't see this in several runs. The Katello::InstalledPackage.count comes to 361 before/after patch so it looks like the upload is behaving as intended. ACK from my testing..:heavy_check_mark:

**Comment by parthaa** [comment]
ack

**Pull request merged**
