### PR TITLE
Fixes #23326 - Create active jobs properly

### PR DESCRIPTION
**Pull request by adamruzicka**
requires:
- [ ] https://github.com/theforeman/foreman/pull/5575

### CODE REVIEW

**Comment by parthaa** [comment]
Can you also update -> https://github.com/Katello/katello/blob/master/katello.gemspec#L31

**Comment by adamruzicka** [comment]
@parthaa Just to bring latest foreman-tasks into katello or to ensure the needed method will be present?

**Comment by jlsherrill** [comment]
@adamruzicka i assume to make sure our dev envs get updated properly (and to properly express the dependency).

**Comment by adamruzicka** [comment]
Given the new triggering method comes from foreman core, shall I bump the dependency on foreman as well (I assume it will land in 1.18)

**Comment by jturel** [comment]
@adamruzicka this looks good to me. do you agree @parthaa ?

**Comment by parthaa** [comment]
ack

**Comment by iNecas** [comment]
How does this change get to Katello 3.7?

**Comment by jlsherrill** [comment]
@iNecas it already is: http://projects.theforeman.org/issues/23326 is marked against 3.7.  It should appear in the next RC

**Pull request merged**
