### PR TITLE
Fixes #12556 - remove System model

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by daviddavis** [comment]
Is this ready for review? If so, can you rebase?

**Comment by johnpmitsch** [comment]
looks like [this reference to Katello::System](https://github.com/Katello/katello/blob/master/app/lib/katello/util/model.rb#L33) can be removed

**Comment by jlsherrill** [comment]
@johnpmitsch good find, updated

**Comment by ehelms** [comment]
ACK for me -- final for @johnpmitsch

**Comment by johnpmitsch** [comment]
ACK

**Pull request merged**
