### PR TITLE
Fixes #21923 - Correct API endpoint for auto_attach/remove/add subscription in host bulk action

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by jturel** [comment]
@akofink maybe you can provide ranjan a little more specific detail on what you'd like to see change?

**Comment by akofink** [comment]
I don't think we want this change at all upstream. It's a downstream-only change, afaict.

**Comment by jturel** [comment]
Oh, you meant what you said! Thanks for clarifying.

**Comment by ranjan** [comment]
@akofink  As per API Doc, the correct endpoint is 
https://github.com/Katello/katello/blob/4b90abce5d9f0bb593aa5c7cbb5eab3c3cf566fb/app/controllers/katello/api/v2/hosts_bulk_actions_controller.rb#L180

Shall we modify the API Doc to /hosts/bulk/auto_attach ?

**Comment by akofink** [comment]
I'm really not sure why the routes were made this way. Perhaps @parthaa could shed some light on why we didn't just use the correct API route in the controller. Note that there are route overrides [here](https://github.com/Katello/katello/blob/master/config/routes/overrides.rb#L66-L68), and that's what's making the routes currently work as written.

**Comment by jlsherrill** [comment]
I'm guessing this was a mistake and they were supposed to go under /hosts/bulk/subscriptions/

However, since they have been under /hosts/bulk for a while and the UI is currently coded to use them, I would suggest leaving the routes as is and update the api docs

**Comment by ranjan** [comment]
Thanks @jlsherrill,  Update API doc

**Pull request merged**
