### PR TITLE
Fixes #32786 - fix pulp task group cancel

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ekohl** [comment]
Shouldn't this be a cherry pick? (I only noticed this because I just changed the PR processor and this is the first PR that actually made an update to Redmine).

**Comment by jlsherrill** [comment]
it would have yes, but the fix for 3.18 is slightly different: https://github.com/Katello/katello/pull/9401

**Comment by ekohl** [comment]
Ah yes. I just wondered if setting both URLs in Redmine's PR URL field was correct. There is logic to determine a cherry pick by looking at the PR title, but I'm wondering if that still makes sense. Personally I like the PR URLs to cherry picks in Redmine. Perhaps not the place to discuss it.

**Review by jturel — APPROVED** [review]
ACK

```
Jun 22 18:36:04 centos7-katello-3-18.jturel.example.com pulpcore-api[14457]: - - [22/Jun/2021:18:36:04 +0000] "GET /pulp/api/v3/tasks/?limit=2000&offset=0&state__in=running%2Cwaiting HTTP/1.1" 200 501 "-" "OpenAPI-Generator/3.7.1/ruby"
Jun 22 18:36:04 centos7-katello-3-18.jturel.example.com pulpcore-resource-manager[14652]: pulp: rq.worker:INFO: resource-manager: Job OK (5bda91f9-4667-402a-803b-6e397cc99e14)
Jun 22 18:36:04 centos7-katello-3-18.jturel.example.com pulpcore-worker-1[14268]: pulp: rq.worker:INFO: 14268@centos7-katello-3-18.jturel.example.com: 41201029-0754-435e-9aae-7ad6ab2bfc60
Jun 22 18:36:04 centos7-katello-3-18.jturel.example.com pulpcore-worker-1[14268]: pulp: pulp_rpm.app.tasks.publishing:INFO: Publishing: repository=TestRepo-1477, version=0
Jun 22 18:36:05 centos7-katello-3-18.jturel.example.com pulpcore-worker-1[14268]: pulp: rq.worker:INFO: 14268@centos7-katello-3-18.jturel.example.com: Job OK (41201029-0754-435e-9aae-7ad6ab2bfc60)
Jun 22 18:36:05 centos7-katello-3-18.jturel.example.com pulpcore-worker-1[14268]: pulp: rq.worker:INFO: 14268@centos7-katello-3-18.jturel.example.com: 81441582-2870-4e5a-9662-870524a5ef64
Jun 22 18:36:05 centos7-katello-3-18.jturel.example.com pulpcore-worker-1[14268]: pulp: rq.worker:INFO: 14268@centos7-katello-3-18.jturel.example.com: Job OK (81441582-2870-4e5a-9662-870524a5ef64)
Jun 22 18:36:05 centos7-katello-3-18.jturel.example.com pulpcore-api[14457]: pulp: pulpcore.tasking.util:INFO: Task canceled: 41201029-0754-435e-9aae-7ad6ab2bfc60.
Jun 22 18:36:05 centos7-katello-3-18.jturel.example.com pulpcore-api[14457]: - - [22/Jun/2021:18:36:05 +0000] "PATCH /pulp/api/v3/tasks/41201029-0754-435e-9aae-7ad6ab2bfc60/ HTTP/1.1" 200 523 "-" "OpenAPI-Generator/3.7.1/ruby
```

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
