### PR TITLE
Refs #10767 - task summary widgets to content dashboard

### PR DESCRIPTION
**Pull request by dustints**
Depends on https://github.com/theforeman/foreman-tasks/pull/109
* add widget that show task count by state/status
* adds list of the latest tasks in warning and error

### CODE REVIEW

**Comment by ehelms** [comment]
This looks similar to the previous PR, and still looks generic enough to live in foreman-tasks. What I am saying is, what about this is content specific?

**Comment by waldenraines** [comment]
Couldn't this replace the notifications widget on the content dashboard?

See also [BZ 1225945: Content Dashboard -> Latest Notifications is blank always](https://bugzilla.redhat.com/show_bug.cgi?id=1225945).

**Comment by ehelms** [comment]
Pretty sure I ripped out the notifications widget. But I feel like my question still stands. This appears to be generic enough that foreman-tasks could add it to the dashboard and show tasks such that this isn't a 'katello' only thing (other things will be taking advantage of foreman-tasks over time).

**Comment by waldenraines** [comment]
> Pretty sure I ripped out the notifications widget.

That's right, I remember seeing that.  I linked up the aforementioned BZ to the redmine issue and set it to post.

**Comment by dustints** [comment]
@ehelms abandoning ....moving widgets to foreman's dashboard

**Pull request closed without merging**
