### PR TITLE
Fixes #37517 - Upgrade theforeman-rubocop gem to the  v0.1.0

### PR DESCRIPTION
**Pull request by archanaserver**
#### What are the changes introduced in this pull request?

- Upgrade theforeman-rubocop gem to version 0.1.0, https://community.theforeman.org/t/standardizing-rubocop-with-theforeman-rubocop/37239/1#use-theforeman-rubocop-010-in-foreman-and-all-plugins-1
- Changed the RuboCop configuration to inherit from the `lenient.yml` style provided by `theforeman-rubocop`, https://github.com/theforeman/theforeman-rubocop?tab=readme-ov-file#not-intrusive-style---lenient
- Removed `Rails` and `Style/Documentation` cops from the configuration as they are already included in the `lenient.yml` style.

#### Considerations taken when implementing this change?

- Chose `lenient.yml` because it aligns well with the existing RuboCop style followed by this repo.
- Removed `Rails` and `Style/Documentation` cops to avoid redundancy and conflicts since they are already covered by `lenient.yml`.

#### What are the testing steps for this pull request?

1. Run `bundle install` to ensure all dependencies are correctly installed, including the updated `theforeman-rubocop` gem.
2. Execute `bundle exec rubocop` to verify that the new RuboCop configuration is being applied without errors.
3. Review the output to ensure there are no unexpected offenses or configuration issues.

### CODE REVIEW

**Comment by archanaserver** [comment]
Note: While testing, there are new RuboCop offenses now. It's unclear for me to know which offenses to fix based on the code style, so should I consider regenerating the `.rubocop_todo.yml` file or I believe we can discuss further.

**Review by jeremylenz — COMMENTED** [review]
Here are my thoughts about specific rules that are failing currently:

```
Style/OptionalBooleanParameter: Prefer keyword arguments for arguments with a boolean default value; use `redirect_on_failure: true` instead of `redirect_on_failure = true`.
```
Yeah kwargs! :+1:  I like them in general because they're more explicit, but they can make function definitions _long_. In the case of Booleans, though, I think requiring them outweighs that, so I'm for it.

```
Style/TrailingCommaInHashLiteral: Put a comma after the last item of a multiline hash.
```
This will be a big change for Katello's Ruby, but it will also bring us in line with `eslint` and our JS code. If Foreman is adopting this, I think Katello should too. :+1: 

```
Style/SlicingWithRange: Prefer ary[n..] over ary[n..-1].
```
uhh sure why not!

```
Rails/HttpStatus: Prefer `:ok` over `200` to define HTTP status code.
```
We do this in most every place, so I'm +1 to this rule.

```
Style/CaseLikeIf: Convert `if-elsif` to `case-when`.
```
I do like `case-when` better, but this may get pushback from some veteran Rubyists. @parthaa thoughts?

**Comment by chris1984** [comment]
> Here are my thoughts about specific rules that are failing currently:
> 
> ```
> Style/OptionalBooleanParameter: Prefer keyword arguments for arguments with a boolean default value; use `redirect_on_failure: true` instead of `redirect_on_failure = true`.
> ```
> Yeah kwargs! :+1:  I like them in general because they're more explicit, but they can make function definitions _long_. In the case of Booleans, though, I think requiring them outweighs that, so I'm for it.
> 
> ```
> Style/TrailingCommaInHashLiteral: Put a comma after the last item of a multiline hash.
> ```
> This will be a big change for Katello's Ruby, but it will also bring us in line with `eslint` and our JS code. If Foreman is adopting this, I think Katello should too. :+1: 
> 
> ```
> Style/SlicingWithRange: Prefer ary[n..] over ary[n..-1].
> ```
> uhh sure why not!
> 
> ```
> Rails/HttpStatus: Prefer `:ok` over `200` to define HTTP status code.
> ```
> We do this in most every place, so I'm +1 to this rule.
> 
> ```
> Style/CaseLikeIf: Convert `if-elsif` to `case-when`.
> ```
> I do like `case-when` better, but this may get pushback from some veteran Rubyists. @parthaa thoughts?
> 
> 
> 

I'm a junior Rubyist if that counts for anything?

**Comment by jeremylenz** [comment]
@archanaserver I haven't seen any dissents so I'd say you can go ahead with keeping these rules and fixing them.

**Comment by archanaserver** [comment]
> ```
> Style/OptionalBooleanParameter: Prefer keyword arguments for arguments with a boolean default value; use `redirect_on_failure: true` instead of `redirect_on_failure = true`.
> ```
> 
> Yeah kwargs! 👍 I like them in general because they're more explicit, but they can make function definitions _long_. In the case of Booleans, though, I think requiring them outweighs that, so I'm for it.

@jeremylenz yes, so looking at the `Style/OptionalBooleanParameter` rule causing approx 60 offenses rn, changing to boolean keyword arguments may enhance our code readability and clarity, but implementing such changes should be considered in a huge refactor. This change would require every method call across the codebase, and could break things. I guess just to make RuboCop happy, this would not be a good idea.

Out current implementation works correctly here and this rule is purely a stylistic preference only and no any other concern. Therefore, I recommend not enforcing this rule at this time to avoid unnecessary complications. We have followed the same approach in some other repos. WDYT?

Also, I have raised few PRs for different cops. Do you want me to update the rubocop_todo file after the changes got merged?

**Comment by jeremylenz** [comment]
> I recommend not enforcing this rule at this time to avoid unnecessary complications. We have followed the same approach in some other repos.

If we've got consistency across repos, I'm fine with this. :+1: 

> I have raised few PRs for different cops. Do you want me to update the rubocop_todo file after the changes got merged?

What does that mean exactly?

**Comment by archanaserver** [comment]
> 
> > I have raised few PRs for different cops. Do you want me to update the rubocop_todo file after the changes got merged?
> 
> What does that mean exactly?

@jeremylenz so even after fixing cops like Style/TrailingCommaInHashLiteral, Style/SlicingWithRange, Rails/HttpStatus and Style/CaseLikeIf. There are still many other cops causing failure in RuboCop job run.

Some of them are from Style/, Layout/, Lint/, Metrics/ and Minitest/. Do you want continue fixing each one of them or want to proceed for now by updating .rubocop_todo.yml file, adding all those in todo list for later fix.

**Comment by jeremylenz** [comment]
> Do you want continue fixing each one of them or want to proceed for now by updating .rubocop_todo.yml file, adding all those in todo list for later fix.

I would prefer to have little or nothing in todo. I feel like most of them should be resolved with `--auto-correct`? How does it look after you run that?

**Comment by archanaserver** [comment]
This is to track list of PRs submitted to fixing cops, after the  theforeman-rubocop version update:

- [ ] https://github.com/Katello/katello/pull/11043
- [ ] https://github.com/Katello/katello/pull/11046
- [ ] https://github.com/Katello/katello/pull/11047
- [ ] https://github.com/Katello/katello/pull/11048
- [ ] https://github.com/Katello/katello/pull/11064
- [ ] https://github.com/Katello/katello/pull/11065
- [ ] https://github.com/Katello/katello/pull/11066
- [ ] https://github.com/Katello/katello/pull/11067

**Comment by archanaserver** [comment]
> > Do you want continue fixing each one of them or want to proceed for now by updating .rubocop_todo.yml file, adding all those in todo list for later fix.
> 
> I would prefer to have little or nothing in todo. I feel like most of them should be resolved with `--auto-correct`? How does it look after you run that?

@jeremylenz I'm on it! I did use `rubocop --auto-correct`, but some offenses required manually adjustments or a scan through to ensure that the change not breaking anything.

I'm making sure to fix the rules which seems relevant and safe to use, or decided to put some marked disabled by following rest of the foreman repo's, like this https://github.com/Katello/katello/pull/11067/commits/9ab6e28ca3e07c9df8936aa90e84d00fec09bb8a. WDYT?

**Comment by jeremylenz** [comment]
> I'm making sure to fix the rules which seems relevant and safe to use, or decided to put some marked disabled by following rest of the foreman repo's, like this [9ab6e28](https://github.com/Katello/katello/commit/9ab6e28ca3e07c9df8936aa90e84d00fec09bb8a). WDYT?

If we are consistent with other repos then :+1: :rocket:

**Comment by ianballou** [comment]
@archanaserver is there a particular order that you'd like these PRs merged? I wasn't sure if there were interdependencies that required some to go before others.
To avoid having a period of time where rubocop is broken across the board, I guess we should merge all of them at once?

**Comment by archanaserver** [comment]
> @archanaserver is there a particular order that you'd like these PRs merged? I wasn't sure if there were interdependencies that required some to go before others. To avoid having a period of time where rubocop is broken across the board, I guess we should merge all of them at once?

@ianballou This particular PR require [all of these PRs](https://github.com/Katello/katello/pull/11009#issuecomment-2213503610) to merge(in any order) first, so that we have all the new rubocop rules here after the theforeman-rubocop gem update to v0.1.0. Also this will make the rubocop job green here.

**Comment by archanaserver** [comment]
@ianballou some of the PRs from the [list](https://github.com/Katello/katello/pull/11009#issuecomment-2213503610) are approved by others and ready to be merge i belive, would you mind taking a look?

**Comment by archanaserver** [comment]
@ianballou I see some failure in rubocop rules here and tried to fix those here https://github.com/Katello/katello/pull/11064

**Comment by archanaserver** [comment]
@ianballou  i don't understand this failure, can you help me here? As per the code change I have specified this gem only once, not sure from where it is detecting two different versions.
```
 [!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: theforeman-rubocop (~> 0.0.6) and theforeman-rubocop (~> 0.1.0). Bundler cannot continue.
```

**Comment by archanaserver** [comment]
> @ianballou i don't understand this failure, can you help me here? As per the code change I have specified this gem only once, not sure from where it is detecting two different versions.
> 
> ```
>  [!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
> You specified: theforeman-rubocop (~> 0.0.6) and theforeman-rubocop (~> 0.1.0). Bundler cannot continue.
> ```

i've rebase this with recent changes but seeing the above issue again, if someone can point me here what i am missing here?

**Comment by ianballou** [comment]
I'm out for a while, so let me redirect this to @sjha4 or @qcjames53

**Comment by archanaserver** [comment]
hie @ianballou, could you please find moment to dropping some reviews here?

**Comment by ianballou** [comment]
Since the tests are broken I'm running them locally. Will report back soon.

**Comment by ianballou** [comment]
Only saw one test failure that is likely not related to this PR:
```
Error:
Katello::PxeFilesDownloaderTest#test_fetches_pxe_files:
OpenSSL::X509::CertificateError: invalid digest
    /home/vagrant/katello/test/services/katello/pxe_files_downloader_test.rb:49:in `sign'
    /home/vagrant/katello/test/services/katello/pxe_files_downloader_test.rb:49:in `generate_certificate'
    /home/vagrant/katello/test/services/katello/pxe_files_downloader_test.rb:14:in `test_fetches_pxe_files'
```

**Comment by ianballou** [comment]
This should be good to ACK once the rebase is done :+1:

**Comment by ehelms** [comment]
> [!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: theforeman-rubocop (~> 0.0.6) and theforeman-rubocop (~> 0.1.0). Bundler cannot continue.

I see this error output. Is this due to Katello specifying `theforeman-rubocop` and inheriting it via Foreman? If katello is inheriting it from Foreman, why specify it in the `test.rb` Gemfile?

I think, unlike other plugins, Katello has a tight relationship with Foreman's target version of the `theforeman-rubocop` that creates this coupling and this will happen anytime the version gets bumped by one or the other. 

I am thinking one of two approaches would help:

1. Move `theforeman-rubocop` to the `.gemspec` as a development dependency like other plugins (https://github.com/theforeman/foreman_ansible/blob/master/foreman_ansible.gemspec#L26). This will mean when the test suite is run it runs with `--without development` and it will ignore this. But it will grab it when it does the rubocop job.

2. Add a `gemfile.d/lint.rb` file and specify `theforeman-rubocop` there, and then make sure the test suite includes `--without lint`

**Comment by ianballou** [comment]
> I think, unlike other plugins, Katello has a tight relationship with Foreman's target version of the `theforeman-rubocop` that creates this coupling and this will happen anytime the version gets bumped by one or the other.

Any chance this is just leftover from when we ran rubocop directly in Katello instead of via foreman-rake katello:rubocop? I wonder if it can be removed entirely.

**Comment by archanaserver** [comment]
> > I think, unlike other plugins, Katello has a tight relationship with Foreman's target version of the `theforeman-rubocop` that creates this coupling and this will happen anytime the version gets bumped by one or the other.
> 
> Any chance this is just leftover from when we ran rubocop directly in Katello instead of via foreman-rake katello:rubocop? I wonder if it can be removed entirely.

I believe in that case it’s better to first test removing the gem declaration from Katello's Gemfile and rely on Foreman's version to see if this resolves the conflict. That would also mean we need to merge the Foreman PR first. If that doesn’t work, I’ll explore the alternative options that @ehelms  suggested, such as moving it to the .gemspec or gemfile.d/lint.rb.

**Comment by archanaserver** [comment]
This now passing all the checks, also added few more fixes for different rubocop offenses. @ianballou @jeremylenz do you have any thoughts on this?

**Comment by jeremylenz** [comment]
If you squash the commits that'll take care of the "Redmine issues" check :)

**Comment by archanaserver** [comment]
> If you squash the commits that'll take care of the "Redmine issues" check :)

Done @jeremylenz ! You can take a look now.

**Comment by archanaserver** [comment]
> Can this merge now? Is it waiting on any dependencies?

Yes, we can merge this now.

**Comment by ianballou** [comment]
Thanks @archanaserver !

**Pull request merged**
