### PR TITLE
Fixes #15524 - don't interfere with puppet fact's last_import

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by stbenjam** [comment]
I prefer not to fix Foreman bugs inside Katello if at all possible.  In fact, I think this is quite easy to fix as the last_compile check is ancient and could probably just get removed.

https://github.com/theforeman/foreman/pull/3615

**Comment by stbenjam** [comment]
This also causes the subscription-manager facts to show the reported at time of Puppet which is kind of weird, I also fixed that in the foreman PR.

**Comment by iNecas** [comment]
I know. I was just not sure if the check for last compile is still valid or not. Let's see how it goes in foreman. Thanks for doing this.

**Comment by stbenjam** [comment]
Foreman PR was merged, I think this one can be closed

**Comment by iNecas** [comment]
@stbenjam++

**Pull request closed without merging**
