### PR TITLE
Fixes #25818 - Show virt-who hypervisor type

### PR DESCRIPTION
**Pull request by johnpmitsch**
virt-who hypervisors use "hypervisor::type" fact rather than
"virt::host_type" for type. This commit updates the UI
to check for both.

To review, [register a virt-who hypervisor](https://gist.github.com/johnpmitsch/fc7d15b314fbb395486ec5051974e649) and check
the type field in the content host details page is
filled out.

This PR is based on https://github.com/Katello/katello/pull/7821, which is currently in this PR. I'll rebase when it is merged.
It also requires a [foreman PR](https://github.com/theforeman/foreman/pull/6398), you will need to check that out manually

### CODE REVIEW

**Comment by beav** [comment]
@johnpmitsch rebase time

**Comment by beav** [comment]
both lines changed in the second commit seem straightforward to me

**Comment by evgeni** [comment]
We already enhance the Host object to have a hypervisor property, that is computed from multiple facts and reflects whether the host is a hypervisor or not.

My thought around adding a more generic type to it is that this would allow all clients to behave the same, without duplicating the logic.

Plus the user who writes a client might not be aware of all the possible facts. Like today if they have RHV/oVirt, virt::host_type is present, they write a client that uses this property. And if they add VMware tomorrow, they'll wonder why their client isn't working as it should.

**Comment by beav** [comment]
> I wonder, if we should add a "synthetic" `type` fact, that gets computed out of `host.facts["virt::host_type"] || host.facts["hypervisor::type"]`?
> 
> or maybe even smth like: https://github.com/RedHatSatellite/katello-attach-subscription/blob/master/lib/katello_attach_subscription/fact_analyzer.rb#L9-L23

I think a synthetic fact may cause confusion in the future, if people try to figure out where it's being reported.

If there was a helper or some other place that the computed value lives, I am OK with that.

**Comment by johnpmitsch** [comment]
> Plus the user who writes a client might not be aware of all the possible facts. Like today if they have RHV/oVirt, virt::host_type is present, they write a client that uses this property. And if they add VMware tomorrow, they'll wonder why their client isn't working as it should.

These are some fair points, I'm thinking another property in the API response would be better than a new host fact though. (I think this is what the hypervisor one is?). Do you think we could do the interpreting of facts at that level and it would solve these concerns?

**Comment by evgeni** [comment]
Yeah, another property is a good plan. Also makes it clear that "this is what we consider the host type" vs "these are all the various facts something reported about the host"

**Comment by johnpmitsch** [comment]
another update for reviewers: This PR no longer relies on any other PR

**Comment by johnpmitsch** [comment]
I'm thinking I will take a look at this further and how we use facts. Right now, us providing facts comes from the assumption there is a content facet since it [is provided here](https://github.com/Katello/katello/blob/master/app/views/katello/api/v2/content_facet/show.json.rabl#L25) in the content facet rabl. Foreman does not show facts for a single host.

I think we should change the UI to use `/host/id/facts` to get the facts for the host to use in the UI since content hosts w/o a content facet (like virt-who hypervisors) won't show facts. This affects fields like `memory` in the UI, for example.

**Comment by johnpmitsch** [comment]
@beav Looking into the facts is a bit of a pandora's box, I'm going to do that separately outside of this PR. Please review normally :)

**Comment by johnpmitsch** [comment]
@evgeni everything look ok to you?

**Comment by evgeni** [comment]
> @evgeni everything look ok to you?

it certainly does!

**Pull request merged**
