### PR TITLE
Fixes #20716: enable toggling of the experimental UI.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/20716

### CODE REVIEW

**Comment by ehelms** [comment]
Should this include a bit more before it's pulled in? I mean, I guess we can argue that the experimental UI is non-existent for now so it does toggle it.

**Comment by waldenraines** [comment]
> Should this include a bit more before it's pulled in? I mean, I guess we can argue that the experimental UI is non-existent for now so it does toggle it.

Yeah, and I just wanted to get this in so we could review what's coming without this as being part of it.  Part of it was for me to not forget to do this as well 😄 

Let me know if you want me to wait until we have more.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by waldenraines** [comment]
@ehelms thoughts on the above?

**Pull request merged**
