### PR TITLE
fixes #20888 - hostgroup create exception handling

### PR DESCRIPTION
**Pull request by amitkarsale**

### CODE REVIEW

**Comment by ares** [comment]
looks reasonable to me, though similar patch should also go to foreman core. I'll be offline next week.

**Comment by jlsherrill** [comment]
Actually i don't think katello even needs to inlcude the create and update methods here.  They were only there to include additional apipieparams iirc.

**Comment by amitkarsale** [comment]
@jlsherrill you are right, the `create` and `update` methods are not needed in katello. Have created a related PR for this issue fix at : https://github.com/theforeman/foreman/pull/6084

@ares

**Comment by xprazak2** [comment]
[test katello]

**Comment by johnsonm325** [comment]
[test katello]

**Comment by amitkarsale** [comment]
@ares is it good to merge?

**Comment by johnsonm325** [comment]
@amitkarsale I tested this a bit and got some errors around the repositories_controller:

```
2019-01-08T16:11:51 [I|app|0e624]   Rendering /home/vagrant/katello/app/views/katello/api/v2/repository_sets/index.json.rabl within katello/api/v2/layouts/collection
2019-01-08T16:11:51 [I|app|0e624]   Rendered /home/vagrant/katello/app/views/katello/api/v2/repository_sets/index.json.rabl within katello/api/v2/layouts/collection (37.8ms)
2019-01-08T16:11:51 [E|app|0e624] ActionView::Template::Error: PG::UndefinedColumn: ERROR:  column katello_repositories.product_id does not exist
 | LINE 1: ...lo_content_view_versions"."content_view_id" WHERE "katello_r...
 |                                                              ^
 | : SELECT "katello_repositories".* FROM "katello_repositories" INNER JOIN "katello_content_view_versions" ON "katello_content_view_versions"."id" = "katello_repositories"."content_view_version_id" INNER JOIN "katello_content_views" ON "katello_content_views"."id" = "katello_content_view_versions"."content_view_id" WHERE "katello_repositories"."product_id" = $1 AND "katello_content_views"."default" = $2 AND (url IS NOT NULL) AND "katello_repositories"."content_id" = $3
```

I'm going to suggest a rebase here if it hasn't already been done. You obviously didn't make changes to the repositories_controller, so I'm thinking/hoping the rebase may fix everything.

**Comment by amitkarsale** [comment]
@johnsonm325 Rebased!

**Comment by jturel** [comment]
Tested in conjunction with https://github.com/theforeman/foreman/pull/6084 and I get a better message:

```
Could not create the hostgroup:
  subnet_id with id 1 not found
```

**Comment by jturel** [comment]
I'll merge once the foreman PR is merged

**Comment by jjeffers** [comment]
Closing this as the dependent foreman PR is also closed.

**Pull request closed without merging**
