### PR TITLE
Fixes #16464 - Inconsistent use of scrollbars in the UI

### PR DESCRIPTION
**Pull request by kgaikwad**
Under 'Content' Tab, scroll bars are applied differently in different areas of the UI.

There should be consistency in use of scroll bars throughout the UI especially while showing list of records in table format.

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@waldenraines is this PR still relevant with the changes you are making?

**Comment by waldenraines** [comment]
> @waldenraines is this PR still relevant with the changes you are making?

No it's not.  I think this can likely be closed.

**Comment by ehelms** [comment]
Thanks @kgaikwad based on comments above, going to close this. If you want to re-open and rebase it with more info as to why its still relevant we will consider it again.

**Pull request closed without merging**
