### PR TITLE
Fixes #14574 - set Kickstart ptable to be available in default taxonomies

### PR DESCRIPTION
**Pull request by ares**
Uses the same technique as provisioning templates.

### CODE REVIEW

**Comment by stbenjam** [comment]
Hmm, I'd rather not have this in Katello, we've had troubles in the past by touching objects that Foreman seeds so I'd prefer to avoid that as much as possible. 

The partition tables do get marked as default:
  https://github.com/theforeman/foreman/blob/develop/db/seeds.d/08-partition_tables.rb#L21

IMHO this should be a bug in Foreman, Foreman should handle putting the default templates it creates in the default taxonomies.

**Comment by stbenjam** [comment]
And I realize we have this code in Katello as a workaround: https://github.com/Katello/katello/blob/master/db/seeds.d/103-provisioning_templates.rb#L36-L42

But I think that should get refactored to only touch templates Katello creates.

**Comment by iNecas** [comment]
As long as we keep the numbers in the seeds file names ordered by dependencies, it should not cause troubles. I'm ok with the current fix and an issue to track extracting that into Foreman

**Comment by iNecas** [comment]
Tested and works as expected

**Comment by stbenjam** [comment]
> I'm ok with the current fix and an issue to track extracting that into Foreman

I'm not, the issue should get moved to Foreman and solved there, sorry.  Code will be basically the same.

**Comment by stbenjam** [comment]
I only say this because I've hacked Katello to fix a Foreman issue and had to deal with the problems it caused.

In this case, there's no reason it can't get fixed in Foreman correctly, it's relatively small.  If it causes some long drawn out discussion in Foreman and it's too difficult to get it core we can revisit it.  But, I can't see why, `default` means something in Foreman, and it's not working on their seeded objects.

**Comment by mccun934** [comment]
this patch doesn't look specific to Katello at all and not sure why it should be carried here, seems like it should be in Foreman proper.

**Comment by ares** [comment]
I put it to Katello since it already did it for provisioning templates. Also it did some associations before Foreman had a default flag. But I agree with @stbenjam, it seems more like Foreman bug that it does associate templates in seeds so I'll open PR there and we can close this if it gets merged.

**Comment by ares** [comment]
Opened a PR against Foreman https://github.com/theforeman/foreman/pull/3416

**Comment by mccun934** [comment]
@ares thanks for re-doing this against Foreman

**Comment by ares** [comment]
Foreman PR got merged, closing this one.

**Pull request closed without merging**
