### PR TITLE
Fixes #17637: remove nutupane from packages pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/17637

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/148

**Comment by jlsherrill** [comment]
The repositories tab seems to have gotten rid of the Lifecycle Environment/content view selector. Any reason why?

**Comment by waldenraines** [comment]
> The repositories tab seems to have gotten rid of the Lifecycle Environment/content view selector. Any reason why?

Were you running the required bastion PR mentioned in the comment above?

**Comment by jlsherrill** [comment]
@waldenraines of course i was not.  Can you remind me how to do that from git checkout?

**Comment by waldenraines** [comment]
> @waldenraines of course i was not. Can you remind me how to do that from git checkout?

https://github.com/katello/bastion#developing-bastion

And also you need to add it to the foreman `bundler.d/katello.locals.rb ` file as well.

**Pull request merged**
