### PR TITLE
Fixes #18452: use table for product content pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/18452

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/katello/pull/6667 and https://github.com/Katello/katello/pull/6656

**Comment by thomasmckay** [comment]
+ content hosts missing 'repository path' column value
+ content hosts override getting saved successfully but status column remains unchanged (remains at "Disabled" or "Enabled")

**Comment by waldenraines** [comment]
> content hosts missing 'repository path' column value
> content hosts override getting saved successfully but status column remains unchanged (remains at "Disabled" or "Enabled")

Both of these issues have been fixed.

**Comment by thomasmckay** [comment]
@jlsherrill - Thoughts on what columns to show in this table? Is the original default value important? As noted on irc channel by a user, it is often useful to see the repo as subscription-manager uses it so should a column for the repo label be added (eg. "rhel-7-server-optional-rpms")?

@waldenraines - Looks good. Is it possible to add an immediate feedback that when the action is selected? As it is now, there is no feedback that the UI is working until the success message appears and the table reloads.

content host devel example com

**Comment by waldenraines** [comment]
> @jlsherrill - Thoughts on what columns to show in this table? Is the original default value important? As noted on irc channel by a user, it is often useful to see the repo as subscription-manager uses it so should a column for the repo label be added (eg. "rhel-7-server-optional-rpms")?

Seems a little late to be defining this feature, can we tweak the columns in a future PR?


> @waldenraines - Looks good. Is it possible to add an immediate feedback that when the action is selected? As it is now, there is no feedback that the UI is working until the success message appears and the table reloads.

Done.

**Comment by thomasmckay** [comment]
ack

**Comment by ehelms** [comment]
Sorry to jump in, and this can be fixed in a follow up (depending where the convo goes) but why call them 'Repository Sets' ? They aren't collections or multiples, they are simply just repositories aren't they? Moreover, they are 'Yum Repositories' since IIRC this only applies to yum repos and not docker or puppet or file etc.

**Comment by waldenraines** [comment]
> Sorry to jump in, and this can be fixed in a follow up (depending where the convo goes) but why call them 'Repository Sets' ? They aren't collections or multiples, they are simply just repositories aren't they? Moreover, they are 'Yum Repositories' since IIRC this only applies to yum repos and not docker or puppet or file etc.

@jlsherrill @parthaa

**Comment by jlsherrill** [comment]
@ehelms 'repository sets' are not just collections of repositories.  Its easier to think about this from the perspective of enabling a repository.  You 'expand' a repository set such as 'RHEL 7 Server RPMs' and then the user specified (via the ui and hammer), to enable a repository with:

repository set: 'RHEL 7 Server RPMs'
arch: x86_64
releaseVer: 7Server

and that creates the repo 'RHEL 7 Server RPMs 7Server x86_64'.

"Enabling" a repository set for a system, may enable entirely different repos depending on the arch and release version of the client system.  Only one repository would be enabled but it could be one of a few different repositories.  So here, enabling "RHEL 7 Server RPMs" on an x86_64 system with a  release version of 7Server would enable "RHEL 7 Server RPMs 7Server x86_64", but on one with a releasever of 7.2 would enable: RHEL 7 Server RPMs 7.2 x86_64'.

I know this is clear as much to users

**Comment by waldenraines** [comment]
@ehelms thoughts on the above?  I would like to merge this if there are no other concerns.

**Comment by ehelms** [comment]
@jlsherrill But this image (https://cloud.githubusercontent.com/assets/338096/23996792/32606b12-0a25-11e7-8fb5-2709f68d785d.png) is a list of repositories is it not? You are right this is clear as mud and I'll give in as usual. I just don't know why we try to confuse users with terminology we don't use anywhere else. I would think a user thinks and cares about the set of 'yum repositories' they have enabled or disabled on a host (even if only in the RH case the "repositories" are multiplexed by releaseVer and arch while in the custom repository case they are just simply the repositories).

At a minimum can we change this to 'Yum Repository Sets' ? Since we are in the business of multiple types of content we should strive to be specific.

**Comment by thomasmckay** [comment]
functional ack - no pref on names

**Comment by waldenraines** [comment]
@ehelms @jlsherrill last chance

**Comment by ehelms** [comment]
I was just waiting on a round of reply from @jlsherrill

**Comment by jlsherrill** [comment]
@ehelms i'm fine with 'yum repository sets'.  Responding to your questions:

> @jlsherrill But this image (https://cloud.githubusercontent.com/assets/338096/23996792/32606b12-0a25-11e7-8fb5-2709f68d785d.png) is a list of repositories is it not? 

Its not, those urls aren't real urls, those names are not repository names.  

> You are right this is clear as mud and I'll give in as usual. I just don't know why we try to confuse users with terminology we don't use anywhere else. 

But we do use it elsewhere.  Its used on the redhat repos page and from hammer for enabling/disabling repos.

**Comment by waldenraines** [comment]
> But we do use it elsewhere. Its used on the redhat repos page and from hammer for enabling/disabling repos.

Since that is the case I would like to revisit any renaming in a future PR as I really don't want to have to touch that page as part of this PR (or at all really :wink:).

screen shot 2017-03-29 at 9 45 25 am

**Comment by waldenraines** [comment]
@jlsherrill @ehelms we good on leaving it as is for now since it's in use elsewhere?

**Comment by ehelms** [comment]
Sure, better to be wrong everywhere then partially correct.

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
