### PR TITLE
Fixes #12598: Support Ruby 2.1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
ACK from me

Out of curiosity what was the actual issue with ruby 2.1 that needed this fix?

**Comment by ehelms** [comment]
Invalid yaml for provider cassette -- it was like it somehow had a double copy of the yaml

**Comment by ehelms** [comment]
And I am guessing `psych` which is used in 2.X couldn't parse it while `sych` from 1.9 could

**Comment by jlsherrill** [comment]
sounds good, affirming ACK

**Comment by johnpmitsch** [comment]
@ehelms should [this](https://github.com/Katello/katello/blob/d10471066eb8a1e11db1d6cb08c257579ec6c2cc/test/support/vcr.rb#L66) be changed to psych?

**Comment by ehelms** [comment]
I think its OK for now until we merge Rails 4 -- it will use psych anyway on 2.X for now

**Pull request merged**
