### PR TITLE
Fixes #22956: Remove gpg key content length limit

### PR DESCRIPTION
**Pull request by akofink**
Since we were using the :text data type in Postgres, we don't have to
change anything on the DB side! Yay! :D

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by sjha4** [comment]
https://github.com/Katello/katello/blob/6aca54157e579d6312a9e4a49609df0ffa1685b1/spec/models/gpg_key_spec.rb#L58

This will not pass anymore.. :)

**Comment by akofink** [comment]
[test katello]

**Pull request merged**
