### PR TITLE
Fixes #32472 - Use pulp_deb 2.9 for Katello 3.18

### PR DESCRIPTION
**Pull request by quba42**
https://projects.theforeman.org/issues/32472

As I understand it, the merge of this PR, needs to be coordinated with:

- https://github.com/theforeman/pulpcore-packaging/pull/144
- https://github.com/theforeman/foreman-packaging/pull/6588
- The Katello 3.18.4 release

### CODE REVIEW

**Comment by jlsherrill** [comment]
After some discussion, we're gonna merge this AFTER 3.18.3 is released for a quick 3.18.4 to go alongside or shortly after 4.0.1

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
https://github.com/Katello/katello/pull/9414 is needed before tests will pass here

**Comment by jturel** [comment]
[test katello]

**Comment by quba42** [comment]
Rebased to the current tip of `KATELLO-3.18`.

**Comment by quba42** [comment]
Yeah! The tests are finally green.

**Pull request merged**
