### PR TITLE
Fixes #23532 - Show correct upstream sub quantity

### PR DESCRIPTION
**Pull request by johnpmitsch**
when editing subscriptions. The full quantity was
showing rather than the available quantity.

Requires https://github.com/Katello/katello/pull/7361

### CODE REVIEW

**Comment by johnpmitsch** [comment]
Requires correlated API change PR

**Comment by jturel** [comment]
Depends on #7361

**Comment by jturel** [comment]
@johnpmitsch I think this needs a rebase so that it includes the dependent PR

**Comment by waldenraines** [comment]
> @johnpmitsch I think this needs a rebase so that it includes the dependent PR

As long as there are no conflicts it should be fine I think.

**Comment by johnpmitsch** [comment]
@jturel ya, you can rebase locally to test since this will rebase when merged

**Pull request merged**
