### PR TITLE
Fixes #14205 - handle missing env on cv history

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
ACK - we should really fix the combining history and task pages :)

**Comment by jlsherrill** [comment]
agreed :)

**Pull request merged**
