### PR TITLE
fixes #12668 - attr_accessible uuid on CpConsumer

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by daviddavis** [comment]
Do we really want to allow users to set uuid on User objects? Would rather see us just change [this line to](https://github.com/Katello/katello/blob/068062449b30e985695aa6071837290e4afbd3df/app/services/katello/authentication/client_authentication.rb#L16):

```ruby
User.current = CpConsumerUser.new do |cp_consumer|
  cp_consumer.uuid = uuid
  cp_consumer.login = uuid
end
```

**Comment by thomasmckay** [comment]
@daviddavis - updated per your suggestion

**Comment by daviddavis** [comment]
APJ

**Comment by johnpmitsch** [comment]
I wrote a method in katello test helper for this as it comes up quite a bit in tests https://github.com/Katello/katello/blob/master/test/katello_test_helper.rb#L191-L196

**Pull request merged**
