### PR TITLE
Fixes #19433: Mv `trigger` to `triggering_action`

### PR DESCRIPTION
**Pull request by akofink**
Due to this change: https://github.com/Dynflow/dynflow/pull/229

@iNecas

### CODE REVIEW

**Comment by iNecas** [comment]
[test] - I 've released dynflow 0.8.24, including this change

**Comment by jlsherrill** [comment]
ACK thanks @akofink !

**Comment by lzap** [comment]
Guys is this in Katello 3.4? Because I was just hit hard with this bug in 3.4 RC2, installation not possible due to seed error because of this. Blocker! http://projects.theforeman.org/issues/19677

**Comment by jlsherrill** [comment]
Its already in 3.4.  The problem is that 
a) we released 3.4rc2 without this commit (because it didn't exist yet)
b) a newer dynflow was released into 1.15 that required this change
c) there was no rc3 planned, just GA
d) we've hit a blocker that prevents us from releasing GA

**Pull request merged**
