### PR TITLE
Fixes #14549: Hide version details tabs without content

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I'm unable to see docker repositories tab on a version with docker content.

screenshots:
[version with docker](http://www.clipular.com/c/4881388602392576.png?k=IQLe2NhlxTLW5zsytb0w0-Onm7Q)
[details for that version](http://www.clipular.com/c/4881388602392576.png?k=IQLe2NhlxTLW5zsytb0w0-Onm7Q)

package, package groups, puppet modules, and ostree tabs are working fine.

**Comment by ehelms** [comment]
Updated to check docker_tag_count and docker_manifest_count

**Comment by johnpmitsch** [comment]
@ehelms I keep seeing this js error when I view a CVV

```
TypeError: Cannot read property 'errata_counts' of undefined
    at Scope.ContentViewVersionController.$scope.hasErrata 
```

**Comment by ehelms** [comment]
@johnpmitsch can you describe what all was in your content view when you see this error so I can reproduce?

**Comment by johnpmitsch** [comment]
@ehelms 
In the content view was:
- this yum repo https://inecas.fedorapeople.org/fakerepos/zoo3/
-  a puppet repo containing an openssl puppet module
- busybox docker repo

It seems to be happening despite which repo is in the CVV, not sure why.  lmk if you have trouble reproducing and I will try another VM

**Comment by ehelms** [comment]
Updated to fix the error

**Comment by johnpmitsch** [comment]
ACK

**Pull request merged**
