### PR TITLE
Fixes #24033 - Refactor Subscriptions state

### PR DESCRIPTION
**Pull request by sharvit**
Move the delete modal state to redux

### CODE REVIEW

**Comment by waldenraines** [comment]
@sharvit one of these PRs will need to use the commit style of "Fixes #24033 ..." so we can ensure the issue is closed.

**Comment by sharvit** [comment]
Yes @waldenraines :+1: 
Updated

**Comment by waldenraines** [comment]
@sharvit sorry, I created some conflicts for you here by merging #7833.

**Comment by sharvit** [comment]
np @waldenraines rebased :+1:

**Comment by waldenraines** [comment]
@sharvit needs a rebase and then we can finally merge this.

**Comment by sharvit** [comment]
Thanks @waldenraines, rebased.

**Pull request merged**
