### PR TITLE
fixes #22301 - upload docker manifest and tag

### PR DESCRIPTION
**Pull request by thomasmckay**
Test with https://github.com/Katello/hammer-cli-katello/pull/538

### CODE REVIEW

**Comment by jturel** [comment]
@thomasmckay can you provide some testing steps & expected behaviors?

**Comment by akofink** [comment]
From the issue:

In foreman the user would use hammer repository upload-content.

1. create an empty docker repo (or use existing)
2. follow pulp docs to create tar of image with skopeo (https://github.com/pulp/pulp_docker/pull/203)
3. `hammer repository upload-content --id <docker repo id> --path </tmp/image_repo.tar>`

**Comment by akofink** [comment]
Had a discussion offline - this is how to use docker pull with this functionality:

```
$ hammer repository upload-content --id 1 --path ../tmp/busybox/1.27.tar
Successfully uploaded manifest file '1.27.tar' with digest 'sha256:b25c0292200c1a9c29a86d367f7e9d05d7deb61cb5210fd180755d6e9d6615c0'

$ hammer repository upload-content --id 1 --digest sha256:b25c0292200c1a9c29a86d367f7e9d05d7deb61cb5210fd180755d6e9d6615c0 --tag 1.27
Successfully uploaded tag '1.27 for digest 'sha256:b25c0292200c1a9c29a86d367f7e9d05d7deb61cb5210fd180755d6e9d6615c0'

$ sudo docker pull devel.example.com:5000/examplecorp-dockerhub-busybox:1.27
Trying to pull repository devel.example.com:5000/examplecorp-dockerhub-busybox ... 
sha256:b25c0292200c1a9c29a86d367f7e9d05d7deb61cb5210fd180755d6e9d6615c0: Pulling from devel.example.com:5000/examplecorp-dockerhub-busybox

Digest: sha256:b25c0292200c1a9c29a86d367f7e9d05d7deb61cb5210fd180755d6e9d6615c0
Status: Downloaded newer image for devel.example.com:5000/examplecorp-dockerhub-busybox:1.27
```

I dislike the tagging step, as it uses `hammer repository upload-content` rather than something like `hammer repository tag` or `tag-image`. What do you think, @jturel?

**Comment by thomasmckay** [comment]
Maybe the tagging should be part of _hammer repository update_? I see type specific options there.
```
hammer repository update --docker-tag
hammer repository update --docker-tag-delete
```

**Comment by akofink** [comment]
@thomasmckay I'd be cool with that approach.

**Comment by thomasmckay** [comment]
@akofink - To be clear, I am not going to change this PR but instead implement hammer commands to hide these details.

**Pull request merged**
