### PR TITLE
Fixes #34756 - Add scope for epoch_to_date method

### PR DESCRIPTION
**Pull request by nadjaheitmann**
(cherry picked from commit 73e1ba218cd437f9d641538944ab1de328657396)

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@sjha4 Can you please have a look? It is a CP from https://github.com/Katello/katello/pull/10081

**Comment by sjha4** [comment]
Ack..although I am not sure when 4.4.1 is scheduled.. 
@ianballou : Feel free to merge this when ready. The issue is tied to 4.4.1.

**Review by sjha4 — APPROVED** [review]

**Comment by sjha4** [comment]
VCR tests are failing..not sure if we need to re-record those for this branch..

**Comment by ianballou** [comment]
Yeah the VCRs need recording. @nadjaheitmann you can either do that now by running `mode=all bundle exec rake test:katello:test:pulpcore` and then re-recording the stragglers, or, you can wait until we do a 4.4.1 release.  The release owner (me) would do the cherry picks (this CP included) and take care of the VCR recordings.

**Comment by nadjaheitmann** [comment]
@ianballou I have never done the recordings before. When are you planning the 4.4.1 release?

**Comment by ianballou** [comment]
@nadjaheitmann I think sometime next week or the week after I should be able to do it.

**Comment by nadjaheitmann** [comment]
@ianballou That is soon, I'll wait until then, it is not that urgent.

**Comment by nadjaheitmann** [comment]
@ianballou Is this done and shall I close the PR?

**Comment by ianballou** [comment]
Yep, feel free to close it @nadjaheitmann

**Comment by nadjaheitmann** [comment]
Thanks you @ianballou

**Pull request closed without merging**
