### PR TITLE
Fixes #36411 - add ability to skip treeinfo files

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
- Adds a new checkbox to skip treeinfo files
- Rewrites a treeinfo Pulp error to give better workaround instructions

#### What are the testing steps for this pull request?
1) Sync https://www.keepersecurity.com/kcm/2/el/8/x86_64
2) Verify the error in the Dynflow action
3) Enable treeinfo skipping
4) Sync again
5) Verify that the sync is successful

### CODE REVIEW

**Comment by sjha4** [comment]
Test failure looks related.

**Comment by sjha4** [comment]
Do we need to call pulp at all when updating ignored_types since pulp doesn't store it anywhere. We should probably remove it from here to avoid the pulp actions: https://github.com/Katello/katello/blob/3efcc7cf5d2aa7f007c7a9f81b34dcd941cce096/app/models/katello/root_repository.rb#L410

**Review by sjha4 — APPROVED** [review]
Acking first commit 👍🏼 
Without ignore_treeinfo checked:
Screenshot from 2023-05-23 13-22-30

With ignore treeinfo checked:
Screenshot from 2023-05-23 13-23-50

**Review by wbclark — COMMENTED** [review]
is the change to `ensure_valid_ignorable_content` related to https://projects.theforeman.org/issues/36428 ?

right now it's attached to the commit with tests

**Comment by sjha4** [comment]
> is the change to ensure_valid_ignorable_content related to https://projects.theforeman.org/issues/36428 ?

No..So that was a small change to make validation error more useful. If you set any of the 2 ignore flags with mirror complete download policy, the error should only report the Ignore flag that was checked.

**Comment by sjha4** [comment]
That change also fixes 2 tests that were failing on the 1st commit which brought this to my notice:
https://ci.theforeman.org/blue/organizations/jenkins/katello-pr-test/detail/katello-pr-test/12784/tests

**Review by wbclark — APPROVED** [review]
ACK to the 2nd commit

**Comment by sjha4** [comment]
Thanks @wclark and @ianballou ! Merging..

**Pull request merged**
