### PR TITLE
fixes #11102 - upgrading to newer deface version

### PR DESCRIPTION
**Pull request by jlsherrill**
not maintaining older version

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by jlsherrill** [comment]
I think this will fail tests until a new version of deface is actually built.  So i don't think this will go green until master is broken :)

**Comment by stbenjam** [comment]
Ah, didn't notice that, only 0.7.x is there.  Is there a reason we use erb-loud? I deface many of the same things just by relying on things like `insert_bottom div#primary` in foreman_salt.

But it doesn't much matter, merge away whenever this one's green.

APJ

**Comment by jlsherrill** [comment]
If i get a few minutes I'll take a look, I just converted what was already there

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@jlsherrill this is green now that the RPM job has been removed

**Comment by jlsherrill** [comment]
not merging yet, don't want to break the rpm for ~45 days.

@stbenjam any thoughts on how i would change https://github.com/Katello/katello/pull/5355/files#diff-326c2df55dd341124e34d7cc4204cef9L13

to not use code/erb ?  I've been able to re-write most of the others.

**Comment by stbenjam** [comment]
> @stbenjam any thoughts on how i would change https://github.com/Katello/katello/pull/5355/files#diff-326c2df55dd341124e34d7cc4204cef9L13

Eek, I don't think so, I can't think of a way to do it without touching the ERB.

**Comment by stbenjam** [comment]
We'll just have to coordinate merging this when Foreman goes to 1.x

**Comment by domcleal** [comment]
All of Foreman's plugins support it, and we have an RPM ready to add to our plugins repo (https://github.com/theforeman/foreman-packaging/pull/777).

**Comment by stbenjam** [comment]
@jlsherrill Needs a rebase

**Comment by jlsherrill** [comment]
Test run:  http://ci.theforeman.org/job/test_katello_pull_request/7139/

**Comment by jlsherrill** [comment]
@stbenjam @ehelms test run is green ^

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
