### PR TITLE
Fixes #33466 - show proper repo count of capsule content

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by sjha4** [comment]
This works as expected for non default CVs. 

Couple of questions: we are also showing Default Organization View in the content tab for Library environment on the capsule..Does that seem right?

And since we are showing the default view currently, the number of archived repos always comes to 0 from this: 
`::Katello::ContentViewVersion.in_environment(env).find_by(:content_view => content_view)&.repositories&.archived&.count`

**Comment by jlsherrill** [comment]
good point, i think we should probably still show it, and show the correct amount

**Comment by jlsherrill** [comment]
turns out there was a helper method to do that exact thing

**Comment by sjha4** [comment]
[test katello]

**Review by sjha4 — APPROVED** [review]
Tested and work great. APJ 👍🏽

**Pull request merged**
