### PR TITLE
Fix typo in tasks/check_config.rake

### PR DESCRIPTION
**Pull request by Gauravtalreja1**

### CODE REVIEW

**Comment by chris1984** [comment]
ok to test

**Review by chris1984 — APPROVED** [review]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
Not sure what the issue is with the tests. @Gauravtalreja1 can you please rebase your code on the latest master branch and open an issue in our Redmine to use the redmine id in your commit? "Fixes #XXXXXX- correct typo in check_config.rake"

**Pull request closed without merging**
