### PR TITLE
Fixes #18784 - Send emails only if Errata count is greater than 0

### PR DESCRIPTION
**Pull request by kgaikwad**

### CODE REVIEW

**Comment by stbenjam** [comment]
This seems to reference the wrong issue number

**Comment by kgaikwad** [comment]
@stbenjam,

Thanks for reviewing the pull-request. 
Corrected the issue number in commit message.

**Comment by stbenjam** [comment]
[test]

**Comment by jlsherrill** [comment]
Thanks @kgaikwad !

**Pull request merged**
