### PR TITLE
[CP] 4.13.1

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
APJ

**Comment by jeremylenz** [comment]
looks like 'React Tests' still uses the old (broken) GH workflow. But there are no Ruby changes in these commits AFAIK, so it's fine to ignore that check.

**Comment by Odilhao** [comment]
@ianballou @parthaa can we include this https://github.com/Katello/katello/pull/11057? At some point we will need to cherrypick the new pulp-rpm into 3.49 branch

**Comment by ianballou** [comment]
@Odilhao yeah we should also include that bindings bump commit here.

**Comment by ianballou** [comment]
@parthaa let me know if CPing in  that pulp-rpm update commit causes VCR errors, if it does we may need to do some re-recording.

**Comment by parthaa** [comment]
> @parthaa let me know if CPing in that pulp-rpm update commit causes VCR errors, if it does we may need to do some re-recording.

CP worked fine. make sure https://github.com/Katello/katello/pull/11081/files#diff-21cb8426e694930953a1fb66d2f1e4c0c4021bcadd760d9582423094a4dcaace looks correct.

**Review by ianballou — APPROVED** [review]

**Pull request merged**
