### PR TITLE
Fixes #20471 - IDs in API doc should be numeric

### PR DESCRIPTION
**Pull request by snagoor**
Content Views created in Katello has numeric IDs. 

Previous API Doc incorrectly states that its a "string" and validation text as follows
~~~
string from 2 to 128 characters containing only alphanumeric characters, space, '_', '-' with no leading or trailing space..
~~~

### CODE REVIEW

**Comment by snagoor** [comment]
There are many other places in Katello API doc (such as packages repos, activation keys, content view versions etc), which needs to be fixed. Shall I modify all of the changes in this PR ? or open a new issue with each of the relevant component.

**Comment by jlsherrill** [comment]
@snagoor I would just update them all in a single PR (much easier that way).  Thanks!

**Comment by jlsherrill** [comment]
[test]

**Comment by snagoor** [comment]
@jlsherrill fixed all of the IDs in API doc to numeric. Can you have a look once you have time.

**Pull request merged**
