### PR TITLE
Fixes #14074 - Select all selects only visible

### PR DESCRIPTION
**Pull request by adamruzicka**
With this patch `select all` selects only visible checkboxes, should this also modify the `select none` so it would deselect only the visible ones?

### CODE REVIEW

**Comment by jlsherrill** [comment]
I'm not sure I agree with the original bug/issue.  Since the select all link is above the table I think it should select everything.  A couple suggestions maybe:

* Show a count of the # of selected repositories (so what is selected is more clear)
* add some sort of select all link for each product when it is expanded.

**Comment by adamruzicka** [comment]
@jlsherrill I didn't like it either (for me the new behavior would be more confusing), but the BZ had all the acks so I just did it.

Now I used the `Details` column of each product to show counts of selected repositories, as far as I know it wasn't used for anything. Or did you mean showing total selected count somewhere?

**Comment by ehelms** [comment]
@jlsherrill please re-review this

**Comment by beav** [comment]
This PR has been open for awhile (over 1 year since last comment). Is it still waiting on review?

**Comment by beav** [comment]
@jlsherrill @adamruzicka Is this still waiting on review? If it is no longer needed, feel free to close.

**Comment by johnpmitsch** [comment]
This has been inactive for some time and there has been no response to the above question, so I'm going to close this, but feel free to reopen if its still a valid change :)

**Pull request closed without merging**
