### PR TITLE
[CP] Katello 4.0.1.2 CP for container gateway fixes

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Comment by ianballou** [comment]
[test katello]

**Review by jlsherrill — APPROVED** [review]
ACK, reproduced the issue, applied this patch, re-ran the bats tests and the problem was solved

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jturel** [comment]
You need to pin foreman-tasks-core as well! (Not sure which pin version is appropriate for this branch however)

https://github.com/Katello/katello/pull/9409/commits/10250a975a42885b2090211679fff7dc16c82b83

**Comment by jjeffers** [comment]
> You need to pin foreman-tasks-core as well! (Not sure which pin version is appropriate for this branch however)
> 
> [10250a9](https://github.com/Katello/katello/commit/10250a975a42885b2090211679fff7dc16c82b83)

Thanks!

**Comment by ianballou** [comment]
[test katello]

**Pull request merged**
