### PR TITLE
Fixes #30021 - upgrade pulpcore to 3.4 and bumps gems

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jlsherrill** [comment]
did you try re-recording all these cassettes locally?

**Comment by jjeffers** [comment]
> did you try re-recording all these cassettes locally?

No, just the ones that failed. I suppose a full re-recording is order, then?

**Comment by jlsherrill** [comment]
We usually do a full re-recording to try to catch any regressions in the new version of pulp we're pulling in

**Comment by jjeffers** [comment]
> We usually do a full re-recording to try to catch any regressions in the new version of pulp we're pulling in

I was too optimistic!

**Comment by jlsherrill** [comment]
Merging! Thanks @jjeffers !

**Pull request merged**
