### PR TITLE
[CP] Katello 4.9.2

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by wbclark** [comment]
Something is still not correct with changelog generation. Most of the cherry-picked issues do not appear in the changelogs.

**Comment by ianballou** [comment]
Looks like some of these commits are tied to redmine issues triaged to 4.10:

[b3b522e](https://github.com/Katello/katello/pull/10726/commits/b3b522e32138c09548d4a55750332dc030f9ffd7) =>  https://projects.theforeman.org/issues/36506 

[205545a](https://github.com/Katello/katello/pull/10726/commits/205545a4505bd6cfffe416c69c8e00337a94aee3) => https://projects.theforeman.org/issues/36497

Since the cherry picking work was already done, I say we can re-triage these to 4.9, but I'm wondering now how the cherry picks were calculated.

There might be more, I only found two 4.10 ones.

**Comment by ekohl** [comment]
> [205545a](https://github.com/Katello/katello/pull/10726/commits/205545a4505bd6cfffe416c69c8e00337a94aee3) => https://projects.theforeman.org/issues/36497

This one was marked by @parthaa as fixed in 4.9.0, but given it shows up here that clearly wasn't true.

**Comment by wbclark** [comment]
> Looks like some of these commits are tied to redmine issues triaged to 4.10:
> 
> [b3b522e](https://github.com/Katello/katello/pull/10726/commits/b3b522e32138c09548d4a55750332dc030f9ffd7) => https://projects.theforeman.org/issues/36506
> 
> [205545a](https://github.com/Katello/katello/pull/10726/commits/205545a4505bd6cfffe416c69c8e00337a94aee3) => https://projects.theforeman.org/issues/36497
> 
> Since the cherry picking work was already done, I say we can re-triage these to 4.9, but I'm wondering now how the cherry picks were calculated.
> 
> There might be more, I only found two 4.10 ones.

Some of the other cherry picks had merge conflicts initially. I cherry-picked these to resolve those merge conflicts safely.

**Comment by ianballou** [comment]
> Some of the other cherry picks had merge conflicts initially. I cherry-picked these to resolve those merge conflicts safely.

Gotcha, that makes more sense now .  Mind setting the version back on the redmines to keep the bookkeeping straight?

**Comment by ianballou** [comment]
Hey @wbclark are the 4.9.2 redmine versions fixed up? Can the changelog be regenerated? I'd like to get this merged this week so we can wrap up 4.9.2 and have it delivered.

**Comment by chris1984** [comment]
What is the status of this?

**Review by chris1984 — APPROVED** [review]
ACK pending jenkins

**Comment by ianballou** [comment]
There are failing React snapshot tests for some reason. Perhaps another commit is missing?

**Comment by ianballou** [comment]
@wbclark looks like we may just need https://projects.theforeman.org/issues/36552 to be CP'd in to fix the failing React tests.

**Comment by wbclark** [comment]
Cherry-picked https://projects.theforeman.org/issues/36552 , regenerated and validated CHANGELOG.md

**Comment by ianballou** [comment]
Thanks, I closed https://github.com/Katello/katello/pull/10754

**Comment by ianballou** [comment]
[test katello]

**Comment by chris1984** [comment]
@wbclark all green for a 4.9.2 release

**Comment by ekohl** [comment]
I just verified that the bot indeed did set the Fixed in Releases field correctly upon merge. Glad to confirm that's been fixed now.

**Pull request merged**
