### PR TITLE
Fixes #28675 - copy all rpms as part of cv publish

### PR DESCRIPTION
**Pull request by jlsherrill**
when no filters are present

### CODE REVIEW

**Comment by jlsherrill** [comment]
How to test:

1) download centos 8 appstream repo
2) publish it in a content view
3) examine the repo on the filesystem (note your path may differ):
```
zgrep "<package " /var/lib/pulp/published/yum/https/repos/Default_Organization/Library/centos8cv/custom/centos8/appstream/repodata/*primary.xml.gz | wc -l
```

4)  you'll see that the incorrect # of rpms are present in the repo.
5) apply the patch (restart dynflowd if needed)
6) publish a new CV with this repository***
7) check the new repos's primary.xml for package count



*** if you republish the same cv, you'll need to forcibly generate the metadata, as metadata generation will be skipped for the Library repo since it thinks nothing has changed

**Comment by parthaa** [comment]
wondering if you can add useful test for generate_copy_clauses method in yum.rb

**Comment by parthaa** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
chatted on irc and since this is a private method, partha said test wasn't really worth it for such a simple change

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jturel** [comment]
I'm tempted to merge but will hold off. This is the last PR needed for 3.14.1 :)

**Comment by jlsherrill** [comment]
green! merging!

**Pull request merged**
