### PR TITLE
fixes #24168 - registry name examples

### PR DESCRIPTION
**Pull request by thomasmckay**
lifecycle environment development

### CODE REVIEW

**Comment by thomasmckay** [comment]
@akofink - The same could be said for anything in the tool. I don't think an info area should replace documentation, only prompt with some hints. Happy to change to whatever @rohoover suggests.

**Comment by akofink** [comment]
Oh, I missed theforeman.org PR. Do you have link? ;)

**Comment by thomasmckay** [comment]
@akofink @rohoover - I don't want to get into a big back and forth here, but here are my thoughts:
- We don't have a lot of info boxes in the tool but this field in particular, after using it myself many times, is hard to remember the syntax.
- Tooltips can't be formatted so I am against a cluttered run-on sentence with examples.
- Alignment of the icon is consistent with everywhere else it is used (built into bastion angular.js).
- I understand some users won't understand what a "registry name pattern" is, but the same can obviously be said for any of the myriad other fields exposed in the UI: If you don't know what it is, you probably shouldn't use it.
repository red hat satellite tools 6 3 for rhel 7 server rpms x86_64

**Comment by akofink** [comment]
> We don't have a lot of info boxes in the tool but this field in particular, after using it myself many times, is hard to remember the syntax.

+1

> Tooltips can't be formatted so I am against a cluttered run-on sentence with examples.

+1

> Alignment of the icon is consistent with everywhere else it is used (built into bastion angular.js).

+1

> I understand some users won't understand what a "registry name pattern" is, but the same can obviously be said for any of the myriad other fields exposed in the UI: If you don't know what it is, you probably shouldn't use it.

+1

So, I agree with everything you said. :) But, what I think would be really helpful, still, is the default pattern being displayed in the field when the value is nil. A tooltip could be super helpful to just list all the supported fields.

**Comment by Rohoover** [comment]
@thomasmckay 

I'm not advocating we combine the examples with the infotip.

I'm suggesting we use the infotip to answer @akofink concern:
"As a user, I still have no idea what "Registry Name Pattern" means, or what the default is."

**Comment by thomasmckay** [comment]
https://github.com/Katello/katello/pull/7597

**Pull request closed without merging**
