### PR TITLE
Refs #37217 - Missing related changes on install package page when di…

### PR DESCRIPTION
**Pull request by Dyrkon**
Followup of [10538](https://github.com/Katello/katello/pull/10538).

### CODE REVIEW

**Comment by stejskalleos** [comment]
@Dyrkon can you please rebase over the latest `master`?

@jeremylenz could you please do the review?

**Review by jeremylenz — APPROVED** [review]
Tested and works as advertised.

CI failures are probably unrelated, but I'll wait for the rebase & green tests to be safe

Thanks @Dyrkon!

**Comment by jeremylenz** [comment]
It seems I can't re-run the tests, so this will definitely need a rebase.

**Comment by amolpati30** [comment]
`Ack, I've tested and it works `

**Review by amolpati30 — APPROVED** [review]
working as expected in upstream.

**Comment by stejskalleos** [comment]
@Dyrkon can you rebase please, so we can have green CI?

**Comment by jeremylenz** [comment]
Looks like the React test failures are legit now :smile: 

you can use `DEBUG=nock.* npx jest <filename>` to debug the nock stuff. let me know if you need help

**Comment by jeremylenz** [comment]
@Dyrkon any updates here?

**Comment by Dyrkon** [comment]
@jeremylenz I have rebased the branch, but there are 8 tests that are failing. I have finals in the next couple of weeks, so I won't have the time to address them for a while.

**Comment by stejskalleos** [comment]
@jeremylenz @Dyrkon Follow up PR with fixed code: https://github.com/Katello/katello/pull/10987/files

**Comment by jeremylenz** [comment]
Closing in favor of https://github.com/Katello/katello/pull/10987 which is already merged.

**Pull request closed without merging**
