### PR TITLE
Fixes #32798 - latest_tasks with foreman-tasks

### PR DESCRIPTION
**Pull request by m-bucher**
requires https://github.com/theforeman/foreman-tasks/pull/514

Has to wait for foreman-tasks >= 5.0 to land.

### CODE REVIEW

**Comment by jeremylenz** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
APJ

**Comment by jeremylenz** [comment]
[test katello]

**Comment by chris1984** [comment]
@m-bucher looks like tests are failing, can you take a look?

**Comment by m-bucher** [comment]
@chris1984, I must admit I do not really know what is happening there.
The test.log says:
```
2021-07-15T14:53:18 [E|app|] ActionView::Template::Error: undefined method `get_latest_tasks_by_resource_ids' for #<Class:0x000000000927fbb0>
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
 | /home/vagrant/katello/app/models/katello/glue/pulp/repos.rb:89:in `last_repo_sync_task_by_repoid'
 | /home/vagrant/katello/app/models/katello/glue/pulp/repos.rb:51:in `sync_summary'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/rabl-0.14.4/lib/rabl/helpers.rb:16:in `data_object_attribute'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/rabl-0.14.4/lib/rabl/builder.rb:145:in `attribute'
 | /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/rabl-0.14.4/lib/rabl/builder.rb:116:in `block in compile_settings'
```
And I can confirm when trying to call the method in `rails console` it is not there.
But I do not understand why. The used foreman-task version is correct and the method is in there.
Does katello/foreman do something weird with the `ForemanTasks::Task`-class? Like removing the existing class-methods?

**Comment by jturel** [comment]
@m-bucher the method you added is called `latest_tasks_by_resource_ids` => https://github.com/theforeman/foreman-tasks/commit/f1f6b629b6cabdd05271024cc93538b1d701229f :)

**Comment by m-bucher** [comment]
Thanks @jturel , apparently I either need :eyeglasses: or :palm_tree: :sweat_smile:

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by jturel** [comment]
Is the same test failing each time?

**Comment by chris1984** [comment]
> Is the same test failing each time?

No, it failed once with one test failure, the last time it could not read a file, and this time it could not find a schema in the foreman db. I will keep the next run up for you to see.

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
