### PR TITLE
Fixes #17564 - use threading to improve RH repos page

### PR DESCRIPTION
**Pull request by jlsherrill**
This commit spawns threads in order to speed up the
Red Hat Repositories page for fetching listing files.

Given a directory structure such as:

/path/$RELEASEVER/$ARCH

we have to make 1 + $RELEASEVER number of requests. On
a high latency connection this can take some time per request.
With this change we put each request in a thread and so are able
speed up the total time to be closer to the same amount of time
as two requests.

### CODE REVIEW

**Comment by jlsherrill** [comment]
@pmoravec curious if you'd be able to test this patch.  On my connection its fairly fast already (but maybe its just a good day)

**Comment by pmoravec** [comment]
It significantly helps here.

Average times in ms before patch when $RELEASEVER had 1, 5 or 18 variants:
5986 13137 18533

Same values after the patch:
5909 7604 8671

So significant improvement, great! :+1:

(I havent tested what happens if an error contacting CDN occurs, i.e. if/how threads will handle it and properly join afterwards)

**Comment by iNecas** [comment]
I think we should use some better abstractions around this, suggesting using futures, that we already do in Dynflow http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Edge/FutureShortcuts.html.

The benefit of this is cleaner interface, as well as using internal concurrent ruby thread pool, rather than creating new threads every time we need it

**Comment by jlsherrill** [comment]
@iNecas yeah, this code is not the prettiest and needs to be re-factored quite a bit :)

I'll look into futures

**Comment by jlsherrill** [comment]
@iNecas if i'm using futures, it won't be restricted to the same 5-thread thread pool that dynflow is using to execute task steps will it?

**Comment by iNecas** [comment]
No, the dynflow trhead pool is using the concurrent-ruby's one, but it's only a small subset. The concurrent ruby trhead pool is self-monitoring, adding as many threads as needed (unless they cross some limit), reuse it for some time and decrese the amount later

**Comment by jlsherrill** [comment]
Updated this to use futures.  Also completely re-factored cdn_var_substitutor to hopefully but much more clear.

**Comment by ehelms** [comment]
I am blocked testing this on:

```
ForemanTasks::TaskError (Task 13c50470-8946-4105-ae3a-203615c5f095: NoMethodError: undefined method `substitutable?' for nil:NilClass):
11:16:45 rails.1   |  |   foreman-tasks (0.8.6) lib/foreman_tasks.rb:40:in `block in sync_task'
11:16:45 rails.1   |  |   foreman-tasks (0.8.6) lib/foreman_tasks.rb:39:in `tap'
11:16:45 rails.1   |  |   foreman-tasks (0.8.6) lib/foreman_tasks.rb:39:in `sync_task'
11:16:45 rails.1   |  |   foreman-tasks (0.8.6) lib/foreman_tasks/triggers.rb:22:in `sync_task'
11:16:45 rails.1   |  |   /home/vagrant/katello/app/controllers/katello/products_controller.rb:19:in `available_repositories'
11:16:45 rails.1   |  |   app/controllers/concerns/application_shared.rb:14:in `set_timezone'
11:16:45 rails.1   |  |   lib/middleware/catch_json_parse_errors.rb:8:in `call'
11:16:45 rails.1   |  |   lib/middleware/tagged_logging.rb:18:in `call'
```

**Comment by jlsherrill** [comment]
Fixed that error.

**Pull request merged**
