### PR TITLE
Fixes #17388: fix display of new repository page.

### PR DESCRIPTION
**Pull request by waldenraines**
The new repository page wasn't using the correct ui-view and thus
wouldn't show up when visited.  This commit changes the ui-router
configuration to make the page display as well as renaming the new
repository page for consistency and fixing a display issue on that page
where the breadcrumbs were being shown twice.

http://projects.theforeman.org/issues/17388

### CODE REVIEW

**Comment by jlsherrill** [comment]
getting an error when clicking "save" on the new repo page:

**Comment by jlsherrill** [comment]
bastion.js:13551 TypeError: Cannot read property 'rows' of undefined
    at success (bastion_katello.js:10767)
    at bastion.js:31596
    at processQueue (bastion.js:15962)

**Comment by waldenraines** [comment]
@jlsherrill fixed.

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
