### PR TITLE
Fixes #15637: use collection for partial render

### PR DESCRIPTION
**Pull request by ranjan**
This will improve performance and reduce noise in log

### CODE REVIEW

**Comment by stbenjam** [comment]
Would you mind updating the sync_errata view? It does a similar thing

**Comment by ranjan** [comment]
@stbenjam , updated pull request with sync_errata changes.

**Comment by stbenjam** [comment]
Thanks @ranjan, this is great, I didn't know about `:collection`.

**Comment by stbenjam** [comment]
ACK from me

**Pull request merged**
