### PR TITLE
Fixes #35735 - Stub pulp3support? for test smart proxy

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the changes introduced in this pull request?
stub :pulp3_support? to return true for intermittently failing test.
#### Considerations taken when implementing this change?
This is safe to do as the mock proxy should return true for docker support anyway. It sometimes randomly returns false due to race conditions or whatever reason on CI. Safest option is to stub to return true.
#### What are the testing steps for this pull request?
Run the CI tests a few (hundred?) times. 😝

### CODE REVIEW

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
Screenshot from 2022-11-09 09-55-12

`
Error
Expected false to be truthy.
Stacktrace
Failure:
test_python_package_count(Minitest::Result) [/home/jenkins/workspace/katello-pr-test/test/models/content_view_version_test.rb:132]:
Expected false to be truthy.
`

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jeremylenz** [comment]
```
[2022-11-09T17:54:29.721Z] Error:

[2022-11-09T17:54:29.721Z] HostsAndHostGroupsHelperKickstartRepositoryIDTest#test_0001_must return host or host group kickstart id:

[2022-11-09T17:54:29.721Z] ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

[2022-11-09T17:54:29.721Z] 

[2022-11-09T17:54:29.721Z]     /home/jenkins/workspace/katello-pr-test/app/models/katello/concerns/redhat_extensions.rb:76:in `distribution_repositories'

[2022-11-09T17:54:29.721Z]     /home/jenkins/workspace/katello-pr-test/app/models/katello/concerns/redhat_extensions.rb:53:in `kickstart_repos'

[2022-11-09T17:54:29.721Z]     /home/jenkins/workspace/katello-pr-test/app/helpers/katello/hosts_and_hostgroups_helper.rb:214:in `kickstart_repository_options'

[2022-11-09T17:54:29.721Z]     /home/jenkins/workspace/katello-pr-test/app/helpers/katello/hosts_and_hostgroups_helper.rb:37:in `kickstart_repository_id'

[2022-11-09T17:54:29.721Z]     /home/jenkins/workspace/katello-pr-test/test/helpers/hosts_and_hostgroups_helper_test.rb:247:in `block in <class:HostsAndHostGroupsHelperKickstartRepositoryIDTest>'

...

[2022-11-09T17:54:29.721Z] Failure:

[2022-11-09T17:54:29.721Z] Katello::SmartProxyExtensionsTest#test_sync_container_gateway [/home/jenkins/workspace/katello-pr-test/app/models/katello/concerns/smart_proxy_extensions.rb:141]

[2022-11-09T17:54:29.721Z] Minitest::Assertion: unexpected invocation: #<AnyInstance:ProxyAPI::ContainerGateway>.repository_list(:repositories => [{:repository => "busybox", :auth_required => true}, {:repository => "empty_organization-puppet_product-busybox", :auth_required => true}])

[2022-11-09T17:54:29.721Z] unsatisfied expectations:

[2022-11-09T17:54:29.721Z] - expected exactly once, invoked never: #<AnyInstance:ProxyAPI::ContainerGateway>.user_repository_mapping()

[2022-11-09T17:54:29.721Z] - expected exactly once, invoked never: #<AnyInstance:ProxyAPI::ContainerGateway>.repository_list(:repositories => [{:repository => "empty_organization-puppet_product-busybox", :auth_required => true}, {:repository => "busybox", :auth_required => true}])

[2022-11-09T17:54:29.721Z] - expected exactly once, invoked never: #<SmartProxy:0x61c9c0>.container_gateway_users(any_parameters)

[2022-11-09T17:54:29.721Z] satisfied expectations:

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:Resolv::DNS>.getaddresses(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:Resolv::DNS>.getaddress(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:Resolv::DNS>.getnames(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:Resolv::DNS>.getname(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:Katello::Pulp3::Repository>.test_remote_name(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: Katello::Ping.ping(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: Cert::Certs.ssl_client_key(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: Cert::Certs.ssl_client_cert(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: Cert::Certs.ca_cert(any_parameters)

[2022-11-09T17:54:29.721Z] - allowed any number of times, invoked never: #<AnyInstance:SmartProxy(id: integer, name: string, url: string, created_at: datetime, updated_at: datetime, expired_logs: string, puppet_path: text, download_policy: string, http_proxy_id: integer)>.associate_features(any_parameters)
```

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
Ah well.. https://ci.theforeman.org/blue/organizations/jenkins/katello-pr-test/detail/katello-pr-test/12006/tests Don't think the stubbing helped much.. 😭 😭

**Comment by sjha4** [comment]
Uff..another random failure: https://ci.theforeman.org/blue/organizations/jenkins/katello-pr-test/detail/katello-pr-test/12008/tests
😸 
This time it's the `test_yum_copy_all_no_filter_rules – Actions::Pulp3::MultiCopyAllUnitYumRepositoryTest`

**Comment by sjha4** [comment]
> test_yum_copy_all_no_filter_rules – Actions::Pulp3::MultiCopyAllUnitYumRepositoryTest

This one should be fixed with the last push. Assert_equal wasn't ordering the 2 arrays right for some reason.

**Comment by jeremylenz** [comment]
We have assert_equal_arrays that would've saved you some work ;)

**Comment by sjha4** [comment]
> assert_equal_arrays

Interesting..that does this:
`assert_equal array1.sort, array2.sort` which we had and that doesn't seem to give us consistently equal ordering. order_by(:id) should make it unambiguous and consistent.

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jeremylenz** [comment]
> Interesting..that does this:
> `assert_equal array1.sort, array2.sort` which we had and that doesn't seem to give us consistently equal ordering. order_by(:id) should make it unambiguous and consistent.

Maybe we should make an `assert_equal_active_record_relations` that does that :smile:

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
New failure: 

test_enabled_repositories – Katello::Api::V2::HostSubscriptionsProductContentTest

```
Error
Expected: 1...
Stacktrace
Failure:
test_enabled_repositories(Minitest::Result) [/home/jenkins/workspace/katello-pr-test/test/controllers/api/v2/host_subscriptions_controller_test.rb:294]:
Expected: 1
  Actual: 0
```

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Review by jeremylenz — APPROVED** [review]

**Pull request merged**
