### PR TITLE
Fixes #32788 - Fix wording on new CV page empty state

### PR DESCRIPTION
**Pull request by maccelf**
The empty state in `/labs/content_views` currently says "A content view can be added by using the "New content view" button below." However, the button is actually above and is called "Create content view."

### CODE REVIEW

**Comment by sjha4** [comment]
[test katello]

**Review by sjha4 — APPROVED** [review]
Thanks @maccelf !

**Comment by sjha4** [comment]
@maccelf : Could you resolve the conflict on the file, keeping your changes and push again?

**Comment by maccelf** [comment]
> @maccelf : Could you resolve the conflict on the file, keeping your changes and push again?

Done

**Comment by sjha4** [comment]
[test katello]
Thanks @maccelf !

**Comment by sjha4** [comment]
[test katello]

**Pull request merged**
