### PR TITLE
Fixes #18288: use foreman style toast notifications.

### PR DESCRIPTION
**Pull request by waldenraines**
Instead of using bst-alerts inline notificaitons use toast style
function via our Notification service.

http://projects.theforeman.org/issues/18288

### CODE REVIEW

**Comment by waldenraines** [comment]
Requires https://github.com/Katello/bastion/pull/172

**Comment by waldenraines** [comment]
Do not merge this yet, still need to fix tests but wanted to open so others could review.

**Comment by waldenraines** [comment]
> Do not merge this yet, still need to fix tests but wanted to open so others could review.

Tests should be fixed now.

**Comment by waldenraines** [comment]
> Tests should be fixed now.

Although they won't pass in this PR until a new version of bastion is out with Katello/bastion#172 included.

**Comment by dLobatog** [comment]
@waldenraines Have you seen https://github.com/theforeman/foreman/pull/4300/files ? I think it's probably feasible to use the component in Katello so that we do not have two implementations for toast notifications, but I would need to look into it with more detail

cc @ohadlevy @gailsteiger

**Comment by waldenraines** [comment]
> @waldenraines Have you seen https://github.com/theforeman/foreman/pull/4300/files ? I think it's probably feasible to use the component in Katello so that we do not have two implementations for toast notifications, but I would need to look into it with more detail
> 
> cc @ohadlevy @gailsteiger

Yeah, in the bastion PR I mention that I am going to wait on https://github.com/theforeman/foreman/pull/4300 and use that instead

**Comment by thomasmckay** [comment]
What's the status of this PR and the bastion one? When they're ready for testing, let me know. Thanks!

**Comment by waldenraines** [comment]
> What's the status of this PR and the bastion one? When they're ready for testing, let me know. Thanks!

On hold for the time being.  I may be able to pick this back up soon but no promises.

**Comment by waldenraines** [comment]
This is now ready for review.

**Comment by waldenraines** [comment]
Tests won't pass until katello/bastion#172 is merged.

**Comment by jturel** [comment]
@waldenraines looks like this branch is pretty old and I think there are places that may be new or were otherwise missed by your changes (also probably explains the merge conflicts). Searching the code for 'successMessages' and 'errorMessages' revealed a few.

**Comment by waldenraines** [comment]
> @waldenraines looks like this branch is pretty old and I think there are places that may be new or were otherwise missed by your changes (also probably explains the merge conflicts). Searching the code for 'successMessages' and 'errorMessages' revealed a few.

I actually just updated it last week but I can do so again.

**Comment by waldenraines** [comment]
@jturel updated.

**Comment by jturel** [comment]
@waldenraines 

I think there's one last occurrence that needs to be changed [here](https://github.com/waldenraines/katello/blob/62df72b59b9905ee801d312fe7c63200465df7fa/engines/bastion_katello/app/assets/javascripts/bastion_katello/host-collections/details/host-collection-copy.controller.js#L16)

**Comment by waldenraines** [comment]
> I think there's one last occurrence that needs to be changed here

@jturel nice catch, updated.

**Pull request merged**
