### PR TITLE
Refs #24033 - Refactor subscriptions task-modal

### PR DESCRIPTION
**Pull request by sharvit**
Move the task-modal state from the SubscriptionsPage to redux

### CODE REVIEW

**Comment by waldenraines** [comment]
@sharvit sorry, I created some conflicts for you here by merging https://github.com/Katello/katello/pull/7833.

**Comment by sharvit** [comment]
np @waldenraines  rebased

**Comment by waldenraines** [comment]
@sharvit needs another rebase.  I will review this one first and then finally https://github.com/Katello/katello/pull/7834

**Comment by sharvit** [comment]
Thanks @waldenraines, rebased!

**Pull request merged**
