### PR TITLE
Fixes #10621: Refactor to use SETTINGS instead of Katello.config

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Depends on -- #5253

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
This is green finally if anyone wants to tackle reviewing it.

**Comment by ehelms** [comment]
Subsequent change needed for puppet module https://github.com/Katello/puppet-katello/pull/74

Note that this won't break on upgrades because the deployed file is still the same name.

**Comment by jlsherrill** [comment]
seeing an issue when looking at a product>repositories list

```

2015-08-04T17:22:25 [app] [E] NoMethodError: undefined method `zero?' for "30":String
 | /home/vagrant/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
 | /home/vagrant/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:877:in `connect'
 | /home/vagrant/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
 | /home/vagrant/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/net/http.rb:851:in `start'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/rbovirt-0.0.35/lib/restclient_ext/request.rb:44:in `transmit'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/rest-client-1.6.9/lib/restclient/request.rb:68:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/rest-client-1.6.9/lib/restclient/request.rb:35:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/rest-client-1.6.9/lib/restclient/resource.rb:51:in `get'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/runcible-1.3.5/lib/runcible/base.rb:91:in `get_response'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/runcible-1.3.5/lib/runcible/base.rb:79:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/runcible-1.3.5/lib/runcible/resources/repository.rb:54:in `retrieve'
 | /home/vagrant/.rvm/gems/ruby-2.0.0-p598/gems/runcible-1.3.5/lib/runcible/extensions/repository.rb:340:in `retrieve_with_details'
```

**Comment by ehelms** [comment]
Updated with a rebase and a fix targeted at the issue you saw @jlsherrill

**Comment by ehelms** [comment]
I would love to get some prioritization on reviewing this from a few folks, it's a large change that could do with getting in sooner rather than later and the constant re-basing required is a touch annoying.

**Comment by parthaa** [comment]
APJ

I tested the following
1) New Org, Env, CV, AK, products, repos (yum + puppet). 
2)Repo Sync/ CV publish/promote .
3) Manifest upload/RH repo enablement.

looked ok. Most of the cp/pulp  interactions should have been tested by this workflow. More over the bats tests should catch functionality or integration errors. So to reiterate

APJ

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
I tested upgrades and investigated the 401 that was happening which was due to not properly merging the base settings defined in engine.rb with those defined in the yaml file.

**Comment by ehelms** [comment]
@parthaa could you double check my addition and look at https://github.com/Katello/puppet-katello/pull/74 and https://github.com/Katello/katello-packaging/pull/85 since we will need both

**Comment by ehelms** [comment]
This as well will be needed -- https://github.com/Katello/puppet-katello_devel/pull/47

**Comment by jlsherrill** [comment]
ACK from me

**Pull request merged**
