### PR TITLE
Fixes #17220 - Add help article link on manifest page

### PR DESCRIPTION
**Pull request by swapab**

### CODE REVIEW

**Comment by thomasmckay** [comment]
I really like the idea of having a link to Red Hat documentation that describes what a manifest is and how to use it. However, the message here is assuming that a primary use case will be that there are errors importing a manifest; I would prefer to see a positive message directing the user to source, or sources, of information. Second, the article linked is for a very specific issue that requires drastic interaction and correction: Are Red Hat subscriptions that broken that this happens all the time?

The issue number 177207 doesn't exist in red mine, what is the correct number?

**Comment by swapnilabnave** [comment]
@thomasmckay 
Issue number is 17220. Sorry for the typo in my PR title.

**Comment by thomasmckay** [comment]
As discussed on IRC, making this a more dynamic feature that takes the error message and directs with a link to either the red hat access insights plugin, if installed, or the customer portal would both solve this specific error case as well as provide a more general means for users to self-solve issues.
Thanks!

**Comment by jlsherrill** [comment]
Moving to Waiting on contributor based on comment

**Comment by ehelms** [comment]
@swapab planning to revisit this? Otherwise, I'll close in a week or so.

**Comment by swapab** [comment]
@ehelms Yes, this is WIP on my side. I'll update in a couple of weeks, please keep it open till then.

**Comment by ehelms** [comment]
@swapab keeping open, looks like it will need a rebase

**Comment by bkearney** [comment]
To be fair, this was a bad RFE from me. If we want to change this to point it at https://access.redhat.com/documentation/en/red-hat-satellite/6.2/paged/content-management-guide/chapter-3-managing-subscriptions then I think it would be fine.

**Comment by thomasmckay** [comment]
Looks like a bad merge/rebase? There are a lot of unrelated changes.

**Comment by swapab** [comment]
@bkearney It might be an apprehensive RFE. But the way it had been suggested by @thomasmckay looks promising. I believe this should come into existence.

I am in a discussion with @lphiri repo owner of [redhataccess-foreman-plugin](https://github.com/redhataccess/foreman-plugin). The feature would be to 'provide the user with a searchable link to redhat-access plugin if installed'
```
Failed to import archive (Katello::Errors::CandlepinError) Click here to resolve
```
I would like to give it a try.

---
I'll close this PR and create a new one(once ready) with dynamic error-resolution suggestions.

**Pull request closed without merging**
