### PR TITLE
Fixes #22748 - API for Selectable columns for Subs

### PR DESCRIPTION
**Pull request by parthaa**
This commit adds the initial API bindings for selectable columns for
subscriptions. We basically massage the API returned by the index call
to include columns that could be displayed and their values.

### CODE REVIEW

**Comment by parthaa** [comment]
Note: This PR is blocked by https://github.com/theforeman/foreman/pull/5262

**Comment by parthaa** [comment]
Basically this is the intended selectable columns mechanism
- Index call on the resource will return the selectable attributes as a part of the index json
```
https://<sat>/katello/api/v2/organizations/1/subscriptions?enabled=true&organization_id=1&page=1&paged=true&per_page=20&search=&sort_order=ASC

return data that looks like

{
    "organization": {},
    "total": 5,
    "subtotal": 5,
    "page": "1",
    "per_page": "20",
    "error": null,
    "search": "",
    "sort": {
        "by": "cp_id",
        "order": "asc"
    },
    "results": [
        .....
        {
            "id": 4,
            "cp_id": "...",
            "subscription_id": 4,
            "name": " Employee Subscription",
            "start_date": "2015-12-15 00:00:00 -0500",
            "end_date": "2021-12-31 23:59:59 -0500",
            "available": 100,
            "quantity": 100,
            "consumed": 0,
            "account_number": XXXXXX,
            "contract_number": YYYYY,
            "support_level": "Self-Support",
            "product_id": "PPPPP",
            "sockets": 128,
            "cores": null,
            "ram": null,
            "instance_multiplier": 1,
            "stacking_id": null,
            "multi_entitlement": null,
            "type": "NORMAL",
            "product_name": "My Employee Subscription",
            "unmapped_guest": false,
            "virt_only": false,
            "virt_who": false,
            "selected_column_values": {
                "name": "My Employee Subscription",
                "account": XXXXXX,
                "contract": YYYYY,
                "start_date": "2015-12-15 00:00:00 -0500",
                "end_date": "2021-12-31 23:59:59 -0500",
                "virt_who": false,
                "entitlements": 0
            }
        },
        .....
    ],
    "selected_columns": {
        "resource": "subscriptions",
        "columns": [
            {
                "name": "name",
                "description": "Name",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "account",
                "description": "Account",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "contract",
                "description": "Contract",
                "default_enabled": true,
                "enabled": false
            },
            {
                "name": "start_date",
                "description": "Start Date",
                "default_enabled": true,
                "enabled": false
            },
            {
                "name": "end_date",
                "description": "End Date",
                "default_enabled": true,
                "enabled": false
            },
            {
                "name": "virt_who",
                "description": "Requires Virt-Who",
                "default_enabled": true,
                "enabled": false
            },
            {
                "name": "entitlements",
                "description": "Entitlements",
                "default_enabled": true,
                "enabled": false
            }
        ]
    }
}

```

Important thing to notice here is the selected_columns at the top level and selected_column_values in the results section. The "enabled" flag will tell you what fields were selected. By default some columns are marked enabled by the model (default_enabled is meant for that)


- To update you are going to have to do the equivalent of 
```
curl -k -u admin:changeme -H "Content-Type: application/json" -X POST -d '{"resource":"subscriptions", "columns":["name","account"]}'   "https://localhost/api/v2/user_columns"
```
ie send a post to user_columns in foreman

- To reset the columns list for user you can do the equivalent of 
```
curl -k -u admin:changeme -H "Content-Type: application/json" -X DELETE -d '{"resource":"subscriptions"}'   "https://localhost/api/v2/user_columns/reset"
```
- To delete the columns list for user for ALL resource you can do the equivalent of
```
curl -k -u admin:changeme -H "Content-Type: application/json" -X DELETE  "https://localhost/api/v2/user_columns"
```

**Comment by waldenraines** [comment]
> Important thing to notice here is the selected_columns at the top level and selected_column_values in the results section.

I am not sure we need the selected_column_values in the result itself.  What would you imagine that would be used for?

Also I wonder if we should call the top level "selected_columns" something like "table_config" so we can support column ordering in the future.

Otherwise I like this approach.

**Comment by waldenraines** [comment]
Can we assume that the column names will match up with the name of the property of the resource itself?  Will the column `entitlements` match up to `subscription.entitlements`, for example?

**Comment by parthaa** [comment]
> Can we assume that the column names will match up with the name of the property of the resource itself? Will the column entitlements match up to subscription.entitlements, for example?

Not really. If we want to infer values in the json based on the name its going to get harder with nested structures and all.  May be thats the reason I added selected_column_values where there was 1:1 matching between name and value (although its still looks like its not needed will likely get rm'ed).

Anyway use the name  to determine which column to show or not in the ui. Don't expect to infer values in the json using that property.  If that is desired I need to look in more. So let me know.

**Comment by waldenraines** [comment]
> Not really. If we want to infer values in the json based on the name its going to get harder with nested structures and all

Seems like this is what we would want though.  Otherwise we will have to have mappings on each client (cli, UI, etc.) to map the columns to the value in the json.  @jlsherrill any thoughts on this?

**Comment by jlsherrill** [comment]
yeah, i thought the original discussion was that it did lead into the json hash of each object, and would support nested attributes 'environment_id' or 'environment.id' depending on what the json structure was

**Comment by parthaa** [comment]
Updated this to work according to @jlsherrill  & @waldenraines ' suggestions. . 
- No "selected_column_values"
- selected_columns got renamed to table_configuration
- new resource entry in the table_configuration. You need to use this as the resource name when you are saving the columns.
i.e. doing the equivalent of
```
curl -k -u admin:changeme -H "Content-Type: application/json" -X POST -d '{"resource":"Katello::Pool", "columns":["name","account"]}'   "https://localhost/api/v2/user_columns"
```
- there is now a 'path' attribute available for every column definition
- New UserColumnRegistry in foreman for a centralized area to add default column definitions

Here is the new format for the index call

```
on GET https://<sat>/katello/api/v2/organizations/1/subscriptions?enabled=true&organization_id=1&page=1&paged=true&per_page=20&search=&sort_order=ASC

{
    "organization": {},
    "total": 5,
    "subtotal": 5,
    "page": "1",
    "per_page": "20",
    "error": null,
    "search": "",
    "sort": {
        "by": "cp_id",
        "order": "asc"
    },
    "results": [
    .....
    ],
    "table_configuration": {
        "resource": "Katello::Pool",
        "columns": [
            {
                "name": "name",
                "description": "Name",
                "path": "name",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "account",
                "description": "Account",
                "path": "account_number",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "contract",
                "description": "Contract",
                "path": "contract_number",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "start_date",
                "description": "Start Date",
                "path": "start_date",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "end_date",
                "description": "End Date",
                "path": "end_date",
                "default_enabled": true,
                "enabled": true
            },
            {
                "name": "entitlements",
                "description": "Entitlements",
                "path": "consumed",
                "default_enabled": true,
                "enabled": true
            }
        ]
    }
}
```

**Comment by waldenraines** [comment]
Thanks for the updates @parthaa!  This looks good to me.  I only have a minor question:  what use case do you see for having both `name` and `path` in the table configuration response?

**Comment by parthaa** [comment]
> Thanks for the updates @parthaa! This looks good to me. I only have a minor question: what use case do you see for having both name and path in the table configuration response?

- name = label 
- path = path to get that attribute (I'd like it to use jsonpath format -``` $['store']['book'][0]['title']```)

**Comment by waldenraines** [comment]
> name = label

Okay, what would the label be used for then?

**Comment by parthaa** [comment]
Closing this as we decided not to have a registry or change api output for this sort of thing and just have the JS frontend handle all that

**Pull request closed without merging**
