### PR TITLE
Fixes #18593 - create repo on capsule with container name

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@jlsherrill seeing this still

```
2017-02-24T14:47:40 991b7eae [foreman-tasks/dynflow] [D]          Step 980d8b2c-b634-4225-a8d1-d6023b07b021:11 got event Dynflow::Action::Polling::Poll
2017-02-24T14:47:40 991b7eae [foreman-tasks/dynflow] [D]          Step 980d8b2c-b634-4225-a8d1-d6023b07b021:11 suspended >>   running in phase      Run Actions::Pulp::Consumer::SyncCapsule
2017-02-24T14:47:40 991b7eae [katello/pulp_rest] [D] RestClient.get "https://sushi-capsule.example.com/pulp/api/v2/tasks/5421dfa9-ca41-4f1a-8f9a-cadf0aa4368f/", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "accept"=>"application/json", "content_type"=>"application/json"
 | \n# => 200 OK | application/json 1415 bytes
 |
2017-02-24T14:47:40 991b7eae [foreman-tasks/action] [E] DKR1007: Could not fetch repository default_organization-dockah-fedorassh from registry https://sushi.example.com:5000 - NOT FOUND (Katello::Errors::PulpError)
 | /home/vagrant/katello/app/lib/actions/pulp/abstract_async_task.rb:121:in `block in external_task='
 | /home/vagrant/katello/app/lib/actions/pulp/abstract_async_task.rb:119:in `each'
 | /home/vagrant/katello/app/lib/actions/pulp/abstract_async_task.rb:119:in `external_task='
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action/polling.rb:98:in `poll_external_task_with_rescue'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action/polling.rb:21:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action/cancellable.rb:9:in `run'
 | /home/vagrant/katello/app/lib/actions/pulp/abstract_async_task.rb:45:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:506:in `block (3 levels) in execute_run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:17:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:30:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:17:in `pass'
 | /home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:16:in `block in run'
 | /home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:40:in `block in as_remote_user'
 | /home/vagrant/katello/app/models/katello/concerns/user_extensions.rb:21:in `cp_config'
 | /home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:27:in `as_cp_user'
 | /home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:39:in `as_remote_user'
 | /home/vagrant/katello/app/lib/actions/middleware/remote_action.rb:16:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:17:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action/progress.rb:30:in `with_progress_calculation'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action/progress.rb:16:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:17:in `pass'
 | /home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:11:in `block in run'
 | /home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:22:in `with_locale'
 | /home/vagrant/katello/app/lib/actions/middleware/keep_locale.rb:11:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:26:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:17:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware.rb:30:in `run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/stack.rb:22:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/middleware/world.rb:30:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:505:in `block (2 levels) in execute_run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:504:in `catch'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:504:in `block in execute_run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:419:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:419:in `block in with_error_handling'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:419:in `catch'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:419:in `with_error_handling'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:499:in `execute_run'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/action.rb:260:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:9:in `block (2 levels) in execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract.rb:155:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract.rb:155:in `with_meta_calculation'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:8:in `block in execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:22:in `open_action'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/execution_plan/steps/abstract_flow_step.rb:7:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/director.rb:55:in `execute'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/executors/parallel/worker.rb:11:in `on_message'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/context.rb:46:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/executes_context.rb:7:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/dynflow-0.8.19/lib/dynflow/actor.rb:26:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/awaits.rb:15:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/buffer.rb:38:in `process_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/buffer.rb:31:in `process_envelopes?'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/buffer.rb:20:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/termination.rb:55:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/removes_child.rb:10:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/abstract.rb:25:in `pass'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/behaviour/sets_results.rb:14:in `on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/core.rb:161:in `process_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/core.rb:95:in `block in on_envelope'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/core.rb:118:in `block (2 levels) in schedule_execution'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-edge-0.2.3/lib/concurrent/actor/core.rb:115:in `block in schedule_execution'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/serialized_execution.rb:18:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/serialized_execution.rb:18:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/serialized_execution.rb:96:in `work'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/serialized_execution.rb:77:in `block in call_job'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/concurrent-ruby-1.0.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
 | /home/vagrant/.rvm/gems/ruby-2.2.4/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
2017-02-24T14:47:40 991b7eae [foreman-tasks/dynflow] [D]          Step 980d8b2c-b634-4225-a8d1-d6023b07b021:11   running >>     error in phase      Run Actions::Pulp::Consumer::SyncCapsule
```

**Comment by johnpmitsch** [comment]
The above is due to a faulty crane config on the dev box, and updating it is not being picked up, issue filed below.

http://projects.theforeman.org/issues/18666

**Comment by thomasmckay** [comment]
ack

**Comment by johnpmitsch** [comment]
@jlsherrill no need to wait on my ACK if @thomasmckay's worked

**Pull request merged**
