### PR TITLE
Fixes #10974 : Add downstream strings.

### PR DESCRIPTION
**Pull request by bkearney**
This is related to https://github.com/Katello/bastion/pull/72.
It would really be nice to have http://projects.theforeman.org/issues/10241 to make this easier.

The strings in this file were generated by:

1) Pulling the latest from zanata (which I think is no longer used)
2) Extracting the latest from the code
3) Applying any changes from the downstream strings.

I have one open question. If I look downstream, I see a directory with translations at
./engines/bastion_katello/app/assets/javascripts/bastion_katello/i18n/locale

but I do not see that upstream. Are we missing something?

Once this is merged, I would suggest engaging with a translation service. Either zanata, or
to be consistent, go with transifex.

### CODE REVIEW

**Comment by waldenraines** [comment]
> have one open question. If I look downstream, I see a directory with translations at
> ./engines/bastion_katello/app/assets/javascripts/bastion_katello/i18n/locale

I think should just commit the files in those directories from downstream.  They won't match up 100% to the text upstream but it's a good start.  What are your thoughts @ehelms?

**Comment by ehelms** [comment]
We never generated the base set of translations for bastion_katello but we should -- are those available to be committed from downstream?

**Comment by bkearney** [comment]
I have refreshed the pull request with the katello_bastion strings as well. In addition, I rebased.

**Comment by bkearney** [comment]
@ehelms i refreshed the code, and it has strings for katello proper and katello-bastion. This should be ready to go. it would be nice to have someone with better rails fu to look at http://projects.theforeman.org/issues/10241

**Comment by ehelms** [comment]
This will need updating to ensure that the generated translations file is not linted to pass CI. I have opened a PR against Bastion to enable this -- https://github.com/Katello/bastion/pull/76

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by bkearney** [comment]
@ehelms it looks like the failure is due to a trailing space in a file I did not edit. Should I fix it anyways in this PR?

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
For the last remaining linting failure, we could either:

a) fix the blank line issue
b) have the linter skip the locale folder since it contains generated files

**Comment by bkearney** [comment]
@ehelms I have an updated script which will remove that.. let me do a force update and then have you retest it.

**Comment by bkearney** [comment]
[test]

**Comment by ehelms** [comment]
I think this all looks fine to me, @waldenraines could you please give it a once over

**Comment by waldenraines** [comment]
ACK

**Comment by ehelms** [comment]
ACK for me as well

**Pull request merged**
