### PR TITLE
Fixes #18084 - Added validators to interger fields

### PR DESCRIPTION
**Pull request by kgaikwad**
With this commit, instead of postgresql exception it will
show proper validation message for interger fields.

### CODE REVIEW

**Comment by xprazak2** [comment]
Works as expected for me:

**Comment by jlsherrill** [comment]
[test]

**Comment by kgaikwad** [comment]
[test]

**Comment by kgaikwad** [comment]
@jlsherrill ,

Test build is failing with error message "Gemset 'test_katello_pull_request-3' does not exist".
I don't know how I can fix it.
Please let me know what are the changes required from my side to pass this check.

**Comment by jlsherrill** [comment]
@kgaikwad looks like  a rubocop failure:  
```
katello/app/models/katello/concerns/subscription_facet_host_extensions.rb:30:201: C: Line is too long. [235/200]
        scoped_search :relation => :activation_keys, :on => :id, :rename => :activation_key_id, :complete_value => true, :ext_method => :find_by_activation_key_id, :only_explicit => true, :validator => ScopedSearch::Validators::INTEGER
```
Simply break that into two lines :)

**Comment by kgaikwad** [comment]
@jlsherrill ,
Thank you!
I apologize that I missed rubocop checking for all files.
I corrected it now.

**Comment by kgaikwad** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK thanks @kgaikwad!

**Pull request merged**
