### PR TITLE
Fixes #19027 - Catch TransportFailure error

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
The referenced issue is not very descriptive, could you explain the reason this is needed?

**Comment by iNecas** [comment]
I'm wondering how this could ever work: I was not able to load the TransportError constant in console. Anyway, the description of a reproducer in the issue would be nice. Would this be something worth backporting?

**Comment by ehelms** [comment]
As @iNecas points out, because TransportError does not exist. This is the same reason it got changed here (https://github.com/Katello/katello/pull/6704/files#diff-c59cd993b468894d27aa7b761aa002ccR45). If you want to replicate this, you can try turning qpidd off or start a qpid that does not have the katello_event_queue.

**Comment by jlsherrill** [comment]
Gotcha, the qpid gem must create that at runtime if an error occurs or something?  ACK

**Comment by ehelms** [comment]
I think we tried to track it down when we fixed that other code location and could not figure it out other than your theory.

**Comment by ehelms** [comment]
@iNecas I have seen this error in logs before but it is not fatal as far as I could tell. I kept hitting this when playing with containers and figured I'd do due diligence and fix it proper.

**Comment by iNecas** [comment]
Thanks for explanation: no action needed now, but for future reference: it's good to leave a code comment explaining the things that are not common, to prevent a person with good intentions to catch the exceptions the right way :)

**Pull request merged**
