### PR TITLE
Fixes #24034 - Refactor Subscriptions Table

### PR DESCRIPTION
**Pull request by Laviro**
Refactor the SubscriptionTable file, divide into small inner components.

### CODE REVIEW

**Comment by Laviro** [comment]
@amirfefer @sharvit could you take a look?

**Comment by sharvit** [comment]
Awesome work @Laviro, it's going to be much easier to understand and maintain this code now :+1: 

Looks like one test is failing and you need to rebase the `SubscriptionsTable.js`.

**Comment by Laviro** [comment]
Thanks @sharvit, rebased, ready for more reviews :)

**Comment by Laviro** [comment]
Thanks @sharvit !! 
@amirfefer @waldenraines could you take a look?

**Comment by johnpmitsch** [comment]
@Laviro @waldenraines @sharvit I'm seeing this error when opening up a grouped subscription:

```
Table.js:33 Uncaught TypeError: Cannot read property 'toggleSubscriptionGroup' of undefined
    at Object.toggle (Table.js:33)
    at onClick (collapseableAndSelectionCellFormatter.js:14)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:270)
    at executeDispatch (react-dom.development.js:561)
    at executeDispatchesInOrder (react-dom.development.js:583)
    at executeDispatchesAndRelease (react-dom.development.js:680)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:688)
```
Does that seem related to this PR?

**Comment by johnpmitsch** [comment]
I filed here: https://projects.theforeman.org/issues/26908

**Comment by waldenraines** [comment]
> @Laviro @waldenraines @sharvit I'm seeing this error when opening up a grouped subscription:

It's possible.  We'll take a look, thanks for filing.

**Pull request merged**
