### PR TITLE
Fixes #24775 - Use REX for errata installation

### PR DESCRIPTION
**Pull request by mdellweg**
Big thank you to @adamruzicka !

### CODE REVIEW

**Comment by jlsherrill** [comment]
Failing a test: /var/lib/workspace/workspace/katello-pr-test/test/actions/katello/host/erratum_test.rb:

you may need to change that setting to false in the test?  i'm not 100% sure why its getting into the rex portion.  We currently don't require REX, nor run tests with REX, which isnt' great, but it is what it is :)

**Comment by mdellweg** [comment]
I think, it is this line:
`Setting.stubs(:[]).returns(2)`

**Comment by adamruzicka** [comment]
Stubbing it like that returned 2 also for `Setting['remote_execution_by_default']` and it tried to trigger the REX action because of that.

Do the `Settings` get reset after each test?

**Comment by mdellweg** [comment]
Can i stub the whole `Settings`?

**Comment by adamruzicka** [comment]
You could probably do something like this
```ruby
Settings.stubs(:[]).with('remote_execution_by_default').returns(false)
Settings.stubs(:[]).with('erratum_install_batch_size').returns(2)
```

**Comment by mdellweg** [comment]
Somehow, this made matters worse. I have no idea how.

**Comment by jlsherrill** [comment]
i think this is a transient error

[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by mdellweg** [comment]
@jlsherrill You were right. Now they pass. ;)

**Comment by sbernhard** [comment]
There are currently 2 possibilities to install Errata
- by Content Host -> Errata (select between via Katello Agent / Remote Execution possible)
- by the Errata menu entry (= no selection possible)

There is one drawback of this PR. In case "use Remote Execution by Default is true" remote execution will even be used when "via Katello-Agent" is selected in Content Host -> Errata Installation.

There is another place in bastion_katello/content-hosts/bulk/content-hosts-bulk-errata-modal.controller.js that already distinguishes between errata installation via Katello Agent or via RemoteExecution.

So either distinguish uniformly in the UI or draw the distinction of the errata installation method directly into the backend.

**Comment by beav** [comment]
@mdellweg apologies for the delay in updates on this. looks like the PR needs a rebase

**Comment by mdellweg** [comment]
@beav Rebased

**Comment by mdellweg** [comment]
I never understood, why you should be able to select the mechanism to use in the GUI. I would prefer that you can configure the mechanism of choice sitewide, or some heuristics (maybe based on operatingsystem) that selects it for you.
The ordinary user of foreman / katello should really not be bothered with that choice.
Ceterum censeo katello-agentem esse delendam.

**Comment by beav** [comment]
> I never understood, why you should be able to select the mechanism to use in the GUI. I would prefer that you can configure the mechanism of choice sitewide, or some heuristics (maybe based on operatingsystem) that selects it for you.
> The ordinary user of foreman / katello should really not be bothered with that choice.
> Ceterum censeo katello-agentem esse delendam.

It's probably worth creating an RFC on the foreman dev list for opinions on this change. It sounds reasonable to me but I don't use that area much.

**Comment by adamruzicka** [comment]
What's the status here?

**Comment by jlsherrill** [comment]
Good question @beav you're thoughts?  I think this just needs some testing  I'm happy to do that in the next few days unless @beav has anything to add

**Comment by beav** [comment]
> Good question @beav you're thoughts? I think this just needs some testing I'm happy to do that in the next few days unless @beav has anything to add

Nothing to add from me, aside from making sure we document this in release notes.

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
I'm not sure that I agree with this change now in 2021. The approach we've taken with respect to eventual katello-agent removal is to encourage use of the job invocation API directly or via `hammer job-invocation create --feature=katello_errata_install` for example. In fact I'm updating the docs right now: https://github.com/theforeman/foreman-documentation/pull/444

This change seems incompatible with the current guidance but I see your original intent and it should have probably worked this way whenever 'remote_execution_by_default' was added. What do you think @mdellweg ?

**Comment by mdellweg** [comment]
I have no objection to closing this.

**Comment by jturel** [comment]
Closing this out per above comment.

**Pull request closed without merging**
