### PR TITLE
Fixes #18383: fix styling on content filter pages.

### PR DESCRIPTION
**Pull request by waldenraines**
Several content filter pages were not using nutupane and were thus never
converted. This commit fixes the styling on these pages and otherwise
simplifies them.

http://projects.theforeman.org/issues/18383

### CODE REVIEW

**Comment by jlsherrill** [comment]
Seeing an issue:

1.  create an errata by id filter
2.  Add a few errata
3.  Select one errata and remove it from the filter
4.  Notice the entire table disappears.

**Comment by waldenraines** [comment]
> Seeing an issue:
> 
> create an errata by id filter
> Add a few errata
> Select one errata and remove it from the filter
> Notice the entire table disappears.

@jlsherrill fixed

**Comment by jlsherrill** [comment]
Following the same procedure above i now cannot remove any errata from an errata by id filter.  It throws a js error:

TypeError: Cannot read property 'name' of undefined
    at bastion_katello.js:8020
    at Scope.$digest (bastion.js:17074)
    at Scope.$apply (bastion.js:17338)
    at done (bastion.js:11573)
    at completeRequest (bastion.js:11779)

dealing with the code:

```
        $scope.$watch('contentView.name', function () {
            if ($scope.contentViewForm.name) {
                $scope.contentViewForm.name.$setValidity('server', true);
                FormUtils.labelize($scope.contentView);
            }
        });
```

**Comment by waldenraines** [comment]
> EDIT: the steps have to be done in this exact order:
> 
> Add an errata to the filter
> click on the List/Remove tab
> Select an errata and try to remove it.
> if you reload the page before step 3 the problem does not occur

Looking at the code this is broken in master too but I went ahead and fixed it here

**Pull request merged**
