### PR TITLE
Fixes #22305: Unscope Host find on create via sub

### PR DESCRIPTION
**Pull request by akofink**
#### To Test

In rake console:
```rb
Host.new(name: 'devel.example.com').save!
```

Try to register `devel.example.com` via subscription-manager.

### CODE REVIEW

**Comment by jturel** [comment]
```
[vagrant@centos7-devel foreman]$ sudo subscription-manager register --force                                                                                                  Unregistering from: centos7-devel.jturel.example.com:443/rhsm                         
The system with UUID 414867c0-cce7-41b8-8e41-916d38f8f06a has been unregistered       
All local data removed                     
Registering to: centos7-devel.jturel.example.com:443/rhsm                             
Username: admin                            
Password:                                  
Organization: Default_Organization         
Environment: Library                       
Validation failed: Name has already been taken 
```
...patch applied...

```
[vagrant@centos7-devel katello]$ sudo subscription-manager register --force           
Registering to: centos7-devel.jturel.example.com:443/rhsm                             
Username: admin                            
Password:                                  
Organization: Default_Organization         
Environment: Library                       
The system has been registered with ID: 8ef678f9-35f9-4aa0-a25f-eb99f371ec33
```

Works well. any potential issues with unscoping the host lookup that you can think of?

**Comment by akofink** [comment]
Before [this change](https://github.com/theforeman/foreman/pull/4878), it was behaving this way, so I think it's fine.

**Comment by jturel** [comment]
Ok, APJ!

**Comment by jturel** [comment]
[test rails-5]

**Comment by akofink** [comment]
Ok! So, the test failure is caused by the added host in the fixtures. The organizations#edit page behaves a bit differently if you have hosts that are not assigned to an organization.

**Pull request merged**
