### PR TITLE
Fixes #29931 - Encrypt Root repository upstream password

### PR DESCRIPTION
**Pull request by piyushtiw**
Bug fix for https://projects.theforeman.org/issues/29931#change-136569

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by piyushtiw** [comment]
The test is failing because it is not able to encrypt the upstream password. If the encryption key is set in the test environment, the test should pass. The test passed in my local after setting the encryption key.

**Comment by piyushtiw** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by tbrisker** [comment]
It appears that core PR katello tests are now failing:
```
--- expected
+++ actual
@@ -1 +1 @@
-"encrypted-WDV6TEVGSUlIZFRWK0RLS1JaaHZCSnVoYklnTEFSY3l1MmRoVTZDeFNiWT0tLVA4aEkzN0czc2xHbGZmSmRFMjZVRlE9PQ==--ef558797d045e2cf1f1b4e293c3f1a4f15fce9d5"
+"secret"
 (Minitest::Assertion)
/home/jenkins/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/actions/katello/repository/discover_test.rb:30    

Standard Error

/home/jenkins/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/actions/katello/repository/discover_test.rb:20: warning: already initialized constant EncryptionKey::ENCRYPTION_KEY
/home/jenkins/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/actions/katello/repository/discover_test.rb:4: warning: previous definition of ENCRYPTION_KEY was here
/home/jenkins/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/actions/katello/repository/discover_test.rb:34: warning: already initialized constant EncryptionKey::ENCRYPTION_KEY
/home/jenkins/workspace/test_develop_pr_katello/database/postgresql/ruby/2.5/slave/fast/plugin/test/actions/katello/repository/discover_test.rb:20: warning: previous definition of ENCRYPTION_KEY was here
  
```

**Comment by snecklifter** [comment]
foreman-rake db:migrate is failing for me with this change:

```PG::StringDataRightTruncation: ERROR:  value too long for type character varying(1024)```

**Comment by parthaa** [comment]
@snecklifter  are you able to confirm this is is related to this PR ? May be  paste us the stack trace.

**Comment by snecklifter** [comment]
> @snecklifter are you able to confirm this is is related to this PR ? May be paste us the stack trace.

Well, when I back out the above changes, the db:migrate completes.

**Comment by parthaa** [comment]
> Well, when I back out the above changes, the db:migrate completes.

Interesting. In our tests we get this failure only on passwords greater than or equal to 500 characters. 
I am guessing you have repos with  passwords more than 500 characters.

**Comment by snecklifter** [comment]
@parthaa like Red Hat registry tokens? :)

**Comment by parthaa** [comment]
@snecklifter hah nice. Ok filed https://projects.theforeman.org/issues/30064 going to be addressed soonish.

**Pull request merged**
