### PR TITLE
Fixes #14644 - Progress bar will no longer show so many decimal places.

### PR DESCRIPTION
**Pull request by zjhuntin**
download

To test sync a capsule and watch the percentage complete.

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by johnpmitsch** [comment]
Its always showing the 1st decimal, (ex. %50.0) I am wondering if we should just show the rounded integer? (ex. %50)

**Comment by zjhuntin** [comment]
@johnpmitsch Okay, I fixed it so it should no longer show trailing zeros (this is what I found after searching around for a bit).

**Comment by zjhuntin** [comment]
[test]

**Comment by johnpmitsch** [comment]
APJ

**Pull request merged**
