### PR TITLE
Fixes #31832 - IDs for system purpose bulk action dialog

### PR DESCRIPTION
**Pull request by pondrejk**
Adding IDs as per 31832, also fixing some ng-model mismatch

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@chris1984 since this was your feature, do you mind reviewing?

**Comment by chris1984** [comment]
@jturel sure

**Review by chris1984 — APPROVED** [review]
ACK, tested I can see the id's in the browser debug and nothing broke as far as end to end testing.

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
