### PR TITLE
fixes #9951 - fixing package update during inc update

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Guessing there is not test hitting this code since this error arose in production?

**Comment by jlsherrill** [comment]
@ehelms added a test, wasn't as bad as i expected

**Comment by ehelms** [comment]
Thanks for adding a test...if I was looking for tests for this file, I'd think to look for `test/actions/katello/content_view_version/incremental_update_test.rb` just like model/controller/glue etc. tests

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
@ehelms thats not how the action tests are structured.  They are all organized by entity.  I think i would prefer what you suggest, but that is not the current trend

**Comment by ehelms** [comment]
APJ

**Comment by ehelms** [comment]
[test]

**Pull request merged**
