### PR TITLE
Fixes #30250 - Can search subscription by name

### PR DESCRIPTION
**Pull request by parthaa**
The commit makes the subscirption index endpoint accept the name
parameter to filter and responds appropriately
It also marks org param required to make hammer --subscriptions flag
function correctly.

### CODE REVIEW

**Comment by parthaa** [comment]
- Create products in multiple orgs with the same name
- Create an activation key in one of em
- The call below should work
```
$ hammer -d activation-key add-subscription --subscription "ProductName" --name "activationkey" --organization org
```

**Comment by parthaa** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Comment by parthaa** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK, works well. Thanks @parthaa

**Pull request merged**
