### PR TITLE
[CP] 3.7.1 Cherry Picks

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@ehelms any thought on this angular-ui failure? I think this has come up before:
```
[bastion_katello] Running shell script

+ grunt ci

Running "eslint:target" (eslint) task

Warning: Cannot find module 'eslint-plugin-jest' Use --force to continue.


Aborted due to warnings.

script returned exit code 3
```

**Comment by jturel** [comment]
angular tests pass on my devel box for this branch

```
[vagrant@centos7-devel bastion_katello]$ grunt ci
Running "eslint:target" (eslint) task


Running "htmlhint:src" (htmlhint) task
>> 221 files lint free.

Running "karma:ci" (karma) task
07 09 2018 17:47:55.401:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
07 09 2018 17:47:55.407:INFO [launcher]: Starting browser PhantomJS
07 09 2018 17:47:55.614:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket BSB8cK9CY8n4ZFWrAAAA with id 65087235
PhantomJS 2.1.1 (Linux 0.0.0): Executed 739 of 740 (skipped 1) SUCCESS (10.866 secs / 10.442 secs)

Done, without errors.
```

**Comment by jturel** [comment]
@sjha4 thanks for trying :)

[test katello]

**Comment by sjha4** [comment]
[test katello]
@jturel welcome! :smile:

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by sjha4** [comment]
[test katello]

**Comment by sjha4** [comment]
@jturel :  Angular-ui is passing though.. :champagne: :fireworks: :smile:

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@sjha4 it's green! are you comfortable acking ?

**Comment by cfouant** [comment]
ACK

**Comment by sjha4** [comment]
ACK! :+1:

**Pull request merged**
