### PR TITLE
Fixes #21261 - Use ::Dynflow::Action::Singleton for long running tasks

### PR DESCRIPTION
**Pull request by adamruzicka**
Specifically for EventQueue::Monitor and ListenOnCandlepingEvent

- [ ] requires https://github.com/Dynflow/dynflow/pull/253

### CODE REVIEW

**Comment by jlsherrill** [comment]
@adamruzicka @iNecas can we get a dynflow release? :)

**Comment by iNecas** [comment]
Yes, there is one more thing I would like to get in to speed up the startup of the rails env in tasks related to https://bugzilla.redhat.com/show_bug.cgi?id=1493046 The new release should be out in few days

**Comment by iNecas** [comment]
Or, you know what, there is enough version numbers for everyone :) 0.8.31 is for you :)

**Comment by jlsherrill** [comment]
@adamruzicka looks like the tests might need updating

**Comment by adamruzicka** [comment]
@jlsherrill not anymore

**Comment by jlsherrill** [comment]
@adamruzicka mind squashing your commits?  Testing, it all looks good!

**Comment by adamruzicka** [comment]
@jlsherrill not at all, squashed

**Comment by jlsherrill** [comment]
ACK thanks @adamruzicka !

**Pull request merged**
