### PR TITLE
Add Changelog for Katello 3.17

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by jturel** [comment]
@chris1984 can you take a look at the issues categorized under Other and see if they fit better into one of the other Redmine categories? Otherwise LGTM!

**Comment by chris1984** [comment]
@jturel updated

**Comment by jturel** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
