### PR TITLE
Fixes #34870 - Remove katello_module_stream_erratum_packages records …

### PR DESCRIPTION
**Pull request by sjha4**
#### What are the testing steps for this pull request?
How I tested this:
On a box in master, sync a repo like rhel-7-server-ansible-2.9-rpms with erarrata and all associations. Create a bunch of duplicate errata records.

err_dup = Katello::Erratum.find(id).dup
err_dup.pulp_id = "random_value"
err_dup.save!

Create a bunch of child records:

err_bug = Katello::ErratumBugzilla.first.dup
err_bug.erratum_id = err_dup.id
err_bug.save!

err_cve = Katello::ErratumCve.first.dup
err_cve.erratum_id = err_dup.id
err_cve.save!

err_package = Katello::ErratumPackage.first.dup
err_package.erratum_id = err_dup.id
err_package.save!

erra_package_mod_stream = Katello::ModuleStreamErratumPackage.new(module_stream_id: mod_stream_id, erratum_package_id: err_package.id)
erra_package_mod_stream.save!

Create a bunch of repository associations with the dup errata records.

repo_err_assoc = ::Katello::RepositoryErratum.new(repository_id: repo_id, erratum_id: err_dup.id)
repo_err_assoc.save!

Switch to PR branch and run db:migrate
To re-run if it has already run:
bundle exec rails db:migrate:down VERSION=20220303160220
bundle exec rails db:migrate:up VERSION=20220303160220

### CODE REVIEW

**Comment by ianballou** [comment]
I think I hit an issue.  I ran through the steps above and have two ModuleStreamErratumPackages that point to the same module stream.  Each ModuleStreamErratumPackage points to a different duplicate ErratumPackage.  When I ran through the migration, it was going to modify the duplicate ModuleStreamErratumPackage to have the same `erratum_package_id` as the original ModuleStreamErratumPackage.  When that was executed, this error popped up:

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "katello_module_stream_erratum_package_uniq"
DETAIL:  Key (module_stream_id, erratum_package_id)=(295, 114) already exists.
...
/home/vagrant/katello/db/migrate/20220303160220_remove_duplicate_errata.rb:42:in `block in up'
...
```

I think that duplicate should be deleted instead?

**Comment by sjha4** [comment]
> I think I hit an issue. I ran through the steps above and have two ModuleStreamErratumPackages that point to the same module stream. Each ModuleStreamErratumPackage points to a different duplicate ErratumPackage. When I ran through the migration, it was going to modify the duplicate ModuleStreamErratumPackage to have the same `erratum_package_id` as the original ModuleStreamErratumPackage. When that was executed, this error popped up:
> 
> ```
> PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "katello_module_stream_erratum_package_uniq"
> DETAIL:  Key (module_stream_id, erratum_package_id)=(295, 114) already exists.
> ...
> /home/vagrant/katello/db/migrate/20220303160220_remove_duplicate_errata.rb:42:in `block in up'
> ...
> ```
> 
> I think that duplicate should be deleted instead?

Hmmm..Maybe don't need to update katello_module_stream_erratum_package if original doesn't exist..I just had a query to update all. Will update.

**Comment by sjha4** [comment]
To test:
Sync 
Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8.4 
Confirm you have errata, modulestreams and in console, check if you have ::Katello::ModuleStreamErratumPackage.count > 0

Create a bunch of duplicate errata:

::Katello::Erratum.all.each do |errata|
 errata.pulp_id = errata.errata_id + 'random'
 errata.save!
end

Do a complete sync on the repo above.
Check ::Katello::ModuleStreamErratumPackage.count again and see if it increased.

Run migration:
bundle exec rails db:migrate:down VERSION=20220303160220
bundle exec rails db:migrate:up VERSION=20220303160220

::Katello::ModuleStreamErratumPackage.count should be back to what you had before the duplication.

**Comment by ianballou** [comment]
So I ran the migration, and all of my ModuleStreamErratumPackages were deleted. I ran
```
::Katello::Erratum.all.each do |errata|
errata.pulp_id = errata.errata_id + 'random'
errata.save!
end
```
and then resynced AppStream, but noticed that the `::Katello::ModuleStreamErratumPackage.count` didn't go up.  Then I took a ModuleStreamErratumPackage and switched it to point at one of the duplicated ErratumPackages to test, and ran the migration. After that I noticed I had no ModuleStreamErratumPackages.

**Review by ianballou — APPROVED** [review]
Doing the full errata duplication worked for me, and I think that's the best test we're gonna get here! I had quite a few RH repos with varying errata.

**Pull request merged**
