### PR TITLE
Fixes #16535: remove nutupane from katello products pages.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/16535

Requires https://github.com/Katello/bastion/pull/128

Here are some screenshots of these changes for comparison.

Products page before:
screen shot 2016-09-13 at 11 48 11 am

Products page after:

screen shot 2016-09-13 at 11 51 32 am

Product repositories list before:

screen shot 2016-09-13 at 11 48 25 am

Product repositories list after:

screen shot 2016-09-13 at 11 51 44 am

Product repositories page at 1280x800px before:
screen shot 2016-09-13 at 11 58 45 am

Product repositories page at 1280x800px after:

screen shot 2016-09-13 at 12 09 28 pm

Repository details before:

screen shot 2016-09-13 at 11 49 31 am

Repository details after:

screen shot 2016-09-13 at 11 53 20 am

### CODE REVIEW

**Comment by waldenraines** [comment]
> Repository details after:

Currently I'm using `<dl>`s for this and I like that semantically but I may change this to `<dl class="dl-horizontal">` instead.  Any thoughts on this?

See also http://getbootstrap.com/css/#description

**Comment by thomasmckay** [comment]
The only suggestion I would make would be to combine the breadcrumbs with the product name. So instead of
```
Products >> Zoo >> Repositories >> Zoo
Zoo
```
just increase the font of the breadcrumbs to have a single line
```
Products >> Zoo >> Repositories >> Zoo
```

**Comment by thomasmckay** [comment]
cc: @Rohoover

**Comment by waldenraines** [comment]
> Typically we do let them repeat - I know they repeat in other products

I agree with this and I like that mockup.  I will change the details pages to look more like that (with the breadcrumbs below the name of the item).

**Comment by jlsherrill** [comment]
The editables on this page:  https://cloud.githubusercontent.com/assets/4116405/18481108/004e9584-79a9-11e6-9935-b935c22c9280.png

look a bit awkward.  They were on the same line with the label but now they aren't

**Comment by waldenraines** [comment]
> The editables on this page: https://cloud.githubusercontent.com/assets/4116405/18481108/004e9584-79a9-11e6-9935-b935c22c9280.png
> 
> look a bit awkward. They were on the same line with the label but now they aren't

See my above comment https://github.com/Katello/katello/pull/6312/#issuecomment-246736676

**Comment by thomasmckay** [comment]
@waldenraines @Rohoover - I'll certainly not go against your combined experience, but in the new image "Packages" is listed twice _and_ the name of the package is listed twice... you've doubled down on what I was suggesting we not do. :) Whatever you decide is honestly fine; I'll certainly know where I am in the chain.

**Comment by Rohoover** [comment]
@waldenraines  @thomasmckay 

So, I think I may see what you're talking about.  The tab "repositories" is appearing in the breadcrumb, when it need not. The breadcrumb should read "Products >> Zoo", with only "Products" being the link. Does that jive with what you're saying @thomasmckay?
"Zoo" is repeated so that the user knows how they got to "Zoo" (through Products).

**Comment by waldenraines** [comment]
> So, I think I may see what you're talking about. The tab "repositories" is appearing in the breadcrumb, when it need not. The breadcrumb should read "Products >> Zoo", with only "Products" being the link. Does that jive with what you're saying @thomasmckay?
> "Zoo" is repeated so that the user knows how they got to "Zoo" (through Products).

The thing is that there is a repositories list within each product so you had to come through that repositories list to get to this repository (i.e. the repository you are viewing is a member of the repositories collection) so I think that it is good to have it in the breadcrumbs since it gives you a way to get back to the product -> repositories list.

I think @thomasmckay wants us to remove the title entirely and have the breadcrumbs be the title as well as the breadcrumbs.  I personally disagree with this.

**Comment by Rohoover** [comment]
@waldenraines 

Okay, I see. I went back and reviewed your previous pages. In that case, yes, it would be included in the breadcrumbs.

**Comment by bbuckingham** [comment]
I mentioned this in to @waldenraines in irc; however, I'll share my preference here as well.  While I like the ability to maximize the view of a given resource/object provided by the updated design, I really like having the ability easily move between objects using the left pane (provided by the existing design).  If possible, I think we should allow that to be configurable or collapsible or...etc.

**Comment by Rohoover** [comment]
@bbuckingham 
Do we have any data on how users are interacting with the two-pane view? Are they using it to compare multiple items? Are they frequently moving between items? 

I wasn't able to find any data on that which is why I offered up two solutions in my design document. I'll attach it here for reference.
[Satellite - Object Level Details.pdf](https://github.com/Katello/katello/files/472098/Satellite.-.Object.Level.Details.pdf)

**Comment by bbuckingham** [comment]
@Rohoover, Unfortunately, I do not have any user data; however, given that it has been in katello for several years, my assumption is that users are used to it.  That doesn't make it 'right' though.  As a dev, I'd consider myself a non-power user; however, I use it essentially every time I work in the UI for quickly moving between objects, comparing and some times to facilitate selecting objects for a multi-select.  That said, I use it most frequently for the 'quick moves'.

There was a time where tupane was written w/ jquery/javascript/haml and it evolved to nutupane using angularjs.  At that time, I thought UX had done some user studies.  Kyle Baker may have some data from back then.

**Comment by waldenraines** [comment]
> I mentioned this in to @waldenraines in irc; however, I'll share my preference here as well. While I like the ability to maximize the view of a given resource/object provided by the updated design, I really like having the ability easily move between objects using the left pane (provided by the existing design). If possible, I think we should allow that to be configurable or collapsible or...etc.

I would like to revisit adding a quick browse or compare after we get these changes in.  Think of this as establishing a new baseline.  From that baseline we can gather requirements and even user test the idea of a quick browse or a comparison between items.

> Kyle Baker may have some data from back then.

@kybaker

**Comment by thomasmckay** [comment]
Having a collapsible/optional left list for quick change between objects would get a +1 for me. When fixing subscriptions on multiple hosts it is handy to switch back and forth. Opening pages in tabs, however, is equally usable for this so I could certainly live without it.

**Comment by waldenraines** [comment]
> Having a collapsible/optional left list for quick change between objects would get a +1 for me. When fixing subscriptions on multiple hosts it is handy to switch back and forth. Opening pages in tabs, however, is equally usable for this so I could certainly live without it.

What about something more compact for quick navigation between list items?  Even something as simple as a `<select>` could work.

**Comment by Rohoover** [comment]
I quickly chatted with Kyle and he didn't have any data on this particular issue. Perhaps we can leverage some customer facing peers to get some semi-formal feedback on this UI pattern. Any feedback directly from customers would be better than the nothing we have now.

Though I trust all of you, and know you are experts in your skill set, getting feedback directly from our users would be invaluable and remove some of the guesswork. 

I don't want to hold up anyone, so I think regardless of what decision is made in this moment we still need to pursue this. I can reach out get some movement on it.

Thoughts?

**Comment by mccun934** [comment]
@Rohoover one of the long standing complaints about our prior project was the fact that viewing details of an object required a full screen and there was no way to quickly switch between similar objects to compare. That was the entire design idea/justification for the existing 2-pane design. That said, there is no real data on this, just long standing collective knowledge from us who have been working on this stuff for a while.

so .. anecdotal data ;) but nothing concrete.

**Comment by mccun934** [comment]
and .. +1 to getting some data from our users

**Comment by bbuckingham** [comment]
@waldenraines, @Rohoover, I am totally open to seeing our design evolve and improve, so my comments were not meant to be negative or blocking progress.  As long as we have a means to support those quick moves, comparisons, multi-selects...etc, I am sure that I will be fine with it.  And +1 to getting data from our users, as they are the ones that will be most impacted by our changes.

**Comment by ehelms** [comment]
I think it would be helpful to know _what_ data y'all and users are looking at when they are switching around between different objects to do comparisons or find ones to select to perform some bulk action on. While not conclusive, there is some indication that this could be evidence that we are not:

 a) providing good enough search capabilities or tagging to enable easy finding of a group of related objects
 b) providing not enough useful information in table view to find and select a set of objects

We can always add a cart if folks need to browse details and build a list ;)

**Comment by waldenraines** [comment]
Bastion PR has changed to https://github.com/Katello/bastion/pull/128.

**Comment by thomasmckay** [comment]
@ehelms @Rohoover @waldenraines I'll give an example from this morning of left list. This page, Compute Profiles, doesn't follow the katello pattern; this page shows a list. Selecting a profile brings you to _another_ list (of compute resources). Selecting a compute resource results in the katello pattern with an abbreviated left list and the details pane to the right. Kind of confusing, actually, now that I'm typing it. :) But, I digress!

My use case was that I wished to set up compute profiles for one of my compute resources. If there was a left list of profiles, I could quickly select the first, adjust, select the second, adjust, etc. As it was, I had to traverse in and out three deep of pages. Since I am new to this area, I also had to return to previous profiles to readjust as I learned a bit more.

In this case, tbh, I probably would have been very happy with having _editable_ fields in the master table like this http://www.patternfly.org/pattern-library/content-views/list-view/#/expanding-rows . That would have been very effective.

I'm sort of talking myself out of the left list in favor of other patternfly patterns.

**Comment by Rohoover** [comment]
I've created a brief survey to get more info on this issue. I've sent it to the one customer contact I do have for summit. He did respond. 

The cliff notes version basically says, it depends. Certain areas of the application the two-pane view is helpful, and in others it is not. 

I've reached out to Dave Caplan to see if we can get this out to more customers. Obviously a sample set of 1 isn't really a set.

**Comment by waldenraines** [comment]
Just pushed a big update with bulk actions and discovery pages.  Here are a couple of screenshots:

screen shot 2016-09-27 at 10 49 10 pm
screen shot 2016-09-27 at 10 49 20 pm

The big thing to notice here is that we are no longer going to "bulk action" pages for these actions.  The bulk actions are a little more complicated with content hosts than they are for products so that may present somewhat of a challenge for this approach but I think we'll manage.

**Comment by thomasmckay** [comment]
I selected two products then chose "Sync" bulk button. Then I visited a product, then returned to product list via breadcrumb. The "Product sync initiated..." green message showed up again and then faded out. Maybe messages stored in js should be cleared on visiting a new page?

**Comment by thomasmckay** [comment]
When selecting multiple objects in the products list, I found the "2 Selected" on the far right to seem not associated with the buttons that appeared. I don't run in fullscreen but if I did they would be _very_ far away from one another. Perhaps the count could be to the left of the action buttons? Are there patternfly suggestions/standards to compare to?

**Comment by thomasmckay** [comment]
The link formed by the "Packages" count in a specific repository (right column w/ Errata and Package Groups) is highlighted as a link but does not lead to page change.

**Comment by thomasmckay** [comment]
Since the bulk buttons perform possibly heavy operations (syncing all my repos!), it may be good to add confirmation dialog.

**Comment by waldenraines** [comment]
> When selecting multiple objects in the products list, I found the "2 Selected" on the far right to seem not associated with the buttons that appeared. I don't run in fullscreen but if I did they would be very far away from one another. Perhaps the count could be to the left of the action buttons? Are there patternfly suggestions/standards to compare to?

Yes, http://www.patternfly.org/pattern-library/content-views/table-view/#_ which has the number selected on the right side.  This is how it was prior to my changes as well.

**Comment by thomasmckay** [comment]
I am not a fan of the pattern where actions are hidden until a row is selected. For example, I visually see no way to remove a product. Visiting the product itself has no remove and the remove button only shows up when a row is selected.

Foreman hosts page has this same issue and a _very_ common user question is, "How do I change a host's organization?" The answer is invariably, "Select the host in the list and then use the bulk actions dropdown." Users naturally expect to be able to do all operations on the individual objects themselves. I think this is especially true when switching away from nutupane which kept the full list buttons present when visiting an individual item. 

I would also consider looking at the massive Host bulk actions drop down and imagine how it would be done w/ buttons instead of a single bulk menu. I see one of the Product bulk buttons is really a menu "Update Sync Plan" but it is not clear from the button itself. Is that purposeful?

Is there a pattern that would make these actions more readily apparent?

**Comment by thomasmckay** [comment]
I'll also say I don't like the way the rows "jump" when the first product checkbox is selected. It causes a mental hiccup that I need to relocate my mouse to the new position to select the second item. It's a bit disconcerting.

**Comment by thomasmckay** [comment]
As we discussed, changing the Details/Repositories/Tasks tabs to be relevant to the drilled-into repository instead of the product would be beneficial. This would allow changing the "Manage" buttons to be tabs.

**Comment by thomasmckay** [comment]
For repo discovery....

1. Breadcrumb says "Scan for Products" but should be "Repo Discovery" (or "Repository Discovery"?)
2. Selecting item and then "Create Selected" brings to page w/o breadcrumbs (says "Create Products" but no prior crumbs)
3. Toggle for create new or use existing product doesn't work (existing bug)
4. GPG Key dropdown box full of a list of "undefined" entries
5. js error when clicking "create" button. Should the create bring user to the product and repo or should it land back on the discovered listing? If I had discovered 20 repos and wanted to put into multiple products being able to go back (maybe just browser back button?) would be useful.

**Comment by waldenraines** [comment]
> js error when clicking

What is the error you're seeing?

**Comment by thomasmckay** [comment]
Two js errors:
Clicking the "Create" button on repo discovery: TypeError: Cannot read property 'addRow' of undefined
    at productCreateSuccess (bastion_katello.js:10751)

Clicking a repo in any product: Error: Could not resolve 'repository.details.info' from state 'product.repositories.index'

**Comment by waldenraines** [comment]
> Two js errors:
> Clicking the "Create" button on repo discovery: TypeError: Cannot read property 'addRow' of undefined
> at productCreateSuccess (bastion_katello.js:10751)
> 
> Clicking a repo in any product: Error: Could not resolve 'repository.details.info' from state 'product.repositories.index'

These have been fixed, thanks for finding them.

**Comment by thomasmckay** [comment]
APJ looks great!

**Comment by waldenraines** [comment]
@ehelms, @bbuckingham, @jlsherrill, @anyone-else any more comments?

**Comment by ehelms** [comment]
Can you update the gemspec to require at least Bastion 3.4.0? Also, I am guessing the commit message nd PR title do not reflect this PR anymore? Or are you planning to split out the individual 'top level' page changes to individual PRs for easier consumption?

**Comment by waldenraines** [comment]
> Can you update the gemspec to require at least Bastion 3.4.0?

Updated.

> Also, I am guessing the commit message nd PR title do not reflect this PR anymore? Or are you planning to split out the individual 'top level' page changes to individual PRs for easier consumption?

I'm still planning on tackling this one top level page at a time.

**Comment by ehelms** [comment]
@waldenraines so should I review only the products page in this PR? Since it sounds like you are going to split the other top level pages in the PR into their own PRs?

**Comment by waldenraines** [comment]
> @waldenraines so should I review only the products page in this PR? Since it sounds like you are going to split the other top level pages in the PR into their own PRs?

Correct, everything under the products page (repositories, discovery, bulk actions, etc.).  It would probably also be good to review the other pages briefly to make sure I didn't break anything.

**Comment by ehelms** [comment]
Items I see on the products/repositories (not all changes are required, just pointing out what I see for discussion):

 1) The cannot remove shows up greyed out with what appears to be a tooltip icon but no tool tip
 2) I remember talk of increasng the left/right padding and pages could benefit from a bigger increase
 3) The gap between breadcrumbs and the sub-header (e.g. when viewing the packages for repository 'Packages in Repository') feels too big
 4) When clicking 'Sync Now' on a repository, if it errors on the server no error appears in the UI
 5) The search box on the repository page bleeds over to the packages page; but returning to repositories list does not keep the search unless I use the back button
 6) On an index page, selected rows have a `>` next to them which makes less sense without the master-detail
 7) Bulk action only has 'Remove Sync Plan' option when no sync plans exist in the system with a blank box above the 'Remove Sync Plan' -- maybe it ought to have a create new sync plan option there
 8) What do you think about changing 'Update Sync Plan' to 'Change Sync Plan' ? I keep thinking I'm updating the actual sync plan itself.
 9) I feel like 'new' happens more often than 'remove'. What about swapping where they live?

**Comment by waldenraines** [comment]
> 1) The cannot remove shows up greyed out with what appears to be a tooltip icon but no tool tip

See http://projects.theforeman.org/issues/16925.

> 2) I remember talk of increasng the left/right padding and pages could benefit from a bigger increase

This will be handled as part of http://projects.theforeman.org/issues/17098.

> 3) The gap between breadcrumbs and the sub-header (e.g. when viewing the packages for repository 'Packages in Repository') feels too big

Agreed, will be removed as part of http://projects.theforeman.org/issues/17098.

> 4) When clicking 'Sync Now' on a repository, if it errors on the server no error appears in the UI

Fixed.

> 5) The search box on the repository page bleeds over to the packages page; but returning to repositories list does not keep the search unless I use the back button

Fixed the search term bleeding over.  See http://projects.theforeman.org/issues/17096 for remembering the search from the parent page.

> 6) On an index page, selected rows have a > next to them which makes less sense without the master-detail

Agreed, removed.

> 7) Bulk action only has 'Remove Sync Plan' option when no sync plans exist in the system with a blank box above the 'Remove Sync Plan' -- maybe it ought to have a create new sync plan option there

Agreed, fixed.

> 8) What do you think about changing 'Update Sync Plan' to 'Change Sync Plan' ? I keep thinking I'm updating the actual sync plan itself.

Agreed, done.

> 9) I feel like 'new' happens more often than 'remove'. What about swapping where they live?

You mean moving “new” to the bottom of the dropdown?  I put remove down there with a divider to make it clear it was a destructive action and to separate it from the other menu items so as to prevent accidental clicks.

**Comment by waldenraines** [comment]
Somewhat blocked by https://github.com/Katello/bastion/pull/136.

**Comment by waldenraines** [comment]
> 5) The search box on the repository page bleeds over to the packages page; but returning to repositories list does not keep the search unless I use the back button
> Fixed the search term bleeding over. See http://projects.theforeman.org/issues/17096 for remembering the search from the parent page.

Actually, I ended up opening a new PR for this issue as it should present itself in master too after the upgrade to UI router, see https://github.com/Katello/bastion/pull/137

**Comment by ehelms** [comment]
Point #9 -- the 'Remove' that is the bulk action on the index page. I think you were trying to put all bulk actions on that bar and all others in the dropdown. However, in terms of functionality and what each does, 'Remove' for products especially in bulk is not worth being so prominent IMO.

**Comment by waldenraines** [comment]
> Point #9 -- the 'Remove' that is the bulk action on the index page. I think you were trying to put all bulk actions on that bar and all others in the dropdown. However, in terms of functionality and what each does, 'Remove' for products especially in bulk is not worth being so prominent IMO.

Oh I see, so you want me to move it to the far right and have "Sync" and "Change Sync Plan" first?

**Comment by ehelms** [comment]
I'd rather see Remove in the dropdown menu. I realize as a developer its bulk actions vs other actions. But as a user, I am just seeing it as things I do most often should be most prominent.

**Comment by waldenraines** [comment]
> I'd rather see Remove in the dropdown menu. I realize as a developer its bulk actions vs other actions. But as a user, I am just seeing it as things I do most often should be most prominent.

It's not just as a developer, it's as a user.  To me, it makes no sense for an action applicable only to the table to be hidden in the dropdown that has item actions in it (as opposed to list actions).

**Comment by ehelms** [comment]
@waldenraines gmail does just that and I appreciate as a user that the actions I want to do most are prominent and additional items are hidden under a dropdown.

**Comment by waldenraines** [comment]
> @waldenraines gmail does just that and I appreciate as a user that the actions I want to do most are prominent and additional items are hidden under a dropdown.

Not really.  All of there actions in the drop down are related to the list of messages not an individual item.  What I don't like about this suggestion is that we are mixing the actions for two different objects into one menu.  I think it's pretty clear that the dropdown refers to the product and not the repositories but it won't be clear when we start adding bulk actions to this dropdown.

What if we added a more button dropdown next to the other buttons similar to how gmail does it?

screen shot 2016-10-27 at 9 55 23 am

**Comment by ehelms** [comment]
We can give that a try. In my personal use cases, I use the 'New' button the most out of anything. The fact that I have to click twice and remember where it is located is what sorta annoys me. I get the general idea of the design, however, I'm just trying to also throw in thoughts on real use. Normally I'd say lets go with whats there and change it, but since this is already something I'd want changed I'm bringing it up for further design thinking.

**Comment by waldenraines** [comment]
> We can give that a try. In my personal use cases, I use the 'New' button the most out of anything. The fact that I have to click twice and remember where it is located is what sorta annoys me. I get the general idea of the design, however, I'm just trying to also throw in thoughts on real use. 

Would a real user create multiple products/repositories regularly?  I feel like it's important for us to differentiate between a develop-on-katello use case and an actual user use case.

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
@ehelms and I discussed moving the items in the kebabs to the table for lists, I have done this with the latest push.

**Comment by thomasmckay** [comment]
still ack from me

**Comment by ehelms** [comment]
I am getting errors in the UI console when trying to change a sync plan or sync a product:

```
angular.self.js:13551 TypeError: Cannot read property 'getSelected' of undefined
    at Scope.$scope.getSelectedProductIds (products-bulk-action.controller.self.js:59)
    at Scope.$scope.syncProducts (products-bulk-action.controller.self.js:73)
    at fn (eval at compile (angular.self.js:1), <anonymous>:4:227)
    at expensiveCheckFn (angular.self.js:15486)
    at callback (angular.self.js:25019)
    at Scope.$eval (angular.self.js:17230)
    at Scope.$apply (angular.self.js:17330)
    at HTMLButtonElement.<anonymous> (angular.self.js:25024)
    at HTMLButtonElement.dispatch (eval at <anonymous> (bundle.js:65), <anonymous>:4670:9)
    at HTMLButtonElement.elemData.handle (eval at <anonymous> (bundle.js:65), <anonymous>:4338:28)
```

**Comment by waldenraines** [comment]
> I am getting errors in the UI console when trying to change a sync plan or sync a product:

Fixed.  Was caused by removing the redundant `$scope.productsTable = $scope.table` but forgetting to update usages.

**Comment by ehelms** [comment]
I now get this:

```
angular.self.js?body=1:13551 TypeError: _.pluck is not a function
    at Scope.$scope.getSelectedProductIds (products-bulk-action.controller.self.js?body=1:60)
    at Scope.$scope.updateSyncPlan (products-bulk-action.controller.self.js?body=1:83)
    at fn (eval at compile (angular.self.js?body=1:14433), <anonymous>:4:338)
    at expensiveCheckFn (angular.self.js?body=1:15486)
    at callback (angular.self.js?body=1:25019)
    at Scope.$eval (angular.self.js?body=1:17230)
    at Scope.$apply (angular.self.js?body=1:17330)
    at HTMLAnchorElement.<anonymous> (angular.self.js?body=1:25024)
    at HTMLAnchorElement.dispatch (eval at <anonymous> (bundle.js:65), <anonymous>:4670:9)
    at HTMLAnchorElement.elemData.handle (eval at <anonymous> (bundle.js:65), <anonymous>:4338:28)
```

**Comment by waldenraines** [comment]
> I now get this:
> 
> angular.self.js?body=1:13551 TypeError: _.pluck is not a function
>     at Scope.$scope.getSelectedProductIds (products-bulk-action.controller.self.js?body=1:60)
>     at Scope.$scope.updateSyncPlan (products-bulk-action.controller.self.js?body=1:83)
>     at fn (eval at compile (angular.self.js?body=1:14433), <anonymous>:4:338)
>     at expensiveCheckFn (angular.self.js?body=1:15486)
>     at callback (angular.self.js?body=1:25019)
>     at Scope.$eval (angular.self.js?body=1:17230)
>     at Scope.$apply (angular.self.js?body=1:17330)
>     at HTMLAnchorElement.<anonymous> (angular.self.js?body=1:25024)
>     at HTMLAnchorElement.dispatch (eval at <anonymous> (bundle.js:65), <anonymous>:4670:9)
>     at HTMLAnchorElement.elemData.handle (eval at <anonymous> (bundle.js:65), <anonymous>:4338:28)

You will see that until https://github.com/Katello/katello/pull/6375 is merged if you are using the latest bastion that includes the switch from underscore.js to lodash.js

**Comment by ehelms** [comment]
Sorry did I miss a design change? I went to create a new product and was taken to what I considered an unexpected page given it lacked context as to where I was currently.

screenshot from 2016-11-01 16-49-07

**Comment by waldenraines** [comment]
This now requires https://github.com/Katello/bastion/pull/136

**Comment by thomasmckay** [comment]
Issues:
+ remove product stayed on product page instead of returning to list (product was deleted successfully)

**Comment by waldenraines** [comment]
@thomasmckay fixed removal of product.

**Comment by Rohoover** [comment]
Feedback from the two-pane view survey. 

https://docs.google.com/a/redhat.com/presentation/d/1OKaYFk9CZV_72nQHDSAgOchHbRVF9JsYXfAky4P0_BA/edit?usp=sharing

**Comment by thomasmckay** [comment]
ack

**Comment by Rohoover** [comment]
@thomasmckay I should note the sample size is small. Also, I did talk to Walden last week about a solution that will work with what he already has.

**Comment by thomasmckay** [comment]
@Rohoover - I have been pestering @waldenraines on the topic of how the collapsed list is used, at least in my case.

Let's say I've searched for "red" content hosts and have found 15 of them. I select one, click auto-attach, the icon in the list goes green (even though it no longer matches the search, but that is completely understandable and actually a plus; I don't want it to disappear suddenly). I then click on the next host in the list and repeat process. At the end I have a list of 15 green hosts.

Now consider w/o the collapsed list as currently written: I search and get 15 red hosts. I select the first one, run auto-attach, then click the breadcrumb to return to main page. The main page _reloads_ all the entries. _Very_ painful in both loading time and that now I have 14 items listed (we could argue if the count change is good or bad but let's not right now).

Now, if instead of reloading when I select the root breadcrumb the previously list simply is unhidden (with the row details adjusted from red to green, which is how it works now so not really new code) then I have effectively the same user experience as the collapsed list in terms of efficiency.

**Comment by Rohoover** [comment]
@thomasmckay This attached wireframe is very basic and lacking the search/filter functionality but this is an interaction pattern I was mentioning to Walden that would still allow a user to quickly jump between items. Again, it's still under construction, but I believe will solve both use cases.

screen shot 2016-11-09 at 11 15 47 am

**Comment by thomasmckay** [comment]
@Rohoover - I get the idea, but you are with a page size of 50 it's going to be a bit awkward; more if you still have infinite scroll. I think having the root breadcrumb be an immediate page show (versus an api call to reload data) would be a big, big win in usefulness. The two ideas don't conflict so I'd say go for it. :)

**Comment by ehelms** [comment]
I feel like the survey focused largely on the left hand list, but did not give us as much of an indicator about one of the major issues we are trying to solve by removing it which is screen real estate especially on dense and busy page views such as most host/content host pages and content views.

**Comment by ehelms** [comment]
The following comments are not necessarily blockers for this PR, but things I htink should be addressed:

@waldenraines could we make the stoplight click box bigger? I was thinking either by enlarging the icon or having a bit of a clickable invisible field around it. 

The grey background on tables on details pages (e.g. the repositories table or packages table) seems unneeded to me and could just as easily be a white background to provide a feeling of more openness and screen real estate.

**Comment by waldenraines** [comment]
> The following comments are not necessarily blockers for this PR, but things I htink should be addressed:
> 
> @waldenraines could we make the stoplight click box bigger? I was thinking either by enlarging the icon or having a bit of a clickable invisible field around it.
> 
> The grey background on tables on details pages (e.g. the repositories table or packages table) seems unneeded to me and could just as easily be a white background to provide a feeling of more openness and screen real estate.

Do you mind if I file issues for these and fix them separately?

**Comment by ehelms** [comment]
@waldenraines +1

**Comment by ehelms** [comment]
ACK pending issues made

**Comment by waldenraines** [comment]
> ACK pending issues made

http://projects.theforeman.org/issues/17353

I need a screenshot for the other issue as I'm not 100% clear what you mean but I will open it once received.

**Pull request merged**
