### PR TITLE
Fixes #31353 - search button text i18n translation

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I don't think the translations work dynamically like that, but I have yet to get a definitive answer. I usually play it safe and translate the fixed strings. For this, you can translate the one [here](https://github.com/Katello/katello/blob/b8c73d768baed4d00b97cfd43997bb826a1a36a3/webpack/components/TypeAhead/pf3Search/TypeAheadSearch.js#L49) and the new one [here](https://github.com/Katello/katello/blob/b8c73d768baed4d00b97cfd43997bb826a1a36a3/webpack/components/TypeAhead/TypeAhead.js#L104) for good measure

**Comment by jjeffers** [comment]
> I don't think the translations work dynamically like that, but I have yet to get a definitive answer. I usually play it safe and translate the fixed strings. For this, you can translate the one [here](https://github.com/Katello/katello/blob/b8c73d768baed4d00b97cfd43997bb826a1a36a3/webpack/components/TypeAhead/pf3Search/TypeAheadSearch.js#L49) and the new one [here](https://github.com/Katello/katello/blob/b8c73d768baed4d00b97cfd43997bb826a1a36a3/webpack/components/TypeAhead/TypeAhead.js#L104) for good measure

Ah! Thank you, I will update the fixed strings instead.

**Comment by johnpmitsch** [comment]
@jjeffers not sure why github actions didn't run, but the linter will probably complain that the `foremanReact` import needs to be above the relative imports (move them to the 1st block of imports), can you double check this with `npm run lint` in the katello dir?

**Comment by jjeffers** [comment]
> can you double check this with `npm run lint` in the katello dir?

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/rh/rh-nodejs12/root/usr/bin/node',
1 verbose cli   '/opt/rh/rh-nodejs12/root/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle katello@1.0.0~prelint: katello@1.0.0
6 info lifecycle katello@1.0.0~lint: katello@1.0.0
7 verbose lifecycle katello@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle katello@1.0.0~lint: PATH: /opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/vagrant/projects/katello/node_modules/.bin:/opt/rh/rh-ruby25/root/usr/local/bin:/opt/rh/rh-ruby25/root/usr/bin:/opt/rh/rh-postgresql12/root/usr/bin:/opt/rh/rh-nodejs12/root/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.gem/ruby/bin:/opt/puppetlabs/bin:/home/vagrant/.local/bin:/home/vagrant/bin
9 verbose lifecycle katello@1.0.0~lint: CWD: /home/vagrant/projects/katello
10 silly lifecycle katello@1.0.0~lint: Args: [ '-c', 'npx eslint webpack/' ]
11 silly lifecycle katello@1.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle katello@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: katello@1.0.0 lint: `npx eslint webpack/`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid katello@1.0.0
15 verbose cwd /home/vagrant/projects/katello
16 verbose Linux 3.10.0-1160.11.1.el7.x86_64
17 verbose argv "/opt/rh/rh-nodejs12/root/usr/bin/node" "/opt/rh/rh-nodejs12/root/usr/bin/npm" "run" "lint"
18 verbose node v12.19.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error katello@1.0.0 lint: `npx eslint webpack/`
22 error Exit status 1
23 error Failed at the katello@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by johnpmitsch** [comment]
@jjeffers that same change needs to be made in the other file:
```
[vagrant@centos7-katello-devel-stable katello{(pr9116)}]$ npm run lint

> katello@1.0.0 lint /home/vagrant/katello
> npx eslint webpack/


/home/vagrant/katello/webpack/components/TypeAhead/pf3Search/TypeAheadSearch.js
  9:33  error  Absolute imports should come before relative imports  import/first
```

**Comment by johnpmitsch** [comment]
@jjeffers I see this is opened on the 3.18 branch, is this a change meant only for that release?

**Comment by jjeffers** [comment]
> @jjeffers I see this is opened on the 3.18 branch, is this a change meant only for that release?

The redmine issue indicated a target version of 3.18.x, so as far as I know just for that version.

**Comment by johnpmitsch** [comment]
> The redmine issue indicated a target version of 3.18.x, so as far as I know just for that version.

I see it's an issue in master, so it wouldn't stay fixed in any future release. Usually a fix is opened and merged in master and then cherry-picked into the release branch. If there's nothing I'm missing, we should do it that way, but let me know if I'm missing some context!

**Pull request closed without merging**
