### PR TITLE
Fixes #13396 - Update the zanata mapping files

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by ehelms** [comment]
Might as well update https://github.com/Katello/katello/blob/master/locale/zanata.xml in this PR.

**Comment by bkearney** [comment]
@ehelms thanks.. I forgot to add that. I have pushed that and a gitignore change to clean up the code base.

**Comment by cpeters** [comment]
LGTM

**Comment by jlsherrill** [comment]
ACK from me, merging thanks @bkearney

**Pull request merged**
