### PR TITLE
Fixes #28677 - Use correct distributor on publish

### PR DESCRIPTION
**Pull request by parthaa**
Prior to this commit the yum clone distributor associated to the
metadata generation did not take cognizance of the source_repository
option during the distributor publish operation.
This commit fixes that by correctly making use of the source_repository
option and chooses the correct values for the distributor publish.

### CODE REVIEW

**Comment by jjeffers** [comment]
@parthaa was there a particular repository you'd recommend generate a substantial difference in the amount of time pre/post PR in the publication step?

**Comment by parthaa** [comment]
How to test this PR
* Check out PR
* Create and Sync repo pointing to a yum repo
* Add to Content View and Publish
* Check out master
* Publish cv again
* Now compare the dynflow action for the 2 Publishes in the dynflow console. 
* In the dynflow console, click on ```15: Actions::Pulp::Repository::DistributorPublish```. Look for distributor_id
On master you would see a value like -> ```1-$CV_NAME-v3_0-78e916ba-3e36-44cf-9c18-735325478a93```
On the PR you would see a value like -> ```1-$CV_NAME=v2_0-78e916ba-3e36-44cf-9c18-735325478a93_clone``` (ends with a _clone signifying the cloned repo as the source)
* Also compare the timings of the Distributor Publish for the 2 publish tasks. You should see a better performance with the PR.

As far as repos are concerned, you should be able to notice better performance with either
* Pulp - https://repos.fedorapeople.org/repos/pulp/pulp/stable/2.20/7Server/x86_64/ - For a reasonable sized
* Centos - http://mirror.linux.duke.edu/pub/centos/8/AppStream/x86_64/os  - For a large repo

**Comment by jjeffers** [comment]
Tested this pre/post PR and worked as advertised. Verified the `distributor_id` was changed as well as indicated.

There was an improvement in task completion time given the repositories I tested, as well.

@parthaa Are there any practical tests that can be added for this change?

**Comment by parthaa** [comment]
> @parthaa Are there any practical tests that can be added for this change?

I was thinking about adding some unit tests. Just to test that distributors_to_publish method returns the right thing. Will add em  in a few

**Comment by parthaa** [comment]
[test katello]

**Pull request merged**
