### PR TITLE
Fixes #22981 - Not able to attach a subscription to a host with hammer

### PR DESCRIPTION
**Pull request by anandkumaragrawal**
Converting string to number in API will resolve the issue from both API and hammer

### CODE REVIEW

**Comment by jlsherrill** [comment]
@anandkumaragrawal notice the commit message is too longer an hound/rubocop error

**Comment by anandkumaragrawal** [comment]
@jlsherrill I have made the changes in the commit message and fixed the rubocop error. Please have a look

**Comment by sjha4** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
