### PR TITLE
Fixes #15288 - Add coverage to Katello

### PR DESCRIPTION
**Pull request by akofink**
@daviddavis was interested

We may need to do a bit of Jenkins config to get the report to show in the UI.

### CODE REVIEW

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Comment by akofink** [comment]
@daviddavis I think it needed a rebase.

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
ACK

**Comment by daviddavis** [comment]
Looks good!

http://ci.theforeman.org/job/test_katello_pr_core/2908/database=postgresql,ruby=2.2/rcov/

**Pull request merged**
