### PR TITLE
Fixes #13289 - Remove backup and restore scripts

### PR DESCRIPTION
**Pull request by dLobatog**
The backup.sh script is still trying to backup elasticsearch when it's not needed

### CODE REVIEW

**Comment by stbenjam** [comment]
I don't think this is used anymore, it should be this one
https://github.com/Katello/katello-packaging/blob/master/katello/katello-backup

**Comment by dLobatog** [comment]
Ah, elasticsearch is not there anymore. I can remove this whole script if you want? I found this 'bug' after using this script on the katello-deploy *-devel machines.

**Comment by stbenjam** [comment]
Yea, this and restore.sh can probably also go.  I wonder how much stuff is out of date here in the scripts directory, maybe other things could too but I'm not sure.

**Comment by ehelms** [comment]
:+1: scrap them both

**Comment by dLobatog** [comment]
Updated, thanks!

**Comment by stbenjam** [comment]
Looks good to me, APJ

**Comment by stbenjam** [comment]
Thanks @dLobatog!

**Pull request merged**
