### PR TITLE
Fix Style Cops

### PR DESCRIPTION
**Pull request by archanaserver**
#### What are the changes introduced in this pull request?
https://github.com/Katello/katello/pull/11009
This pull request addresses several style issues in the codebase and updates the .rubocop.yml configuration file to better manage RuboCop offenses. 

#### Considerations taken when implementing this change?
Check commits for details

#### What are the testing steps for this pull request?
bundle exec rubocop

### CODE REVIEW

**Review by qcjames53 — APPROVED** [review]
Hey Archana! Your PR looks great to me, I'm going to ACK. Quick question: It looks like there are some conflicts with the branch, would you like me to take care of those when we squash and merge or would you rather rebase and re-push first?

**Comment by archanaserver** [comment]
> Hey Archana! Your PR looks great to me, I'm going to ACK. Quick question: It looks like there are some conflicts with the branch, would you like me to take care of those when we squash and merge or would you rather rebase and re-push first?

@qcjames53 i just rebased it!

**Comment by ianballou** [comment]
@archanaserver looks like we need another rebase because I merged a bunch of your PRs :)

**Comment by archanaserver** [comment]
> @archanaserver looks like we need another rebase because I merged a bunch of your PRs :)

thanks @ianballou , and rebased it again!

**Pull request merged**
