### PR TITLE
Fixes #27367 - custom repo default download policy immediate

### PR DESCRIPTION
**Pull request by jlsherrill**
This PR, separates the default download policy for custom repos and for redhat repos, and sets the default for redhat repos to 'on_demand', but custom repos to immediate.

### CODE REVIEW

**Comment by ianballou** [comment]
Should we add some kind of warning for people who decide to choose on demand for their custom repos? I feel like people might still try to change it to on demand because it seems better on the surface.

**Comment by jlsherrill** [comment]
@ianballou  added some to the help text

**Comment by parthaa** [comment]
can you add a test if its not a lot of work..

**Comment by jlsherrill** [comment]
@parthaa added

**Pull request merged**
