### PR TITLE
[CP] Katello 4.0 GA Cherry-picks, version update, CHANGELOG update, translation updates

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by jjeffers** [comment]
[test katello]

**Review by jturel — APPROVED** [review]
I took a look at the tool belt config to make sure the expected priors are there. So if this collection of picks reflects those then ACK from me!

**Comment by jlsherrill** [comment]
there's a slew of cherry picks in here that aren't needed and are only intended for 3.18, i think removing those should help.  Here are the 3 which SHOULD be cherry picked:

Fixes #32110,#31905 - adjust task group error check
Fixes #32230 - fix SPC sync with pulp2 for container
Fixes #31867 - updates references to content to /pulp/content

one rule of thumb is if the change only went into the 3.18 branch, it doesn't need to be cherry picked to 4.0.  (if it went into master, it does)

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
```
[2021-04-14T09:29:19.946Z] Using /usr/local/rvm/gems/ruby-2.5.1 with gemset katello-pr-test-6740-1

[2021-04-14T09:29:20.227Z] /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.1.2) required by your /home/jenkins/workspace/katello-pr-test/foreman/Gemfile.lock. (Gem::GemNotFoundException)

[2021-04-14T09:29:20.227Z] To update to the latest version installed on your system, run `bundle update --bundler`.

[2021-04-14T09:29:20.227Z] To install the missing version, run `gem install bundler:2.1.2`

[2021-04-14T09:29:20.227Z] 	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'

[2021-04-14T09:29:20.227Z] 	from /usr/local/rvm/gems/ruby-2.5.1@katello-pr-test-6740-1/bin/bundle:23:in `<main>'

[2021-04-14T09:29:20.227Z] 	from /usr/local/rvm/gems/ruby-2.5.1@katello-pr-test-6740-1/bin/ruby_executable_hooks:24:in `eval'

[2021-04-14T09:29:20.227Z] 	from /usr/local/rvm/gems/ruby-2.5.1@katello-pr-test-6740-1/bin/ruby_executable_hooks:24:in `<main>'

script returned exit code 1
```

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
[test katello]

**Comment by jjeffers** [comment]
@jturel @jlsherrill Updated and pushed a Katello config change to reflect the final 2 CPs. This should be the final iteration for 4.0 GA.

**Review by jlsherrill — APPROVED** [review]

**Comment by jturel** [comment]
My ACK stands!

**Pull request merged**
