### PR TITLE
Fixes #13653: Allow creation of custom file type repositories

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by jlsherrill** [comment]
I get this error when trying to create a file repo:
    RuntimeError: A validation error occurred.

**Comment by jlsherrill** [comment]
Pulp is throwing a traceback:
```
pulp.server.controllers.repository:ERROR: (6222-64928) Exception adding importer to repo [test-smallrepo-file]; the repo will be deleted
pulp.server.controllers.repository:ERROR: (6222-64928) Traceback (most recent call last):
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/pulp/server/controllers/repository.py", line 410, in create_re

pulp.server.controllers.repository:ERROR: (6222-64928)     importer_controller.set_importer(repo_id, importer_type_id, importer_repo_plugin_config)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/celery/local.py", line 167, in <lambda>
pulp.server.controllers.repository:ERROR: (6222-64928)     __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/pulp/server/async/tasks.py", line 473, in __call__
pulp.server.controllers.repository:ERROR: (6222-64928)     return super(Task, self).__call__(*args, **kwargs)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/pulp/server/async/tasks.py", line 103, in __call__
pulp.server.controllers.repository:ERROR: (6222-64928)     return super(PulpTask, self).__call__(*args, **kwargs)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
pulp.server.controllers.repository:ERROR: (6222-64928)     return self.run(*args, **kwargs)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/pulp/server/controllers/importer.py", line 72, in set_importer
pulp.server.controllers.repository:ERROR: (6222-64928)     validate_importer_config(repo.repo_id, importer_type_id, repo_plugin_config)
pulp.server.controllers.repository:ERROR: (6222-64928)   File "/usr/lib/python2.7/site-packages/pulp/server/controllers/importer.py", line 160, in validate_im

pulp.server.controllers.repository:ERROR: (6222-64928)     raise exceptions.PulpCodedValidationException(validation_errors=message)
pulp.server.controllers.repository:ERROR: (6222-64928) PulpCodedValidationException: A validation error occurred.
py.warnings:WARNING: (6222-64928) /usr/lib/python2.7/site-packages/mongoengine/queryset/base.py:420: DeprecationWarning: remove is deprecated. Use delete_one 

py.warnings:WARNING: (6222-64928)   result = queryset._collection.remove(queryset._query, **write_concern)
py.warnings:WARNING: (6222-64928)
pulp.server.webservices.middleware.exception:INFO: A validation error occurred.
```

**Comment by jlsherrill** [comment]
Here's the rest call:

```
 RestClient.post "https://hackme.usersys.redhat.com/pulp/api/v2/repositories/", "{\"id\":\"test-smallrepo
-file\",\"display_name\":\"file\",\"importer_type_id\":\"iso_importer\",\"importer_config\":{\"feed\":null,\"ssl_ca_cert\":null,\"ssl_client_cert\":null,\"ssl_client_key\":null},\"distributors\":[{\"distributor_type_id\":\"iso_distributor\",\"distributor_config\":{\"serve_http\":true,\"serve_https\":true},\"auto_publish\":true,\"distributor_id\":\"1017cef093195e00681d\"}]}", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"359", "accept"=>"application/json", "content_type"=>"application/json"

```

**Comment by jlsherrill** [comment]
I debugged a bit and apparently it does not work with blank feeds.  I would file a bug on that.

**Comment by jlsherrill** [comment]
on the repository details page i don't see a count of units, but i do see the heading 'content units'.  

There also isn't any way to remove units from the repository.  I'm not necessarily saying its required in this PR, but i think needs to probably be added before it hit users.

**Comment by jlsherrill** [comment]
Other than that comment, everything seems to work well.  Even tested capsule syncing and it was fine.  Please to rebase and i'll glance over it again.  We can also discuss about the unit removal.

**Comment by ehelms** [comment]
How serious is the error about the repo being deleted? Would that mean
upload repos won't work until that is fixed?

**Comment by jlsherrill** [comment]
That error was the result of trying to create a file repo without a feed URL, was just me trying to provide information and debug the issue.

**Comment by ehelms** [comment]
I created a repository without a feed when testing, had no issues. Re-tested it again and still had no issues and saw no errors that you did. How recent is your devel setup? I am using:

```
pulp-server-2.8.0-0.4.beta.el7.noarch
```

**Comment by jlsherrill** [comment]
I'm on a nightly:  pulp-server-2.8.0-0.5.beta.git.59.f7eb659.el7.noarch
but i also saw this on 2.6:  pulp-server-2.6.4-1.el7.noarch  Same exact
error that goes away if i provide a feed url

I can't imagine the same bug was fixed and reintroduced in a later release,
so it must be something environmental.  Maybe we should get up with the
pulp team tomorrow to figure it out?

**Comment by jlsherrill** [comment]
So this error seems fixed in pulp-server-2.8.0-0.5.beta.git.125.1d7e5c5.el7.noarch

**Comment by ehelms** [comment]
Updated to remove content counts as part of this initial change, as well updated the upload section to properly indicate what to upload.

Show counts: http://projects.theforeman.org/issues/13815
list/remove content: http://projects.theforeman.org/issues/13816

**Comment by jlsherrill** [comment]
ACK

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
