### PR TITLE
fixes #10735 - remove default and custom info

### PR DESCRIPTION
**Pull request by stbenjam**
The org default_info hash is initialized by the after_initialize callback,
however confusingly after_initalize also happens when the object is
[instantiated by a finder](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html) (Model.find...).

initialize_default_info should happen from the before_validation callback
instead.

### CODE REVIEW

**Comment by ehelms** [comment]
I was trying to look at the Redmine issue to see what the traceback that the default info callback causes but wasn't seeing it. Could you point me at it?

**Comment by jlsherrill** [comment]
Makes sense to me, but would be nice to see the traceback as ehelms said

**Comment by stbenjam** [comment]
```ruby
irb(main):003:0> Host::Managed.complete_for("organization = ")
2015-06-10 14:55:03 [D]   Organization Load (0.9ms)  SELECT DISTINCT "taxonomies"."title" FROM "taxonomies" WHERE "taxonomies"."type" IN ('Organization') ORDER BY "taxonomies"."title" LIMIT 20
ActiveModel::MissingAttributeError: missing attribute: default_info
	from /opt/rh/ruby193/root/usr/share/gems/gems/katello-2.2.0.46/app/models/katello/concerns/organization_extensions.rb:163:in `initialize_default_info'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `_run__3021705694797225020__initialize__4238915344773198177__callbacks'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:405:in `__run_callback'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:385:in `_run_initialize_callbacks'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/base.rb:524:in `init_with'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/inheritance.rb:68:in `instantiate'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/querying.rb:38:in `block (2 levels) in find_by_sql'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/querying.rb:38:in `collect!'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/querying.rb:38:in `block in find_by_sql'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/explain.rb:40:in `logging_query_plan'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/querying.rb:37:in `find_by_sql'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/relation.rb:171:in `exec_queries'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/relation.rb:160:in `block in to_a'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/explain.rb:40:in `logging_query_plan'
	from /opt/rh/ruby193/root/usr/share/gems/gems/activerecord-3.2.8/lib/active_record/relation.rb:159:in `to_a'
... 16 levels...
	from /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `each'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:200:in `execute'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:158:in `block in invoke_with_call_chain'
	from /opt/rh/ruby193/root/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:151:in `invoke_with_call_chain'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/task.rb:144:in `invoke'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:116:in `invoke_task'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block (2 levels) in top_level'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `each'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:94:in `block in top_level'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:88:in `top_level'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:66:in `block in run'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:133:in `standard_exception_handling'
	from /opt/rh/ruby193/root/usr/share/ruby/rake/application.rb:63:in `run'
	from /opt/rh/ruby193/root/usr/bin/rake:32:in `<main>'irb(main):004:0> 
```

**Comment by stbenjam** [comment]
I'd rather just pull out all this legacy code if we don't need it, changing the callback clearly has other ramifications.

Although why is there all this weird after_initialization magic to begin with? It was added during enginficiation so it's hard to track down the reason as those commits are so large.  A default value in the DB schema seems less troublesome than this init method?

**Comment by jlsherrill** [comment]
I don't think we need default_info any more,  @komidore64  @thomasmckay ?

**Comment by komidore64** [comment]
remove `default_info` and `custom_info`.

**Comment by thomasmckay** [comment]
custom info is legacy and not supported (or exposed, hopefully) in current tooling

**Comment by stbenjam** [comment]
Thanks, that's great! I'll try my hand at removing it.  It does look exposed through the API, though.  Hopefully no one is using it as a dumb data store or something.

**Comment by ehelms** [comment]
You will still find it on the content host details page as that is where users can add things. Whether anyone actually uses it though, remains to be seen.

**Comment by ehelms** [comment]
We should ask ourselves if should have a deprecation cycle for this or bump the major version of Katello if we are pulling this out since it involves removing an API.

**Comment by stbenjam** [comment]
Can you add custom info in the UI? It just says "You don't have any custom information, add some above" for me, although I don't know where above is.

I do agree it's there for use, and certainly someone, somewhere has seen this and stored something there.

With the idea of merging Content Hosts and Hosts, I think we could eliminate this data and we could store it as parameters on the Foreman host object.

**Comment by ehelms** [comment]
Looks like at some point, the edit controls were hidden in the UI without meaning to.

**Comment by ehelms** [comment]
After some digging, looks like my memory reaches too far back. Prior to the 2.0 release we killed off the V1 API which included custom_info thus breaking any ability to interact with it. The UI piece on the content host has remained ever since, but it reaches out to a non-existent API. Thus, since we actually haven't exposed this since the 2.0 release, I rescind my comment about needing to do a major bump.

**Comment by ehelms** [comment]
Looks like you missed removing `engines/bastion_katello/app/assets/javascripts/bastion_katello/custom-info` folder as a whole.

**Comment by stbenjam** [comment]
Ah good catch, I missed the dashed version.

**Comment by ehelms** [comment]
APJ

**Pull request merged**
