### PR TITLE
fixes #14259 - just make one method call, rather than 13

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by ehelms** [comment]
This looks good to me, can you fix the commit message please?

**Comment by komidore64** [comment]
oops, sorry about that.

**Comment by komidore64** [comment]
I recorded some improvements.

These numbers were recorded on a development installation with 7-10 RH products enabled each with one repo enabled and sync'd, along with 10 custom products. I hit the products index api endpoint 100 times and then averaged the execution time.

Before this patch:

```
$ for i in $( seq 1 100); do /usr/bin/time --output product.index.out --append --format "%E" curl -sk -u admin:changeme 'https://perfbox/katello/api/v2/products
?enabled=true&organization_id=3&page=1&paged=true&search=&sort_by=name&sort_order=ASC' >/dev/null; done                                                                        
$ vim product.index.out # needed a small hand edit for awk to do proper math
$ awk '{sum+=$1}END{print sum/NR}' product.index.out 
17.968
```

After this patch:

```
$ for i in $( seq 1 101); do /usr/bin/time --output optimized.product.index.out --append --format "%E" curl -sk -u admin:changeme 'https://perfbox/katello/api/v
2/products?enabled=true&organization_id=3&page=1&paged=true&search=&sort_by=name&sort_order=ASC' >/dev/null; done                                                              
$ vim optimized.product.index.out # needed a small hand edit for awk to do proper math
$ awk '{sum+=$1}END{print sum/NR}' optimized.product.index.out
5.56545
```

**Comment by komidore64** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
