### PR TITLE
Fixes #16344 - Show error when content is too big

### PR DESCRIPTION
**Pull request by daviddavis**
When you upload a file that's too big, you currently don't get an error message. This fixes that and properly shows an error message.

Requires https://github.com/Katello/bastion/pull/124

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Comment by daviddavis** [comment]
[test]

**Comment by jlsherrill** [comment]
I love log files too @daviddavis but they more belong in Catello/catello

**Comment by daviddavis** [comment]
Ha good catch 🐱

**Comment by jlsherrill** [comment]
APJ

**Pull request merged**
