### PR TITLE
i18n - pulling from tx

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@sjha4 how does this look?

**Review by sjha4 — APPROVED** [review]

**Comment by sjha4** [comment]
You can add an issue to update translations on master if you want..

**Comment by chris1984** [comment]
> You can add an issue to update translations on master if you want..

Will make an issue and update the pr to get the redmine test green

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Pull request merged**
