### PR TITLE
Fixes #37569 - "Upload profile - Katello Script Default" doesn't work for SLES

### PR DESCRIPTION
**Pull request by USunyaev**
the condition under which the update package upload for SLES has been added

<% elsif @host.operatingsystem.family == 'Suse' -%> 
katello-package-upload --force

### CODE REVIEW

**Comment by sbernhard** [comment]
Please open an issue first at https://projects.theforeman.org/ and reference this issue id in the commit message. Have a look at previous pull requests.

**Review by sbernhard — APPROVED** [review]

**Comment by sbernhard** [comment]
@jeremylenz I thought I would be able to approve so that the github workflow actions will start but this isn't the case. Can you start the process, please?

**Comment by jeremylenz** [comment]
tests running now :+1:

**Review by ianballou — APPROVED** [review]
Looks fine! Just want to see the other tests go green.

**Comment by ianballou** [comment]
Actually @USunyaev mind rebasing? I think you're missing some test fixes we made a few days ago.

**Pull request closed without merging**
