### PR TITLE
Fixes #11448: Removes haml in favor of ERB.

### PR DESCRIPTION
**Pull request by ehelms**
The number of views previously written in HAML from the days when
Katello was an application has dwindled and the haml-rails dependency
carries with it a number of unneeded dependencies.

### CODE REVIEW

**Comment by ehelms** [comment]
Relies on this conversion first: https://github.com/Katello/katello/pull/5383

**Comment by ehelms** [comment]
Also note that this will block the SCL packaging work for Katello bits as I would like to resolve this instead of having to package and deal with upgrading it.

**Comment by ehelms** [comment]
Rebased and updated after merging the content dashboard migration PR. If someone could find time to review, that would be much appreciated so I can continue SCL work.

**Comment by jlsherrill** [comment]
Few issues i noted:

* Note seeing browser titles on the old pages
* On the redhat repos page the alternating row colors is gone

**Comment by ehelms** [comment]
Good finds, those should both be fixed.

**Comment by jlsherrill** [comment]
APJ   bye bye haml!


 sad

**Comment by waldenraines** [comment]
Hah, I'll be glad when we get rid of erb too.

**Pull request merged**
