### PR TITLE
[CP] 3.17.2 Cherrypicks

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Review by jjeffers — APPROVED** [review]
APJ

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
@jlsherrill do you know why this is failing? I pulled in all 3 cherrypicks for this guy https://projects.theforeman.org/issues/31725

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
[test katello]

**Pull request closed without merging**
