### PR TITLE
Generate package-lock and run npm ci separately for react UI tests

### PR DESCRIPTION
**Pull request by ehelms**
This is just an idea to get better granular data on the time each step takes for tests to later inform ways we might speed up tests. I do not think this should increase test runtime (and locally it had small improvements).

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
Makes sense, ACK

**Comment by ehelms** [comment]
[test katello]

**Comment by ehelms** [comment]
30 minute run of the Katello Jenkins tests! @evgeni smooookkinnnnn

**Comment by evgeni** [comment]
I've been called worse things!

😽

**Pull request merged**
