### PR TITLE
Fixes #31967 - treat background as immediate

### PR DESCRIPTION
**Pull request by jlsherrill**
for pulp3

### CODE REVIEW

**Comment by jlsherrill** [comment]
note i'm still spinning up a 3.18 to test this

**Comment by jlsherrill** [comment]
This is ready for testing.  It treats background policy as immediate.  Upon upgrade to 4.0 the background policy will be removed.  To properly hide the background policy option when pulp3 is enabled is a bit too much for 3.18 at this point IMO

**Review by jjeffers — APPROVED** [review]
Tested this pre- and post- patched on 3.18 production  - worked like a champ.

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
