### PR TITLE
Fixes #19958 - fix package actions in UI

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
The perform button blends in with the rest of the dropdown and the entry box due to its gray color, meanwhile the 'Update All Packages' button is bright blue to indicate its the primary action. IMO I think we should make either both blue or swap the coloring to prevent an update all when a user mean to run a single action since its draws attention to itself. @jlsherrill @waldenraines thoughts?

**Comment by jlsherrill** [comment]
@ehelms i agree, but it seems out of the scope of this issue?

**Comment by waldenraines** [comment]
> The perform button blends in with the rest of the dropdown and the entry box due to its gray color, meanwhile the 'Update All Packages' button is bright blue to indicate its the primary action. IMO I think we should make either both blue or swap the coloring to prevent an update all when a user mean to run a single action since its draws attention to itself. @jlsherrill @waldenraines thoughts?

Generally speaking whatever the primary action on the page is should be blue (i.e. `.btn-primary`) and everything else should be `.btn-default`.  If we have multiple primary actions within one form/page then we may have designed things incorrectly.

In this case I think "Upgrade selected" is the primary action here and "upgrade all packages" should be grey.

**Comment by jlsherrill** [comment]
updated!

**Pull request merged**
