### PR TITLE
Fix Style/SoleNestedConditional cop

### PR DESCRIPTION
**Pull request by archanaserver**
#### What are the changes introduced in this pull request?

https://github.com/Katello/katello/pull/11009
This pull request addresses the Style/SoleNestedConditional RuboCop offense by refactoring conditional logic in the codebase.

https://docs.rubocop.org/rubocop/cops_style.html#stylesolenestedconditional

#### Considerations taken when implementing this change?
Refactored nested conditionals.

#### What are the testing steps for this pull request?
bundle exec rubocop

### CODE REVIEW

**Review by ianballou — COMMENTED** [review]
Looks like there are some indentation issues.

**Comment by archanaserver** [comment]
> Looks like there are some indentation issues.

Fixed it!

**Review by ianballou — APPROVED** [review]
Looking great to me. I'm just going to re-run the one failing test because it was halted.

**Comment by ianballou** [comment]
@archanaserver thanks!

**Pull request merged**
