### PR TITLE
fixes #12605 - adapt host page deface to new inherit syntax

### PR DESCRIPTION
**Pull request by jlsherrill**
which allows for puppet environment to be inherited

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note: this fix is just for 2.4.  The fix for master will need to be developed separately

**Comment by jlsherrill** [comment]
Issue for fixing in master:  http://projects.theforeman.org/issues/12899

**Comment by jlsherrill** [comment]
Test run against 1.10:  http://ci.theforeman.org/job/test_katello_pull_request/7931/

**Comment by ehelms** [comment]
ACK

**Pull request merged**
