### PR TITLE
Fixes #36861 - fix username and password definition into request_params

### PR DESCRIPTION
**Pull request by jpasqualetto**
#### What are the changes introduced in this pull request?

username and password should not be inside headers

#### What are the testing steps for this pull request?

- To properly test this a private container registry, using API v2 is necessary. 
- Having the registry url and credentials, try discovering the repositories available on such registry
- no authentication errors are to be expected

### CODE REVIEW

**Comment by chris1984** [comment]
@jpasqualetto do you have a registry I can test with?

**Comment by jpasqualetto** [comment]
> @jpasqualetto do you have a registry I can test with?

I shared the credentials to the registry privately ;-)

**Review by chris1984 — COMMENTED** [review]
Code looks fine, starting to test and figure out how to fix the unit tests

**Comment by chris1984** [comment]
PR works great, was able to quickly see the Azure registry, working on fixing the tests now

**Comment by chris1984** [comment]
[test katello]

**Comment by chris1984** [comment]
Tests pass locally for me, so going to rekick jenkins
```bash
[vagrant@centos8-katello-devel foreman]$ ktest ../katello/test/models/concerns/smart_proxy_extensions_test.rb 
------------
 
(1 row)

Emptying /home/vagrant/foreman/jenkins/reports/unit
-- execute("SET CONSTRAINTS ALL DEFERRED;")
WARNING:  SET CONSTRAINTS can only be used in transaction blocks
   -> 0.0007s

# Running tests with run options --seed 28914:

.................Mocha deprecation warning at /home/vagrant/katello/app/models/katello/concerns/smart_proxy_extensions.rb:178:in `update_container_repo_list': Expectation defined at /home/vagrant/katello/test/models/concerns/smart_proxy_extensions_test.rb:251:in `test_sync_container_gateway' expected keyword arguments (:repositories => [{:repository => "empty_organization-puppet_product-busybox", :auth_required => true}, {:repository => "busybox", :auth_required => true}]), but received positional hash ({:repositories => [{:repository => "empty_organization-puppet_product-busybox", :auth_required => true}, {:repository => "busybox", :auth_required => true}]}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=.
.....Writing XML reports to /home/vagrant/foreman/jenkins/reports/unit


Finished tests in 4.182962s, 5.2594 tests/s, 14.1048 assertions/s.


22 tests, 59 assertions, 0 failures, 0 errors, 0 skips

Minitest Reporters: Mean Time Report (Samples: 1, Order: :avg :desc)
Avg: 2.561133768  Min: 2.561133768  Max: 2.561133768  Last: 2.561133768  Description: Katello::SmartProxyPulp3Test
Avg: 1.619509329  Min: 1.619509329  Max: 1.619509329  Last: 1.619509329  Description: Katello::SmartProxyExtensionsTest
Coverage report Rcov style generated for Unit Tests to /home/vagrant/foreman/coverage/rcov
Coverage report generated for Unit Tests to /home/vagrant/foreman/coverage. 0 / 0 LOC (100.0%) covered.

[vagrant@centos8-katello-devel katello]$ git grep 'test_sync_container_gateway'
test/models/concerns/smart_proxy_extensions_test.rb:    def test_sync_container_gateway
```

**Review by chris1984 — APPROVED** [review]
Thanks @jpasqualetto

**Pull request merged**
