### PR TITLE
[CP] Fixes #31162 - Add a Slot to manage manifest modal

### PR DESCRIPTION
**Pull request by laviro**
(cherry picked from commit 25b42acc432a6b68501545cffdd5c2315fd27aaa)

cc @johnpmitsch @ShimShtein

### CODE REVIEW

**Comment by laviro** [comment]
Test error doesn't look related

**Comment by laviro** [comment]
@jturel can we make this cherry-pick part of the katello 3.18 release?
tested and it works well with https://github.com/theforeman/foreman_rh_cloud/pull/399

**Comment by jturel** [comment]
> @jturel can we make this cherry-pick part of the katello 3.18 release?
> tested and it works well with [theforeman/foreman_rh_cloud#399](https://github.com/theforeman/foreman_rh_cloud/pull/399)

For sure! It's already triaged to 3.18 which means it'll be in the next RC (RC2), but it never hurts to ask.

**Comment by jturel** [comment]
Oh I didn't realize this PR is a cherry-pick. Lol. Thanks @laviro

**Pull request merged**
