### PR TITLE
Cherry picks Katello 2.3 RC3

### PR DESCRIPTION
**Pull request by stbenjam**
I think there's enough bugs being fixed since RC2 that I'll do a small RC3 on Monday, which would most likely become the GA release for Thursday or Friday.

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by stbenjam** [comment]
@ehelms Thanks, one more CP - also yoinked https://github.com/Katello/katello/pull/5410

**Comment by ehelms** [comment]
I am going to push out 2.2.3 today -- have you checked to make sure the two issues there are included in the 2.3 branch?

**Comment by stbenjam** [comment]
I have now, thanks

**Comment by ehelms** [comment]
ACK

**Pull request merged**
