### PR TITLE
Merge Master to Ostree

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by parthaa** [comment]
Only one conflict -> test/fixtures/models/katello_repositories.yml

I just need to rename ->Fixtures to FixtureSet

**Comment by parthaa** [comment]
Not gonna change comments from previous commits.

**Comment by bbuckingham** [comment]
APJ

**Comment by parthaa** [comment]
[test]

**Comment by parthaa** [comment]
[test]

**Comment by jlsherrill** [comment]
manual run:  http://ci.theforeman.org/job/test_katello_pull_request/7970/

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
