### PR TITLE
Bump version to 4.0.0

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Review by jjeffers — APPROVED** [review]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Review by chris1984 — APPROVED** [review]
ACK pending jenkins

**Pull request merged**
