### PR TITLE
Fixes #30238 - Fix undefined method `klass' when searching on hosts

### PR DESCRIPTION
**Pull request by adamruzicka**
This error could be reproduced by searching like this
Host.search_for('applicable_errata_issued = "10 days ago"')

Requirements:
- [x] https://github.com/wvanbergen/scoped_search/pull/196

### CODE REVIEW

**Comment by parthaa** [comment]
Works well. Will approve once https://github.com/wvanbergen/scoped_search/pull/196 is merged

**Comment by jlsherrill** [comment]
@parthaa this has been merged, should we wait on a scoped search release? or just merge now?  I guess its not any more broken with this change while we wait for the release is it?

**Comment by adamruzicka** [comment]
Merging this shouldn't (tm) break anything, however it will not help until the scoped search counterpart is released

**Comment by adamruzicka** [comment]
Looks like I pushed too early, rekicking the tests

[test katello]

**Comment by parthaa** [comment]
[test katello]

**Pull request merged**
