### PR TITLE
Fixes #9079 - Add /var/lib/mongodb to the foreman-debug collection

### PR DESCRIPTION
**Pull request by bkearney**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Why would we want to collect this as part of a foreman debug?  That directory on a fresh install will be several Gigs in size and on a fully populated server could be ~12 GB.  I don't think that is something we want collected in a foreman-debug

**Comment by jlsherrill** [comment]
Reading the issue, i think you would want to grab /var/lib/mongodb/mongodb.log*  explicitly.

**Comment by bkearney** [comment]
@jlsherrill fixed.. thanks.

**Comment by jlsherrill** [comment]
ACK, merging, thanks @bkearney

**Pull request merged**
