### PR TITLE
fixes #9455 - fixes validation error, BZ1139576

### PR DESCRIPTION
**Pull request by cfouant**

### CODE REVIEW

**Comment by ehelms** [comment]
Reading the issue - wouldn't I get the same error if  used the API and supplied a large number? Can we protect against this for all cases?

**Comment by cfouant** [comment]
@ehelms It did not have multiple errors in CLI or API, only in the UI was it producing the error twice.  I wanted it to block the save button if any invalid number was input (as it was for negative numbers, or blank names) which also solves the double error from being produced.

**Comment by cfouant** [comment]
@ehelms - so, this patch is actually just fixing the particular double error which failed qa at the bottom of the bug. A different p-r [4785](https://github.com/Katello/katello/pull/4785) was already merged which fixed the overall problem of validation handling. I didn't understand what you were talking about when I wrote the above comment.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
