### PR TITLE
Fixes #24929 - Disable check for matching content in deb repos

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@mdellweg would you mind opening a new issue for this that would help describe the problem with leaving this in place?

**Comment by mdellweg** [comment]
@jlsherrill https://projects.theforeman.org/issues/24929

**Comment by jlsherrill** [comment]
@mdellweg would it be easier to just make it work properly?   It should be fairly simple to add a debian check: https://github.com/Katello/katello/blob/master/app/lib/actions/katello/repository/check_matching_content.rb

Or are there other reasons to not do this?  (is repo publishing pretty fast for large repos?)

**Comment by mdellweg** [comment]
> (is repo publishing pretty fast for large repos?)

Hell no!
I will have a try.

**Comment by mdellweg** [comment]
On the other hand, i have been asking myself, why there is a need to clone the repositories for lifecycle promotion. They should be serving the exact same content than the promoted contentview-version. So i think, a single symlink to each repository in the already published version should be sufficient.
What do i miss here? @jlsherrill

**Comment by jlsherrill** [comment]
> On the other hand, i have been asking myself, why there is a need to clone the repositories for lifecycle promotion. 

Thats a great question.  Pulp 2 doesn't really support the ability to serve a repo from two different paths (other than http and https).  So there really isn't any way to do this with pulp 2.  We have written our own custom distributor for pulp 2 called the 'yum_clone_distributor' which copies the metadata from one filesystem path to another.  This speeds it up quite a bit (and probably debian would benefit from a 'deb_clone_distributor'.  

Pulp 3 will actually support this natively, as you can 'distribute' a repo to as many paths as you want.

**Pull request merged**
