### PR TITLE
Fixes #17557 - fix test to run in december

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
http://ci.theforeman.org/job/test_katello_pull_request/10699/

**Comment by johnpmitsch** [comment]
APJ

**Comment by ehelms** [comment]
What is the error that occurs by not running in December? Leaves on your lawn?

**Comment by jlsherrill** [comment]
@ehelms see the issue for more details, basically 'invalid date'

**Comment by iNecas** [comment]
Alternatively, we can just call it a month and wait for January with more fixes…

**Pull request merged**
