### PR TITLE
Fixes #10381 - reduce #queries on products page

### PR DESCRIPTION
**Pull request by dustints**

### CODE REVIEW

**Comment by dustints** [comment]
This should speed up products index page.
for 9 products, this reduced  number of queries from 942  to 150.

**Comment by jlsherrill** [comment]
I'm getting some N+1 query notices:

N+1 Query detected
  Katello::Repository => [:environment]
  Add to your finder: :includes => [:environment]

mind fixing those too?

**Comment by dustints** [comment]
@jlsherrill adding environment is difficult because environment isn't a true relation.
...getting 'association environment does not exist'

**Comment by dustints** [comment]
i fixed another N+1 issues in repositories..

I think i could be able to express an efficient query that includes environment through arel...but can we tackle later or in a different PR?

**Comment by dustints** [comment]
updated, fixing the N+1 for products#show

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
small comment:

this actually introduces on the products index:
```
Unused Eager Loading detected
  Katello::Product => [:repositories, :gpg_key]
  Remove from your finder: :includes => [:repositories, :gpg_key
```

i'd change in products_controller:
```
      options[:includes] = [:repositories, :gpg_key, :sync_plan, :provider]
```

to
```
      options[:includes] = [ :sync_plan, :provider]
```

as repositories is no longer needed (:repository_count i'm assuming just runs a count() query, and :gpg_key is no longer included)

Otherwise looks good!

**Comment by dustints** [comment]
@jlsherrill thanks, updated!

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK

**Comment by jlsherrill** [comment]
actually hold off on merging for a few

**Comment by jlsherrill** [comment]
so i re-read the issue and saw that the actual issue and bz is targeted towards the repo list for a product, so i'm syncing 10 repos and re-testing with that

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
