### PR TITLE
Fixes #20235 - Add "Files" and "Images" tabs to "Red Hat Repositories" page

### PR DESCRIPTION
**Pull request by masatake**
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

### CODE REVIEW

**Comment by masatake** [comment]
Though I take a ticket in RedMine, I cannot do it.
I visited http://projects.theforeman.org/login and clicked "Login Via Github".
The page showed "You haven't activated your account yet. If you want to receive a new activation email, please click this link.".  I clicked "click this link". But no mail came.

**Comment by jlsherrill** [comment]
I opened an issue for you here:  http://projects.theforeman.org/issues/20235  to tie to this PR.  

You might check your spam folder or try 'creating an account' instead of using the github login for future submissions.

**Comment by masatake** [comment]
I cannot find  'creating an account'...

**Comment by jlsherrill** [comment]
Should be able to register here:
http://projects.theforeman.org/account/register

**Comment by masatake** [comment]
Thank you but I don't want to manage much acconts. I would like to use github account if possible.

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by masatake** [comment]
O.k. I will find a mail for activation my account in "promotion".

**Comment by masatake** [comment]
O.k. I will find a mail for activation my account in "promotion".

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by masatake** [comment]
Unacceptable?

**Comment by jlsherrill** [comment]
[test default]

**Comment by masatake** [comment]
Unacceptable?

**Comment by jlsherrill** [comment]
Hi, sorry for the delay.  We had some CI issues a while back and i think this got lost in the shuffle.  Linting is failing with:

```
00:05:11.592 /var/lib/workspace/workspace/test_katello_pull_request@2/slave/fast/plugin/app/helpers/katello/providers_helper.rb:21:5: C: Metrics/MethodLength: Method has too many lines. [31/30]
00:05:11.592     def redhat_repo_tab(provider, tab_id) .
```

Can you override rubocop for this rule on this file?  you'd just add:
```
# rubocop:disable MethodLength
```

right before `def redhat_repo_tab(provider, tab_id)`, so it'd look like:

```
   # rubocop:disable MethodLength
   def redhat_repo_tab(provider, tab_id)
```

**Comment by masatake** [comment]
Updated.

**Comment by jlsherrill** [comment]
[test default]

**Pull request merged**
