### PR TITLE
Fixes #33951 - Don't show RH Repos page in disconnected mode

### PR DESCRIPTION
**Pull request by jeremylenz**
#### What are the changes introduced in this pull request?

- [x] Don't show the Red Hat Repositories page in the nav when in disconnected mode
- [x] Update repository sets api to not provide available repository sets if disconnected

#### Considerations taken when implementing this change?

Since one does not have access to available repositories we can't really enable anything via this page.

I added a 403 response to `/repository_sets` with the explanatory error.  I chose 403 Forbidden because [the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) says this means "The server understood the request, but is refusing to fulfill it." I think that fits pretty well.

* Are there other endpoints I should also block, besides index?
* I decided not to change any wording etc. on the RH Repositories page, because it won't be displayed anyway

#### What are the testing steps for this pull request?

1. Settings > Content > Disconnected mode > Yes
2. Upon page refresh, verify that Red Hat Repositories is not listed in the navigation
3. Verify API error when trying to list repository sets (you can still go to /redhat_repositories manually to try it)
4. Turn the setting back to No and refresh the page; RH Repos should reappear in the nav

### CODE REVIEW

**Comment by jlsherrill** [comment]
I assume we don't want to support the situation where:

1) a satellite is disconnected
2) they are syncing from locally available CDN source, such as previous iso content?  (i agree this use case may be a stretch, but wanted to bring it up)

Also how does this affect ISS?  Couldn't a satellite be disconnected (i.e. not able to talk to the portal), but still want to enable repos from another satellite?

**Comment by jeremylenz** [comment]
@parthaa would also like your input on how this affects disconnected Satellites :)

**Comment by parthaa** [comment]
> parthaa would also like your input on how this affects disconnected Satellites :)

@jlsherrill brings up a good point.
That being said I 'd think `Disconected` should really only apply for `Airgapped Disconnected` setups. If its talking to a different CDN I 'd consider that a `Connected` case

**Comment by jlsherrill** [comment]
I feel like there are two aspects:
Disconnected subscriptions
Disconnected content

and we're trying to combine them both with one setting, which maybe isn't appropriate ?

**Comment by jeremylenz** [comment]
Closing in favor of a future PR from Partha after the design discussion today.

**Pull request closed without merging**
