### PR TITLE
Fixes #18972 - clean hosts with nil sub uuid

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
To test, simply register a host and run:

Host.find(id).subscription_facet.update_attributes(:uuid => nil)

**Comment by mccun934** [comment]
BTW, this didn't fix my issue. While it found the systems that needed unregistering/deleting they still could not be deleted. The task that got spawned died with a 404 error:

```
Katello::Resources::Candlepin::CandlepinResource: 404 Resource Not Found {"displayMessage":"Runtime Error RESTEASY001185: Could not find resource for relative : /consumers//entitlements of full path: https://localhost:8443/candlepin/consumers//entitlements at org.jboss.resteasy.core.registry.PathParamSegment.matchPattern:209","requestUuid":"beaf50e0-6f2c-4295-ba4f-4d3bf2ee4789"} (GET /candlepin/consumers//entitlements) (RestClient::ResourceNotFound)
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
/opt/theforeman/tfm/root/usr/share/gems/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
/opt/theforeman/tfm/root/usr/share/gems/gems/rbovirt-0.0.38/lib/restclient_ext/request.rb:50:in `block in transmit'
/opt/rh/rh-ruby22/root/usr/share/ruby/net/http.rb:853:in `start'
```

**Comment by jlsherrill** [comment]
as discussed offline, that issue is no longer present in the current katello

**Comment by johnpmitsch** [comment]
@jlsherrill 

I am seeing this when I run the `rake katello:clean_backend_objects`
```
2017-03-22T13:21:16  [katello/pulp_rest] [D] RestClient.get "https://sausage.example.com/pulp/api/v2/consumers/74e1e16c-55d9-415e-b077-76f7310d37e4/", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "accept"=>"application/json", "content_type"=>"application/json"
 | \n# => 200 OK | application/json 208 bytes
 | 
Host 5 sausage-client2.example.com  is partially missing.  Un-registering
2017-03-22T13:21:16  [katello/cp_rest] [D] Resource GET request: /candlepin/consumers/?
2017-03-22T13:21:16  [katello/cp_rest] [D] Headers: {"accept":"application/json","accept-language":"en","content-type":"application/json","cp-user":"foreman_admin"}
2017-03-22T13:21:16  [katello/cp_rest] [D] Body: {}
rake aborted!
RestClient::BadRequest: Katello::Resources::Candlepin::Consumer: 400 Bad Request {"displayMessage":"Must specify at least one search criteria.","requestUuid":"a959beb6-8f13-4c48-ab04-f2aa0141c28d"} (GET /candlepin/consumers/?)
```
The SubscriptionFacet still exists, but it looks like it was unregistered. (not sure if that is the expected outcome)

I still see the Content Host in the UI, but there is an error when I navigate to it
here

here is the [traceback](https://paste.fedoraproject.org/paste/BpO3Evik~MhMhjLTyxj69l5M1UNdIGYhyRLivL9gydE=)

**Comment by jlsherrill** [comment]
@johnpmitsch this may be candlepin 2.0 related.  Do you have the traceback from teh rake task?

**Comment by jlsherrill** [comment]
actually i can reproduce

**Comment by chris1984** [comment]
I was going to test this morning, but it looks like an updated commit is coming. I will test with the new one.

**Comment by jlsherrill** [comment]
Note, i fixed the cp 2.0 error in https://github.com/Katello/katello/pull/6695.  These two prs should be tested together.

**Comment by jlsherrill** [comment]
https://github.com/Katello/katello/pull/6695 is merged, this is ready to be retested.

**Comment by chris1984** [comment]
[root@centos7-katello-nightly ~]# foreman-rake katello:clean_backend_objects
Successfully encrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully encrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
The following changes will not actually be performed.  Rerun with COMMIT=true to apply the changes
1 orphaned consumer id(s) found.
[root@centos7-katello-nightly ~]# foreman-rake katello:clean_backend_objects COMMIT=true
Successfully encrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully decrypted field for Setting::Auth oauth_consumer_key
Successfully encrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
Successfully decrypted field for Setting::Auth oauth_consumer_secret
1 orphaned consumer id(s) found.

Works here after the #6695 merge

**Pull request merged**
