### PR TITLE
Fixes #15042 - Use a single fixture dir

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
If you had current test runs on a single Jenkins slave, I think this could result in clashes within that fixture directory? With it either missing or having a different set than expected? Might be rarer or intermittent, but we could try sticking with tmpdir and cleaning it up at the end of a test run somehow. Rails 4 might have the ability to specify multiple fixture directories now but we'd have to dig and check.

**Comment by jlsherrill** [comment]
Updated to use a path in the katello directory.  I looked at the code and it doesn't seem like you can provide multiple dirs still.

**Comment by jlsherrill** [comment]
I didn't see a clear way to clean up at the end of all the tests.

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
