### PR TITLE
fixes #22834 - fix JS error on host collection bulk errata

### PR DESCRIPTION
**Pull request by thomasmckay**
Similar to https://github.com/Katello/katello/pull/7151

### CODE REVIEW

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello]

**Comment by akofink** [comment]
[test katello] :pray:

**Comment by akofink** [comment]
@thomasmckay This is a legitimate failure, I think. You might need to rebase.

**Comment by stbenjam** [comment]
[test katello]

**Comment by thomasmckay** [comment]
[test katello]

**Pull request merged**
