### PR TITLE
Fix #30626 - filtering applied errata by host search

### PR DESCRIPTION
**Pull request by ezr-ondrej**
There is a desire to have applied errata filtrable by host to provide similar functionality to a applicable errata.

I must say it feels quite hacky, but the request is valid, so OTOH I feel we should do our best to implement it.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Ping? Any opinions?

**Review by sjha4 — APPROVED** [review]
Looks good to me with the associated report change adding optional host filter. Ack :+1: 
Thanks @ezr-ondrej !

**Comment by sjha4** [comment]
@ezr-ondrej : Should we wait for the foreman PR to get merged? Should be ok with the default nil value either way. Thoughts?

**Comment by ezr-ondrej** [comment]
The core pr depends on this one :)
This adds the support for the change in the template.

**Comment by sjha4** [comment]
Thanks @ezr-ondrej .. Merging!

**Pull request merged**
