### PR TITLE
fixes #10934 - per-page/page options for puppet-module list, BZ1202050

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by pmoravec** [comment]
I have tested it on my system and it does not help - e.g.:

    hammer -u admin -p <password> content-view puppet-module list --help

does not show the expected additional pagination options.

**Comment by komidore64** [comment]
@pmoravec did you regenerate you server's apidoc after checking out this PR?

**Comment by pmoravec** [comment]
@komidore64 yes I did, no change.

**Comment by komidore64** [comment]
from IRC:
> pmoravec, hey, i looked at that system yesterday. i checked the apidoc and it was displaying the correct new params for the content-view puppet-modules list commands. for some reason, hammer wasn't pulling the new apidoc-cache. i deleted `~/.cache/apipie_bindings` and then the params showed up correctly in hammer

**Comment by pmoravec** [comment]
Agreed, verified it works.

**Comment by ehelms** [comment]
ACK

**Pull request merged**
