### PR TITLE
Fixes #34608 - use only public setting interface

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Use only public setting interface to manipulate settings.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test katello]

**Comment by jeremylenz** [comment]
Test failure seems related:

```
Failure:

[2022-03-16T22:35:54.878Z] Katello::SettingTest#test_foreman_proxy_content_auto_sync_setting [/home/jenkins/workspace/katello-pr-test/test/models/setting_test.rb:14]

[2022-03-16T22:35:54.878Z] Minitest::Assertion: Expected true to not be truthy.
```

**Comment by ezr-ondrej** [comment]
> Test failure seems related:

It is, I tried to fix, but it is a pointless test for the new DSL as we have static typing there, so I've decided just to skip in hope Katello will go with the DSL soon, which this helps to unblock :)

**Review by jeremylenz — APPROVED** [review]
Thanks @ezr-ondrej!

will make a note to fix that test when we finally tackle https://projects.theforeman.org/issues/33608.

**Pull request merged**
