### PR TITLE
Fixes #28080 - Remove RHSM facts when unregistering

### PR DESCRIPTION
**Pull request by jturel**
**To test**

1. register a client ie host.example.com (subman register)
2. unregister the client (subman unregister)
3. change hostname to host-a.example.com (hostnamectl)
4. attempt re-register (subman register)

(4) would have failed with an error, but now it should succeed since we don't keep the old registration's facts around

### CODE REVIEW

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
@jlsherrill any thoughts on why we may have not deleted the RHSM facts while unregistering before? I'm guessing it's because it didn't really matter, but now it does - or can at least

**Comment by jlsherrill** [comment]
@jturel seems very reasonable, i think the only reason we didn't previously was because no one ever asked for it :)

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by jturel** [comment]
[test katello]

**Comment by chris1984** [comment]
Starting to test

**Pull request merged**
