### PR TITLE
Fixes #15456 - replace details with warning on unregd host

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by komidore64** [comment]
testing...

**Comment by bbuckingham** [comment]
The code looks good; however,  I want to take a quick look at what it looks like to the user as well.

**Comment by jlsherrill** [comment]
Preview with correct style: 

preview

**Comment by bbuckingham** [comment]
@jlsherrill, do you think we should hide any of the tabs (e.g. Subscriptions, Packages, Errata, Product Content) when the subscription/content facet are not available or have those tabs also show the message?  Also, do you think it would be worthwhile on the list details to reflect the lack of subscription/content?

**Comment by jlsherrill** [comment]
@bbuckingham some of the tabs do show the message (such as subscriptions).

The packages tab is still usable with REX which is why i didn't do the same there previously
The errata tab is still usable (no errata should show up), it just seemed like less complexity to show an empty table than show a message, but that's probably the weakest of the reasoning.

**Comment by bbuckingham** [comment]
@jlsherrill, I think that is reasonable for now.  The reality is that when we extend the 'unification' to the UI, it will become more obvious to the user.   I agree with not blocking tabs that can still be used, so subscriptions is the biggest one and it is covered.

ACK

**Pull request merged**
