### PR TITLE
Fixes #28658 - switch to cert based auth for pulp3

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
This requires some installer changes in order to review/merged

**Comment by jlsherrill** [comment]
Note that you'll want to redeploy with the newest forklift pr:  https://github.com/theforeman/forklift/pull/980

**Comment by jlsherrill** [comment]
hold off on testing for one bit, seeing an issue

**Comment by jturel** [comment]
Just making sure - this ready to test?

**Comment by jlsherrill** [comment]
Yes... although on new pulp3 dev envs, i'm seeing this :/   https://pulp.plan.io/issues/5955

so maybe we need to hold off a little bit.

**Comment by jturel** [comment]
> Yes... although on new pulp3 dev envs, i'm seeing this :/ https://pulp.plan.io/issues/5955
> 
> so maybe we need to hold off a little bit.

ack, will hold off for now

**Comment by jlsherrill** [comment]
This is now ready to test, just make sure re-run the pulp3 deployment playbook

**Comment by jlsherrill** [comment]
[test katello]

**Pull request merged**
