### PR TITLE
Fixes #25084 - Module Stream-Errata bindings

### PR DESCRIPTION
**Pull request by parthaa**
This commit adds module stream errata bindings along with the migration
and api changes.

### CODE REVIEW

**Comment by parthaa** [comment]
To test
- Update pulp nightly in the dev environment
```
# The Latest Nightly Build
[pulp-nightlies]
name=Pulp Nightlies $releasever - $basearch
baseurl=https://repos.fedorapeople.org/repos/pulp/pulp/testing/automation/2.18/stage/7Server/x86_64/
master/stage/fedora-$releasever/$basearch/
enabled=1
skip_if_unavailable=1
gpgcheck=0

```
- ```yum update *pulp*```
- ```systemctl  stop httpd.service pulp_workers.service pulp_resource_manager.service pulp_celerybeat.service```
- ```sudo -u apache /usr/bin/pulp-manage-db```
- ```systemctl  start httpd.service pulp_workers.service pulp_resource_manager.service pulp_celerybeat.service```

From katello 
- ```rake db:migrate``
- create a repo that points to https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-with-modules/ and sync (if you already have that  you can do a resync or ```rake katello:reimport```)

Once all of thats done you should be able to 
```
[vagrant@gamma ~]$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/2?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   564    0   564    0     0    116      0 --:--:--  0:00:04 --:--:--   153
{
    "id": 2,
    "uuid": "6eed26cf-825d-47bb-a723-5b83062a2545",
    "title": "Bird_Erratum",
    "errata_id": "RHEA-2012:0056",
    "issued": "2013-01-27",
    "updated": "2013-02-27",
    "severity": "",
    "description": "ParthaBird_Erratum",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Bird_Erratum",
    "type": "security",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [
        "crow-0.8-1.noarch",
        "duck-0.6-1.noarch",
        "stork-0.12-2.noarch"
    ],
    "module_stream_packages": {

    },
    "non_module_stream_packages": [
        "crow-0.8-1.noarch",
        "duck-0.6-1.noarch",
        "stork-0.12-2.noarch"
    ]
}
[vagrant@gamma ~]$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/3?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   651    0   651    0     0   2266      0 --:--:-- --:--:-- --:--:--  2268
{
    "id": 3,
    "uuid": "71ca7ce2-5230-4da5-8334-97ee9d9ffe1e",
    "title": "Duck_Kangaroo_Erratum",
    "errata_id": "RHEA-2012:0059",
    "issued": "2018-01-27",
    "updated": "2018-07-20",
    "severity": "",
    "description": "Duck_Kangaro_Erratum description",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Duck_Kangaroo_Erratum",
    "type": "enhancement",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [
        "duck-0.7-1.noarch",
        "kangaroo-0.3-1.noarch"
    ],
    "module_stream_packages": {
        "duck:0:20180730233102:deadbeef:noarch": [
            "duck-0.7-1.noarch"
        ],
        "kangaroo:0:20180730223407:deadbeef:noarch": [
            "kangaroo-0.3-1.noarch"
        ]
    },
    "non_module_stream_packages": [

    ]
}
```

Note the new columns - ```non_module_stream_packages``` and ```non_module_stream_packages```

**Comment by parthaa** [comment]
Removed ```non_module_stream_packages``` and instead changed ```packages``` to return non module streams.
```
$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/2?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   471    0   471    0     0     66      0 --:--:--  0:00:07 --:--:--   121
{
    "id": 2,
    "uuid": "6eed26cf-825d-47bb-a723-5b83062a2545",
    "title": "Bird_Erratum",
    "errata_id": "RHEA-2012:0056",
    "issued": "2013-01-27",
    "updated": "2013-02-27",
    "severity": "",
    "description": "ParthaBird_Erratum",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Bird_Erratum",
    "type": "security",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [
        "crow-0.8-1.noarch",
        "duck-0.6-1.noarch",
        "stork-0.12-2.noarch"
    ],
    "module_stream_packages": {

    }
}

$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/3?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   576    0   576    0     0   2209      0 --:--:-- --:--:-- --:--:--  2215
{
    "id": 3,
    "uuid": "71ca7ce2-5230-4da5-8334-97ee9d9ffe1e",
    "title": "Duck_Kangaroo_Erratum",
    "errata_id": "RHEA-2012:0059",
    "issued": "2018-01-27",
    "updated": "2018-07-20",
    "severity": "",
    "description": "Duck_Kangaro_Erratum description",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Duck_Kangaroo_Erratum",
    "type": "enhancement",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [

    ],
    "module_stream_packages": {
        "duck:0:20180730233102:deadbeef:noarch": [
            "duck-0.7-1.noarch"
        ],
        "kangaroo:0:20180730223407:deadbeef:noarch": [
            "kangaroo-0.3-1.noarch"
        ]
    }
}
```

**Comment by omkarkhatavkar** [comment]
@parthaa as per above example, errata's with only the packages which are part of module stream are going to be listed in **"module_stream_packages"** node else are listed in **"package"** node.

If my understanding is correct then, I see some discrepancies with below calls on same sync repo. 

```
[vagrant@centos7-devel ~]$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/6?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   469    0   469    0     0   2366      0 --:--:-- --:--:-- --:--:--  2380
{
    "id": 6,
    "uuid": "c68e591e-3427-458e-8817-410d37d9f711",
    "title": "Sea_Erratum",
    "errata_id": "RHEA-2012:0055",
    "issued": "2012-01-27",
    "updated": "2012-01-27",
    "severity": "",
    "description": "Sea_Erratum",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Sea_Erratum",
    "type": "security",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [
        "penguin-0.9.1-1.noarch",
        "shark-0.1-1.noarch",
        "walrus-5.21-1.noarch"
    ],
    "module_stream_packages": {

    }
}
```
```
[vagrant@centos7-devel ~]$ curl -u admin:changeme 'https://localhost/katello/api/v2/errata/5?sort_by=issued&sort_order=DESC' -k --globoff|json_reformat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   471    0   471    0     0   2119      0 --:--:-- --:--:-- --:--:--  2131
{
    "id": 5,
    "uuid": "4efb139a-c2bf-4777-ba11-c61695585028",
    "title": "Bird_Erratum",
    "errata_id": "RHEA-2012:0056",
    "issued": "2013-01-27",
    "updated": "2013-02-27",
    "severity": "",
    "description": "ParthaBird_Erratum",
    "solution": "",
    "summary": "",
    "reboot_suggested": false,
    "name": "Bird_Erratum",
    "type": "security",
    "cves": [

    ],
    "bugs": [

    ],
    "hosts_available_count": 0,
    "hosts_applicable_count": 0,
    "packages": [
        "crow-0.8-1.noarch",
        "duck-0.6-1.noarch",
        "stork-0.12-2.noarch"
    ],
    "module_stream_packages": {

    }
}
```

**Comment by parthaa** [comment]
> @parthaa as per above example, errata's with only the packages which are part of module stream are going to be listed in **"module_stream_packages"** node else are listed in **"packages"** node.

The errata needs to have that module information embedded in it for it to show up in our api.

> If my understanding is correct then, I see some discrepancies with below calls on same sync repo.
Can you point out the discrepancy you are referring to. I see 2 ids

**Comment by johnpmitsch** [comment]
@parthaa can you structure the package data this way?
```
module_stream_packages: [
	{
    	name: foo
        stream: 1
        packages: [
        	duck,
            bird
        ]
     },
     {
     ...
     }
]
```

**Comment by parthaa** [comment]
> can you structure the package data this way?

@johnpmitsch updated. Check the new output in comment 2

**Comment by johnpmitsch** [comment]
@parthaa looks good, I wonder if we should change `module_stream_packages` to just `module_streams` now

**Comment by johnpmitsch** [comment]
One small thing I thought of :) 

Would it make sense to return the module stream id so I could easily link to the module stream details?

**Comment by parthaa** [comment]
> Would it make sense to return the module stream id so I could easily link to the module stream details?

added :)

**Comment by omkarkhatavkar** [comment]
@partha @johnpmitsch : 

I tried the same steps and now I'm not able to see updated module stream json after syncing https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-with-modules/ repo. I was able to see some result before previous some commits. Are you able to see the result?

**Comment by johnpmitsch** [comment]
approval stands!

@omkarkhatavkar I think you are missing a pulp patch, we can help you off thread

**Pull request merged**
