### PR TITLE
Fixes #36044 - Update pf4 to 2022.16+ release

### PR DESCRIPTION
**Pull request by MariaAga**
Thank you Katello team for the great tests, was able to find which things broke during the update and fix them.
* Changes to Wizard step functions break the ASC step navigation.
* DatePicker onChange function changed arguments
* Tab has an href prop, and Tabs break when Tab is wrapped so removed the `a` tag wrap
Blocked by https://github.com/theforeman/foreman/pull/9593

### CODE REVIEW

**Comment by MariaAga** [comment]
Foreman pr is merged, @jeremylenz can you take a look?

**Comment by jeremylenz** [comment]
@MariaAga do you mind updating the snapshots? Looks like this updated Patternfly as well and changed some checkboxes etc.

**Comment by MariaAga** [comment]
The test were run on the old foreman version, can you please rerun them?

**Comment by jeremylenz** [comment]
> The test were run on the old foreman version, can you please rerun them?

Rerunning now

**Review by jeremylenz — APPROVED** [review]
All green now, thanks @MariaAga!

Clicked around all of the changed UIs and confirmed it still works fine. ACK :+1:

**Pull request merged**
