### PR TITLE
fixes #16480 - host/hostgroup ui media selection

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
@parthaa - having trouble testing this since i think my os/media are not set up... or this PR is wrong

**Comment by jlsherrill** [comment]
The os_selected() method still doesn't quite match what is in foreman.  We have:
```
    success: function(request) {
      $('#media_select').html(request);
      reload_host_params();
    }
```

While foreman master has:

```
    success: function(request) {
      $('#media_select').html(request);
      reload_host_params();
      reload_puppetclass_params();
    }
```

**Comment by thomasmckay** [comment]
@jlsherrill - updated to match foreman's host_edit.js

**Comment by jlsherrill** [comment]
APJ

**Pull request merged**
