### PR TITLE
[CP] Katello 4.1.3 cherry-picks

### PR DESCRIPTION
**Pull request by jeremylenz**
- [ ] cherry-picks
- [x] changelog
- [x] version bump

### CODE REVIEW

**Comment by jturel** [comment]
I saw some discussion on IRC around merge conflicts here yesterday and now I see some test failures. I wonder if there was an intermediate commit that wasn't marked for 4.1.3 (intentionally or not) that would alleviate the merge conflicts and perhaps the test failures? My assumption is that the conflicts and test failures are related, and you can ignore me if they're not :)

**Comment by jeremylenz** [comment]
@jturel that's quite possible, but I would defer to @ianballou to tell me if that might be the case? :)

In any case, trying Ian's suggestion to fix the tests now..

**Comment by jturel** [comment]
> @jturel that's quite possible, but I would defer to @ianballou to tell me if that might be the case? :)
> 
> In any case, trying Ian's suggestion to fix the tests now..

tig $FILENAME will show the commit history against that file and you may be able to determine that (or wait for Ian to comment of course)

**Comment by jeremylenz** [comment]
[test katello]

**Comment by jeremylenz** [comment]
closed in favor of https://github.com/Katello/katello/pull/9568

**Pull request closed without merging**
