### PR TITLE
Fixes #13789 - Update content host attribute service_level, release_ver and last_checking using API

### PR DESCRIPTION
**Pull request by ranjan**
This will allow to update service_level, release_ver and last_checking using API

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@ranjan tests should run now, please squash commits into a single commit, thanks!

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by jlsherrill** [comment]
ACK thanks @ranjan sorry for the delay!

**Pull request merged**
