### PR TITLE
Fixes #24436 - use new api for pool consumer ids

### PR DESCRIPTION
**Pull request by parthaa**
When indexing pool to subscription facet association, use
a new api that only returns the consumer uuids

### CODE REVIEW

**Comment by parthaa** [comment]
@beav - Added the vcr tests based on your suggestion -> https://github.com/Katello/katello/pull/7576#issuecomment-408677364

**Comment by johnpmitsch** [comment]
This isn't related, but I'm not able to load subscrpitions for a content host when I go to that content host > subscription > add tab. Does anyone else see this?

```
2:41:10 rails.1   | 2018-07-30T22:41:10 [E|app|e9da8] NoMethodError: undefined method `path' for #<Class:0x000000000b4756e8>
22:41:10 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
22:41:10 rails.1   |  | /home/vagrant/katello/app/lib/katello/resources/candlepin/consumer.rb:78:in `available_pools'
22:41:10 rails.1   |  | /home/vagrant/katello/app/services/katello/candlepin/consumer.rb:20:in `block in <class:Consumer>'
22:41:10 rails.1   |  | /home/vagrant/katello/app/lib/katello/lazy_accessor.rb:160:in `instance_eval'
22:41:10 rails.1   |  | /home/vagrant/katello/app/lib/katello/lazy_accessor.rb:160:in `run_initializer'
22:41:10 rails.1   |  | /home/vagrant/katello/app/lib/katello/lazy_accessor.rb:139:in `lazy_attribute_get'
22:41:10 rails.1   |  | /home/vagrant/katello/app/lib/katello/lazy_accessor.rb:60:in `block (2 levels) in lazy_accessor'
22:41:10 rails.1   |  | /home/vagrant/katello/app/services/katello/candlepin/consumer.rb:56:in `filtered_pools'
22:41:10 rails.1   |  | /home/vagrant/katello/app/controllers/katello/api/v2/subscriptions_controller.rb:161:in `for_host'
22:41:10 rails.1   |  | /home/vagrant/katello/app/controllers/katello/api/v2/subscriptions_controller.rb:68:in `index_relation'
22:41:10 rails.1   |  | /home/vagrant/katello/app/controllers/katello/api/v2/subscriptions_controller.rb:34:in `index'
22:41:10 rails.1   |  | /home/vagrant/.rvm/gems/ruby-2.4.4/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_acti
```

**Comment by beav** [comment]
@johnpmitsch I get this when trying to register:

```
2018-07-30T23:25:11 [E|kat|1471f] <Class> ActiveRecord::RecordInvalid
2018-07-30T23:25:11 [E|kat|1471f] environment_id: ["with id 1 doesn't exist or is not assigned to proper organization and/or location"]
```

This is with nightly, were you able to get around it?

**Comment by johnpmitsch** [comment]
@beav I was able to register fine, but am using a devel box, not nightly

**Comment by beav** [comment]
:ballot_box_with_check: reg/unreg pass
:ballot_box_with_check: clean_backend_objects finds nothing after reg/unreg/reg
:ballot_box_with_check: `import_subscriptions` job calls new API, candlepin returns a 200

ACK from me as well!

**Pull request merged**
