### PR TITLE
Fixes #20113 - Use admin user to create hypervisors

### PR DESCRIPTION
**Pull request by Klaas-**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@Klaas- I invited you to the Katello org, if you accept and set yourself public this will kickoff tests automatically.

**Comment by Klaas-** [comment]
are those errors related to my change? I don't think I've tinkered with the operating systems :)

**Comment by ehelms** [comment]
They are a known set of intermittent but happening more and more often breakages. We are digging into them.

**Pull request merged**
