### PR TITLE
Fixes #31173 - no deb repo in sub-man

### PR DESCRIPTION
**Pull request by sbernhard**
CC @jlsherrill - we have talked about this last week in IRC.

### CODE REVIEW

**Comment by sbernhard** [comment]
Is the test failure related to this PR? I dont think so @jlsherrill.

**Comment by jlsherrill** [comment]
i don't see a failure... the test task just aborted. lets re-kick it

[test katello]

**Comment by jlsherrill** [comment]
i'm not sure why the builds are taking longer than 2 hours to run and timing out.  this isn't isolated to this pr

**Comment by jlsherrill** [comment]
[test katello]

**Comment by sbernhard** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test katello]

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
