### PR TITLE
Fixes #36903 - upgrade to Pulpcore 3.39

### PR DESCRIPTION
**Pull request by ianballou**
#### What are the changes introduced in this pull request?
VCR recordings for Pulpcore 3.39

#### Considerations taken when implementing this change?
All tests were recorded on Pulpcore 3.39

#### What are the testing steps for this pull request?
Upgrade to Pulpcore 3.39 and test some actions. N-1 smart proxy sync testing is in-progress.

### CODE REVIEW

**Review by sjha4 — APPROVED** [review]
Katello side of this is working fine in my smoke testing. Ack based on that. Feel free to merge whenever ready.

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Comment by ianballou** [comment]
[test katello]

**Review by ekohl — APPROVED** [review]
Can this be merged? I don't have permissions here, but can merge the packaging side.

**Comment by ekohl** [comment]
There is a failure in the pipeline: https://community.theforeman.org/t/katello-nightly-rpm-pipeline-1838-failed/35929/2

**Pull request merged**
