### PR TITLE
Katello 3.1 backports

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by jlsherrill** [comment]
[test]

**Comment by bbuckingham** [comment]
APJ

**Comment by jlsherrill** [comment]
running here http://ci.theforeman.org/job/test_katello_pull_request/9933/

**Comment by jlsherrill** [comment]
This passes locally, merging!

**Pull request merged**
