### PR TITLE
Fixes #15741 - Use parameter_filter to whitelist attrs

### PR DESCRIPTION
**Pull request by daviddavis**
Requires https://github.com/theforeman/foreman/pull/3659 and release of foreman_docker with https://github.com/theforeman/foreman-docker/pull/171

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test]

**Comment by beav** [comment]
this did the trick for my dev install, `db:migrate` passed after applying this patch.

APJ from me

**Comment by jlsherrill** [comment]
hrmmm, autoheal doesn't seem to be updating, investigating

**Comment by jlsherrill** [comment]
auto heal issue seems pre-existing, opened http://projects.theforeman.org/issues/15935

**Comment by jlsherrill** [comment]
functionality wise, everything seems fine.

**Comment by daviddavis** [comment]
I fixed the org tests. For the content host tests, I had to move them to the controller level since that's where params are now being filtered. Review the test changes if you would. Thanks.

**Comment by jlsherrill** [comment]
ACK

**Comment by jlsherrill** [comment]
MERGING

**Pull request merged**
