### PR TITLE
Fixes #10177 - Sync details can be edited properly.

### PR DESCRIPTION
**Pull request by zjhuntin**
Before if you tried to edit information on a sync plan, other than the sync date, it would  cause the sync date to become invalid making it unable to saved. To test try creating a sync plan and editing each of the features.

### CODE REVIEW

**Comment by zjhuntin** [comment]
Firefox is not as flexible as Chrome at parsing date time objects. EG: new Date(2016-03-31 16:25:00) in the Firefox console would return an invalid date. I changed the rabl file so that sync_date would return the date in a form that could be parsed by Firefox and Chrome.

**Comment by johnpmitsch** [comment]
:+1: everything works fine for me

**Comment by johnpmitsch** [comment]
ACK

**Comment by johnpmitsch** [comment]
thanks @zjhuntin!

**Pull request merged**
